---
# tasks file for roles/auth

- name: Configure authorized_keys
  ansible.posix.authorized_key:
    user: "{{ item.0.name }}"
    state: present
    key: "{{ lookup('file', item.1) }}"
  loop: "{{ auth__authorized_keys | subelements('keys', skip_missing=true) }}"
  when: auth__authorized_keys_enable
