---
# tasks file for roles/auth


- name: Install and configure nscd
  tags: [ 'auth', 'nscd' ]
  when: auth__enable and auth__nscd_enable
  block:

  - name: Install nscd packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ auth__nscd_packages_combined }}"

- name: Install and configure nslcd
  tags: [ 'auth', 'nslcd' ]
  when: auth__enable and auth__nslcd_enable
  block:

  - name: Install nslcd packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ auth__nslcd_packages_combined }}"

  - name: Configure nslcd
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/nslcd.conf.j2
      dest: /etc/nslcd.conf
      owner: root
      group: root
      mode: 0640
    notify:
    - Restart nslcd

- name: Configure nsswitch
  tags: [ 'auth', 'nsswitch' ]
  when: auth__enable and auth__nsswitch_enable
  block:

  - name: Configure nsswitch
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/nsswitch.conf.j2
      dest: /etc/nsswitch.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - Restart systemd-logind

- name: Configure authorized_keys
  tags: [ 'auth', 'ssh' ]
  when: auth__enable and auth__authorized_keys_enable
  block:

  - name: Configure authorized_keys
    tags: [ 'configuration' ]
    ansible.posix.authorized_key:
      user: "{{ item.0.name }}"
      state: present
      key: "{{ lookup('file', item.1) }}"
    loop: "{{ auth__authorized_keys | subelements('keys', skip_missing=true) }}"
