---

- name: Install and configure monitoring plugins
  tags: [ monitoring ]
  when: monitoring__plugins_enable
  block:

  - name: Create local plugins directory
    ansible.builtin.file:
      dest: "{{ monitoring__plugins_local_dir }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Create Icinga command plugins directory
    when: monitoring__plugins_icinga_enable
    ansible.builtin.file:
      dest: "{{ monitoring__plugins_icinga_dir }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Copy plugins
    include_tasks: plugin.yml
    loop_control:
      loop_var: plugin
    with_items: "{{ monitoring__plugins_list }}"
