---


- name: "Install plugin {{ plugin }}"
  when: monitoring__plugins_combined[plugin]
  block:

  - name: "Copy plugin {{ plugin }}"
    when: monitoring__plugins_config[plugin].src is defined
    ansible.builtin.copy:
      src: "{{ monitoring__plugins_local_dir | regex_replace('^/') }}/{{ monitoring__plugins_config[plugin].src }}"
      dest: "{{ monitoring__plugins_local_dir }}/{{ monitoring__plugins_config[plugin].target | default(monitoring__plugins_config[plugin].src) }}"
      mode: 0755

  - name: "Copy configuration {{ plugin }}"
    when: monitoring__plugins_icinga_enable
    ansible.builtin.copy:
      src: "{{ monitoring__plugins_icinga_dir | regex_replace('^/') }}/{{ monitoring__plugins_config[plugin].config }}"
      dest: "{{ monitoring__plugins_icinga_dir }}/{{ monitoring__plugins_config[plugin].config }}"
      owner: nagios
      group: nagios
      mode: 0640

  - name: "Install plugin packages {{ plugin }}"
    tags: [ 'packages' ]
    when: monitoring__plugins_config[plugin].packages is defined
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ monitoring__plugins_config[plugin].packages }}"
