---


- name: "Install plugin {{ plugin }}"
  when: monitoring__plugins_combined[plugin]
  block:

  - name: Copy plugin
    ansible.builtin.copy:
      src: "{{ monitoring__plugins_local_dir | regex_replace('^/') }}/{{ monitoring__plugins_config[plugin].src }}"
      dest: "{{ monitoring__plugins_local_dir }}/{{ monitoring__plugins_config[plugin].target }}"
      mode: 0755

  - name: Copy configuration
    when: monitoring__plugins_icinga_enable
    ansible.builtin.copy:
      src: "{{ monitoring__plugins_icinga_dir | regex_replace('^/') }}/{{ monitoring__plugins_config[plugin].config }}"
      dest: "{{ monitoring__plugins_icinga_dir }}/{{ monitoring__plugins_config[plugin].config }}"
      owner: nagios
      group: nagios
      mode: 0640
