---

- name: 'Restart mosquitto service'
  ansible.builtin.service:
    name: 'mosquitto'
    state: 'restarted'
  when: 'not ansible_check_mode and not mosquitto_server__use_podman'

- name: 'Restart mosquitto container'
  ansible.builtin.service:
    name: "{{ mosquitto_server__container.name }}"
    state: 'restarted'
  when: 'not ansible_check_mode and mosquitto_server__use_podman'
