---

- name: Restart mosquitto
  ansible.builtin.service:
    name: mosquitto
    state: restarted
  when: not ansible_check_mode and not mosquitto_server__use_podman

- name: Restart mosquitto container
  containers.podman.podman_container:
    name: mosquitto
    state: started
    force_restart: true
  when: not ansible_check_mode and mosquitto_server__use_podman
