---

- name: 'Install PowerDNS using podman'
  block:

    - name: 'Create PowerDNS directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0755') }}"
        state: 'directory'
      with_items:
        - dest: "{{ dns_powerdns__podman_home }}"
        - dest: "{{ dns_powerdns__podman_config_dir }}"
        - dest: "{{ dns_powerdns__podman_config_dir }}/{{ dns_powerdns__include_subdir }}"
        - dest: "{{ dns_powerdns__podman_run_dir }}"
          owner: '953'
          group: '953'

    - name: 'Generate PowerDNS configuration'
      ansible.builtin.template:
        src: 'pdns.conf.j2'
        dest: "{{ dns_powerdns__podman_config_dir }}/pdns.conf"
      when: 'not podman___update_mode | bool'
      notify: 'Restart PowerDNS container'

    - name: 'Generate PowerDNS pgsql backend configuration'
      ansible.builtin.template:
        src: 'gpgsql.conf.j2'
        dest: "{{ dns_powerdns__podman_config_dir }}/{{ dns_powerdns__include_subdir }}/gpgsql.conf"
      notify: 'Restart PowerDNS container'
      when: 'not podman___update_mode | bool and dns_powerdns__gpgsql'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ dns_powerdns__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[dns_powerdns__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ dns_powerdns__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ dns_powerdns__container.name }}"
        hostname: "{{ dns_powerdns__container.hostname }}"
        image: "{{ dns_powerdns__container.image }}"
        ip: "{{ dns_powerdns__container.ip }}"
        ip6: "{{ dns_powerdns__container.ipv6 | default(omit) }}"
        network: "{{ dns_powerdns__container.network }}"
        expose: "{{ dns_powerdns__container.expose | default(omit) }}"
        publish: "{{ dns_powerdns__container.publish | default(omit) }}"
        timezone: "{{ dns_powerdns__container.timezone }}"
        label: "{{ dns_powerdns__container.labels | default(omit) }}"
        volume: "{{ dns_powerdns__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          {% if dns_powerdns__container.exec_start_pre is defined %}
          {% for command in dns_powerdns__container.exec_start_pre %}
          ExecStartPre={{ command }}
          {% endfor %}
          {% endif %}
          RestartSec=5
          Restart=always

          [Unit]
          {% if dns_powerdns__container.requires is defined %}
          Requires={{ dns_powerdns__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd_service:
        name: "{{ dns_powerdns__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
