---

- name: 'Configure InfluxDB Core backup'
  tags: [ 'backup_influxdb_core'  ]
  block:

    - name: 'Include OS-specific variables'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"

    - name: 'Install InfluxDB Core packages'
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ backup_influxdb_core__packages }}"

    - name: 'Copy InfluxDB Core backup scripts to host'
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup__lib_dir }}/{{ item }}"
        mode: '755'
      with_items: "{{ backup_influxdb_core__files }}"

    - name: 'Generate InfluxDB Core backup configuration file'
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ backup__etc_dir }}/{{ item }}"
        owner: 'root'
        group: 'root'
        mode: '640'
      with_items:
        - 'influxdb-core'
