---

- name: 'Install pass'
  tags: [ 'security_pass' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        mode: '0700'
        state: 'directory'
      with_items:
        - "{{ security_pass__podman_home }}"

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ security_pass__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ security_pass__container.name }}"
        hostname: "{{ security_pass__container.hostname }}"
        image: "{{ security_pass__container.image }}"
        timezone: "{{ security_pass__container.timezone }}"
        volume: "{{ security_pass__container.volumes }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ security_pass__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
