---
# tasks file for roles/apt

- name: Bootstrap apt setup
  block:

  - name: 'Update APT cache'
    ansible.builtin.apt:
      update_cache: 'yes'
    tags:
    - apt

  - name: Install required packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ apt__packages_combined }}"
    tags:
    - apt
    - packages

  - name: Remove obsolete configuration files
    ansible.builtin.file:
      dest: "{{ item }}"
      state: absent
    with_items: "{{ apt__files_absent }}"
    tags:
    - apt
    - bootstrap
    - configuration

- name: Configure apt setup
  block:

  - name: Create APT configuration files
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: etc/apt/apt.conf.d/50languages.j2
      dest: /etc/apt/apt.conf.d/50languages
    - src: etc/apt/apt.conf.d/50recommends.j2
      dest: /etc/apt/apt.conf.d/50recommends
    - src: etc/apt/apt.conf.d/50suggests.j2
      dest: /etc/apt/apt.conf.d/50suggests
    - src: etc/apt/apt.conf.d/50periodic.j2
      dest: /etc/apt/apt.conf.d/50periodic
    - src: etc/apt/apt.conf.d/50unattended-upgrades.j2
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
    tags:
    - apt
    - configuration

  - name: Create apt sources lists
    ansible.builtin.template:
      src: etc/apt/sources.list.d/source.list.j2
      dest: "/etc/apt/sources.list.d/{{ item.name }}.list"
      owner: root
      group: root
      mode: 0644
    vars:
      repos: "{{ item.repos }}"
    with_items: "{{ apt__sources_combined }}"
    tags:
    - apt
    - configuration

  - name: 'Update APT cache'
    ansible.builtin.apt:
      update_cache: 'yes'
    tags:
    - apt
