---

- name: Configure GitLab backup
  tags: [ 'backup_gitlab'  ]
  block:

    - name: Copy GitLab backup scripts to host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup_common__lib_dir }}/{{ item }}"
        mode: '755'
      with_items: "{{ backup_gitlab__files }}"

    - name: Generate GitLab backup configuration file
      ansible.builtin.template:
        src: gitlab.j2
        dest: "{{ backup_common__etc_dir }}/gitlab"
        owner: root
        group: root
        mode: '640'
