---
# tasks file for roles/supervisor

- name: Install and configure supervisor
  tags: [ 'supervisor' ]
  when: supervisor__enable
  block:

  - name: Create directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0750
    with_items: "{{ supervisor__directories }}"

  - name: Generate configuration 
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "etc/supervisor/conf.d/service.conf.j2"
      dest: "/etc/supervisor/conf.d/{{ item.name }}.conf"
      owner: root
      group: root
      mode: 0644
    vars:
      service: "{{ item }}"
    with_items: "{{ supervisor__services }}"
