#!/bin/bash

#
# (c) 2020-2022,  Gerrit Beine, mail@gerritbeine.com
#

OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

function usage()
{
        echo "Usage: ./check_pass_alive"
}

function check_pass_alive()
{
	RESULT=`$TIMEOUT -f 5 $PODMAN exec -it pass pass check/alive`
	if [ $? == 0 ]; then
		echo "OK: pass is alive $RESULT"
		exit $OK
	else
		echo "CRITICAL: something's wrong"
		exit $CRITICAL
	fi
}

# -- Main -- #

TIMEOUT=/usr/bin/timeout
PODMAN=/usr/bin/podman

check_pass_alive
