---

- name: Deploy phpMyAdmin container
  tags: [ 'app_phpmyadmin' ]
  block:

    - name: Deploy container via podman
      ansible.builtin.import_role:
        name: podman
      vars:
        pod_containers:
          - "{{ app_phpmyadmin__container }}"
