---

- name: Deploy phpMyAdmin container
  tags: [ 'app_phpmyadmin' ]
  block:

    - name: Create podman containers
      ansible.builtin.debug:
        msg: "{{ app_phpmyadmin__podman_container }}"
      when: ansible_check_mode

    - name: Create podman containers
      containers.podman.podman_container:
        name: "{{ app_phpmyadmin__podman_container.name }}"
        hostname: "{{ app_phpmyadmin__podman_container.hostname }}"
        image: "{{ app_phpmyadmin__podman_container.image }}"
        ip: "{{ app_phpmyadmin__podman_container.ip }}"
        network: "{{ app_phpmyadmin__podman_container.network }}"
        restart_policy: "{{ app_phpmyadmin__podman_container.restart_policy }}"
        env: "{{ app_phpmyadmin__podman_container.environment }}"
        etc_hosts: "{{ app_phpmyadmin__podman_container.hosts }}"
      when: not ansible_check_mode
