---

- name: Install and configure dovecot
  tags: [ 'dovecot' ]
  when: dovecot__enable
  block:

  - name: Install dovecot packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ dovecot__packages_combined }}"

  - name: Create log directory
    ansible.builtin.file:
      dest: "{{ dovecot__log_path }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Remove obsolete configuration files
    tags: [ 'configuration' ]
    ansible.builtin.file:
      path: "{{ dovecot__etc_path }}/{{ item }}"
      state: absent
    with_items: "{{ dovecot__files_remove }}"
    notify:
    - Restart dovecot

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: etc/dovecot/dovecot.conf.j2
      dest: "{{ dovecot__etc_path }}/dovecot.conf"
    - src: etc/logrotate.d/dovecot.j2
      dest: "/etc/logrotate.d/dovecot"
    notify:
    - Restart dovecot

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "etc/dovecot/{{ item.key }}.j2"
      dest: "{{ dovecot__etc_path }}/{{ item.key }}"
      owner: root
      group: root
      mode: "{{ item.value._mode | default('0644') }}"
    vars:
      conf: "{{ item.value }}"
    loop: "{{ dovecot__conf | dict2items }}"
    notify:
    - Restart dovecot
