---

- name: Install and configure OpenDKIM
  tags: [ 'mail_opendkim' ]
  block:

    - name: Install OpenDKIM
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ mail_opendkim__packages }}"

    - name: "Generate DKIM private key"
      ansible.builtin.shell: "test -f {{ mail_opendkim__key_file }} || {{ mail_opendkim__key_genkey }} --bits={{ mail_opendkim__key_bits }} --domain={{ mail_opendkim__key_domain }} --selector={{ mail_opendkim__key_selector }} --directory={{ mail_opendkim__key_dir }}"

    - name: Create OpenDKIM directories
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        state: directory
        owner: "{{ mail_opendkim__user }}"
        group: "{{ mail_opendkim__group }}"
        mode: '750'
      with_items:
        - dest: "{{ mail_opendkim__etc_dir }}"
        - dest: "{{ mail_opendkim__lib_dir }}"
        - dest: "{{ mail_opendkim__log_dir }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '644'
      with_items:
        - src: opendkim.j2
          dest: /etc/default/opendkim
        - src: opendkim.conf.j2
          dest: /etc/opendkim.conf
      notify:
        - Restart OpenDKIM
