---

#
# Substitutes - do not change
#

app_foundryvtt__network: "{{ foundryvtt_network | mandatory }}"
app_foundryvtt__version: "{{ foundryvtt_version | default('latest') }}"

app_foundryvtt__hosts: "{{ foundryvtt_hosts | default({}) }}"
app_foundryvtt__environment: "{{ foundryvtt_environment | default({}) }}"
app_foundryvtt__publish: "{{ foundryvtt_publish | default([]) }}"
app_foundryvtt__timezone: "{{ foundryvtt_timezone | default(bootstrap_timezone__timezone) }}"

app_foundryvtt__containers: "{{ foundryvtt_containers | default([]) }}"

#
# Defaults - do not change
#

app_foundryvtt__container_default:
  image: "docker.io/gbeine/foundry:{{ app_foundryvtt__version }}"
  network: "{{ app_foundryvtt__network }}"
  restart_policy: 'always'
  hosts: "{{ app_foundryvtt__hosts }}"
  environment: "{{ app_foundryvtt__environment }}"
  publish: "{{ app_foundryvtt__publish }}"
  timezone: "{{ app_foundryvtt__timezone }}"
