---

#
# Substitutes - do not change
#

app_bookstack__user: "{{ bookstack_user | default('bookstack') }}"
app_bookstack__uid: "{{ bookstack_uid | mandatory }}"
app_bookstack__gid: "{{ bookstack_gid | mandatory }}"
app_bookstack__home: "{{ bookstack_home | mandatory }}"

app_bookstack__hostname: "{{ bookstack_hostname | default('bookstack.localhost') }}"
app_bookstack__ip: "{{ bookstack_ip | mandatory }}"
app_bookstack__network: "{{ bookstack_network | mandatory }}"
app_bookstack__url: "{{ bookstack_url | mandatory }}"
app_bookstack__db_host: "{{ bookstack_db_host | mandatory }}"
app_bookstack__db_port: "{{ bookstack_db_port | default(3306) }}"
app_bookstack__db_user: "{{ bookstack_db_user | default('bookstack') }}"
app_bookstack__db_pass: "{{ bookstack_db_pass | mandatory }}"
app_bookstack__db_database: "{{ bookstack_db_database | default('bookstack') }}"

app_bookstack__hosts: "{{ bookstack_hosts | default({}) }}"

app_bookstack__container: "{{ app_bookstack__container_default | combine(bookstack_container | default({})) }}"
app_bookstack__account: "{{ app_bookstack__account_default | combine(bookstack_account | default({})) }}"

#
# Defaults - do not change
#

app_bookstack__account_default:
  user: "{{ app_bookstack__user }}"
  uid: "{{ app_bookstack__uid }}"
  gid: "{{ app_bookstack__gid }}"
  home: "{{ app_bookstack__home }}"

app_bookstack__container_default:
  name: bookstack
  hostname: "{{ app_bookstack__hostname }}"
  image: 'lscr.io/linuxserver/bookstack:latest'
  ip: "{{ app_bookstack__ip }}"
  network: "{{ app_bookstack__network }}"
  restart_policy: always
  environment:
    - PUID: "{{ app_bookstack__uid }}"
    - PGID: "{{ app_bookstack__gid }}"
    - APP_URL: "{{ app_bookstack__url }}"
    - DB_HOST: "{{ app_bookstack__db_host }}"
    - DB_PORT: "{{ app_bookstack__db_port }}"
    - DB_USER: "{{ app_bookstack__db_user }}"
    - DB_PASS: "{{ app_bookstack__db_pass }}"
    - DB_DATABASE: "{{ app_bookstack__db_database }}"
  volumes:
    - "{{ app_bookstack__home }}:/config"
  expose:
    - 80
  requires:
    - mariadb
  hosts: "{{ app_bookstack__hosts }}"