---

#
# Substitutes - do not change
#

app_bookstack__user: "{{ bookstack_user | default('bookstack') }}"
app_bookstack__uid: "{{ bookstack_uid | mandatory }}"
app_bookstack__gid: "{{ bookstack_gid | default(app_bookstack__uid) }}"
app_bookstack__home: "{{ bookstack_home | mandatory }}"

app_bookstack__hostname: "{{ bookstack_hostname | default('bookstack.localhost') }}"
app_bookstack__ip: "{{ bookstack_ip | mandatory }}"
app_bookstack__ipv6: "{{ bookstack_ipv6 | default('') }}"
app_bookstack__version: "{{ bookstack_version | default('latest') }}"

app_bookstack__network: "{{ bookstack_network | mandatory }}"
app_bookstack__hosts: "{{ bookstack_hosts | default({}) }}"
app_bookstack__timezone: "{{ bookstack_timezone | default(bootstrap_timezone__timezone) }}"

app_bookstack__url: "{{ bookstack_url | mandatory }}"
app_bookstack__db_host: "{{ bookstack_db_host | mandatory }}"
app_bookstack__db_port: "{{ bookstack_db_port | default(3306) }}"
app_bookstack__db_user: "{{ bookstack_db_user | default('bookstack') }}"
app_bookstack__db_pass: "{{ bookstack_db_pass | mandatory }}"
app_bookstack__db_database: "{{ bookstack_db_database | default('bookstack') }}"

app_bookstack__container: "{{ app_bookstack__container_default | combine(bookstack_container | default({})) }}"
app_bookstack__account: "{{ app_bookstack__account_default | combine(bookstack_account | default({})) }}"

app_bookstack__app_key: "{{ bookstack_app_key | mandatory }}"
app_bookstack__app_url: "{{ app_bookstack__url }}"

app_bookstack__mail_driver: "{{ bookstack_mail_driver | default('sendmail') }}"

app_bookstack__mail_from_name: "{{ bookstack_mail_from_name | default('BookStack') }}"
app_bookstack__mail_from: "{{ bookstack_mail_from | mandatory }}"
app_bookstack__mail_host: "{{ bookstack_mail_host | default('localhost') }}"
app_bookstack__mail_port: "{{ bookstack_mail_port | default(25) }}"
app_bookstack__mail_username: "{{ bookstack_mail_username | default('null') }}"
app_bookstack__mail_password: "{{ bookstack_mail_password | default('null') }}"
app_bookstack__mail_encryption: "{{ bookstack_mail_encryption | default('null') }}"
app_bookstack__mail_sendmail_command: "{{ bookstack_mail_sendmail_command | default('/usr/sbin/sendmail -bs') }}"

app_bookstack__auth_method: "{{ bookstack_auth_method | default('') }}"

app_bookstack__ldap_server: "{{ bookstack_ldap_server |  default('localhost') }}"
app_bookstack__ldap_base_dn: "{{ bookstack_ldap_base_dn |  default('dc=example,dc=org') }}"
app_bookstack__ldap_dn: "{{ bookstack_ldap_dn | default('') }}"
app_bookstack__ldap_pass: "{{ bookstack_ldap_pass | default('') }}"
app_bookstack__ldap_filter: "{{ bookstack_ldap_filter | default('(&(uid=${user}))') }}"
app_bookstack__ldap_version: "{{ bookstack_ldap_version | default(3) }}"
app_bookstack__ldap_uid: "{{ bookstack_ldap_uid | default('uid') }}"
app_bookstack__ldap_email_attribute: "{{ bookstack_ldap_email_attribute | default('mail') }}"
app_bookstack__ldap_display_name_attribute: "{{ bookstack_ldap_display_name_attribute | default('cn') }}"
app_bookstack__ldap_user_to_groups: "{{ bookstack_ldap_user_to_groups | default(false) }}"
app_bookstack__ldap_group_attribute: "{{ bookstack_ldap_group_attribute | default('memberOf') }}"
app_bookstack__ldap_remove_from_groups: "{{ bookstack_ldap_remove_from_groups |  default(true) }}"

app_bookstack__drawio: "{{ bookstack_drawio | default('') }}"

app_bookstack__session_secure_cookie: "{{ bookstack_session_secure_cookie | default(true) }}"
app_bookstack__session_lifetime: "{{ bookstack_session_lifetime | default(120) }}"

app_bookstack__ca_file: "{{ bookstack_ca | default('') }}"

#
# Defaults - do not change
#

app_bookstack__config_dir: "{{ app_bookstack__home }}/www"

app_bookstack__account_default:
  user: "{{ app_bookstack__user }}"
  uid: "{{ app_bookstack__uid }}"
  gid: "{{ app_bookstack__gid }}"
  home: "{{ app_bookstack__home }}"

app_bookstack__container_default:
  name: bookstack
  hostname: "{{ app_bookstack__hostname }}"
  image: 'lscr.io/linuxserver/bookstack:latest'
  ip: "{{ app_bookstack__ip }}"
  network: "{{ app_bookstack__network }}"
  restart_policy: always
  environment:
    PUID: "{{ app_bookstack__uid }}"
    PGID: "{{ app_bookstack__gid }}"
    APP_URL: "{{ app_bookstack__url }}"
    DB_HOST: "{{ app_bookstack__db_host }}"
    DB_PORT: "{{ app_bookstack__db_port }}"
    DB_USER: "{{ app_bookstack__db_user }}"
    DB_PASS: "{{ app_bookstack__db_pass }}"
    DB_DATABASE: "{{ app_bookstack__db_database }}"
  volumes:
    - "{{ app_bookstack__home }}:/config"
  hosts: "{{ app_bookstack__hosts }}"
  timezone: "{{ app_bookstack__timezone }}"
