---

- name: Deploy forward-domain container
  tags: [ 'app_forward_domain' ]
  block:

    - name: Create forward-domain home directory
      ansible.builtin.file:
        mode: '750'
        owner: nobody
        group: nogroup
        path: "{{ app_forward_domain__home }}"
        state: directory
      when: not ansible_check_mode

    - name: Create podman containers
      ansible.builtin.debug:
        msg: "{{ app_forward_domain__container_default }}"
      when: ansible_check_mode

    - name: Create podman containers
      containers.podman.podman_container: "{{ app_forward_domain__container_default }}"
      when: not ansible_check_mode
