---

- name: Deploy Hugo container
  tags: [ 'app_hugo' ]
  block:

    - name: Create sites configuration
      include_tasks: site.yml
      loop_control:
        loop_var: site
      with_items: "{{ app_hugo__sites }}"

