---

- name: "Create Hugo site {{ site.name }} container"
  containers.podman.podman_container:
    name: "{{ site.name }}"
    hostname: "{{ site.hostname }}"
    image: "{{ site.image | default(app_hugo__image) }}"
    ip: "{{ site.ip }}"
    network: "{{ site.network | default(app_hugo__network) }}"
    recreate: "{{ podman___update_mode | default(false) }}"
    restart_policy: "{{ site.restart_policy | default(app_hugo__restart_policy) }}"
    timezone: "{{ site.timezone | default(bootstrap_timezone__timezone) }}"
    env:
      HUGO_REPO: "{{ site.repo }}"
    command: "{{ site.command | default(app_hugo__command) }}"
