---

- name: 'Install Telegraf'
  tags: [ 'telegraf'  ]
  block:

    - name: 'Create Telegraf directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ telegraf__home }}"

    - name: 'Create Telegraf directories'
      ansible.builtin.template:
        src: 'telegraf.conf.j2'
        dest: "{{ telegraf__home }}/telegraf.conf"
        owner: 'root'
        group: 'root'
        mode: '644'
      notify:
        - 'Restart Telegraf container'

    - name: 'Install Telegraf container'
      containers.podman.podman_container:
        name: "{{ telegraf__container.name }}"
        hostname: "{{ telegraf__container.hostname }}"
        image: "{{ telegraf__container.image }}"
        ip: "{{ telegraf__container.ip }}"
        network: "{{ telegraf__container.network }}"
        etc_hosts: "{{ telegraf__container.hosts }}"
        timezone: "{{ telegraf__container.timezone }}"
        volume: "{{ telegraf__container.volumes }}"
        pull: 'always'
        cap_add:
          - 'cap_net_raw'
      when: telegraf__ipv6 | length == 0
