---

- name: 'Deploy mautrix Discord bridge container'
  tags: [ 'matrix_bridge_discord' ]
  block:

    - name: "Has configuration been generate?"
      ansible.builtin.stat:
        path: "{{ matrix_bridge_discord__home }}/config.yaml"
      register: 'matrix_bridge_discord_configuration_stat_result'

    - name: 'Generate mautrix discord bridge configuration'
      containers.podman.podman_container:
        name: "{{ matrix_bridge_discord__container.name }}-generate"
        hostname: "{{ matrix_bridge_discord__container.hostname }}"
        image: "{{ matrix_bridge_discord__container.image }}"
        ip: "{{ matrix_bridge_discord__container.ip }}"
        network: "{{ matrix_bridge_discord__container.network }}"
        etc_hosts: "{{ matrix_bridge_discord__container.hosts }}"
        env: "{{ matrix_bridge_discord__container.environment }}"
        timezone: "{{ matrix_bridge_discord__container.timezone }}"
        volume: "{{ matrix_bridge_discord__container.volumes }}"
        pull: 'always'
        rm: true
      when: matrix_bridge_discord__ipv6 | length == 0 and not matrix_bridge_discord_configuration_stat_result.stat.exists

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ matrix_bridge_discord__container.name }}"
        hostname: "{{ matrix_bridge_discord__container.hostname }}"
        image: "{{ matrix_bridge_discord__container.image }}"
        ip: "{{ matrix_bridge_discord__container.ip }}"
        network: "{{ matrix_bridge_discord__container.network }}"
        restart_policy: "{{ matrix_bridge_discord__container.restart_policy }}"
        etc_hosts: "{{ matrix_bridge_discord__container.hosts }}"
        dns_servers: "{{ matrix_bridge_discord__container.dns_servers }}"
        env: "{{ matrix_bridge_discord__container.environment }}"
        timezone: "{{ matrix_bridge_discord__container.timezone }}"
        volume: "{{ matrix_bridge_discord__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: |
        matrix_bridge_discord__ipv6 | length == 0
        and matrix_bridge_discord_configuration_stat_result.stat.exists
        and not matrix_bridge_discord__setup
