---

- name: Install MongoDB
  tags: [ 'database_mongodb'  ]
  block:

    - name: Install MongoDB using podman
      ansible.builtin.include_tasks:
        file: podman.yml
      when: database_mongodb__use_podman
