---
# tasks file for roles/gitlab

- name: Install and configure gitlab
  tags: [ 'gitlab' ]
  when: gitlab__enable
  block:

  - name: Create gitlab configuration file
    tags: [ 'bootstrap' ]
    ansible.builtin.template:
      src: etc/gitlab/gitlab.rb
      dest: /etc/gitlab/gitlab.rb
      owner: root
      group: root
      mode: 0600
  
  - name: Install gitlab packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ gitlab__packages_combined }}"
