---
# tasks file for roles/gitlab

- name: Install and configure gitlab via docker
  tags: [ 'gitlab' ]
  when: gitlab__enable and gitlab__docker
  block:

  - name: Create directories for container
    tags: [ 'configuration' ]
    ansible.builtin.file:
      path: "{{ item }}"
      owner: root
      group: root
      state: directory
    with_items:
      - "{{ gitlab_home }}"
      - "{{ gitlab_data }}"
      - "{{ gitlab_logs }}"
      - "{{ gitlab_config }}"

  - name: Create gitlab.rb
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: gitlab.rb.j2
      dest: "{{ gitlab_config }}/gitlab.rb"
      owner: root
      group: root
      mode: 0640

  - name: Create docker-compose for gitlab
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: docker-compose.yml.j2
      dest: "{{ gitlab__home }}/docker-compose.yml"
      owner: root
      group: root
      mode: 0644
