---

- name: Install and configure SpamPD
  tags: [ 'mail_spampd' ]
  block:

    - name: Install SpamAssassin
      ansible.builtin.import_role:
        name: mail_spamassassin

    - name: Install SpamPD
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ mail_spampd__packages }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '644'
      with_items:
        - src: spampd.j2
          dest: /etc/default/spampd
        - src: spampd.conf.j2
          dest: /etc/spampd.conf
      notify:
        - Restart SpamPD
