---

- name: 'Restart PowerDNS container'
  ansible.builtin.systemd_service:
    name: "{{ dns_powerdns__container.name }}"
    state: 'restarted'
  when: 'not ansible_check_mode and dns_powerdns__use_podman'
