---

- name: 'Removes all anonymous user accounts'
  community.mysql.mysql_user:
    login_user: 'root'
    login_password: "{{ database_mariadb__root_password }}"
    login_host: "{{ database_mariadb__ip }}"
    name: "{{ item }}"
    host_all: 'yes'
    state: 'absent'
  with_items:
    - ''
    - 'PUBLIC'

- name: 'Create database users with privileges'
  community.mysql.mysql_user:
    login_user: 'root'
    login_password: "{{ database_mariadb__root_password }}"
    login_host: "{{ database_mariadb__ip }}"
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ database_mariadb__passwords[item.name] }}"
    priv: "{{ item.privileges }}"
    state: 'present'
  with_items: "{{ database_mariadb__accounts }}"
