---

- name: Install MariaDB using apt
  block:

    - name: Install MariaDB packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ database_mariadb__packages }}"
      register: database_mariadb_packages_installation_result

    - name: Set password for root
      ansible.builtin.shell: "{{ database_mariadb__server_password_reset }}"
      when: database_mariadb__password.root is defined and database_mariadb_packages_installation_result.changed

    - name: Generate configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('644') }}"
      with_items:
        - src: mariadb.cnf.j2
          dest: "{{ database_mariadb__etc_dir }}/mariadb.cnf"
        - src: mysql.cnf.j2
          dest: "{{ database_mariadb__etc_dir }}/conf.d/mysql.cnf"
        - src: mysqldump.cnf.j2
          dest: "{{ database_mariadb__etc_dir }}/conf.d/mysqldump.cnf"
        - src: 50-client.cnf.j2
          dest: "{{ database_mariadb__etc_dir }}/mariadb.conf.d/50-client.cnf"
        - src: 50-mysql-clients.cnf.j2
          dest: "{{ database_mariadb__etc_dir }}/mariadb.conf.d/50-mysql-clients.cnf"
        - src: 50-server.cnf.j2
          dest: "{{ database_mariadb__etc_dir }}/mariadb.conf.d/50-server.cnf"

    - name: Removes all anonymous user accounts
      community.mysql.mysql_user:
        login_user: root
        login_password: "{{ database_mariadb__password.root }}"
        login_unix_socket: '/var/run/mysqld/mysqld.sock'
        name: ''
        host_all: yes
        state: absent

    - name: Create databases
      community.mysql.mysql_db:
        login_user: root
        login_password: "{{ database_mariadb__password.root }}"
        login_unix_socket: '/var/run/mysqld/mysqld.sock'
        name: "{{ item.name }}"
        encoding: "{{ item.encoding | default('utf8') }}"
        collation: "{{ item.collation | default('utf8_bin') }}"
        state: present
      with_items: "{{ database_mariadb__databases }}"

    - name: Create database users with privileges
      community.mysql.mysql_user:
        login_user: root
        login_password: "{{ database_mariadb__password.root }}"
        login_unix_socket: '/var/run/mysqld/mysqld.sock'
        name: "{{ item.name }}"
        host: "{{ item.host | default('localhost') }}"
        password: "{{ database_mariadb__password[item.name] }}"
        priv: "{{ item.privileges }}"
        state: present
      with_items: "{{ database_mariadb__accounts }}"

    - name: Generate root login configuration
      ansible.builtin.template:
        src: my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0600
