---

- name: Install MariaDB using apt
  block:

    - name: Install MariaDB packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ database_mariadb__packages }}"
      register: database_mariadb_packages_installation_result

    - name: Set password for root
      ansible.builtin.shell: "{{ database_mariadb__server_password_reset }}"
      when: database_mariadb__password.root is defined and database_mariadb_packages_installation_result.changed

    - name: Removes all anonymous user accounts
      community.mysql.mysql_user:
        login_user: root
        login_password: "{{ database_mariadb__password.root }}"
        login_unix_socket: '/var/run/mysqld/mysqld.sock'
        name: ''
        host_all: yes
        state: absent

    - name: Create databases
      community.mysql.mysql_db:
        login_user: root
        login_password: "{{ database_mariadb__password.root }}"
        login_unix_socket: '/var/run/mysqld/mysqld.sock'
        name: "{{ database_mariadb__databases }}"
        encoding: utf8
        collation: utf8_bin
        state: present

    - name: Create database users with privileges
      community.mysql.mysql_user:
        login_user: root
        login_password: "{{ database_mariadb__password.root }}"
        login_unix_socket: '/var/run/mysqld/mysqld.sock'
        name: "{{ item.name }}"
        password: "{{ database_mariadb__password[item.name] }}"
        priv: "{{ item.privileges }}"
        state: present
      with_items: "{{ database_mariadb__accounts }}"
