---

- name: 'Create databases'
  community.mysql.mysql_db:
    login_user: 'root'
    login_password: "{{ database_mariadb__root_password }}"
    login_host: "{{ database_mariadb__ip }}"
    name: "{{ database_mariadb__databases }}"
    state: 'present'
