---

- name: Install MariaDB
  tags: [ 'database_mariadb'  ]
  block:

    - name: Install MariaDB packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ database_mariadb__packages }}"
      register: database_mariadb_packages_installation_result

    - name: Install MariaDB using package management
      ansible.builtin.include_tasks:
        file: apt.yml
      when: not database_mariadb__use_podman

    - name: Install MariaDB using podman
      ansible.builtin.include_tasks:
        file: podman.yml
      when: database_mariadb__use_podman
