---

- name: 'Install MariaDB'
  tags: [ 'database_mariadb'  ]
  block:

    - name: 'Include OS-specific variables (podman)'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}-podman.yml"
        - "{{ ansible_facts['distribution'] }}-podman.yml"
      when: 'database_mariadb__use_podman'

    - name: 'Include OS-specific variables (native)'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
      when: 'not database_mariadb__use_podman'

    - name: 'Install MariaDB packages'
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ database_mariadb__packages }}"
      register: 'database_mariadb_packages_installation_result'

    - name: 'Generate root login configuration'
      no_log: true
      ansible.builtin.template:
        src: 'my.cnf.j2'
        dest: '/root/.my.cnf'
        owner: 'root'
        group: 'root'
        mode: '600'

    - name: 'Install MariaDB using package management'
      ansible.builtin.include_tasks:
        file: 'apt.yml'
      when: 'not database_mariadb__use_podman'

    - name: 'Install MariaDB using podman'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: 'database_mariadb__use_podman'

    - name: 'Initialize MariaDB'
      block:
        - name: 'Initialize MariaDB accounts'
          ansible.builtin.include_tasks:
            file: 'accounts.yml'
        - name: 'Initialize MariaDB databases'
          ansible.builtin.include_tasks:
            file: 'databases.yml'
      when: 'not ansible_check_mode and not podman___update_mode | bool'
