---

- name: Install MariaDB
  tags: [ 'database_mariadb'  ]
  block:

    - name: Install MariaDB using package management
      ansible.builtin.include_tasks:
        file: apt.yml
      when: not database_mariadb__use_podman

    - name: Install MariaDB using podman
      ansible.builtin.include_tasks:
        file: podman.yml
      when: database_mariadb__use_podman
