---

- name: 'Install MariaDB using podman'
  block:

    - name: 'Create MariaDB directory'
      ansible.builtin.file:
        mode: '700'
        owner: "{{ database_mariadb__uid }}"
        group: "{{ database_mariadb__gid }}"
        path: "{{ database_mariadb__home }}"
        state: 'directory'

    - name: 'Generate MariaDB configuration'
      ansible.builtin.template:
        src: 'podman-custom.cnf.j2'
        dest: "{{ database_mariadb__home }}/custom.cnf"
        owner: "{{ database_mariadb__uid }}"
        group: "{{ database_mariadb__gid }}"
        mode: '640'
      notify:
        - 'Restart MariaDB'
      when: 'not podman___update_mode | bool'

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'mariadb_password'
        data: "{{ database_mariadb__root_password }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd_service:
        name: "{{ database_mariadb__container.name }}"
        state: 'stopped'
      when: 'ansible_facts.services[database_mariadb__container.name + ".service"] is defined and ansible_facts.services[database_mariadb__container.name + ".service"]["status"] != "not-found"'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ database_mariadb__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install MariaDB container'
      containers.podman.podman_container:
        name: "{{ database_mariadb__container.name }}"
        hostname: "{{ database_mariadb__container.hostname }}"
        image: "{{ database_mariadb__container.image }}"
        ip: "{{ database_mariadb__container.ip }}"
        network: "{{ database_mariadb__container.network }}"
        expose: "{{ database_mariadb__container.expose | default([]) }}"
        publish: "{{ database_mariadb__container.publish | default([]) }}"
        timezone: "{{ database_mariadb__container.timezone }}"
        env: "{{ database_mariadb__container.environment }}"
        secrets: "{{ database_mariadb__container.secrets }}"
        volume: "{{ database_mariadb__container.volumes }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if database_mariadb__container.requires is defined %}
          Requires={{ database_mariadb__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'database_mariadb__ipv6 | length == 0'

    - name: 'Install MariaDB container'
      containers.podman.podman_container:
        name: "{{ database_mariadb__container.name }}"
        hostname: "{{ database_mariadb__container.hostname }}"
        image: "{{ database_mariadb__container.image }}"
        ip: "{{ database_mariadb__container.ip }}"
        ip6: "{{ database_mariadb__container.ipv6 }}"
        network: "{{ database_mariadb__container.network }}"
        expose: "{{ database_mariadb__container.expose | default([]) }}"
        publish: "{{ database_mariadb__container.publish | default([]) }}"
        timezone: "{{ database_mariadb__container.timezone }}"
        env: "{{ database_mariadb__container.environment }}"
        secrets: "{{ database_mariadb__container.secrets }}"
        volume: "{{ database_mariadb__container.volumes }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if database_mariadb__container.requires is defined %}
          Requires={{ database_mariadb__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'database_mariadb__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd_service:
        name: "{{ database_mariadb__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Wait for MariaDB port to be opened'
      ansible.builtin.wait_for:
        host: "{{ database_mariadb__container.ip }}"
        port: "{{ database_mariadb__port }}"
