---

- name: Install and configure clamsmtpd
  tags: [ 'clamav' ]
  when: clamav__clamsmtpd_enable
  block:

  - name: Install clamsmtpd
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ clamav__clamsmtpd_packages }}"

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/clamsmtpd.conf.j2
      dest: /etc/clamsmtpd.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - Restart clamsmtpd
