---

- name: Install and configure ClamAV
  tags: [ 'clamav' ]
  when: clamav__enable
  block:

  - name: Install ClamAV packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ clamav__packages }}"

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    with_items:
    - src: etc/clamav/freshclam.conf.j2
      dest: /etc/clamav/freshclam.conf
      owner: clamav
      group: adm
      mode: '0444'
    - src: etc/clamav/clamd.conf.j2
      dest: /etc/clamav/clamd.conf
      owner: root
      group: root
      mode: '0644'
    notify:
    - Restart clamav-daemon
    - Restart freshclam

  - name: Install clamsmtp
    when: clamav__clamsmtpd_enable
    include_tasks: clamsmtpd.yml
