---

- name: Install and configure WireGuard
  tags: [ vpn, wireguard]
  when: wireguard__enable
  block:
  
  - name: Install packages
    tags: [ packages ]
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ wireguard__packages }}"

  - name: Generate configuration files
    tags: [ configuration ]
    ansible.builtin.template:
      src: etc/wireguard/wg.conf.j2
      dest: "/etc/wireguard/{{ item.interface }}.conf"
      owner: root
      group: root
      mode: 0640
    vars:
      wgnet: "{{ item }}"
    register: wireguard__create_config_result
    notify:
    - Restart WireGuard
    with_items: "{{ wireguard__networks }}"

  - name: Enable service
    tags: [ configuration, service ]
    ansible.builtin.service:
      name: "wg-quick@{{ item.interface }}"
      state: started
      enabled: yes
    with_items: "{{ wireguard__networks }}"
