---

#
# Substitutes - do not change
#

monitoring_icinga_master__use_podman: "{{ icinga_master_use_podman | default(false) }}"

monitoring_icinga_master__hostname: "{{ icinga_master_hostname | default('icinga.' + dns_hostname) }}"
monitoring_icinga_master__ip: "{{ icinga_master_ip | mandatory }}"
monitoring_icinga_master__ipv6: "{{ icinga_master_ipv6 | default('') }}"
monitoring_icinga_master__network: "{{ icinga_master_network | mandatory }}"
monitoring_icinga_master__home: "{{ icinga_master_home | mandatory }}"
monitoring_icinga_master__version: "{{ icinga_master_version | default('latest') }}"

monitoring_icinga_master__etc_hosts: "{{ icinga_master_etc_hosts | default({}) }}"
monitoring_icinga_master__environment: "{{ icinga_master_environment | default(monitoring_icinga_master__environment_default) }}"
monitoring_icinga_master__publish: "{{ icinga_master_publish | default([]) }}"
monitoring_icinga_master__expose: "{{ icinga_master_expose | default([ 5665 ]) }}"

monitoring_icinga_master__container: "{{ monitoring_icinga_master__container_default | combine(icinga_container | default({})) }}"

monitoring_icinga_master__node_name: "{{ icinga_master_node_name | mandatory }}"
monitoring_icinga_master__certificate_realm: "{{ icinga_master_certificate_realm | default(monitoring_icinga_master__node_name) }}"

monitoring_icinga_master__configuration_files: "{{ icinga_master_configuration_files | default(monitoring_icinga_master__configuration_files_default) }}"
monitoring_icinga_master__configuration_files_absent: "{{ icinga_master_configuration_files_absent | default(monitoring_icinga_master__configuration_files_absent_default) }}"
monitoring_icinga_master__features_enabled: "{{ icinga_master_features_enabled | default(monitoring_icinga_master__features_enabled_default) }}"

monitoring_icinga_master__mysql_enabled: "{{ icinga_master_mysql | default(false) }}"
monitoring_icinga_master__pgsql_enabled: "{{ icinga_master_pgsql | default(false) }}"
monitoring_icinga_master__influxdb_enabled: "{{ icinga_master_influxdb | default(false) }}"

monitoring_icinga_master__api_accept_config: "{{ icinga_master_api_accept_config }}"
monitoring_icinga_master__api_accept_commands: "{{ icinga_master_api_accept_commands }}"
monitoring_icinga_master__api_bind_host: "{{ icinga_master_api_bind_host }}"
monitoring_icinga_master__api_bind_port: "{{ icinga_master_api_bind_port }}"
monitoring_icinga_master__api_users: "{{ icinga_master_api_users }}"
monitoring_icinga_master__commands: "{{ monitoring_icinga_master__commands_default }}"
monitoring_icinga_master__constants: "{{ icinga_master_constants }}"
monitoring_icinga_master__debug_log_file: "{{ icinga_master_debug_log_file }}"
monitoring_icinga_master__debug_log_severity: "{{ icinga_master_debug_log_severity }}"
monitoring_icinga_master__endpoints: "{{ icinga_master_endpoints }}"
monitoring_icinga_master__host_dependencies: "{{ icinga_master_host_dependencies }}"
monitoring_icinga_master__host_groups: "{{ icinga_master_host_groups }}"
monitoring_icinga_master__hosts: "{{ icinga_master_hosts }}"
monitoring_icinga_master__includes: "{{ icinga_master_includes }}"
monitoring_icinga_master__mysql_user: "{{ icinga_master_mysql_user }}"
monitoring_icinga_master__mysql_password: "{{ icinga_master_mysql_password }}"
monitoring_icinga_master__mysql_host: "{{ icinga_master_mysql_host }}"
monitoring_icinga_master__mysql_database: "{{ icinga_master_mysql_database }}"
monitoring_icinga_master__influxdb_host: "{{ icinga_master_influxdb_host }}"
monitoring_icinga_master__influxdb_port: "{{ icinga_master_influxdb_port }}"
monitoring_icinga_master__influxdb_token: "{{ icinga_master_influxdb_token }}"
monitoring_icinga_master__influxdb_bucket: "{{ icinga_master_influxdb_bucket }}"
monitoring_icinga_master__influxdb_organization: "{{ icinga_master_influxdb_organization }}"
monitoring_icinga_master__influxdb_thresholds: "{{ icinga_master_influxdb_thresholds }}"
monitoring_icinga_master__influxdb_metadata: "{{ icinga_master_influxdb_metadata }}"
monitoring_icinga_master__main_log_file: "{{ icinga_master_main_log_file }}"
monitoring_icinga_master__main_log_severity: "{{ icinga_master_main_log_severity }}"
monitoring_icinga_master__notifications: "{{ icinga_master_notifications }}"
monitoring_icinga_master__service_dependencies: "{{ icinga_master_service_dependencies }}"
monitoring_icinga_master__service_groups: "{{ icinga_master_service_groups }}"
monitoring_icinga_master__services: "{{ icinga_master_services }}"
monitoring_icinga_master__templates: "{{ icinga_master_templates }}"
monitoring_icinga_master__timeperiods: "{{ icinga_master_timeperiods }}"
monitoring_icinga_master__user_groups: "{{ icinga_master_user_groups }}"
monitoring_icinga_master__users: "{{ icinga_master_users }}"
monitoring_icinga_master__zones: "{{ icinga_master_zones }}"
monitoring_icinga_master__zone_hosts: "{{ icinga_master_zone_hosts }}"
monitoring_icinga_master__zone_services: "{{ icinga_master_zone_services }}"

#
# Defaults - do not change
#

monitoring_icinga_master__data_dir: "{{ monitoring_icinga_master__home }}/data"
monitoring_icinga_master__etc_dir: "{{ monitoring_icinga_master__data_dir + '/etc' if monitoring_icinga_master__use_podman else '/etc' }}"

monitoring_icinga_master__dir: "{{ icinga_master_config_dir | default(monitoring_icinga_master__etc_dir + '/icinga2') }}"
monitoring_icinga_master__conf_dir: "{{ icinga_master_conf_dir | default(monitoring_icinga_master__dir + '/conf.d') }}"
monitoring_icinga_master__features_available_dir: "{{ icinga_master_features_available_dir | default(monitoring_icinga_master__dir + '/features-available') }}"
monitoring_icinga_master__scripts_dir: "{{ icinga_master_scripts_dir | default(monitoring_icinga_master__dir + '/scripts') }}"

monitoring_icinga_master__var_dir: "{{ monitoring_icinga_master__data_dir }}/var"
monitoring_icinga_master__cert_dir: "{{ monitoring_icinga_master__var_dir }}/lib/icinga2/certs"

monitoring_icinga_master__user: 5665
monitoring_icinga_master__group: 5665

monitoring_icinga_master__configuration_files_mysql: "{{ [
  { 'src': 'ido-mysql.conf.j2', 'dest': monitoring_icinga_master__features_available_dir + '/ido-mysql.conf' }
] if monitoring_icinga_master__mysql_enabled else [] }}"

monitoring_icinga_master__configuration_files_pgsql: "{{ [
  { 'src': 'ido-pgsql.conf.j2', 'dest': monitoring_icinga_master__features_available_dir + '/ido-pgsql.conf' }
] if monitoring_icinga_master__pgsql_enabled else [] }}"

monitoring_icinga_master__configuration_files_influxdb: "{{ [
  { 'src': 'influxdb.conf.j2', 'dest': monitoring_icinga_master__features_available_dir + '/influxdb.conf' }
] if monitoring_icinga_master__influxdb_enabled else [] }}"

monitoring_icinga_master__configuration_files_default: "{{ [
  { 'src': 'api.conf.j2', 'dest': monitoring_icinga_master__features_available_dir + '/api.conf' },
  { 'src': 'checker.conf.j2', 'dest': monitoring_icinga_master__features_available_dir + '/checker.conf' },
  { 'src': 'debuglog.conf.j2', 'dest': monitoring_icinga_master__features_available_dir + '/debuglog.conf' },
  { 'src': 'mainlog.conf.j2', 'dest': monitoring_icinga_master__features_available_dir + '/mainlog.conf' },
  { 'src': 'notification.conf.j2', 'dest': monitoring_icinga_master__features_available_dir + '/notification.conf' },
  { 'src': 'constants.conf.j2', 'dest': monitoring_icinga_master__dir + '/constants.conf' },
  { 'src': 'icinga2.conf.j2', 'dest': monitoring_icinga_master__dir + '/icinga2.conf' },
  { 'src': 'zones.conf.j2', 'dest': monitoring_icinga_master__dir + '/zones.conf' },
  { 'src': 'api-users.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/api-users.conf', 'mode': '600' },
  { 'src': 'app.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/app.conf' },
  { 'src': 'commands.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/commands.conf' },
  { 'src': 'host_dependencies.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/host_dependencies.conf' },
  { 'src': 'host_groups.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/host_groups.conf' },
  { 'src': 'hosts.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/hosts.conf' },
  { 'src': 'notifications.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/notifications.conf' },
  { 'src': 'service_dependencies.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/service_dependencies.conf' },
  { 'src': 'service_groups.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/service_groups.conf' },
  { 'src': 'services.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/services.conf' },
  { 'src': 'templates.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/templates.conf' },
  { 'src': 'timeperiods.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/timeperiods.conf' },
  { 'src': 'user_groups.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/user_groups.conf' },
  { 'src': 'users.conf.j2', 'dest': monitoring_icinga_master__conf_dir + '/users.conf' },
  { 'src': 'endpoints.conf.j2', 'dest': monitoring_icinga_master__dir + '/endpoints.conf' }
] +
    monitoring_icinga_master__configuration_files_mysql +
    monitoring_icinga_master__configuration_files_pgsql +
    monitoring_icinga_master__configuration_files_influxdb
}}"

monitoring_icinga_master__configuration_files_absent_default:
  - "{{ monitoring_icinga_master__conf_dir }}/apt.conf"
  - "{{ monitoring_icinga_master__conf_dir }}/downtimes.conf"

monitoring_icinga_master__features_enabled_mysql: "{{ [ 'ido-mysql' ] if monitoring_icinga_master__mysql_enabled else [] }}"

monitoring_icinga_master__features_enabled_pgsql: "{{ [ 'ido-pgsql' ] if monitoring_icinga_master__pgsql_enabled else [] }}"

monitoring_icinga_master__features_enabled_influxdb: "{{ [ 'influxdb' ] if monitoring_icinga_master__influxdb_enabled else [] }}"

monitoring_icinga_master__features_enabled_default: "{{ [
  'api',
  'checker',
  'mainlog',
  'notification'
] +
    monitoring_icinga_master__features_enabled_mysql +
    monitoring_icinga_master__features_enabled_pgsql +
    monitoring_icinga_master__features_enabled_influxdb
}}"

monitoring_icinga_master__commands_default:
  - name: 'mail-host-notification'
    object: 'NotificationCommand'
    command: '[ ConfigDir + "/scripts/mail-host-notification.sh" ]'
    arguments:
      - key: '-4'
        value: '"$notification_address$"'
      - key: '-6'
        value: '"$notification_address6$"'
      - key: '-b'
        value: '"$notification_author$"'
      - key: '-c'
        value: '"$notification_comment$"'
      - key: '-d'
        value:
          required: 'true'
          value: '"$notification_date$"'
      - key: '-f'
        value:
          value: '"$notification_from$"'
          description: '"Set from address. Requires GNU mailutils (Debian/Ubuntu) or mailx (RHEL/SUSE)"'
      - key: '-i'
        value: '"$notification_icingaweb2url$"'
      - key: '-l'
        value:
          required: 'true'
          value: '"$notification_hostname$"'
      - key: '-n'
        value:
          required: 'true'
          value: '"$notification_hostdisplayname$"'
      - key: '-o'
        value:
          required: 'true'
          value: '"$notification_hostoutput$"'
      - key: '-r'
        value:
          required: 'true'
          value: '"$notification_useremail$"'
      - key: '-s'
        value:
          required: 'true'
          value: '"$notification_hoststate$"'
      - key: '-t'
        value:
          required: 'true'
          value: '"$notification_type$"'
      - key: '-v'
        value: '"$notification_logtosyslog$"'
    vars:
      - key: 'notification_address'
        value: '"$address$"'
      - key: 'notification_address6'
        value: '"$address6$"'
      - key: 'notification_author'
        value: '"$notification.author$"'
      - key: 'notification_comment'
        value: '"$notification.comment$"'
      - key: 'notification_type'
        value: '"$notification.type$"'
      - key: 'notification_date'
        value: '"$icinga.long_date_time$"'
      - key: 'notification_hostname'
        value: '"$host.name$"'
      - key: 'notification_hostdisplayname'
        value: '"$host.display_name$"'
      - key: 'notification_hostoutput'
        value: '"$host.output$"'
      - key: 'notification_hoststate'
        value: '"$host.state$"'
      - key: 'notification_useremail'
        value: '"$user.email$"'
  - name: 'mail-service-notification'
    object: 'NotificationCommand'
    command: '[ ConfigDir + "/scripts/mail-service-notification.sh" ]'
    arguments:
      - key: '-4'
        value: '"$notification_address$"'
      - key: '-6'
        value: '"$notification_address6$"'
      - key: '-b'
        value: '"$notification_author$"'
      - key: '-c'
        value: '"$notification_comment$"'
      - key: '-d'
        value:
          required: 'true'
          value: '"$notification_date$"'
      - key: '-e'
        value:
          required: 'true'
          value: '"$notification_servicename$"'
      - key: '-f'
        value:
          value: '"$notification_from$"'
          description: '"Set from address. Requires GNU mailutils (Debian/Ubuntu) or mailx (RHEL/SUSE)"'
      - key: '-i'
        value: '"$notification_icingaweb2url$"'
      - key: '-l'
        value:
          required: 'true'
          value: '"$notification_hostname$"'
      - key: '-n'
        value:
          required: 'true'
          value: '"$notification_hostdisplayname$"'
      - key: '-o'
        value:
          required: 'true'
          value: '"$notification_serviceoutput$"'
      - key: '-r'
        value:
          required: 'true'
          value: '"$notification_useremail$"'
      - key: '-s'
        value:
          required: 'true'
          value: '"$notification_servicestate$"'
      - key: '-t'
        value:
          required: 'true'
          value: '"$notification_type$"'
      - key: '-u'
        value:
          required: 'true'
          value: '"$notification_servicedisplayname$"'
      - key: '-v'
        value: '"$notification_logtosyslog$"'
    vars:
      - key: 'notification_address'
        value: '"$address$"'
      - key: 'notification_address6'
        value: '"$address6$"'
      - key: 'notification_author'
        value: '"$notification.author$"'
      - key: 'notification_comment'
        value: '"$notification.comment$"'
      - key: 'notification_type'
        value: '"$notification.type$"'
      - key: 'notification_date'
        value: '"$icinga.long_date_time$"'
      - key: 'notification_hostname'
        value: '"$host.name$"'
      - key: 'notification_hostdisplayname'
        value: '"$host.display_name$"'
      - key: 'notification_servicename'
        value: '"$service.name$"'
      - key: 'notification_serviceoutput'
        value: '"$service.output$"'
      - key: 'notification_servicestate'
        value: '"$service.state$"'
      - key: 'notification_useremail'
        value: '"$user.email$"'
      - key: 'notification_servicedisplayname'
        value: '"$service.display_name$"'
  - name: 'push-host-notification'
    object: 'NotificationCommand'
    command: '[ ConfigDir + "/scripts/pushover.sh" ]'
    env:
      - key: 'token'
        value: '"$user.vars.pushover_token$"'
      - key: 'user'
        value: '"$user.vars.pushover_user$"'
      - key: 'title'
        value: '"$host.display_name$ ($address$): Status changed to $host.state$"'
      - key: 'message'
        value: '"$host.output$"'
  - name: 'push-service-notification'
    object: 'NotificationCommand'
    command: '[ ConfigDir + "/scripts/pushover.sh" ]'
    env:
      - key: 'token'
        value: '"$user.vars.pushover_token$"'
      - key: 'user'
        value: '"$user.vars.pushover_user$"'
      - key: 'title'
        value: '"$service.display_name$ on $host.display_name$: Status changed to $service.state$"'
      - key: 'message'
        value: '"$service.output$"'

monitoring_icinga_master__container_default:
  name: 'icinga'
  hostname: "{{ monitoring_icinga_master__hostname }}"
  image: "docker.io/icinga/icinga2:{{ monitoring_icinga_master__version }}"
  ip: "{{ monitoring_icinga_master__ip }}"
  ipv6: "{{ monitoring_icinga_master__ipv6 }}"
  network: "{{ monitoring_icinga_master__network }}"
  restart_policy: 'always'
  hosts: "{{ monitoring_icinga_master__etc_hosts }}"
  environment: "{{ monitoring_icinga_master__environment }}"
  publish: "{{ monitoring_icinga_master__publish }}"
  expose: "{{ monitoring_icinga_master__expose }}"
  timezone: "{{ bootstrap_timezone__timezone }}"

monitoring_icinga_master__environment_default:
  ICINGA_MASTER: 1

#monitoring_icinga_master__packages_mysql:
#  Debian: "{{ [
#    'icinga2-ido-mysql',
#    'default-mysql-client',
#    'libdbd-mysql-perl'
#] if monitoring_icinga_master__mysql_enabled else [] }}"
#
#monitoring_icinga_master__packages_pgsql:
#  Debian: "{{ [
#    'icinga2-ido-pgsql',
#    'postgresql-client'
#] if monitoring_icinga_master__pgsql_enabled else [] }}"
#
#monitoring_icinga_master__packages: "{{ monitoring_icinga_master__packages_default[bootstrap_ansible__distribution] | default([]) }}"
#
#monitoring_icinga_master__packages_default:
#  Debian: "{{ [
#    'icinga2',
#    'icinga2-bin',
#    'icinga2-common',
#    'monitoring-plugins',
#    'monitoring-plugins-basic',
#    'monitoring-plugins-common',
#    'monitoring-plugins-standard',
#    'libnet-snmp-perl'
#] +
#    monitoring_icinga_master__packages_mysql[bootstrap_ansible__distribution] +
#    monitoring_icinga_master__packages_pgsql[bootstrap_ansible__distribution]
#}}"
