---

- name: Restart Samba server
  tags: [ 'service' ]
  when: not ansible_check_mode
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - smbd
  - nmbd

- name: Restart winbind
  tags: [ 'service' ]
  when: samba__winbind_enable and not ansible_check_mode
  ansible.builtin.service:
    name: winbind
    state: restarted
