---

- name: Deploy FileRise container
  tags: [ 'app_filerise' ]
  block:

    - name: Create directories
      block:
        - ansible.builtin.file:
            path: "{{ item.uploads_dir }}"
            state: 'directory'
            mode: '0755'
            recurse: true
            owner: 99
            group: 100
          with_items: "{{ app_filerise__containers }}"
        - ansible.builtin.file:
            path: "{{ item.users_dir }}"
            state: 'directory'
            mode: '0755'
            recurse: true
            owner: 99
            group: 100
          with_items: "{{ app_filerise__containers }}"
        - ansible.builtin.file:
            path: "{{ item.metadata_dir }}"
            state: 'directory'
            mode: '0755'
            recurse: true
            owner: 99
            group: 100
          with_items: "{{ app_filerise__containers }}"

# See: https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html
    - name: Create podman containers
      containers.podman.podman_container:
        name: "{{ item.name | mandatory }}"
        hostname: "{{ item.hostname | mandatory }}"
        image: "{{ item.image | default(app_filerise__container_default.image) }}"
        ip: "{{ item.ip | mandatory }}"
        network: "{{ item.network | default(app_filerise__container_default.network) }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ item.restart_policy | default(app_filerise__container_default.restart_policy) }}"
        env: "{{ item.environment | default(app_filerise__container_default.environment) }}"
        timezone: "{{ item.timezone | default(app_filerise__container_default.timezone) }}"
        volume: "{{ [
          item.uploads_dir + ':/var/www/uploads',
          item.users_dir + ':/var/www/users',
          item.metadata_dir + ':/var/www/metadata'          
        ] }}"
      when: item.ipv6 | default('') | length == 0
      with_items: "{{ app_filerise__containers }}"

# See: https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html
    - name: Create podman containers
      containers.podman.podman_container:
        name: "{{ item.name | mandatory }}"
        hostname: "{{ item.hostname | mandatory }}"
        image: "{{ item.image | default(app_filerise__container_default.image) }}"
        ip: "{{ item.ip | mandatory }}"
        ipv6: "{{ item.ipv6 | mandatory }}"
        network: "{{ item.network | default(app_filerise__container_default.network) }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ item.restart_policy | default(app_filerise__container_default.restart_policy) }}"
        env: "{{ item.environment | default(app_filerise__container_default.environment) }}"
        timezone: "{{ item.timezone | default(app_filerise__container_default.timezone) }}"
        volume: "{{ [
          item.uploads_dir + ':/var/www/uploads',
          item.users_dir + ':/var/www/users',
          item.metadata_dir + ':/var/www/metadata'          
        ] }}"
      when: item.ipv6 | default('') | length > 0
      with_items: "{{ app_filerise__containers }}"
