---

- name: Common mail tasks
  tags: [ 'mail_common' ]
  block:

    - name: Generate forward file
      ansible.builtin.copy:
        dest: /root/.forward
        content: "{{ mail_common__root_forward }}"
        owner: root
        group: root
        mode: 0644
      when: mail_common__root_forward | length > 0
