---

- name: 'Create databases'
  community.postgresql.postgresql_db:
    login_user: 'postgres'
    login_password: "{{ database_postgresql__password }}"
    login_host: "{{ database_postgresql__ip }}"
    name: "{{ item.name }}"
    comment: "{{ item.comment | default ('') }}"
    owner: "{{ item.owner | default ('') }}"
    encoding: "{{ item.encoding | default ('') }}"
    lc_collate: "{{ item.lc_collate | default ('') }}"
    lc_ctype: "{{ item.lc_ctype | default ('') }}"
    locale_provider: "{{ item.locale_provider | default ('') }}"
    icu_locale: "{{ item.icu_locale | default ('') }}"
    template: "{{ item.template | default ('') }}"
    state: 'present'
  with_items: "{{ database_postgresql__databases }}"
