---

- name: 'Install PostgreSQL'
  tags: [ 'database_postgresql'  ]
  block:

    - name: 'Install PostgreSQL using podman'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: database_postgresql__use_podman
