---

- name: 'Install PostgreSQL using podman'
  block:

    - name: 'Create PostgreSQL directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ database_postgresql__data_dir }}"

    - name: 'Install PostgreSQL container'
      ansible.builtin.debug:
        msg: "{{ database_postgresql__container }}"
      when: ansible_check_mode

    - name: 'Install PostgreSQL container'
      containers.podman.podman_container:
        name: "{{ database_postgresql__container.name }}"
        hostname: "{{ database_postgresql__container.hostname }}"
        image: "{{ database_postgresql__container.image }}"
        ip: "{{ database_postgresql__container.ip }}"
        network: "{{ database_postgresql__container.network }}"
        expose: "{{ database_postgresql__container.expose | default([]) }}"
        publish: "{{ database_postgresql__container.publish | default([]) }}"
        restart_policy: "{{ database_postgresql__container.restart_policy }}"
        etc_hosts: "{{ database_postgresql__container.hosts }}"
        env: "{{ database_postgresql__container.environment }}"
        timezone: "{{ database_postgresql__container.timezone }}"
        volume: "{{ database_postgresql__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: database_postgresql__ipv6 | length == 0

    - name: 'Wait for PostgreSQL port to be opened'
      ansible.builtin.wait_for:
        host: "{{ database_postgresql__container.ip }}"
        port: "{{ database_postgresql__port }}"
        delay: 10
