---

- name: 'Install PostgreSQL using podman'
  block:

    - name: 'Create PostgreSQL directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ database_postgresql__data_dir }}"

    - name: 'Install PostgreSQL container'
      ansible.builtin.debug:
        msg: "{{ database_postgresql__container }}"
      when: ansible_check_mode

    - name: 'Install PostgreSQL container'
      containers.podman.podman_container:
        name: "{{ database_postgresql__container.name }}"
        hostname: "{{ database_postgresql__container.hostname }}"
        image: "{{ database_postgresql__container.image }}"
        ip: "{{ database_postgresql__container.ip }}"
        network: "{{ database_postgresql__container.network }}"
        expose: "{{ database_postgresql__container.expose | default([]) }}"
        publish: "{{ database_postgresql__container.publish | default([]) }}"
        restart_policy: "{{ database_postgresql__container.restart_policy }}"
        etc_hosts: "{{ database_postgresql__container.hosts }}"
        env: "{{ database_postgresql__container.environment }}"
        timezone: "{{ database_postgresql__container.timezone }}"
        volume: "{{ database_postgresql__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: database_postgresql__ipv6 | length == 0

    - name: 'Wait for PostgreSQL port to be opened'
      ansible.builtin.wait_for:
        host: "{{ database_postgresql__container.ip }}"
        port: "{{ database_postgresql__port }}"
        delay: 10

    - name: 'Create database users'
      community.postgresql.postgresql_user:
        login_db: 'postgres'
        login_user: 'postgres'
        login_password: "{{ database_postgresql__password }}"
        login_host: "{{ database_postgresql__ip }}"
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        password: "{{ database_postgresql__passwords[item.name] }}"
      with_items: "{{ database_postgresql__accounts }}"
      when: not ansible_check_mode and not podman___update_mode

    - name: 'Create databases'
      community.postgresql.postgresql_db:
        login_user: 'postgres'
        login_password: "{{ database_postgresql__password }}"
        login_host: "{{ database_postgresql__ip }}"
        name: "{{ item.name }}"
        comment: "{{ item.comment | default ('') }}"
        owner: "{{ item.owner | default ('') }}"
        encoding: "{{ item.encoding | default ('') }}"
        lc_collate: "{{ item.lc_collate | default ('') }}"
        lc_ctype: "{{ item.lc_ctype | default ('') }}"
        locale_provider: "{{ item.locale_provider | default ('') }}"
        icu_locale: "{{ item.icu_locale | default ('') }}"
        template: "{{ item.template | default ('') }}"
        state: 'present'
      with_items: "{{ database_postgresql__databases }}"
      when: not ansible_check_mode and not podman___update_mode

    - name: 'Grant privileges to users'
      community.postgresql.postgresql_privs:
        login_db: 'postgres'
        login_user: 'postgres'
        login_password: "{{ database_postgresql__password }}"
        login_host: "{{ database_postgresql__ip }}"
        type: "{{ item.type | default ('table') }}"
        privs: "{{ item.privs | default ('') }}"
        roles: "{{ item.roles }}"
      with_items: "{{ database_postgresql__privileges }}"
      when: not ansible_check_mode and not podman___update_mode

