---

- name: 'Grant privileges to users'
  community.postgresql.postgresql_privs:
    login_user: 'postgres'
    login_password: "{{ database_postgresql__password }}"
    login_host: "{{ database_postgresql__ip }}"
    login_db: "{{ item.database }}"
    type: "{{ item.type | default ('table') }}"
    objs: "{{ item.objects | default ('') }}"
    privs: "{{ item.privs | default ('') }}"
    roles: "{{ item.roles | default ('') }}"
#    schema: "{{ item.schema | default ('public') }}"
  with_items: "{{ database_postgresql__privileges }}"
