---

- name: 'Create database users'
  community.postgresql.postgresql_user:
    login_db: 'postgres'
    login_user: 'postgres'
    login_password: "{{ database_postgresql__password }}"
    login_host: "{{ database_postgresql__ip }}"
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    password: "{{ database_postgresql__passwords[item.name] }}"
    role_attr_flags: "{{ item.attributes | default ('') }}"
  with_items: "{{ database_postgresql__accounts }}"
