---

- name: 'Create replication slots'
  community.postgresql.postgresql_slot:
    login_db: 'postgres'
    login_user: 'postgres'
    login_password: "{{ database_postgresql__password }}"
    login_host: "{{ database_postgresql__ip }}"
    name: "{{ item.name }}"
    slot_type: "{{ item.type }}"
  with_items: "{{ database_postgresql__slots }}"
