---

- name: Install Redis using apt
  block:

    - name: Install Redis packages
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ database_redis__packages }}"
