---

- name: 'Loop over redis instances'
  tags: [ 'database_redis' ]
  include_role:
    name: 'database_redis'
    apply:
      tags: [ 'database_redis' ]
  loop: "{{ redis_instances }}"
  loop_control:
    loop_var: 'redis'
  vars:
    redis_home: "{{ redis.home }}"
    redis_ip: "{{ redis.ip }}"
    redis_ipv6: "{{ redis.ipv6 }}"
    redis_network: "{{ redis.network }}"
    redis_hostname: "{{ redis.hostname }}"
    redis_timezone: "{{ redis.timezone }}"
    redis_container: "{{ redis.container }}"
    redis_config: "{{ redis.config }}"
