---

- name: Install Redis
  tags: [ 'database_redis'  ]
  block:

    - name: Install Redis using package management
      ansible.builtin.include_tasks:
        file: 'apt.yml'
      when: not database_redis__use_podman

    - name: Install Redis using podman
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: database_redis__use_podman
