---

- name: 'Install Redis'
  tags: [ 'database_redis'  ]
  block:

    - name: 'Include OS-specific variables'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"

    - name: 'Install Redis using podman'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: 'database_redis__use_podman'
