---

- name: 'Install Redis'
  tags: [ 'database_redis'  ]
  block:

    - name: 'Include OS-specific variables'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"

    - name: 'Install Redis using podman'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: 'database_redis__use_podman'
