---

- name: 'Install Redis using podman'
  block:

    - name: 'Create Redis directory'
      ansible.builtin.file:
        mode: '750'
        path: "{{ database_redis__podman_home }}/data"
        state: 'directory'

    - name: 'Create Redis configuration file'
      ansible.builtin.copy:
        content: "{{ database_redis__config }}"
        dest: "{{ database_redis__podman_home }}/data/redis.conf"
        mode: '640'
      when: 'database_redis__config | length > 0'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ database_redis__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[database_redis__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ database_redis__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install Redis container'
      containers.podman.podman_container:
        name: "{{ database_redis__container.name }}"
        hostname: "{{ database_redis__container.hostname }}"
        image: "{{ database_redis__container.image }}"
        ip: "{{ database_redis__container.ip }}"
        network: "{{ database_redis__container.network }}"
        timezone: "{{ database_redis__container.timezone }}"
        expose: "{{ database_redis__container.expose | default(omit) }}"
        publish: "{{ database_redis__container.publish | default(omit) }}"
        secrets: "{{ database_redis__container.secrets | default(omit) }}"
        env: "{{ database_redis__container.environment | default(omit) }}"
        label: "{{ database_redis__container.labels | default(omit) }}"
        volume: "{{ database_redis__container.volumes }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if database_redis__container.requires is defined %}
          Requires={{ database_redis__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'database_redis__ipv6 | length == 0'

    - name: 'Install Redis container'
      containers.podman.podman_container:
        name: "{{ database_redis__container.name }}"
        hostname: "{{ database_redis__container.hostname }}"
        image: "{{ database_redis__container.image }}"
        ip: "{{ database_redis__container.ip }}"
        ip6: "{{ database_redis__container.ipv6 }}"
        network: "{{ database_redis__container.network }}"
        timezone: "{{ database_redis__container.timezone }}"
        expose: "{{ database_redis__container.expose | default(omit) }}"
        publish: "{{ database_redis__container.publish | default(omit) }}"
        secrets: "{{ database_redis__container.secrets | default(omit) }}"
        env: "{{ database_redis__container.environment | default(omit) }}"
        label: "{{ database_redis__container.labels | default(omit) }}"
        volume: "{{ database_redis__container.volumes }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if database_redis__container.requires is defined %}
          Requires={{ database_redis__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'database_redis__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd_service:
        name: "{{ database_redis__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Wait for Redis port to be opened'
      ansible.builtin.wait_for:
        host: "{{ database_redis__container.ip }}"
        port: "{{ database_redis__port }}"
