---

- name: Install Redis using podman
  block:

    - name: Create Redis directory
      ansible.builtin.file:
        mode: '750'
        path: "{{ database_redis__home }}/data"
        state: 'directory'
      when: not ansible_check_mode

    - name: Generate Redis configuration
      ansible.builtin.template:
        src: 'redis.conf.j2'
        dest: "{{ database_redis__home }}/redis.conf"
        mode: '640'
      notify: Restart Redis container

    - name: Install Redis container
      containers.podman.podman_container:
        name: "{{ database_redis__container.name }}"
        hostname: "{{ database_redis__container.hostname }}"
        image: "{{ database_redis__container.image }}"
        ip: "{{ database_redis__container.ip }}"
        network: "{{ database_redis__container.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ database_redis__container.restart_policy }}"
        etc_hosts: "{{ database_redis__container.hosts }}"
        env: "{{ database_redis__container.environment }}"
        timezone: "{{ database_redis__container.timezone }}"
        volume: "{{ database_redis__container.volumes }}"
      notify: Restart Redis container
      when: database_redis__ipv6 | length == 0
