---

- name: 'Install nextcloud whiteboard'
  tags: [ 'app_nextcloud_whiteboard' ]
  block:

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'whiteboard_jwt_secret'
        data: "{{ app_nextcloud_whiteboard__secret }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_nextcloud_whiteboard__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_nextcloud_whiteboard__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_nextcloud_whiteboard__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_nextcloud_whiteboard__container.name }}"
        hostname: "{{ app_nextcloud_whiteboard__container.hostname }}"
        image: "{{ app_nextcloud_whiteboard__container.image }}"
        ip: "{{ app_nextcloud_whiteboard__container.ip }}"
        ip6: "{{ app_nextcloud_whiteboard__container.ipv6 | default(omit) }}"
        network: "{{ app_nextcloud_whiteboard__container.network }}"
        timezone: "{{ app_nextcloud_whiteboard__container.timezone }}"
        env: "{{ app_nextcloud_whiteboard__container.environment | default(omit) }}"
        label: "{{ app_nextcloud_whiteboard__container.labels | default(omit) }}"
        secrets: "{{ app_nextcloud_whiteboard__container.secrets | default(omit) }}"
        volume: "{{ app_nextcloud_whiteboard__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_nextcloud_whiteboard__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode is defined and podman___update_mode else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'app_nextcloud_whiteboard__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ app_nextcloud_whiteboard__container.name }}"
        container_image: "{{ app_nextcloud_whiteboard__container.image }}"
