---

- name: 'Deploy Jellyfin container'
  tags: [ 'app_jellyfin' ]
  block:

    - name: 'Create Jellyfin directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
        owner: "{{ app_jellyfin__uid }}"
        group: "{{ app_jellyfin__gid }}"
        mode: '750'
      with_items:
        - "{{ app_jellyfin__podman_home }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_jellyfin__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_jellyfin__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_jellyfin__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_jellyfin__container.name }}"
        hostname: "{{ app_jellyfin__container.hostname }}"
        image: "{{ app_jellyfin__container.image }}"
        ip: "{{ app_jellyfin__container.ip }}"
        network: "{{ app_jellyfin__container.network }}"
        timezone: "{{ app_jellyfin__container.timezone }}"
        env: "{{ app_jellyfin__container.environment }}"
        label: "{{ app_jellyfin__container.labels }}"
        publish: "{{ app_jellyfin__container.publish }}"
        volume: "{{ app_jellyfin__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_jellyfin__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_jellyfin__container.name }}"
        hostname: "{{ app_jellyfin__container.hostname }}"
        image: "{{ app_jellyfin__container.image }}"
        ip: "{{ app_jellyfin__container.ip }}"
        ip6: "{{ app_jellyfin__container.ipv6 }}"
        network: "{{ app_jellyfin__container.network }}"
        timezone: "{{ app_jellyfin__container.timezone }}"
        env: "{{ app_jellyfin__container.environment }}"
        label: "{{ app_jellyfin__container.labels }}"
        publish: "{{ app_jellyfin__container.publish }}"
        volume: "{{ app_jellyfin__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_jellyfin__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_jellyfin__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'app_jellyfin__autoupdate_enabled'
      block:
        - name: 'Create autoupdate systemd service'
          ansible.builtin.copy:
            content: |
              [Unit]
              Description=Auto-update {{ app_jellyfin__container.name }} container

              [Service]
              Type=oneshot
              ExecStart=/usr/bin/podman pull {{ app_jellyfin__container.image }}
              ExecStartPost=/usr/bin/systemctl restart {{ app_jellyfin__container.name }}
            dest: "/etc/systemd/system/container-{{ app_jellyfin__container.name }}-update.service"
            mode: '0644'
            owner: root
            group: root

        - name: 'Create autoupdate systemd timer'
          ansible.builtin.copy:
            content: |
              [Unit]
              Description=Auto-update {{ app_jellyfin__container.name }} timer

              [Timer]
              OnCalendar=*-*-* 00/3:00:00
              RandomizedDelaySec=30m
              Persistent=true

              [Install]
              WantedBy=timers.target
            dest: "/etc/systemd/system/container-{{ app_jellyfin__container.name }}-update.timer"
            mode: '0644'
            owner: root
            group: root

        - name: 'Start and enable autoupdate timer'
          ansible.builtin.systemd:
            name: "container-{{ app_jellyfin__container.name }}-update.timer"
            daemon_reload: true
            state: 'started'
            enabled: true
          when: 'not ansible_check_mode'

