---

- name: 'Deploy Jellyfin container'
  tags: [ 'app_jellyfin' ]
  block:

    - name: 'Create Jellyfin directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
        owner: "{{ app_jellyfin__uid }}"
        group: "{{ app_jellyfin__gid }}"
        mode: '750'
      with_items:
        - "{{ app_jellyfin__data_dir }}"

    - name: 'Create podman containers'
      containers.podman.podman_container:
        name: "{{ app_jellyfin__container.name }}"
        hostname: "{{ app_jellyfin__container.hostname }}"
        image: "{{ app_jellyfin__container.image }}"
        ip: "{{ app_jellyfin__container.ip }}"
        network: "{{ app_jellyfin__container.network }}"
        etc_hosts: "{{ app_jellyfin__container.hosts }}"
        restart_policy: "{{ app_jellyfin__container.restart_policy }}"
        timezone: "{{ app_jellyfin__container.timezone }}"
        publish: "{{ app_jellyfin__container.publish }}"
        env: "{{ app_jellyfin__container.environment }}"
        device: "{{ app_jellyfin__container.devices }}"
        volume: "{{ app_jellyfin__container.volumes }}"
        pull: 'always'
      when: app_jellyfin__ipv6 | length == 0
