---

- name: Aquire ACME certificate {{ site.name }}
  when: site.acme_enabled is defined and site.acme_enabled
  block:

  - name: "Has certificate for site {{ site.name }} been aquired?"
    ansible.builtin.stat:
      path: "{{ pki__acme_renewal_dir }}/{{ site.name }}.conf"
    register: acme_realm_stat_result

  - name: "Aquire ACME certificate for site {{ site.name }}"
    when: not acme_realm_stat_result.stat.exists
    ansible.builtin.command:
      cmd: "certbot certonly {{ pki__acme_global_options }} --nginx --cert-name {{ site.name }} -d {{ site.server_name | join(' -d ') }} --rsa-key-size {{ site.key_size | default(2048) }}"
    environment: "{{ pki__acme_environment }}"
