---
# tasks file for roles/nginx

- name: Generate configuration snippet for acme
  tags: [ 'configuration' ]
  ansible.builtin.template:
    src: etc/nginx/snippets/acme-challenge.conf.j2
    dest: "{{ nginx__snippets_path }}/acme-challenge.conf"
    owner: root
    group: root
    mode: 0644

- name: Install packages
  tags: [ 'packages' ]
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ nginx__acme_packages }}"

- name: Create acme challenge directory
  tags: [ 'configuration' ]
  ansible.builtin.file:
    dest: "{{ nginx__www_path }}/acme"
    state: directory
    owner: "{{ nginx__user }}"
    group: "{{ nginx__group }}"
    mode: "{{ nginx__site_mode }}"

- name: Aquire ACME certificate
  include_tasks: acme_site.yml
  loop_control:
    loop_var: site
  with_items: "{{ nginx__sites }}"
