---

- name: Install and configure nginx
  tags: [ 'nginx' ]
  when: nginx__enable
  block:

  - name: Install nginx packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ nginx__packages_combined }}"

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: etc/nginx/nginx.conf.j2
      dest: "{{ nginx__etc_path }}/nginx.conf"
    - src: etc/nginx/snippets/ssl.conf.j2
      dest: "{{ nginx__snippets_path }}/ssl.conf"
    - src: etc/nginx/snippets/locations.conf.j2
      dest: "{{ nginx__snippets_path }}/locations.conf"
    - src: etc/nginx/snippets/status.conf.j2
      dest: "{{ nginx__snippets_path }}/status.conf"
    - src: etc/nginx/snippets/phpfpm-status.conf.j2
      dest: "{{ nginx__snippets_path }}/phpfpm-status.conf"

  - name: Configure and aquire ACME certificates
    tags: [ 'acme' ]
    when: nginx__acme_enable
    include_tasks: acme.yml

  - name: Install and configure CGI wrapper daemon
    tags: [ 'cgi' ]
    when: nginx__cgi_enable
    block:
    - name: Install CGI wrapper daemon
      tags: [ 'packages' ]
      ansible.builtin.apt:
        name: "{{ item }}"
        install_recommends: no
        state: present
      with_items: "{{ nginx__cgi_fcgiwrap_packages }}"
    - name: Configure CGI wrapper daemon
      tags: [ 'configuration' ]
      ansible.builtin.template:
        src: etc/nginx/snippets/fcgiwrap.conf.j2
        dest: /etc/nginx/snippets/fcgiwrap.conf
        owner: root
        group: root
        mode: 0644

  - name: Generate configuration snippet for PHP/FastCGI
    tags: [ 'configuration', 'php' ]
    when: nginx__php_enable
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: etc/nginx/snippets/fastcgi-php.conf.j2
      dest: "{{ nginx__snippets_path }}/fastcgi-php.conf"
    - src: etc/nginx/conf.d/fastcgi-php.conf.j2
      dest: "{{ nginx__conf_path }}/fastcgi-php.conf"

  - name: "Disable default site"
    tags: [ 'configuration' ]
    ansible.builtin.file:
      dest: "{{ nginx__sites_enabled_path }}/default"
      state: absent

  - name: Create sites configuration
    tags: [ 'configuration' ]
    include_tasks: nginx_site.yml
    loop_control:
      loop_var: site
    with_items: "{{ nginx__sites }}"
