---
# tasks file for roles/nginx

- name: Configure site {{ site.name }}
  tags: [ 'nginx' ]
  block:

  - name: "Generate configuration file for site {{ site.name }}"
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/nginx/sites-available/site.conf.j2
      dest: "{{ nginx__sites_available_path }}/{{ site.name }}.conf"
      owner: root
      group: root
      mode: 0644
    notify:
    - Restart nginx

  - name: "Ensure root exists for site {{ site.name }}"
    tags: [ 'configuration' ]
    when: not site.root is defined
    ansible.builtin.file:
      dest: "{{ nginx__www_path }}/{{ site.name }}/public"
      state: directory
      owner: "{{ nginx__user }}"
      group: "{{ nginx__group }}"
      mode: "{{ nginx__site_mode }}"

  - name: "Enable site  {{ site.name }}"
    tags: [ 'configuration' ]
    ansible.builtin.file:
      src: "{{ nginx__sites_available_path }}/{{ site.name }}.conf"
      dest: "{{ nginx__sites_enabled_path }}/{{ site.name }}.conf"
      state: link
    when: site.enabled and not ansible_check_mode
    notify:
    - Restart nginx
