---

- name: Restart clamav-daemon
  ansible.builtin.service:
    name: clamav-daemon
    state: restarted
  when: not ansible_check_mode

- name: Restart freshclam
  ansible.builtin.service:
    name: clamav-freshclam
    state: restarted
  when: not ansible_check_mode
