---

- name: Create Easy-RSA certificate
  tags: [ 'pki', 'pki_easyrsa_cert'  ]
  become: no
  block:

    - name: Is Easy-RSA CA initialized?
      local_action:
        module: ansible.builtin.stat
        path: "{{ pki_easyrsa_cert__pki_dir }}/ca.crt"
      register: easyrsa_ca_stat_result

    - name: Easy-RSA PKI is not initialized
      ansible.builtin.fail:
        msg: The Easy-RSA CA has is not initialized
      when: not easyrsa_ca_stat_result.stat.exists

    - name: Create realms
      include_tasks: realm.yml
      loop_control:
        loop_var: realm
      with_items: "{{ pki_easyrsa_cert__realms }}"
