---

- name: Create Easy-RSA certificate for realm
  when: realm.easyrsa | default(false)
  block:

    - name: "Has certificate for {{ realm.name }} been generated?"
      local_action:
        module: ansible.builtin.stat
        path: "{{ pki_easyrsa_cert__pki_dir }}/issued/{{ realm.name }}.crt"
      register: easyrsa_realm_stat_result

    - name: "Create server certificate for {{ realm.name }}"
      local_action:
        module: ansible.builtin.command
        chdir: "{{ pki_easyrsa_cert__pki_dir }}"
        cmd: "{{ pki_easyrsa_cert__path }} build-server-full {{ realm.name }} nopass"
      environment: "{{ pki_easyrsa_cert__environment | combine(realm.easyrsa_environment) }}"
      when: realm.easyrsa_type == 'server' and not easyrsa_realm_stat_result.stat.exists

    - name: "Create client certificate for {{ realm.name }}"
      local_action:
        module: ansible.builtin.command
        chdir: "{{ pki_easyrsa_cert__pki_dir }}"
        cmd: "{{ pki_easyrsa_cert__path }} build-client-full {{ realm.name }} nopass"
      environment: "{{ pki_easyrsa_cert__environment | combine(realm.easyrsa_environment) }}"
      when: realm.easyrsa_type == 'client' and not easyrsa_realm_stat_result.stat.exists

    - name: "Create client/server certificate for {{ realm.name }}"
      local_action:
        module: ansible.builtin.command
        chdir: "{{ pki_easyrsa_cert__pki_dir }}"
        cmd: "{{ pki_easyrsa_cert__path }} build-serverClient-full {{ realm.name }} nopass"
      environment: "{{ pki_easyrsa_cert__environment | combine(realm.easyrsa_environment) }}"
      when: realm.easyrsa_type == 'cs' and not easyrsa_realm_stat_result.stat.exists
