---

- name: Install Znuny
  tags: [ 'app_znuny' ]
  block:

    - name: Generate dbconfig file
      ansible.builtin.template:
        src: otrs2.conf.j2
        dest: "{{ app_znuny__dbconfig_dir }}/otrs2.conf"
        owner: root
        group: root
        mode: '600'

    - name: Install Znuny packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ app_znuny__packages }}"

    - name: Disable global Znuny configuration
      ansible.builtin.shell: "a2disconf otrs2"

    - name: Generate Znuny apache site
      ansible.builtin.import_role:
        name: webserver_apache
      vars:
        apache_sites: "[ {{ app_znuny__site }} ] "

