---

- name: 'Deploy phpRedisAdmin container'
  tags: [ 'database_phpredisadmin' ]
  block:

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'pra_admin_password'
        data: "{{ database_phpredisadmin__admin_password }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ database_phpredisadmin__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[database_phpredisadmin__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ database_phpredisadmin__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install phpredisadmin container'
      containers.podman.podman_container:
        name: "{{ database_phpredisadmin__container.name }}"
        hostname: "{{ database_phpredisadmin__container.hostname }}"
        image: "{{ database_phpredisadmin__container.image }}"
        ip: "{{ database_phpredisadmin__container.ip }}"
        network: "{{ database_phpredisadmin__container.network }}"
        timezone: "{{ database_phpredisadmin__container.timezone }}"
        env: "{{ database_phpredisadmin__container.environment }}"
        label: "{{ database_phpredisadmin__container.labels }}"
        secrets: "{{ database_phpredisadmin__container.secrets }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if database_phpredisadmin__container.requires is defined %}
          Requires={{ database_phpredisadmin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'database_phpredisadmin__ipv6 | length == 0'

    - name: 'Install phpredisadmin container'
      containers.podman.podman_container:
        name: "{{ database_phpredisadmin__container.name }}"
        hostname: "{{ database_phpredisadmin__container.hostname }}"
        image: "{{ database_phpredisadmin__container.image }}"
        ip: "{{ database_phpredisadmin__container.ip }}"
        ip6: "{{ database_phpredisadmin__container.ipv6 }}"
        network: "{{ database_phpredisadmin__container.network }}"
        timezone: "{{ database_phpredisadmin__container.timezone }}"
        env: "{{ database_phpredisadmin__container.environment }}"
        label: "{{ database_phpredisadmin__container.labels }}"
        secrets: "{{ database_phpredisadmin__container.secrets }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if database_phpredisadmin__container.requires is defined %}
          Requires={{ database_phpredisadmin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'database_phpredisadmin__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd_service:
        name: "{{ database_phpredisadmin__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'database_phpredisadmin__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ database_phpredisadmin__container.name }}"
        container_image: "{{ database_phpredisadmin__container.image }}"
