---

icinga__conf_services_default:
  
  ping4:
    doc: |
      These are generic `ping4` and `ping6`
      checks applied to all hosts having the
      `address` resp. `address6` attribute
      defined.
    import: [ 'generic-service' ]
    check_command: ping4
    assign:
    - host.address

  ping6:
    doc: |
      These are generic `ping4` and `ping6`
      checks applied to all hosts having the
      `address` resp. `address6` attribute
      defined.
    import: [ 'generic-service' ]
    check_command: ping6
    assign:
    - host.address6

  ssh:
    doc: |
      Apply the `ssh` service to all hosts
      with the `address` attribute defined and
      the custom variable `os` set to `Linux`.
    import: [ 'generic-service' ]
    check_command: ssh
    assign:
    - (host.address || host.address6) && host.vars.os == "Linux"

  http:
    for: (http_vhost => config in host.vars.http_vhosts)
    import: [ 'generic-service' ]
    check_command: http
    vars_add:
      - config

  disk:
    for: (disk => config in host.vars.disks)
    import: [ 'generic-service' ]
    check_command: disk
    vars_add:
      - config
    ignore:
    - host.vars.agent_endpoint

  icinga:
    import: [ 'generic-service' ]
    check_command: icinga
    assign:
    - host.name == NodeName

  load:
    import: [ 'generic-service' ]
    check_command: load
    vars:
      backup_downtime: 02:00-03:00
    assign:
    - host.name == NodeName

  procs:
    import: [ 'generic-service' ]
    check_command: procs
    assign:
    - host.name == NodeName

  swap:
    import: [ 'generic-service' ]
    check_command: swap
    assign:
    - host.name == NodeName

  users:
    import: [ 'generic-service' ]
    check_command: users
    assign:
    - host.name == NodeName
