---

- name: 'Deploy Forward Auth container'
  tags: [ 'security_traefik_forward_auth' ]
  block:

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: "{{ item.name }}"
        data: "{{ item.data }}"
      with_items:
        - name: "forward_auth_client_secret"
          data: "{{ security_traefik_forward_auth__client_secret }}"
        - name: "forward_auth_secret"
          data: "{{ security_traefik_forward_auth__secret }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ security_traefik_forward_auth__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[security_traefik_forward_auth__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ security_traefik_forward_auth__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ security_traefik_forward_auth__container.name }}"
        hostname: "{{ security_traefik_forward_auth__container.hostname }}"
        image: "{{ security_traefik_forward_auth__container.image }}"
        ip: "{{ security_traefik_forward_auth__container.ip }}"
        ip6: "{{ security_traefik_forward_auth__container.ipv6 | default(omit) }}"
        network: "{{ security_traefik_forward_auth__container.network }}"
        timezone: "{{ security_traefik_forward_auth__container.timezone }}"
        env: "{{ security_traefik_forward_auth__container.environment | default(omit) }}"
        label: "{{ security_traefik_forward_auth__container.labels | default(omit) }}"
        secrets: "{{ security_traefik_forward_auth__container.secrets | default(omit) }}"
        volume: "{{ security_traefik_forward_auth__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ security_traefik_forward_auth__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'
