---

- name: Deploy Rocket.Chat container
  tags: [ 'app_rocketchat' ]
  block:

    - name: Create podman containers
      containers.podman.podman_container:
        name: "{{ app_rocketchat__container_default.name }}"
        hostname: "{{ app_rocketchat__container_default.hostname }}"
        image: "{{ app_rocketchat__container_default.image }}"
        ip: "{{ app_rocketchat__container_default.ip }}"
        network: "{{ app_rocketchat__container_default.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ app_rocketchat__container_default.restart_policy }}"
        etc_hosts: "{{ app_rocketchat__container_default.hosts }}"
        shm_size: "{{ app_rocketchat__container_default.shm_size }}"
        env: "{{ app_rocketchat__container_default.environment }}"
        timezone: "{{ app_rocketchat__container_default.timezone | default(bootstrap_timezone__timezone) }}"
        volume: "{{ app_rocketchat__container_default.volumes }}"
      when: app_rocketchat__ipv6 | length == 0

    - name: Create podman containers
      containers.podman.podman_container:
        name: "{{ app_rocketchat__container_default.name }}"
        hostname: "{{ app_rocketchat__container_default.hostname }}"
        image: "{{ app_rocketchat__container_default.image }}"
        ip: "{{ app_rocketchat__container_default.ip }}"
        ip6: "{{ app_rocketchat__container_default.ipv6 }}"
        network: "{{ app_rocketchat__container_default.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ app_rocketchat__container_default.restart_policy }}"
        etc_hosts: "{{ app_rocketchat__container_default.hosts }}"
        shm_size: "{{ app_rocketchat__container_default.shm_size }}"
        env: "{{ app_rocketchat__container_default.environment }}"
        timezone: "{{ app_rocketchat__container_default.timezone | default(bootstrap_timezone__timezone) }}"
        volume: "{{ app_rocketchat__container_default.volumes }}"
      when: app_rocketchat__ipv6 | length > 0
