---

- name: Deploy Rocket.Chat container
  tags: [ 'app_rocketchat' ]
  block:

    - name: Deploy Rocket.Chat container via podman
      ansible.builtin.import_role:
        name: podman
      vars:
        pod_containers:
          - "{{ app_rocketchat__container }}"
