---

- name: Configure logrotate
  tags: [ 'log_logrotate'  ]
  block:

    - name: Install logrotate packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ log_logrotate__packages }}"

    - name: Generate logrotate main configuration
      ansible.builtin.template:
        src: logrotate.conf.j2
        dest: /etc/logrotate.conf
        owner: root
        group: root
        mode: '644'

    - name: Generate logrotate configuration files
      ansible.builtin.template:
        src: logrotate.j2
        dest: "{{ log_logrotate__etc_dir }}/{{ item.name }}"
        owner: root
        group: root
        mode: '640'
      with_items: "{{ log_logrotate__files }}"
