---

- name: 'Loop over BookStack instances'
  tags: [ 'app_bookstack' ]
  include_role:
    name: 'app_bookstack'
  loop: "{{ bookstack_instances }}"
  loop_control:
    loop_var: 'bookstack'
  vars:
    bookstack_home: "{{ bookstack.home }}"
    bookstack_ip: "{{ bookstack.ip }}"
    bookstack_ipv6: "{{ bookstack.ipv6 | default(app_bookstack__ipv6_default) }}"
    bookstack_network: "{{ bookstack.network }}"
    bookstack_hostname: "{{ bookstack.hostname }}"
    bookstack_timezone: "{{ bookstack.timezone }}"
    bookstack_labels: "{{ bookstack.labels | default(app_bookstack__labels_default) }}"
    bookstack_version: "{{ bookstack.version | default(app_bookstack__version_default) }}"
    bookstack_container: "{{ bookstack.container | default(app_bookstack__container_default) }}"

    bookstack_db_host: "{{ bookstack.db_host }}"
    bookstack_db_port: "{{ bookstack.db_port | default(app_bookstack__db_port_default) }}"
    bookstack_db_user: "{{ bookstack.db_user | default(app_bookstack__db_user_default) }}"
    bookstack_db_pass: "{{ bookstack.db_pass }}"
    bookstack_db_name: "{{ bookstack.db_name | default(app_bookstack__db_name_default) }}"

    bookstack_url: "{{ bookstack.url }}"
    bookstack_account: "{{ bookstack.account | default({}) }}"
    bookstack_app_key: "{{ bookstack.app_key }}"

    bookstack_mail_driver: "{{ bookstack.mail_driver | default(app_bookstack__mail_driver_default) }}"
    bookstack_mail_from_name: "{{ bookstack.mail_from_name | default(app_bookstack__mail_from_name_default) }}"
    bookstack_mail_from: "{{ bookstack.mail_from }}"
    bookstack_mail_host: "{{ bookstack.mail_host | default(app_bookstack__mail_host_default) }}"
    bookstack_mail_port: "{{ bookstack.mail_port | default(app_bookstack__mail_port_default) }}"
    bookstack_mail_username: "{{ bookstack.mail_username | default(app_bookstack__mail_username_default) }}"
    bookstack_mail_password: "{{ bookstack.mail_password | default(app_bookstack__mail_password_default) }}"
    bookstack_mail_encryption: "{{ bookstack.mail_encryption | default(app_bookstack__mail_encryption_default) }}"
    bookstack_mail_sendmail_command: "{{ bookstack.mail_sendmail_command | default(app_bookstack__mail_sendmail_command_default) }}"

    bookstack_auth_method: "{{ bookstack.auth_method | default(app_bookstack__auth_method_default) }}"

    bookstack_ldap_server: "{{ bookstack.ldap_server }}"
    bookstack_ldap_base_dn: "{{ bookstack.ldap_base_dn }}"
    bookstack_ldap_dn: "{{ bookstack.ldap_dn | default(app_bookstack__ldap_dn_default) }}"
    bookstack_ldap_pass: "{{ bookstack.ldap_pass | default(app_bookstack__ldap_pass_default) }}"
    bookstack_ldap_filter: "{{ bookstack.ldap_filter | default(app_bookstack__ldap_filter_default) }}"
    bookstack_ldap_version: "{{ bookstack.ldap_version | default(app_bookstack__ldap_version_default) }}"
    bookstack_ldap_uid: "{{ bookstack.ldap_uid | default(app_bookstack__ldap_uid_default) }}"
    bookstack_ldap_email_attribute: "{{ bookstack.ldap_email_attribute | default(app_bookstack__ldap_email_attribute_default) }}"
    bookstack_ldap_display_name_attribute: "{{ bookstack.ldap_display_name_attribute | default(app_bookstack__ldap_display_name_attribute_default) }}"
    bookstack_ldap_user_to_groups: "{{ bookstack.ldap_user_to_groups | default(app_bookstack__ldap_user_to_groups_default) }}"
    bookstack_ldap_group_attribute: "{{ bookstack.ldap_group_attribute | default(app_bookstack__ldap_group_attribute_default) }}"
    bookstack_ldap_remove_from_groups: "{{ bookstack.ldap_remove_from_groups | default(app_bookstack__ldap_remove_from_groups_default) }}"

    bookstack_oidc_auto_initiate: "{{ bookstack.oidc_auto_initiate | default(app_bookstack__oidc_auto_initiate_default) }}"
    bookstack_oidc_name: "{{ bookstack.oidc_name | default(app_bookstack__oidc_name_default) }}"
    bookstack_oidc_display_name_claims: "{{ bookstack.oidc_display_name_claims | default(app_bookstack__oidc_display_name_claims_default) }}"
    bookstack_oidc_client_id: "{{ bookstack.oidc_client_id | default(app_bookstack__oidc_client_id_default) }}"
    bookstack_oidc_client_secret: "{{ bookstack.oidc_client_secret }}"
    bookstack_oidc_issuer: "{{ bookstack.oidc_issuer }}"
    bookstack_oidc_end_session_endpoint: "{{ bookstack.oidc_end_session_endpoint | default(app_bookstack__oidc_end_session_endpoint_default) }}"
    bookstack_oidc_issuer_discover: "{{ bookstack.oidc_issuer_discover | default(app_bookstack__oidc_issuer_discover_default) }}"
    bookstack_oidc_external_id_claim: "{{ bookstack.oidc_external_id_claim | default(app_bookstack__oidc_external_id_claim_default) }}"

    bookstack_drawio: "{{ bookstack.drawio | default(app_bookstack__drawio_default) }}"
    bookstack_memcached_servers: "{{ bookstack.memcached_servers | default(app_bookstack__memcached_servers_default) }}"
    bookstack_redis_servers: "{{ bookstack.redis_servers | default(app_bookstack__redis_servers_default) }}"
    bookstack_cache_driver: "{{ bookstack.cache_driver | default(app_bookstack__cache_driver_default) }}"
    bookstack_session_driver: "{{ bookstack.session_driver | default(app_bookstack__session_driver_default) }}"

    bookstack_session_cookie_name: "{{ bookstack.session_cookie_name | default(app_bookstack__session_cookie_name_default) }}"
    bookstack_session_secure_cookie: "{{ bookstack.session_secure_cookie | default(app_bookstack__session_secure_cookie_default) }}"
    bookstack_session_lifetime: "{{ bookstack.session_lifetime | default(app_bookstack__session_lifetime_default) }}"

    bookstack_dark_mode: "{{ bookstack.dark_mode | default(app_bookstack__dark_mode_default) }}"
    bookstack_view_books_as_grid: "{{ bookstack.view_books_as_grid | default(app_bookstack__view_books_as_grid_default) }}"
    bookstack_uid: "{{ bookstack.uid }}"
