---

- name: 'Deploy BookStack container'
  tags: [ 'app_bookstack' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ app_bookstack__uid }}"
        group: "{{ app_bookstack__gid }}"
        mode: "{{ item.mode | default('0700') }}"
        state: 'directory'
      with_items:
        - dest: "{{ app_bookstack__podman_config_dir }}"

    - name: 'Generate BookStack .env file'
      ansible.builtin.template:
        src: 'env.j2'
        dest: "{{ app_bookstack__podman_config_dir }}/.env"
        owner: "{{ app_bookstack__uid }}"
        group: "{{ app_bookstack__gid }}"
        mode: '600'
      when: 'not podman___update_mode | bool'

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'bookstack_database_pass'
        data: "{{ app_bookstack__db_pass }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_bookstack__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_bookstack__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_bookstack__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_bookstack__container.name }}"
        hostname: "{{ app_bookstack__container.hostname }}"
        image: "{{ app_bookstack__container.image }}"
        ip: "{{ app_bookstack__container.ip }}"
        ip6: "{{ app_bookstack__container.ipv6 | default(omit) }}"
        network: "{{ app_bookstack__container.network }}"
        timezone: "{{ app_bookstack__container.timezone }}"
        env: "{{ app_bookstack__container.environment | default(omit) }}"
        label: "{{ app_bookstack__container.labels | default(omit) }}"
        secrets: "{{ app_bookstack__container.secrets | default(omit) }}"
        volume: "{{ app_bookstack__container.volumes | default(omit) }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always

          [Unit]
          {% if app_bookstack__container.requires is defined %}
          Requires={{ app_bookstack__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_bookstack__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'app_bookstack__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ app_bookstack__container.name }}"
        container_image: "{{ app_bookstack__container.image }}"
