---

- name: Deploy BookStack container
  tags: [ 'app_bookstack' ]
  block:

    - name: Deploy container via podman
      ansible.builtin.import_role:
        name: podman
      vars:
        pod_containers:
          - "{{ app_bookstack__container }}"
        pod_users:
          - "{{ app_bookstack__account }}"

    - name: Generate BookStack .env file
      ansible.builtin.template:
        src: env.j2
        dest: "{{ app_bookstack__config_dir }}/.env"
        owner: "{{ app_bookstack__user }}"
        group: "{{ app_bookstack__user }}"
        mode: '600'
