---

- name: Deploy BookStack container
  tags: [ 'app_bookstack' ]
  block:

    - name: Deploy container via podman
      ansible.builtin.import_role:
        name: podman
      vars:
        pod_containers:
          - "{{ app_bookstack__container }}"
        pod_users:
          - "{{ app_bookstack__account }}"
