---

- name: 'Install InfluxDB 3 Explorer'
  tags: [ 'database_influxdb_explorer'  ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: 'root'
        group: 'root'
        mode: "{{ item.mode | default('0700') }}"
        state: 'directory'
      with_items:
        - dest: "{{ database_influxdb_explorer__podman_data_dir }}"
        - dest: "{{ database_influxdb_explorer__podman_config_dir }}"

    - name: 'Generate config file'
      no_log: true
      ansible.builtin.template:
        src: 'config.json.j2'
        dest: "{{ database_influxdb_explorer__podman_config_dir }}/config.json"
        owner: 'root'
        group: 'root'
        mode: '600'
      when: 'not podman___update_mode | bool'

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'influxdb_explorer_session_secret'
        data: "{{ database_influxdb_explorer__session_secret }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ database_influxdb_explorer__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[database_influxdb_explorer__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ database_influxdb_explorer__container.image }}"
        force: true
      when: 'podman___update_mode | bool'
      
    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ database_influxdb_explorer__container.name }}"
        hostname: "{{ database_influxdb_explorer__container.hostname }}"
        image: "{{ database_influxdb_explorer__container.image }}"
        ip: "{{ database_influxdb_explorer__container.ip }}"
        network: "{{ database_influxdb_explorer__container.network }}"
        timezone: "{{ database_influxdb_explorer__container.timezone }}"
        label: "{{ database_influxdb_explorer__container.labels }}"
        secrets: "{{ database_influxdb_explorer__container.secrets }}"
        volume: "{{ database_influxdb_explorer__container.volumes }}"
        command: '--mode=admin'
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'database_influxdb_explorer__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ database_influxdb_explorer__container.name }}"
        hostname: "{{ database_influxdb_explorer__container.hostname }}"
        image: "{{ database_influxdb_explorer__container.image }}"
        ip: "{{ database_influxdb_explorer__container.ip }}"
        ip6: "{{ database_influxdb_explorer__container.ipv6 }}"
        network: "{{ database_influxdb_explorer__container.network }}"
        timezone: "{{ database_influxdb_explorer__container.timezone }}"
        label: "{{ database_influxdb_explorer__container.labels }}"
        secrets: "{{ database_influxdb_explorer__container.secrets }}"
        volume: "{{ database_influxdb_explorer__container.volumes }}"
        command: '--mode=admin'
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'database_influxdb_explorer__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ database_influxdb_explorer__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'database_influxdb_explorer__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ database_influxdb_explorer__container.name }}"
        container_image: "{{ database_influxdb_explorer__container.image }}"
