---

- name: 'Install container update for'
  tags: [ 'container_update' ]
  block:

    - name: 'Include OS-specific variables'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"

    - name: 'Install container update packages'
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ container_update__packages }}"

    - name: 'Create environment file'
      ansible.builtin.copy:
        content: |
          PUSHOVER_APP_TOKEN="{{ container_update__pushover_token }}"
          PUSHOVER_USER_KEY="{{ container_update__pushover_key }}"
        dest: "/etc/systemd/container-update.env"
        mode: '0600'
      when: 'container_update__pushover_key | length > 0 and container_update__pushover_token | length > 0'

    - name: 'Create autoupdate systemd service template'
      ansible.builtin.template:
        src: 'container-update.service.j2'
        dest:  "/etc/systemd/system/container-update@.service"

    - name: 'Create autoupdate systemd timer template'
      ansible.builtin.template:
        src: 'container-update.timer.j2'
        dest:  "/etc/systemd/system/container-update@.timer"

    - name: 'Create autoupdate systemd failure notification template'
      ansible.builtin.template:
        src: 'container-update-notify-failure.service.j2'
        dest:  "/etc/systemd/system/container-update-notify-failure@.service"
      when: 'container_update__pushover_key | length > 0 and container_update__pushover_token | length > 0'

    - name: 'Create directory for container service'
      ansible.builtin.file:
        path: "/etc/systemd/system/container-update@{{ container_update__container_name }}.service.d"
        state: 'directory'
        mode: '0755'
      when: 'container_update__container_name | length > 0'

    - name: 'Create override for container service'
      ansible.builtin.template:
        src: 'service.override.conf.j2'
        dest:  "/etc/systemd/system/container-update@{{ container_update__container_name }}.service.d/override.conf"
      when: 'container_update__container_name | length > 0'

    - name: 'Create directory for container timer'
      ansible.builtin.file:
        path: "/etc/systemd/system/container-update@{{ container_update__container_name }}.timer.d"
        state: 'directory'
        mode: '0755'
      when: 'container_update__container_name | length > 0 and container_update__schedule | length > 0'

    - name: 'Create override for container timer'
      ansible.builtin.template:
        src: 'service.override.conf.j2'
        dest:  "/etc/systemd/system/container-update@{{ container_update__container_name }}.timer.d/override.conf"
      when: 'container_update__container_name | length > 0 and container_update__schedule | length > 0'

    - name: 'Start and enable autoupdate timer'
      ansible.builtin.systemd:
        name: "container-update@{{ container_update__container_name }}.timer"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode and container_update__container_name | length > 0'

    - name: 'Reload systemd'
      ansible.builtin.systemd:
        daemon_reload: true
