---

- name: 'Install container update for'
  tags: [ 'container_update' ]
  block:

    - name: 'Include OS-specific variables'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"

    - name: 'Install container update packages'
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ container_update__packages }}"

    - name: 'Create autoupdate systemd service'
      ansible.builtin.template:
        src: 'container-update.service.j2'
        dest:  "/etc/systemd/system/container-{{ container_update__container_name }}-update.service"

    - name: 'Create autoupdate systemd timer'
      ansible.builtin.template:
        src: 'container-update.timer.j2'
        dest:  "/etc/systemd/system/container-{{ container_update__container_name }}-update.timer"

    - name: 'Start and enable autoupdate timer'
      ansible.builtin.systemd:
        name: "container-{{ container_update__container_name }}-update.timer"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'
