---

- name: Install can2mqtt
  tags: [ 'smarthome_can2mqtt' ]
  block:

    - name: Create can2mqtt directories
      ansible.builtin.file:
        mode: '755'
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ smarthome_can2mqtt__home }}"

    - name: Generate can2mqtt configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('644') }}"
      with_items:
        - src: can2mqtt.csv.j2
          dest: "{{ smarthome_can2mqtt__config_file }}"
      notify:
        - Restart can2mqtt container

    - name: Install can2mqtt container
      containers.podman.podman_container:
        name: "{{ smarthome_can2mqtt__container.name }}"
        hostname: "{{ smarthome_can2mqtt__container.hostname }}"
        image: "{{ smarthome_can2mqtt__container.image }}"
        network: 'host'
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ smarthome_can2mqtt__container.restart_policy }}"
        etc_hosts: "{{ smarthome_can2mqtt__container.hosts }}"
        env: "{{ smarthome_can2mqtt__container.environment }}"
        timezone: "{{ smarthome_can2mqtt__container.timezone }}"
        volume: "{{ smarthome_can2mqtt__container.volumes }}"
      when: smarthome_can2mqtt__ipv6 | length == 0
