---

- name: Install airrohr2mqtt
  tags: [ 'smarthome_airrohr2mqtt' ]
  block:

    - name: Create airrohr2mqtt directories
      ansible.builtin.file:
        mode: '755'
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ smarthome_airrohr2mqtt__home }}"

    - name: Generate airrohr2mqtt configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('644') }}"
      with_items:
        - src: airrohr2mqtt.conf.j2
          dest: "{{ smarthome_airrohr2mqtt__config_file }}"
      notify:
        - Restart airrohr2mqtt container

    - name: Install airrohr2mqtt container
      containers.podman.podman_container:
        name: "{{ smarthome_airrohr2mqtt__container.name }}"
        hostname: "{{ smarthome_airrohr2mqtt__container.hostname }}"
        image: "{{ smarthome_airrohr2mqtt__container.image }}"
        ip: "{{ smarthome_airrohr2mqtt__container.ip }}"
        network: "{{ smarthome_airrohr2mqtt__container.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ smarthome_airrohr2mqtt__container.restart_policy }}"
        etc_hosts: "{{ smarthome_airrohr2mqtt__container.hosts }}"
        expose: "{{ smarthome_airrohr2mqtt__container.expose }}"
        publish: "{{ smarthome_airrohr2mqtt__container.publish }}"
        timezone: "{{ smarthome_airrohr2mqtt__container.timezone }}"
        volume: "{{ smarthome_airrohr2mqtt__container.volumes }}"
      when: smarthome_airrohr2mqtt__ipv6 | length == 0
