---

# See https://stackoverflow.com/a/78148504

- name: Restart Icinga master - block
  block:

    - name: Restart Icinga master service
      ansible.builtin.service:
        name: 'icinga2'
        state: 'restarted'
      listen: 'Restart Icinga'
      when: not ansible_check_mode and not monitoring_icinga_master__use_podman

    - name: Restart Icinga master container
      ansible.builtin.shell: 'podman restart icinga'
      listen: 'Restart Icinga'
      when: not ansible_check_mode and monitoring_icinga_master__use_podman
