---

#
# Substitutes - do not change
#

monitoring_diun__db_file: "{{ diun_db_file | default(monitoring_diun__lib_dir + '/diun.db') }}"

monitoring_diun__workers: "{{ diun_workers | default(10) }}"
monitoring_diun__schedule: "{{ diun_schedule | default('0 */6 * * *') }}"
monitoring_diun__jitter: "{{ diun_jitter | default(30) }}"
monitoring_diun__first_check_notif: "{{ diun_first_check_notif | default(false) }}"
monitoring_diun__run_on_startup: "{{ diun_run_on_startup | default(true) }}"
monitoring_diun__compare_digest: "{{ diun_compare_digest | default(false) }}"
monitoring_diun__healthchecks_baseurl: "{{ diun_healthchecks | default('') }}"
monitoring_diun__healthchecks_uuid: "{{ diun_healthchecks | default('') }}"

monitoring_diun__watch_repo: "{{ diun_watch_repo | default(false) }}"
monitoring_diun__notify_on: "{{ diun_notify_on | default(['new', 'update']) }}"
monitoring_diun__max_tags: "{{ diun_max_tags | default(10) }}"
monitoring_diun__sort_tags: "{{ diun_sort_tags | default('reverse') }}"
monitoring_diun__include_tags: "{{ diun_include_tags | default('') }}"
monitoring_diun__exclude_tags: "{{ diun_exclude_tags | default('') }}"
monitoring_diun__metadata: "{{ diun_metadata | default({}) }}"

monitoring_diun__notify_mail: "{{ diun_notify_mail | default(false) }}"
monitoring_diun__notify_mail_host: "{{ diun_mail_host | default('localhost') }}"
monitoring_diun__notify_mail_port: "{{ diun_mail_port | default(25) }}"
monitoring_diun__notify_mail_ssl: "{{ diun_mail_ssl | default(false) }}"
monitoring_diun__notify_mail_insecure_skip_verify: "{{ diun_mail_insecure_skip_verify | default(false) }}"
monitoring_diun__notify_mail_local_name: "{{ diun_mail_local_name | default('localhost') }}"
monitoring_diun__notify_mail_username: "{{ diun_mail_username | default('') }}"
monitoring_diun__notify_mail_username_file: "{{ diun_mail_username_file | default('') }}"
monitoring_diun__notify_mail_password: "{{ diun_mail_password | default('') }}"
monitoring_diun__notify_mail_password_file: "{{ diun_mail_password_file | default('') }}"
monitoring_diun__notify_mail_from: "{{ diun_mail_from | default('') }}"
monitoring_diun__notify_mail_to: "{{ diun_mail_to | default('') }}"
monitoring_diun__notify_mail_template_title: "{{ diun_mail_template_title | default('') }}"
monitoring_diun__notify_mail_template_body: "{{ diun_mail_template_body | default('') }}"

monitoring_diun__provider_docker: "{{ diun_provider_docker | default(false) }}"
monitoring_diun__provider_docker_endpoint: "{{ diun_docker_endpoint | default('/var/run/docker.sock') }}"
monitoring_diun__provider_docker_api_version: "{{ diun_docker_api_version | default('') }}"
monitoring_diun__provider_docker_tls_certs_path: "{{ diun_docker_tls_certs_path | default('') }}"
monitoring_diun__provider_docker_tls_verify: "{{ diun_docker_tls_verify | default(false) }}"
monitoring_diun__provider_docker_watch_by_default: "{{ diun_docker_watch_by_default | default(false) }}"
monitoring_diun__provider_docker_watch_stopped: "{{ diun_docker_watch_stopped | default(false) }}"

monitoring_diun__service: "{{ monitoring_diun__service_default | ansible.builtin.combine(diun_service | default({})) }}"

#
# Defaults - do not change
#

monitoring_diun__bin_dir: /usr/local/bin
monitoring_diun__etc_dir: /etc/diun
monitoring_diun__lib_dir: /var/lib/diun

monitoring_diun__user: diun
monitoring_diun__group: diun

monitoring_diun__url: "https://github.com/crazy-max/diun/releases/download/v{{ monitoring_diun__version }}/{{ monitoring_diun__package }}"
monitoring_diun__checksum_url: "https://github.com/crazy-max/diun/releases/download/v{{ monitoring_diun__version }}/checksums.txt"

monitoring_diun__package: "diun_{{ monitoring_diun__version }}_linux_{{ monitoring_diun__arch }}.tar.gz"

monitoring_diun__version: "4.26.0"

monitoring_diun__arch: "{{ monitoring_diun__arch_flavors[ansible_facts.userspace_architecture] }}"

monitoring_diun__arch_flavors:
  x86_64: amd64

monitoring_diun__service_default:
  name: diun
  enabled: true
  description: Diun
  documentation: https://crazymax.dev/diun/
  after:
    - syslog.target
    - network.target
  type: simple
  user: "{{ monitoring_diun__user }}"
  group: "{{ monitoring_diun__group }}"
  restart: always
  restart_sec: 2
  exec_start: "{{ monitoring_diun__bin_dir }}/diun serve --config {{ monitoring_diun__etc_dir }}/diun.yml --log-level info"
  wanted_by:
    - multi-user.target
