---

#
# Substitutes - do not change
#

mosquitto_server__use_podman: "{{ mosquitto_use_podman | default(true) }}"

mosquitto_server__home: "{{ mosquitto_home | mandatory }}"
mosquitto_server__owner: "{{ mosquitto_user | default(1883) }}"
mosquitto_server__group: "{{ mosquitto_group | default(1883) }}"

mosquitto_server__hostname: "{{ mosquitto_hostname | mandatory }}"
mosquitto_server__ip: "{{ mosquitto_ip | mandatory }}"
mosquitto_server__ipv6: "{{ mosquitto_ipv6 | default('') }}"
mosquitto_server__network: "{{ mosquitto_network | mandatory }}"
mosquitto_server__hosts: "{{ mosquitto_hosts | default(podman__container_etc_hosts) }}"
mosquitto_server__version: "{{ mosquitto_version | default('latest') }}"

mosquitto_server__container: "{{ mosquitto_server__container_default | combine(mosquitto_container | default({})) }}"

mosquitto_server__allow_anonymous: "{{ mosquitto_allow_anonymous | default(false) }}"
mosquitto_server__allow_duplicate_messages: "{{ mosquitto_allow_duplicate_messages | default(true) }}"
mosquitto_server__log_type_debug: "{{ mosquitto_log_debug | default(false) }}"
mosquitto_server__log_type_error: "{{ mosquitto_log_error | default(true) }}"
mosquitto_server__log_type_warning: "{{ mosquitto_log_warning | default(true) }}"
mosquitto_server__log_type_notice: "{{ mosquitto_log_notice | default(true) }}"
mosquitto_server__log_type_information: "{{ mosquitto_log_information | default(true) }}"
mosquitto_server__log_type_subscribe: "{{ mosquitto_log_subscribe | default(false) }}"
mosquitto_server__log_type_unsubscribe: "{{ mosquitto_log_unsubscribe | default(false) }}"
mosquitto_server__log_type_websockets: "{{ mosquitto_log_websockets | default(false) }}"
mosquitto_server__persistence: "{{ mosquitto_persistence | default(false) }}"

mosquitto_server__acl_global: "{{ mosquitto_acl | default({ 'topics': [], 'patterns': [] }) }}"
mosquitto_server__acl_per_user: "{{ mosquitto_acl_per_user | default({}) }}"

mosquitto_server__user_password: "{{ mosquitto_secrets | default({}) }}"

mosquitto_server__listeners: "{{ mosquitto__listeners | default(mosquitto_server__listeners_default) }}"

#
# Defaults - do not change
#

mosquitto_server__acl_file: '/mosquitto/config/aclfile'
mosquitto_server__password_file: '/mosquitto/config/pwfile'
mosquitto_server__persistence_file: 'mosquitto.db'
mosquitto_server__persistence_location: "{{ mosquitto_server__data_dir }}"

mosquitto_server__listeners_default:
  - port: 1883
    protocol: 'mqtt'

mosquitto_server__name: 'mosquitto'
mosquitto_server__image: 'docker.io/eclipse-mosquitto'
mosquitto_server__config_dir: "{{ mosquitto_server__home + '/config' }}"
mosquitto_server__data_dir: "{{ mosquitto_server__home + '/data' }}"
mosquitto_server__log_dir: "{{ mosquitto_server__home + '/log' }}"

mosquitto_server__container_default:
  name: "{{ mosquitto_server__name }}"
  hostname: "{{ mosquitto_server__hostname }}"
  image: "{{ mosquitto_server__image }}:{{ mosquitto_server__version }}"
  ip: "{{ mosquitto_server__ip }}"
  network: "{{ mosquitto_server__network }}"
  restart_policy: always
  hosts: "{{ mosquitto_server__hosts }}"
  expose:
    - 1883
    - 8883
  publish:
    - '1883:1883'
    - '8883:8883'
  timezone: "{{ bootstrap_timezone__timezone }}"
  volumes:
    - "{{ mosquitto_server__config_dir }}:/mosquitto/config"
    - "{{ mosquitto_server__data_dir }}:/mosquitto/data"
    - "{{ mosquitto_server__log_dir }}:/mosquitto/log"
