---
# tasks file for roles/docker

- name: Install and configure docker
  tags: [ 'docker' ]
  when: docker__enable
  block:
    - name: Create docker config directory
      tags: [ 'configuration' ]
      ansible.builtin.file:
        path: "{{ docker__config_path }}"
        owner: root
        group: root
        mode: 750
        state: directory

    - name: Create config files
      tags: [ 'configuration' ]
      ansible.builtin.template:
        src: daemon.json.j2
        dest: "{{ docker__config_path }}/daemon.json"
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart docker

    - name: Install docker packages
      tags: [ 'packages' ]
      ansible.builtin.apt:
        name: "{{ item }}"
        install_recommends: no
        state: present
      with_items: "{{ docker__packages }}"
