---

- name: Install and configure ClamAV
  tags: [ 'mail_clamav' ]
  block:

    - name: Install ClamAV packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ mail_clamav__packages }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items:
        - src: freshclam.conf.j2
          dest: "{{ mail_clamav__freshclam_config_file }}"
          owner: "{{ mail_clamav__user }}"
          group: adm
          mode: '444'
        - src: clamd.conf.j2
          dest: "{{ mail_clamav__clamd_config_file }}"
          owner: root
          group: root
          mode: '644'
      notify:
        - Restart clamav-daemon
        - Restart freshclam
