---

- name: 'Include OS-specific variables'
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"

- name: 'Fetch InfluxData repository signing key'
  ansible.builtin.get_url:
    url: "{{ monitoring_telegraf__signing_key_url }}"
    dest: "{{ monitoring_telegraf__signing_key_file }}"

- name: 'Add InfluxData repository to sources list'
  ansible.builtin.apt_repository:
    filename: 'influxdata'
    repo: "deb [arch=amd64 signed-by={{ monitoring_telegraf__signing_key_file }}] {{ monitoring_telegraf__repository_url }}  stable main"
    update_cache: true
    state: 'present'

- name: 'Install Telegraf packages'
  ansible.builtin.apt:
    update_cache: 'yes'
    install_recommends: 'no'
    pkg: "{{ monitoring_telegraf__packages }}"

- name: 'Create Telegraf configuration'
  ansible.builtin.template:
    src: 'telegraf.conf.j2'
    dest: "{{ monitoring_telegraf__etc_dir }}/telegraf.conf"
    owner: "{{ monitoring_telegraf__uid }}"
    group: "{{ monitoring_telegraf__gid }}"
    mode: '400'
  notify:
    - 'Restart Telegraf service'

- name: 'Configure Telegraf sudo privileges'
  community.general.sudoers:
    name: 'telegraf'
    state: 'present'
    noexec: true
    nopassword: true
    runas: 'root'
    user: "{{ monitoring_telegraf__uid }}"
    commands: "{{ item.commands }}"
  with_items: "{{ monitoring_telegraf__sudoers }}"

- name: 'Create Telegraf overrides'
  include_role:
    name: 'systemd_override'
  vars:
    systemd_override_service_name: 'telegraf'
    systemd_override_unit: "{{ monitoring_telegraf__systemd_override_unit }}"
    systemd_override_service: "{{ monitoring_telegraf__systemd_override_service }}"

- name: 'Start and enable service'
  ansible.builtin.systemd:
    name: 'telegraf'
    daemon_reload: true
    state: 'started'
    enabled: true
  when: 'not ansible_check_mode'
