---

- name: 'Install Telegraf'
  tags: [ 'monitoring_telegraf'  ]
  block:

    - name: 'Deploy Telegraf container'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: 'monitoring_telegraf__use_podman'

    - name: 'Install Telegraf package'
      ansible.builtin.include_tasks:
        file: 'apt.yml'
      when: 'not monitoring_telegraf__use_podman'
