---

- name: 'Include podman-specific variables'
  ansible.builtin.include_vars: 'podman.yml'

- name: 'Create Telegraf directories'
  ansible.builtin.file:
    dest: "{{ item }}"
    state: 'directory'
  with_items:
    - "{{ monitoring_telegraf__podman_home }}"

- name: 'Create Telegraf configuration'
  ansible.builtin.template:
    src: 'telegraf.conf.j2'
    dest: "{{ monitoring_telegraf__home }}/telegraf.conf"
    owner: "{{ monitoring_telegraf__uid }}"
    group: "{{ monitoring_telegraf__gid }}"
    mode: '400'
  notify:
    - 'Restart Telegraf container'
  when: 'not podman___update_mode | bool'

- name: 'Gathering facts about services...'
  ansible.builtin.service_facts:

- name: 'Stop container when it is running'
  ansible.builtin.systemd:
    name: "{{ monitoring_telegraf__container.name }}.service"
    state: 'stopped'
  when: 'ansible_facts.services[monitoring_telegraf__container.name + ".service"] is defined and podman___update_mode | bool'

- name: 'Pull image'
  containers.podman.podman_image:
    name: "{{ monitoring_telegraf__container.image }}"
    force: true
  when: 'podman___update_mode | bool'

- name: 'Install container'
  containers.podman.podman_container:
    name: "{{ monitoring_telegraf__container.name }}"
    hostname: "{{ monitoring_telegraf__container.hostname }}"
    image: "{{ monitoring_telegraf__container.image }}"
    ip: "{{ monitoring_telegraf__container.ip }}"
    network: "{{ monitoring_telegraf__container.network }}"
    timezone: "{{ monitoring_telegraf__container.timezone }}"
    volume: "{{ monitoring_telegraf__container.volumes }}"
    cap_add:
      - 'cap_net_raw'
    quadlet_options: |
      [Install]
      WantedBy=default.target
      
      [Service]
      RestartSec=5
      Restart=always
      
      [Unit]
      {% if monitoring_telegraf__container.requires is defined %}
      Requires={{ monitoring_telegraf__container.requires | join(' ') }}
      {% endif %}
    restart_policy: 'no'
    state: 'quadlet'
    recreate: "{{ podman___update_mode | bool }}"
  when: 'monitoring_telegraf__ipv6 | length == 0'

- name: 'Install container'
  containers.podman.podman_container:
    name: "{{ monitoring_telegraf__container.name }}"
    hostname: "{{ monitoring_telegraf__container.hostname }}"
    image: "{{ monitoring_telegraf__container.image }}"
    ip: "{{ monitoring_telegraf__container.ip }}"
    ip6: "{{ monitoring_telegraf__container.ipv6 }}"
    network: "{{ monitoring_telegraf__container.network }}"
    timezone: "{{ monitoring_telegraf__container.timezone }}"
    volume: "{{ monitoring_telegraf__container.volumes }}"
    cap_add:
      - 'cap_net_raw'
    quadlet_options: |
      [Install]
      WantedBy=default.target
      
      [Service]
      RestartSec=5
      Restart=always
      
      [Unit]
      {% if monitoring_telegraf__container.requires is defined %}
      Requires={{ monitoring_telegraf__container.requires | join(' ') }}
      {% endif %}
    restart_policy: 'no'
    state: 'quadlet'
    recreate: "{{ podman___update_mode | bool }}"
  when: 'monitoring_telegraf__ipv6 | length > 0'

- name: 'Start and enable container'
  ansible.builtin.systemd:
    name: "{{ monitoring_telegraf__container.name }}"
    daemon_reload: true
    state: 'started'
    enabled: true
  when: 'not ansible_check_mode'
