---

- name: Deploy MediaWiki container
  tags: [ 'app_mediawiki' ]
  block:

    - name: Create sites configuration
      include_tasks: site.yml
      loop_control:
        loop_var: site
      with_items: "{{ app_mediawiki__sites }}"

