---

- name: "Is LocalSettings.php available for site {{ site.name }}?"
  ansible.builtin.stat:
    path: "{{ site.home }}/LocalSettings.php"
  register: 'mediawiki_site_stat_result'

- name: "Define LocalSettings.php volume"
  ansible.builtin.set_fact:
    local_settings_volume: "{{ [ site.home + '/LocalSettings.php:/var/www/html/LocalSettings.php' ] if mediawiki_site_stat_result.stat.exists else [] }}"

- name: "Create MediaWiki directories for site {{ site.name }}"
  ansible.builtin.file:
    mode: '755'
    path: "{{ site.home }}/{{ item }}"
    state: 'directory'
  with_items:
    - 'data'
    - 'images'
    - 'extensions'
    - 'skins'

- name: "Create MediaWiki site {{ site.name }} container"
  containers.podman.podman_container:
    name: "{{ site.name | mandatory  }}"
    hostname: "{{ site.hostname | mandatory  }}"
    image: "{{ site.image | default(app_mediawiki__container_default.image) }}"
    ip: "{{ site.ip | mandatory }}"
    ip6: "{{ site.ipv6 | default(omit) }}"
    network: "{{ site.network | default(app_mediawiki__container_default.network) }}"
    timezone: "{{ site.timezone | default(app_mediawiki__container_default.timezone) }}"
    env: "{{ site.environment | default(omit) }}"
    etc_hosts: "{{ site.etc_hosts | default(omit) }}"
    label: "{{ site.labels | default(omit) }}"
    publish: "{{ site.publish | default(omit) }}"
    secrets: "{{ site.secrets | default(omit) }}"
    expose: "{{ site.expose | default(omit) }}"
    volume: "{{ [
      site.home + '/data:/var/www/data',
      site.home + '/images:/var/www/html/images',
      site.home + '/extensions:/var/www/html/extensions',
      site.home + '/skins:/var/www/html/skins'
    ] + local_settings_volume }}"
    quadlet_options: |

      [Install]
      WantedBy=default.target

      [Service]
      RestartSec=5
      Restart=always
    restart_policy: 'no'
    state: 'quadlet'
    recreate: "{{ podman___update_mode | bool }}"

