---

- name: "Is LocalSettings.php available for site {{ site.name }}?"
  ansible.builtin.stat:
    path: "{{ site.home }}/LocalSettings.php"
  register: mediawiki_site_stat_result

- name: "Define LocalSettings.php volume"
  ansible.builtin.set_fact:
    local_settings_volume: "{{ [ site.home + '/LocalSettings.php:/var/www/html/LocalSettings.php' ] if mediawiki_site_stat_result.stat.exists else [] }}"

- name: "Create MediaWiki directories for site {{ site.name }}"
  ansible.builtin.file:
    mode: '755'
    path: "{{ site.home }}/{{ item }}"
    state: directory
  with_items:
    - data
    - images
    - extensions
    - skins

- name: "Create MediaWiki site {{ site.name }} container"
  containers.podman.podman_container:
    name: "{{ site.name }}"
    hostname: "{{ site.hostname }}"
    image: "{{ site.image | default(app_mediawiki__image) }}"
    ip: "{{ site.ip }}"
    network: "{{ site.network | default(app_mediawiki__network) }}"
    restart_policy: "{{ site.restart_policy | default(app_mediawiki__restart_policy) }}"
    etc_hosts: "{{ site.hosts | default(app_mediawiki__hosts) }}"
    timezone: "{{ site.timezone | default(bootstrap_timezone__timezone) }}"
    volume: "{{ [
      site.home + '/data:/var/www/data',
      site.home + '/images:/var/www/html/images',
      site.home + '/extensions:/var/www/html/extensions',
      site.home + '/skins:/var/www/html/skins'
    ] + local_settings_volume }}"
