---

- name: 'Deploy mautrix Bluesky bridge container'
  tags: [ 'mautrix_bridge_bluesky' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ mautrix_bridge_bluesky__uid }}"
        group: "{{ mautrix_bridge_bluesky__gid }}"
        mode: "{{ item.mode | default('0750') }}"
        state: 'directory'
      with_items:
        - dest: "{{ mautrix_bridge_bluesky__podman_home }}"

    - name: "Has configuration been generate?"
      ansible.builtin.stat:
        path: "{{ mautrix_bridge_bluesky__podman_home }}/config.yaml"
      register: 'mautrix_bridge_bluesky_configuration_stat_result'

    - name: 'Generate mautrix bluesky bridge configuration'
      when: 'not mautrix_bridge_bluesky_configuration_stat_result.stat.exists and not podman___update_mode | bool'
      block:
        - name: 'Generate mautrix bluesky bridge configuration'
          containers.podman.podman_container:
            name: "{{ mautrix_bridge_bluesky__container.name }}-generate"
            hostname: "{{ mautrix_bridge_bluesky__container.hostname }}"
            image: "{{ mautrix_bridge_bluesky__container.image }}"
            ip: "{{ mautrix_bridge_bluesky__container.ip }}"
            network: "{{ mautrix_bridge_bluesky__container.network }}"
            env: "{{ mautrix_bridge_bluesky__container.environment }}"
            timezone: "{{ mautrix_bridge_bluesky__container.timezone }}"
            volume: "{{ mautrix_bridge_bluesky__container.volumes }}"
            rm: true
          when: 'mautrix_bridge_bluesky__ipv6 | length == 0'

        - name: 'Generate mautrix bluesky bridge configuration'
          containers.podman.podman_container:
            name: "{{ mautrix_bridge_bluesky__container.name }}-generate"
            hostname: "{{ mautrix_bridge_bluesky__container.hostname }}"
            image: "{{ mautrix_bridge_bluesky__container.image }}"
            ip: "{{ mautrix_bridge_bluesky__container.ip }}"
            ip6: "{{ mautrix_bridge_bluesky__container.ipv6 }}"
            network: "{{ mautrix_bridge_bluesky__container.network }}"
            env: "{{ mautrix_bridge_bluesky__container.environment }}"
            timezone: "{{ mautrix_bridge_bluesky__container.timezone }}"
            volume: "{{ mautrix_bridge_bluesky__container.volumes }}"
            rm: true
          when: 'mautrix_bridge_bluesky__ipv6 | length > 0'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ mautrix_bridge_bluesky__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[mautrix_bridge_bluesky__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ mautrix_bridge_bluesky__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ mautrix_bridge_bluesky__container.name }}"
        hostname: "{{ mautrix_bridge_bluesky__container.hostname }}"
        image: "{{ mautrix_bridge_bluesky__container.image }}"
        ip: "{{ mautrix_bridge_bluesky__container.ip }}"
        network: "{{ mautrix_bridge_bluesky__container.network }}"
        timezone: "{{ mautrix_bridge_bluesky__container.timezone }}"
        dns_servers: "{{ mautrix_bridge_bluesky__container.dns_servers }}"
        env: "{{ mautrix_bridge_bluesky__container.environment }}"
        volume: "{{ mautrix_bridge_bluesky__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if mautrix_bridge_bluesky__container.requires is defined %}
          Requires={{ mautrix_bridge_bluesky__container.requires | join(' ') }}
          {% endif %}
          {% if mautrix_bridge_bluesky__container.wants is defined %}
          Wants={{ mautrix_bridge_bluesky__container.wants | join(' ') }}
          {% endif %}
          {% if mautrix_bridge_bluesky__container.after is defined %}
          After={{ mautrix_bridge_bluesky__container.after | join(' ') }}
          {% endif %}
          {% if mautrix_bridge_bluesky__container.part_of is defined %}
          PartOf={{ mautrix_bridge_bluesky__container.part_of | join(' ') }}
          {% endif %}
          {% if mautrix_bridge_bluesky__container.binds_to is defined %}
          BindsTo={{ mautrix_bridge_bluesky__container.binds_to | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: |
        mautrix_bridge_bluesky__ipv6 | length == 0
        and mautrix_bridge_bluesky_configuration_stat_result.stat.exists
        and not mautrix_bridge_bluesky__setup

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ mautrix_bridge_bluesky__container.name }}"
        hostname: "{{ mautrix_bridge_bluesky__container.hostname }}"
        image: "{{ mautrix_bridge_bluesky__container.image }}"
        ip: "{{ mautrix_bridge_bluesky__container.ip }}"
        ip6: "{{ mautrix_bridge_bluesky__container.ipv6 }}"
        network: "{{ mautrix_bridge_bluesky__container.network }}"
        timezone: "{{ mautrix_bridge_bluesky__container.timezone }}"
        dns_servers: "{{ mautrix_bridge_bluesky__container.dns_servers }}"
        env: "{{ mautrix_bridge_bluesky__container.environment }}"
        volume: "{{ mautrix_bridge_bluesky__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if mautrix_bridge_bluesky__container.requires is defined %}
          Requires={{ mautrix_bridge_bluesky__container.requires | join(' ') }}
          {% endif %}
          {% if mautrix_bridge_bluesky__container.wants is defined %}
          Wants={{ mautrix_bridge_bluesky__container.wants | join(' ') }}
          {% endif %}
          {% if mautrix_bridge_bluesky__container.after is defined %}
          After={{ mautrix_bridge_bluesky__container.after | join(' ') }}
          {% endif %}
          {% if mautrix_bridge_bluesky__container.part_of is defined %}
          PartOf={{ mautrix_bridge_bluesky__container.part_of | join(' ') }}
          {% endif %}
          {% if mautrix_bridge_bluesky__container.binds_to is defined %}
          BindsTo={{ mautrix_bridge_bluesky__container.binds_to | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: |
        mautrix_bridge_bluesky__ipv6 | length > 0
        and mautrix_bridge_bluesky_configuration_stat_result.stat.exists
        and not mautrix_bridge_bluesky__setup

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ mautrix_bridge_bluesky__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: |
        not ansible_check_mode
        and mautrix_bridge_bluesky_configuration_stat_result.stat.exists
        and not mautrix_bridge_bluesky__setup

    - name: 'Enable autoupdate on container'
      when: 'mautrix_bridge_bluesky__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ mautrix_bridge_bluesky__container.name }}"
        container_image: "{{ mautrix_bridge_bluesky__container.image }}"
