---

- name: Setup coturn
  tags: [ 'coturn' ]
  block:

    - name: Install coturn packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ coturn__packages }}"

    - name: Generate configuration file
      ansible.builtin.template:
        src: turnserver.conf.j2
        dest: /etc/turnserver.conf
        owner: root
        group: root
        mode: '640'
      notify:
        - Restart coturn
