---

- name: 'Deploy pgAdmin container'
  tags: [ 'database_pgadmin' ]
  block:

    - name: 'Create secrets'
      containers.podman.podman_secret:
        state: 'present'
        name: 'pgadmin_password'
        data: "{{ database_pgadmin__pass }}"

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ database_pgadmin__container.name }}"
        hostname: "{{ database_pgadmin__container.hostname }}"
        image: "{{ database_pgadmin__container.image }}"
        ip: "{{ database_pgadmin__container.ip }}"
        network: "{{ database_pgadmin__container.network }}"
        restart_policy: "{{ database_pgadmin__container.restart_policy }}"
        timezone: "{{ database_pgadmin__container.timezone }}"
        env: "{{ database_pgadmin__container.environment }}"
        label: "{{ database_pgadmin__container.labels }}"
        secrets: "{{ database_pgadmin__container.secrets }}"
        volume: "{{ database_pgadmin__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'database_pgadmin__ipv6 | length == 0'

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ database_pgadmin__container.name }}"
        hostname: "{{ database_pgadmin__container.hostname }}"
        image: "{{ database_pgadmin__container.image }}"
        ip: "{{ database_pgadmin__container.ip }}"
        ipv6: "{{ database_pgadmin__container.ipv6 }}"
        network: "{{ database_pgadmin__container.network }}"
        restart_policy: "{{ database_pgadmin__container.restart_policy }}"
        timezone: "{{ database_pgadmin__container.timezone }}"
        env: "{{ database_pgadmin__container.environment }}"
        label: "{{ database_pgadmin__container.labels }}"
        secrets: "{{ database_pgadmin__container.secrets }}"
        volume: "{{ database_pgadmin__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'database_pgadmin__ipv6 | length > 0'
