---

- name: 'Deploy pgAdmin container'
  tags: [ 'database_pgadmin' ]
  block:

    - name: 'Create pgAdmin directory'
      ansible.builtin.file:
        mode: '750'
        path: "{{ database_pgadmin__podman_home }}"
        state: 'directory'

    - name: 'Create pgAdmin configuration file'
      ansible.builtin.copy:
        content: "{{ database_pgadmin__server | to_nice_json }}"
        dest: "{{ database_pgadmin__podman_home }}/servers.json"
        mode: '644'
      when: 'database_pgadmin__server | length > 0'

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'pgadmin_password'
        data: "{{ database_pgadmin__pass }}"

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ database_pgadmin__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[database_pgadmin__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ database_pgadmin__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ database_pgadmin__container.name }}"
        hostname: "{{ database_pgadmin__container.hostname }}"
        image: "{{ database_pgadmin__container.image }}"
        ip: "{{ database_pgadmin__container.ip }}"
        network: "{{ database_pgadmin__container.network }}"
        timezone: "{{ database_pgadmin__container.timezone }}"
        env: "{{ database_pgadmin__container.environment }}"
        label: "{{ database_pgadmin__container.labels }}"
        secrets: "{{ database_pgadmin__container.secrets }}"
        volume: "{{ database_pgadmin__container.volumes }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if database_pgadmin__container.requires is defined %}
          Requires={{ database_pgadmin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'database_pgadmin__ipv6 | length == 0'

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ database_pgadmin__container.name }}"
        hostname: "{{ database_pgadmin__container.hostname }}"
        image: "{{ database_pgadmin__container.image }}"
        ip: "{{ database_pgadmin__container.ip }}"
        ip6: "{{ database_pgadmin__container.ipv6 }}"
        network: "{{ database_pgadmin__container.network }}"
        timezone: "{{ database_pgadmin__container.timezone }}"
        env: "{{ database_pgadmin__container.environment }}"
        label: "{{ database_pgadmin__container.labels }}"
        secrets: "{{ database_pgadmin__container.secrets }}"
        volume: "{{ database_pgadmin__container.volumes }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if database_pgadmin__container.requires is defined %}
          Requires={{ database_pgadmin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'database_pgadmin__ipv6 | length > 0'

    - name: 'Started and enable container'
      ansible.builtin.systemd:
        name: "{{ database_pgadmin__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
