---

- name: 'Deploy pgAdmin container'
  tags: [ 'database_pgadmin' ]
  block:

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'pgadmin_password'
        data: "{{ database_pgadmin__pass }}"

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ database_pgadmin__container.name }}"
        hostname: "{{ database_pgadmin__container.hostname }}"
        image: "{{ database_pgadmin__container.image }}"
        ip: "{{ database_pgadmin__container.ip }}"
        network: "{{ database_pgadmin__container.network }}"
        timezone: "{{ database_pgadmin__container.timezone }}"
        env: "{{ database_pgadmin__container.environment }}"
        label: "{{ database_pgadmin__container.labels }}"
        secrets: "{{ database_pgadmin__container.secrets }}"
        volume: "{{ database_pgadmin__container.volumes }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if database_pgadmin__container.requires is defined %}
          Requires={{ database_pgadmin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'database_pgadmin__ipv6 | length == 0'

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ database_pgadmin__container.name }}"
        hostname: "{{ database_pgadmin__container.hostname }}"
        image: "{{ database_pgadmin__container.image }}"
        ip: "{{ database_pgadmin__container.ip }}"
        ip6: "{{ database_pgadmin__container.ipv6 }}"
        network: "{{ database_pgadmin__container.network }}"
        timezone: "{{ database_pgadmin__container.timezone }}"
        env: "{{ database_pgadmin__container.environment }}"
        label: "{{ database_pgadmin__container.labels }}"
        secrets: "{{ database_pgadmin__container.secrets }}"
        volume: "{{ database_pgadmin__container.volumes }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if database_pgadmin__container.requires is defined %}
          Requires={{ database_pgadmin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'database_pgadmin__ipv6 | length > 0'

    - name: 'Started and enable container'
      ansible.builtin.systemd:
        name: "{{ database_pgadmin__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode is defined and podman___update_mode else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
