---
- name: 'Converge'
  hosts: 'all'

  vars_files:
    - 'test_cases.yml'

  vars:
    podman___update_mode: false
    webserver_traefik__test_case: "{{ webserver_traefik__test_cases | selectattr('name', 'eq', inventory_hostname) | first }}"

  tasks:

    - name: 'Run webserver_traefik'
      ansible.builtin.include_role:
        name: 'webserver_traefik'
      vars:
        traefik_home: "{{ webserver_traefik__test_case.role_vars.traefik_home }}"
        traefik_ip: "{{ webserver_traefik__test_case.role_vars.traefik_ip }}"
        traefik_ipv6: "{{ webserver_traefik__test_case.role_vars.traefik_ipv6 | default(omit) }}"
        traefik_network: "{{ webserver_traefik__test_case.role_vars.traefik_network }}"
        traefik_hostname: "{{ webserver_traefik__test_case.role_vars.traefik_hostname }}"
        traefik_timezone: "{{ webserver_traefik__test_case.role_vars.traefik_timezone }}"
