---
- name: 'Prepare test instance'
  hosts: 'all'
  tasks:

    - name: 'Install podman and dependencies'
      ansible.builtin.apt:
        name:
          - 'podman'
          - 'curl'
        state: 'present'
        update_cache: true

    - name: 'Use the vfs storage driver'
      ansible.builtin.copy:
        dest: '/etc/containers/storage.conf'
        content: |
          [storage]
          driver = "vfs"
          runroot = "/run/containers/storage"
          graphroot = "/var/lib/containers/storage"

    - name: 'Create the podman network used by the test container'
      containers.podman.podman_network:
        name: 'podman-molecule'
        state: 'present'
        ipv6: true
        net_config:
          - subnet: '10.89.0.0/24'
            gateway: '10.89.0.1'
          - subnet: 'fd00:89::/64'
            gateway: 'fd00:89::1'

    - name: 'Ensure /etc/timezone exists'
      ansible.builtin.copy:
        dest: '/etc/timezone'
        content: |
          Etc/UTC
