---
webserver_traefik__test_cases:

  - name: 'traefik-ipv4-only'
    role_vars:
      traefik_home: '/opt/traefik-molecule'
      traefik_ip: '10.89.0.10'
      traefik_network: 'podman-molecule'
      traefik_hostname: 'traefik-molecule'
      traefik_timezone: 'Europe/Berlin'
    expect:
      ip: '10.89.0.10'
      ip6: ~

  - name: 'traefik-ipv6'
    role_vars:
      traefik_home: '/opt/traefik-molecule'
      traefik_ip: '10.89.0.10'
      traefik_ipv6: 'fd00:89::10'
      traefik_network: 'podman-molecule'
      traefik_hostname: 'traefik-molecule'
      traefik_timezone: 'Europe/Berlin'
    expect:
      ip: '10.89.0.10'
      ip6: 'fd00:89::10'
