---

- name: Install and configure policyd
  tags: [ 'mail_policyd' ]
  block:

    - name: Install policyd
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ mail_policyd__packages }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: policyd-spf.conf.j2
        dest: "{{ mail_policyd__etc_dir }}/policyd-spf.conf"
        owner: root
        group: root
        mode: '644'
      when: mail_policyd__flavor == 'python'
