---

- name: 'Configure restic backup'
  tags: [ 'backup_restic'  ]
  block:

    - name: 'Include OS-specific variables'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"

    - name: 'Install restic backup packages'
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ backup_restic__packages }}"

    - name: 'Copy restic backup scripts to host'
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup__lib_dir }}/{{ item }}"
        mode: '755'
      with_items:
        - '950.backup.restic'

    - name: 'Generate restic backup configuration file'
      ansible.builtin.template:
        src: 'restic.j2'
        dest: "{{ backup__etc_dir }}/restic"
        owner: 'root'
        group: 'root'
        mode: '640'

    - name: 'Generate restic ssh configuration file'
      ansible.builtin.template:
        src: 'restic-ssh.j2'
        dest: "{{ backup__etc_dir }}/restic-ssh"
        owner: 'root'
        group: 'root'
        mode: '640'
      when: 'backup_restic__ssh'

    - name: 'Generate restic includes file'
      ansible.builtin.copy:
        dest: '/etc/backup/restic-directories'
        content: "{{ backup_restic__include | join('\n') }}"
        owner: 'root'
        group: 'root'
        mode: '644'

    - name: 'Write restic password file'
      no_log: true
      ansible.builtin.copy:
        dest: "{{ backup__etc_dir }}/restic_password"
        owner: 'root'
        group: 'root'
        mode: '400'
        content: |
          {{ backup_restic__password }}
      when: 'not backup_restic__pass_enable'
