---

- name: Configure restic backup
  tags: [ 'backup_restic'  ]
  block:

    - name: Install restic backup packages
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ backup_restic__packages }}"

    - name: Copy restic backup scripts to host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup_common__lib_dir }}/{{ item }}"
        mode: '755'
      with_items: "{{ backup_restic__files }}"

    - name: Generate restic backup configuration file
      ansible.builtin.template:
        src: 'restic.j2'
        dest: "{{ backup_common__etc_dir }}/restic"
        owner: 'root'
        group: 'root'
        mode: '640'

    - name: Generate restic ssh configuration file
      ansible.builtin.template:
        src: 'restic-ssh.j2'
        dest: "{{ backup_common__etc_dir }}/restic-ssh"
        owner: 'root'
        group: 'root'
        mode: '640'

    - name: Generate restic includes file
      ansible.builtin.copy:
        dest: '/etc/backup/restic-directories'
        content: "{{ backup_restic__include | join('\n') }}"
        owner: 'root'
        group: 'root'
        mode: '644'
