---

- name: 'Deploy Redis Insight container'
  tags: [ 'app_rediscommander' ]
  block:

    - name: 'Create podman containers'
      containers.podman.podman_container:
        name: "{{ app_rediscommander__podman_container.name }}"
        hostname: "{{ app_rediscommander__podman_container.hostname }}"
        image: "{{ app_rediscommander__podman_container.image }}"
        ip: "{{ app_rediscommander__podman_container.ip }}"
        network: "{{ app_rediscommander__podman_container.network }}"
        restart_policy: "{{ app_rediscommander__podman_container.restart_policy }}"
        env: "{{ app_rediscommander__podman_container.environment }}"
        etc_hosts: "{{ app_rediscommander__podman_container.hosts }}"
        timezone: "{{ app_rediscommander__podman_container.timezone }}"
        volume: "{{ app_rediscommander__podman_container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: app_rediscommander__ipv6 | length == 0
