---

- name: 'Deploy phpMyAdmin container'
  tags: [ 'database_phpmyadmin' ]
  block:

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'pma_controluser_password'
        data: "{{ database_phpmyadmin__db_pass }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ database_phpmyadmin__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[database_phpmyadmin__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ database_phpmyadmin__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install phpMyAdmin container'
      containers.podman.podman_container:
        name: "{{ database_phpmyadmin__container.name }}"
        hostname: "{{ database_phpmyadmin__container.hostname }}"
        image: "{{ database_phpmyadmin__container.image }}"
        ip: "{{ database_phpmyadmin__container.ip }}"
        ip6: "{{ database_phpmyadmin__container.ipv6 | default(omit) }}"
        network: "{{ database_phpmyadmin__container.network }}"
        timezone: "{{ database_phpmyadmin__container.timezone }}"
        env: "{{ database_phpmyadmin__container.environment | default(omit) }}"
        etc_hosts: "{{ database_phpmyadmin__container.etc_hosts | default(omit) }}"
        label: "{{ database_phpmyadmin__container.labels | default(omit) }}"
        publish: "{{ database_phpmyadmin__container.publish | default(omit) }}"
        expose: "{{ database_phpmyadmin__container.expose | default(omit) }}"
        secrets: "{{ database_phpmyadmin__container.secrets | default(omit) }}"
        volume: "{{ database_phpmyadmin__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always

          [Unit]
          {% if database_phpmyadmin__container.requires is defined %}
          Requires={{ database_phpmyadmin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd_service:
        name: "{{ database_phpmyadmin__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'database_phpmyadmin__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ database_phpmyadmin__container.name }}"
        container_image: "{{ database_phpmyadmin__container.image }}"
