---

- name: Install and configure Icinga 2 agent
  tags: [ 'monitoring_icinga_agent' ]
  block:

    - name: Install Icinga 2 packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ monitoring_icinga_agent__packages }}"

    - name: Create directories for Icinga 2 agent
      ansible.builtin.file:
        path: "{{ item }}"
        owner: "{{ monitoring_icinga_agent__user }}"
        group: "{{ monitoring_icinga_agent__group }}"
        state: 'directory'
      with_items:
        - "{{ monitoring_icinga_agent__cert_dir }}"

    - name: Copy SSL certificates
      ansible.builtin.copy:
        src: "{{ item.name }}"
        mode: "{{ item.mode | default('644') }}"
        dest: "{{ monitoring_icinga_agent__cert_dir }}"
        owner: "{{ monitoring_icinga_agent__user }}"
        group: "{{ monitoring_icinga_agent__group }}"
        remote_src: yes
      with_items:
        - name: "{{ pki_easyrsa_deploy__realms_dir }}/{{ monitoring_icinga_agent__certificate_realm }}/public/ca.crt"
        - name: "{{ pki_easyrsa_deploy__realms_dir }}/{{ monitoring_icinga_agent__certificate_realm }}/public/{{ monitoring_icinga_agent__certificate_realm }}.crt"
        - name: "{{ pki_easyrsa_deploy__realms_dir }}/{{ monitoring_icinga_agent__certificate_realm }}/private/{{ monitoring_icinga_agent__certificate_realm }}.key"
          mode: '600'

    - name: Create Icinga 2 agent configuration
      ansible.builtin.include_role:
        name: 'monitoring_icinga_config'

