---

#
# Substitutes - do not change
#

dns_unbound__use_podman: "{{ unbound_use_podman | default(true) }}"

dns_unbound__home: "{{ unbound_home | mandatory }}"

dns_unbound__hostname: "{{ unbound_hostname | default('unbound.' + dns_hostname) }}"
dns_unbound__ip: "{{ unbound_ip | mandatory }}"
dns_unbound__ipv6: "{{ unbound_ipv6 | default('') }}"
dns_unbound__version: "{{ unbound_version | default('latest') }}"

dns_unbound__network: "{{ unbound_network | mandatory }}"
dns_unbound__hosts: "{{ unbound_hosts | default({}) }}"
dns_unbound__timezone: "{{ unbound_timezone | default(bootstrap_timezone__timezone) }}"
dns_unbound__publish: "{{ unbound_publish | default(true) }}"

dns_unbound__container: "{{ dns_unbound__container_default | combine(unbound_container | default({})) }}"

# https://docs.pi-hole.net/guides/dns/unbound/

dns_unbound__syslog: "{{ unbound_syslog | default(true) }}"
dns_unbound__logfile: "{{ unbound_logfile | default('/var/log/unbound/unbound.log') }}"
dns_unbound__verbosity: "{{ unbound_verbosity | default(0) }}"
dns_unbound__interface_automatic: "{{ unbound_interface_automatic | default(true) }}"
dns_unbound__interfaces: "{{ unbound_interfaces | default(dns_unbound__interfaces_default) }}"
dns_unbound__port: "{{ unbound_port | default(53) }}"
dns_unbound__ip4: "{{ unbound_ip4 | default(true) }}"
dns_unbound__ip6: "{{ unbound_ip6 | default(true) }}"
dns_unbound__udp: "{{ unbound_udp | default(true) }}"
dns_unbound__tcp: "{{ unbound_tcp | default(true) }}"
dns_unbound__prefer_ip4: "{{ unbound_prefer_ip4 | default(false) }}"
dns_unbound__prefer_ip6: "{{ unbound_prefer_ip6 | default(false) }}"
dns_unbound__harden_glue: "{{ unbound_harden_glue | default(true) }}"
dns_unbound__harden_dnssec_stripped: "{{ unbound_harden_dnssec_stripped | default(true) }}"
dns_unbound__use_caps_for_id: "{{ unbound_use_caps_for_id | default(false) }}"
dns_unbound__prefetch: "{{ unbound_prefetch | default(true) }}"
dns_unbound__num_threads: "{{ unbound_num_threads | default(1) }}"
dns_unbound__so_rcvbuf: "{{ unbound_so_rcvbuf | default('1m') }}"
dns_unbound__access_control: "{{ unbound_access_control | default(dns_unbound__access_control_default) }}"

dns_unbound__control_enable: "{{ unbound_control_enable | default(true) }}"
dns_unbound__control_interface: "{{ unbound_control_interface | default('/run/unbound.ctl') }}"

dns_unbound__disable_resolvconf: "{{ unbound_disable_resolvconf | default(false) }}"

dns_unbound__packages: "{{ dns_unbound__packages_default[bootstrap_ansible__distribution] }}"

#
# Defaults - do not change
#

# native installation related variables

dns_unbound__etc: '/etc/unbound/unbound.conf.d'
dns_unbound__var: '/var/lib/unbound'

dns_unbound__packages_default:
  Debian:
    - 'unbound'
    - 'unbound-anchor'
    - 'unbound-host'

# podman related variables

dns_unbound__uid: 1000
dns_unbound__gid: "{{ dns_unbound__uid }}"
dns_unbound__name: 'unbound'
dns_unbound__image: "docker.io/mvance/unbound"

dns_unbound__publish_tcp: "{{
   dns_unbound__port + ':' + dns_unbound__port + '/tcp' if  dns_unbound__tcp else ''
}}"

dns_unbound__publish_udp: "{{
   dns_unbound__port + ':' + dns_unbound__port + '/udp' if  dns_unbound__udp else ''
}}"

dns_unbound__publish_ports: "{{
   [ dns_unbound__publish_tcp, dns_unbound__publish_udp ] if  dns_unbound__publish else []
}}"

dns_unbound__container_default:
  name: "{{ dns_unbound__name }}"
  hostname: "{{ dns_unbound__hostname }}"
  image: "{{ dns_unbound__image }}:{{ dns_unbound__version }}"
  ip: "{{ dns_unbound__ip }}"
  network: "{{ dns_unbound__network }}"
  restart_policy: 'always'
  volumes:
    - "{{ dns_unbound__home }}:/opt/unbound/etc/unbound/"
  publish: "{{ dns_unbound__publish_ports }}"
  hosts: "{{ dns_unbound__hosts }}"
  timezone: "{{ dns_unbound__timezone }}"

dns_unbound__interfaces_default:
 - '127.0.0.1'

dns_unbound__private_addresses:
# Ensure privacy of local IP ranges
 - '10.0.0.0/8'
 - '172.16.0.0/12'
 - '192.168.0.0/16'
 - '169.254.0.0/16'
 - 'fd00::/8'
 - 'fe80::/10'
 - '::ffff:0:0/96'
# Ensure no reverse queries to non-public IP ranges (RFC6303 4.2)
 - '192.0.2.0/24'
 - '198.51.100.0/24'
 - '203.0.113.0/24'
 - '255.255.255.255/32'
 - '2001:db8::/32'

dns_unbound__access_control_default:
  - '127.0.0.1/32 allow'
  - '192.168.0.0/16 allow'
  - '172.16.0.0/12 allow'
  - '10.0.0.0/8 allow'
  - 'fc00::/7 allow'
  - '::1/128 allow'

# >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
# by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
dns_unbound__edns_buffer_size: 1232

