---

- name: 'Deploy synapse-admin container'
  tags: [ 'matrix_admin' ]
  block:

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ matrix_admin__container.name }}"
        hostname: "{{ matrix_admin__container.hostname }}"
        image: "{{ matrix_admin__container.image }}"
        ip: "{{ matrix_admin__container.ip }}"
        network: "{{ matrix_admin__container.network }}"
        restart_policy: "{{ matrix_admin__container.restart_policy }}"
        etc_hosts: "{{ matrix_admin__container.hosts }}"
        env: "{{ matrix_admin__container.environment }}"
        timezone: "{{ matrix_admin__container.timezone }}"
        volume: "{{ matrix_admin__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: matrix_admin__ipv6 | length == 0
