---

- name: 'Deploy synapse-admin container'
  tags: [ 'matrix_admin' ]
  block:

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ matrix_admin__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[matrix_admin__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ matrix_admin__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ matrix_admin__container.name }}"
        hostname: "{{ matrix_admin__container.hostname }}"
        image: "{{ matrix_admin__container.image }}"
        ip: "{{ matrix_admin__container.ip }}"
        network: "{{ matrix_admin__container.network }}"
        timezone: "{{ matrix_admin__container.timezone }}"
        env: "{{ matrix_admin__container.environment }}"
        label: "{{ matrix_admin__container.labels }}"
        volume: "{{ matrix_admin__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if matrix_admin__container.requires is defined %}
          Requires={{ matrix_admin__container.requires | join(' ') }}
          {% endif %}
          {% if matrix_admin__container.wants is defined %}
          Wants={{ matrix_admin__container.wants | join(' ') }}
          {% endif %}
          {% if matrix_admin__container.after is defined %}
          After={{ matrix_admin__container.after | join(' ') }}
          {% endif %}
          {% if matrix_admin__container.part_of is defined %}
          PartOf={{ matrix_admin__container.part_of | join(' ') }}
          {% endif %}
          {% if matrix_admin__container.binds_to is defined %}
          BindsTo={{ matrix_admin__container.binds_to | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'matrix_admin__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ matrix_admin__container.name }}"
        hostname: "{{ matrix_admin__container.hostname }}"
        image: "{{ matrix_admin__container.image }}"
        ip: "{{ matrix_admin__container.ip }}"
        ip6: "{{ matrix_admin__container.ipv6 }}"
        network: "{{ matrix_admin__container.network }}"
        timezone: "{{ matrix_admin__container.timezone }}"
        env: "{{ matrix_admin__container.environment }}"
        label: "{{ matrix_admin__container.labels }}"
        volume: "{{ matrix_admin__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if matrix_admin__container.requires is defined %}
          Requires={{ matrix_admin__container.requires | join(' ') }}
          {% endif %}
          {% if matrix_admin__container.wants is defined %}
          Wants={{ matrix_admin__container.wants | join(' ') }}
          {% endif %}
          {% if matrix_admin__container.after is defined %}
          After={{ matrix_admin__container.after | join(' ') }}
          {% endif %}
          {% if matrix_admin__container.part_of is defined %}
          PartOf={{ matrix_admin__container.part_of | join(' ') }}
          {% endif %}
          {% if matrix_admin__container.binds_to is defined %}
          BindsTo={{ matrix_admin__container.binds_to | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'matrix_admin__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ matrix_admin__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'matrix_admin__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ matrix_admin__container.name }}"
        container_image: "{{ matrix_admin__container.image }}"
