---

- name: 'Deploy Voting System container'
  tags: [ 'app_voting_system' ]
  block:

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'voting_system_database_password'
        data: "{{ app_voting_system__db_pass }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_voting_system__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_voting_system__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_voting_system__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_voting_system__container.name }}"
        hostname: "{{ app_voting_system__container.hostname }}"
        image: "{{ app_voting_system__container.image }}"
        ip: "{{ app_voting_system__container.ip }}"
        network: "{{ app_voting_system__container.network }}"
        timezone: "{{ app_voting_system__container.timezone }}"
        env: "{{ app_voting_system__container.environment }}"
        label: "{{ app_voting_system__container.labels }}"
        secrets: "{{ app_voting_system__container.secrets }}"
        volume: "{{ app_voting_system__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_voting_system__container.requires is defined %}
          Requires={{ app_voting_system__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_voting_system__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_voting_system__container.name }}"
        hostname: "{{ app_voting_system__container.hostname }}"
        image: "{{ app_voting_system__container.image }}"
        ip: "{{ app_voting_system__container.ip }}"
        ip6: "{{ app_voting_system__container.ipv6 }}"
        network: "{{ app_voting_system__container.network }}"
        timezone: "{{ app_voting_system__container.timezone }}"
        env: "{{ app_voting_system__container.environment }}"
        label: "{{ app_voting_system__container.labels }}"
        secrets: "{{ app_voting_system__container.secrets }}"
        volume: "{{ app_voting_system__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_voting_system__container.requires is defined %}
          Requires={{ app_voting_system__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_voting_system__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_voting_system__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
