---

- name: Install systemd-timesyncd
  tags: [ 'systemd_timesyncd' ]
  block:

    - name: Install systemd-timesyncd packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ systemd_timesyncd__packages }}"

    - name: Generate systemd-timesyncd configuration file
      ansible.builtin.template:
        src: timesyncd.conf.j2
        dest: "{{ systemd_timesyncd__etc_dir }}/timesyncd.conf"
        owner: root
        group: root
        mode: 644
      notify:
        - Restart systemd-timesyncd

    - name: Enable systemd-timesyncd service
      ansible.builtin.systemd:
        enabled: true
        state: started
        name: systemd-timesyncd
      when: not ansible_check_mode
