---

- name: Deploy GitLab Runner container
  tags: [ 'app_gitlab_runner' ]
  block:

    - name: Deploy container via podman
      ansible.builtin.import_role:
        name: podman
      vars:
        pod_containers:
          - "{{ app_gitlab_runner__container }}"
