---
webserver_anubis__test_cases:

  - name: 'anubis-ipv4-only'
    role_vars:
      anubis_home: '/opt/anubis-molecule'
      anubis_ip: '10.89.0.10'
      anubis_network: 'podman-molecule'
      anubis_hostname: 'anubis-molecule'
      anubis_timezone: 'Europe/Berlin'
      anubis_target: 'http://127.0.0.1:8080'
    expect:
      ip: '10.89.0.10'
      ip6: ~

  - name: 'anubis-ipv6'
    role_vars:
      anubis_home: '/opt/anubis-molecule'
      anubis_ip: '10.89.0.10'
      anubis_ipv6: 'fd00:89::10'
      anubis_network: 'podman-molecule'
      anubis_hostname: 'anubis-molecule'
      anubis_timezone: 'Europe/Berlin'
      anubis_target: 'http://127.0.0.1:8080'
    expect:
      ip: '10.89.0.10'
      ip6: 'fd00:89::10'
