---
# tasks file for roles/msmtp

- name: Install msmtp packages
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ msmtp__packages_combined }}"

- name: Generate configuration file
  ansible.builtin.template:
    src: etc/msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: 0444
  vars:
    accounts: "{{ msmtp__accounts }}"
    passwords: "{{ msmtp__password }}"
    auto_from: "{{ msmtp__auto_from }}"
    maildomain: "{{ msmtp__maildomain }}"
    syslog: "{{ msmtp__syslog }}"

- name: Generate forward file
  ansible.builtin.copy:
    dest: /root/.forward
    content: |
      {{ msmtp__root_forward }}
    owner: root
    group: root
    mode: 0644
  when: msmtp__root_forward | length > 0

- name: Set msmtp as role for sendmail
  ansible.builtin.copy:
    dest: /etc/ansible/sendmail
    content: |
      msmtp
    owner: root
    group: root
    mode: 0644
