---

- name: Install fail2ban packages
  tags: [ 'packages' ]
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ security__fail2ban_packages }}"

- name: Configure fail2ban
  tags: [ 'configuration' ]
  ansible.builtin.template:
    src: fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify:
  - Restart fail2ban

- name: Configure fail2ban filters
  tags: [ 'configuration' ]
  ansible.builtin.template:
    src: fail2ban/filter.conf.j2
    dest: "/etc/fail2ban/filter.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ security__fail2ban_filter }}"
  notify:
  - Restart fail2ban

- name: Configure fail2ban jails
  tags: [ 'configuration' ]
  ansible.builtin.template:
    src: fail2ban/jail.conf.j2
    dest: "/etc/fail2ban/jail.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ security__fail2ban_jails }}"
  notify:
  - Restart fail2ban
