---

- name: Install fail2ban packages
  tags: [ 'packages' ]
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ security__fail2ban_packages }}"

- name: Configure fail2ban
  tags: [ 'configuration' ]
  ansible.builtin.template:
    src: etc/fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify:
  - Restart fail2ban
