---

- name: 'Deploy Node-RED container'
  tags: [ 'app_nodered' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{  app_nodered__uid }}"
        mode: "{{ item.mode | default('0700') }}"
        state: 'directory'
      with_items:
        - dest: "{{ app_nodered__podman_home }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_nodered__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_nodered__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_nodered__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_nodered__container.name }}"
        hostname: "{{ app_nodered__container.hostname }}"
        image: "{{ app_nodered__container.image }}"
        ip: "{{ app_nodered__container.ip }}"
        network: "{{ app_nodered__container.network }}"
        timezone: "{{ app_nodered__container.timezone }}"
        env: "{{ app_nodered__container.environment }}"
        label: "{{ app_nodered__container.labels }}"
        volume: "{{ app_nodered__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          {% if app_nodered__container.exec_start_pre is defined %}
          {% for command in app_nodered__container.exec_start_pre %}
          ExecStartPre={{ command }}
          {% endfor %}
          {% endif %}
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_nodered__container.requires is defined %}
          Requires={{ app_nodered__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_nodered__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_nodered__container.name }}"
        hostname: "{{ app_nodered__container.hostname }}"
        image: "{{ app_nodered__container.image }}"
        ip: "{{ app_nodered__container.ip }}"
        ip6: "{{ app_nodered__container.ipv6 }}"
        network: "{{ app_nodered__container.network }}"
        timezone: "{{ app_nodered__container.timezone }}"
        env: "{{ app_nodered__container.environment }}"
        label: "{{ app_nodered__container.labels }}"
        volume: "{{ app_nodered__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          {% if app_nodered__container.exec_start_pre is defined %}
          {% for command in app_nodered__container.exec_start_pre %}
          ExecStartPre={{ command }}
          {% endfor %}
          {% endif %}
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_nodered__container.requires is defined %}
          Requires={{ app_nodered__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_nodered__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_nodered__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
