---

#
# Substitutes - do not change
#

app_odoo__hostname: "{{ odoo_hostname | default('odoo.' + dns_hostname) }}"
app_odoo__ip: "{{ odoo_ip | mandatory }}"
app_odoo__ipv6: "{{ odoo_ipv6 | default('') }}"
app_odoo__network: "{{ odoo_network | mandatory }}"
app_odoo__hosts: "{{ odoo_hosts | default({}) }}"
app_odoo__timezone: "{{ odoo_timezone | default(bootstrap_timezone__timezone) }}"
app_odoo__home: "{{ odoo_home | mandatory }}"

app_odoo__setup: "{{ odoo_setup | default(true) }}"

app_odoo__db_name: "{{ odoo_db_name | default('odoo') }}"
app_odoo__db_user: "{{ odoo_db_user | default('odoo') }}"
app_odoo__db_pass: "{{ odoo_db_pass | mandatory }}"
app_odoo__db_host: "{{ odoo_db_host | mandatory }}"
app_odoo__db_port: "{{ odoo_db_port | default(5432) }}"

app_odoo__smtp_server: "{{ odoo_smtp_server | default('localhost') }}"
app_odoo__smtp_port: "{{ odoo_smtp_port | default(25) }}"
app_odoo__smtp_user: "{{ odoo_smtp_user | default('') }}"
app_odoo__smtp_password: "{{ odoo_smtp_password | default('') }}"
app_odoo__smtp_ssl: "{{ odoo_smtp_ssl | default(true) }}"
app_odoo__email_from: "{{ odoo_email_from | default('') }}"

app_odoo__version: "{{ odoo_version | default('18') }}"
app_odoo__container: "{{ app_odoo__podman_container_default }}"

#
# Defaults - do not change
#

app_odoo__data_dir: "{{ app_odoo__home + '/data' }}"
app_odoo__config_dir: "{{ app_odoo__home + '/config' }}"

# Set to fix value in the docker image
app_odoo__uid: 100

app_odoo__command: "{{
  ['odoo', '-i', 'base'] if app_odoo__setup else ['odoo']
}}"

app_odoo__podman_image: 'docker.io/library/odoo'

app_odoo__podman_container_default:
  name: 'odoo'
  hostname: "{{ app_odoo__hostname }}"
  image: "{{ app_odoo__podman_image }}:{{ app_odoo__version }}"
  ip: "{{ app_odoo__ip }}"
  ipv6: "{{ app_odoo__ipv6 }}"
  network: "{{ app_odoo__network }}"
  restart_policy: 'always'
  hosts: "{{ app_odoo__hosts }}"
  environment: {}
#    HOST: "{{ app_odoo__db_host }}"
#    PORT: "{{ app_odoo__db_port }}"
#    USER: "{{ app_odoo__db_user }}"
#    PASSWORD: "{{ app_odoo__db_pass }}"
  timezone: "{{ app_odoo__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - "{{ app_odoo__config_dir }}:/etc/odoo"
    - "{{ app_odoo__data_dir }}:/var/lib/odoo"
  command: "{{ app_odoo__command }}"
