---

- name: 'Configure FoundryVTT backup'
  tags: [ 'backup_foundryvtt'  ]
  block:

    - name: 'Include OS-specific variables'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"

    - name: 'Install borg backup packages'
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ backup_foundryvtt__packages }}"

    - name: 'Copy borg backup scripts to host'
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup__lib_dir }}/{{ item }}"
        mode: '755'
      with_items:
        - '910.backup.foundryvtt'

    - name: 'Generate borg backup configuration file'
      ansible.builtin.template:
        src: 'foundryvtt.j2'
        dest: "{{ backup__etc_dir }}/foundryvtt"
        owner: 'root'
        group: 'root'
        mode: '640'
