---

- name: Install Apache mod_perl2
  tags: [ 'webserver_apache_perl'  ]
  block:

    - name: Install mod_perl2 packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ webserver_apache_perl__packages }}"

    - name: "Enable mod_perl2"
      ansible.builtin.shell: "a2enmod perl"
