---

- name: Install and configure WireGuard
  tags: [ 'vpn_wireguard' ]
  block:
  
    - name: Install packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ vpn_wireguard__packages }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: wg.conf.j2
        dest: "/etc/wireguard/{{ item.interface }}.conf"
        owner: root
        group: root
        mode: '640'
      vars:
        wgnet: "{{ item }}"
      register: vpn_wireguard__create_config_result
      notify:
      - Restart WireGuard
      with_items: "{{ vpn_wireguard__networks }}"

    - name: Enable service
      when: not ansible_check_mode
      ansible.builtin.service:
        name: "wg-quick@{{ item.interface }}"
        state: started
        enabled: yes
      with_items: "{{ vpn_wireguard__networks }}"
