---

- name: Setup ssh
  tags: [ 'ssh' ]
  block:

    - name: Generate ssh configuration
      ansible.builtin.template:
        src: ssh_config.j2
        dest: "{{ ssh__ssh_config_dir }}/ssh_config.conf"
        owner: root
        group: root
        mode: '644'

    - name: Generate sshd configuration
      ansible.builtin.template:
        src: sshd_config.j2
        dest: "{{ ssh__sshd_config_dir }}/sshd_config.conf"
        owner: root
        group: root
        mode: '644'
      notify:
        - Restart sshd
