---
# tasks file for roles/icinga

- name: Configure Icingaweb module
  tags: [ 'icingaweb' ]
  block:

  - name: Enable module
    tags: [ 'configuration' ]
    ansible.builtin.file:
      src: "/usr/share/icingaweb2/modules/{{ module }}"
      dest: "/etc/icingaweb2/enabledModules/{{ module }}"
      state: link

  - name: Create module configuration directory
    tags: [ 'configuration' ]
    ansible.builtin.file:
      dest: "/etc/icingaweb2/modules/{{ module }}"
      owner: root
      group: www-data
      mode: 0750
      state: directory

  - name: Create module configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "etc/icingaweb2/ini.j2"
      dest: "/etc/icingaweb2/modules/{{ module }}/{{ item }}.ini"
      owner: root
      group: www-data
      mode: 0640
    vars:
      content: "{{ icingaweb__modules_config[module][item] }}"
    with_items: "{{ icingaweb__modules_config[module] }}"
