---
# tasks file for roles/icinga

- name: Initialize zone
  tags: [ 'icinga' ]
  block:

  - name: Create zone directory
    ansible.builtin.file:
      dest: "/etc/icinga2/zones.d/{{ zone.key }}"
      state: directory

  - name: Generate configuration files for master and standalone
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 0644
    vars:
      icinga__conf_hosts: "{{ zone.value.hosts }}"
      icinga__conf_services: "{{ zone.value.services }}"
    with_items:
    - src: etc/icinga2/conf.d/hosts.conf.j2
      dest: /etc/icinga2/zones.d/{{ zone.key }}/hosts.conf
    - src: etc/icinga2/conf.d/services.conf.j2
      dest: /etc/icinga2/zones.d/{{ zone.key }}/services.conf
    notify:
    - Restart Icinga
