---
# tasks file for roles/icinga

- name: Install icingaweb packages
  tags: [ 'packages' ]
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ icingaweb__packages_combined }}"

- name: Generate configuration files
  tags: [ 'configuration' ]
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  vars:
    content: "{{ item.content }}"
  with_items:
  - src: etc/icingaweb2/config.ini.j2
    dest: /etc/icingaweb2/config.ini
  - src: etc/icingaweb2/authentication.ini.j2
    dest: /etc/icingaweb2/authentication.ini
  - src: etc/icingaweb2/groups.ini.j2
    dest: /etc/icingaweb2/groups.ini
  - src: etc/icingaweb2/ini.j2
    dest: /etc/icingaweb2/resources.ini
    content: "{{ icingaweb__resources }}"
  - src: etc/icingaweb2/ini.j2
    dest: /etc/icingaweb2/roles.ini
    content: "{{ icingaweb__roles }}"

- name: Create directory for enabled modules
  tags: [ 'configuration' ]
  ansible.builtin.file:
    dest: /etc/icingaweb2/enabledModules
    owner: www-data
    group: www-data
    mode: 0750
    state: directory

- name: Create log directory for icingaweb
  tags: [ 'configuration' ]
  ansible.builtin.file:
    dest: /var/log/icingaweb2
    owner: www-data
    group: www-data
    mode: 0750
    state: directory

- name: Configure modules
  tags: [ 'configuration' ]
  include: icingaweb_modules.yml
  loop_control:
    loop_var: module
  with_items: "{{ icingaweb__modules_combined }}"
