---
# tasks file for roles/icinga

- name: Install and configure Icinga
  tags: [ 'icinga' ]
  when: icinga__enable
  block:
  
  - name: Install icinga packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ icinga__packages_combined }}"

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 0644
    vars:
      objects: "{{ item.objects | default({}) }}"
    with_items:
    - src: etc/icinga2/constants.conf.j2
      dest: /etc/icinga2/constants.conf
    - src: etc/icinga2/icinga2.conf.j2
      dest: /etc/icinga2/icinga2.conf
    - src: etc/icinga2/zones.conf.j2
      dest: /etc/icinga2/zones.conf
    - src: etc/icinga2/conf.d/app.conf.j2
      dest: /etc/icinga2/conf.d/app.conf
    - src: etc/icinga2/conf.d/objects.conf.j2
      dest: /etc/icinga2/conf.d/commands.conf
      objects: "{{ icinga__conf_commands }}"
    - src: etc/icinga2/conf.d/objects.conf.j2
      dest: /etc/icinga2/conf.d/templates.conf
      objects: "{{ icinga__conf_templates }}"
    - src: etc/icinga2/conf.d/timeperiods.conf.j2
      dest: /etc/icinga2/conf.d/timeperiods.conf
    - src: etc/icinga2/conf.d/objects.conf.j2
      dest: /etc/icinga2/conf.d/users.conf
      objects: "{{ icinga__conf_users }}"

  - name: Generate MySQL configuration
    tags: [ 'configuration' ]
    when: icinga__mysql_enable
    ansible.builtin.template:
      src: etc/icinga2/features-available/ido-mysql.conf.j2
      dest: /etc/icinga2/features-available/ido-mysql.conf
      mode: 0600

  - name: Enable features
    tags: [ 'configuration' ]
    when: not ansible_check_mode
    ansible.builtin.file:
      src: "/etc/icinga2/features-available/{{ item }}.conf"
      dest: "/etc/icinga2/features-enabled/{{ item }}.conf"
      state: link
    with_items: "{{ icinga__features_combined }}"

- name: Install and configure Icingaweb
  tags: [ 'icinga' ]
  when: icinga__web_enable
  block:
  
  - name: Install icingaweb packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ icinga__web_packages_combined }}"
