---
# tasks file for roles/icinga

- name: Install and configure Icinga
  tags: [ 'icinga' ]
  when: icinga__enable
  include: icinga.yml

- name: Install and configure Icingaweb
  tags: [ 'icinga' ]
  when: icingaweb__enable
  include: icingaweb.yml
