---

- name: Install and configure SpamAssassin
  tags: [ 'mail_spamassassin' ]
  block:

    - name: Install SpamAssassin
      block:
        - name: Install spamassassin
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_spamassassin__packages }}"
        - name: Install spamc
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_spamassassin__spamc_packages }}"
          when: mail_spamassassin__spamc
        - name: Install spamd
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_spamassassin__spamd_packages }}"
          when: mail_spamassassin__spamd
        - name: Install compile
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_spamassassin__compile_packages }}"
          when: mail_spamassassin__compile
