---
- name: 'Converge'
  hosts: 'all'

  vars_files:
    - 'test_cases.yml'

  vars:
    podman___update_mode: false
    webserver_sws__test_case: "{{ webserver_sws__test_cases | selectattr('name', 'eq', inventory_hostname) | first }}"

  tasks:

    - name: 'Run webserver_sws'
      ansible.builtin.include_role:
        name: 'webserver_sws'
      vars:
        sws_home: "{{ webserver_sws__test_case.role_vars.sws_home }}"
        sws_ip: "{{ webserver_sws__test_case.role_vars.sws_ip }}"
        sws_ipv6: "{{ webserver_sws__test_case.role_vars.sws_ipv6 | default(omit) }}"
        sws_network: "{{ webserver_sws__test_case.role_vars.sws_network }}"
        sws_hostname: "{{ webserver_sws__test_case.role_vars.sws_hostname }}"
        sws_timezone: "{{ webserver_sws__test_case.role_vars.sws_timezone }}"
