---
dependency:
  name: 'galaxy'
driver:
  name: 'podman'
platforms:
  - name: 'sws-ipv4-only'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    pre_build_image: true
    privileged: true
    systemd: 'always'
    command: '/lib/systemd/systemd'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - 'SYS_ADMIN'
  - name: 'sws-ipv6'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    pre_build_image: true
    privileged: true
    systemd: 'always'
    command: '/lib/systemd/systemd'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - 'SYS_ADMIN'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      callback_result_format: 'yaml'
      gathering: 'smart'
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_ROLES_PATH: '../../../'
verifier:
  name: 'ansible'
