---
webserver_sws__test_cases:

  - name: 'sws-ipv4-only'
    role_vars:
      sws_home: '/opt/sws-molecule'
      sws_ip: '10.89.0.10'
      sws_network: 'podman-molecule'
      sws_hostname: 'sws-molecule'
      sws_timezone: 'Europe/Berlin'
    expect:
      ip: '10.89.0.10'
      ip6: ~

  - name: 'sws-ipv6'
    role_vars:
      sws_home: '/opt/sws-molecule'
      sws_ip: '10.89.0.10'
      sws_ipv6: 'fd00:89::10'
      sws_network: 'podman-molecule'
      sws_hostname: 'sws-molecule'
      sws_timezone: 'Europe/Berlin'
    expect:
      ip: '10.89.0.10'
      ip6: 'fd00:89::10'
