---

- name: Install nebula-sync
  tags: [ 'dns_nebula_sync' ]
  block:

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ dns_nebula_sync__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[dns_nebula_sync__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ dns_nebula_sync__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ dns_nebula_sync__container.name }}"
        hostname: "{{ dns_nebula_sync__container.hostname }}"
        image: "{{ dns_nebula_sync__container.image }}"
        ip: "{{ dns_nebula_sync__container.ip }}"
        ip6: "{{ dns_nebula_sync__container.ipv6 | default(omit) }}"
        network: "{{ dns_nebula_sync__container.network }}"
        timezone: "{{ dns_nebula_sync__container.timezone }}"
        env: "{{ dns_nebula_sync__container.environment | default(omit) }}"
        volume: "{{ dns_nebula_sync__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ dns_nebula_sync__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode is defined and podman___update_mode else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
