---

- name: 'Create override configuration for systemd service'
  tags: [ 'systemd_override' ]
  block:

    - name: 'Create systemd service override directory'
      ansible.builtin.file:
        path: "{{ systemd_override__service_dir }}"
        state: 'directory'

    - name: 'Modify systemd service'
      ansible.builtin.template:
        src: 'override.conf.j2'
        dest: "{{ systemd_override__service_dir }}/override.conf"
