---

- name: 'Configure systemd service'
  tags: [ 'systemd_service' ]
  block:

    - name: 'Include OS-specific variables'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"

    - name: 'Generate service file'
      ansible.builtin.template:
        src: 'service.j2'
        dest: "{{ systemd_service__system_dir }}/{{ systemd_service__name }}.service"
        owner: 'root'
        group: 'root'
        mode: '644'
      notify:
        - 'Restart systemd service'

    - name: 'Enable service'
      ansible.builtin.systemd:
        daemon_reload: true
        name: "{{ systemd_service__name }}.service"
        enabled: true
      when: 'not ansible_check_mode'
