---

- name: Configure systemd network interfaces
  tags: [ 'systemd_network' ]
  block:

    - name: Generate CAN network interfaces
      ansible.builtin.template:
        src: can.network.j2
        dest: "{{ systemd_network__system_dir }}/{{ item.name }}.network"
        owner: root
        group: root
        mode: '644'
      with_items: "{{ systemd_network__interfaces }}"
      when: item.type == 'can'
      notify:
        - Reload systemd

    - name: Force systemd reload
      meta: flush_handlers
      when: not ansible_check_mode

    - name: Enable systemd-networkd
      ansible.builtin.systemd:
        name: 'systemd-networkd'
        enabled: "{{ systemd_network__networkd | ternary('yes', 'no') }}"
        state: 'started'
      when: not ansible_check_mode

#    - name: Enable services
#      ansible.builtin.systemd:
#        name: "{{ item.name }}.network"
#        enabled: "{{ item.enabled | ternary('yes', 'no') }}"
#      with_items: "{{ systemd_network__services | selectattr('enabled', 'defined') | list }}"
#      when: not ansible_check_mode
