---

- name: 'Deploy Grafana container'
  tags: [ 'app_grafana' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ app_grafana__uid }}"
        mode: "{{ item.mode | default('0700') }}"
        state: 'directory'
      with_items:
        - dest: "{{ app_grafana__podman_etc_dir }}"
        - dest: "{{ app_grafana__podman_data_dir }}"
        - dest: "{{ app_grafana__podman_log_dir }}"

    - name: 'Generate Grafana configuration'
      ansible.builtin.template:
        src: 'grafana.ini.j2'
        dest: "{{ app_grafana__podman_etc_dir }}/grafana.ini"
        owner: "{{ app_grafana__uid }}"
        mode: '640'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_grafana__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_grafana__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_grafana__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_grafana__container.name }}"
        hostname: "{{ app_grafana__container.hostname }}"
        image: "{{ app_grafana__container.image }}"
        ip: "{{ app_grafana__container.ip }}"
        network: "{{ app_grafana__container.network }}"
        timezone: "{{ app_grafana__container.timezone }}"
        label: "{{ app_grafana__container.labels }}"
        volume: "{{ app_grafana__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_grafana__container.requires is defined %}
          Requires={{ app_grafana__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_grafana__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_grafana__container.name }}"
        hostname: "{{ app_grafana__container.hostname }}"
        image: "{{ app_grafana__container.image }}"
        ip: "{{ app_grafana__container.ip }}"
        ip6: "{{ app_grafana__container.ipv6 }}"
        network: "{{ app_grafana__container.network }}"
        timezone: "{{ app_grafana__container.timezone }}"
        label: "{{ app_grafana__container.labels }}"
        volume: "{{ app_grafana__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_grafana__container.requires is defined %}
          Requires={{ app_grafana__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_grafana__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_grafana__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'
