---

- name: 'Deploy Grafana container'
  tags: [ 'app_grafana' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ app_grafana__uid }}"
        mode: "{{ item.mode | default('0700') }}"
        state: 'directory'
      with_items:
        - dest: "{{ app_grafana__podman_etc_dir }}"
        - dest: "{{ app_grafana__podman_data_dir }}"
        - dest: "{{ app_grafana__podman_log_dir }}"

    - name: 'Generate Grafana configuration'
      ansible.builtin.template:
        src: 'grafana.ini.j2'
        dest: "{{ app_grafana__podman_etc_dir }}/grafana.ini"
        owner: "{{ app_grafana__uid }}"
        mode: '640'
      when: 'not podman___update_mode | bool'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_grafana__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_grafana__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_grafana__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_grafana__container.name }}"
        hostname: "{{ app_grafana__container.hostname }}"
        image: "{{ app_grafana__container.image }}"
        ip: "{{ app_grafana__container.ip }}"
        ip6: "{{ app_grafana__container.ipv6 | default(omit) }}"
        network: "{{ app_grafana__container.network }}"
        timezone: "{{ app_grafana__container.timezone }}"
        env: "{{ app_grafana__container.environment | default(omit) }}"
        etc_hosts: "{{ app_grafana__container.etc_hosts | default(omit) }}"
        label: "{{ app_grafana__container.labels | default(omit) }}"
        publish: "{{ app_grafana__container.publish | default(omit) }}"
        expose: "{{ app_grafana__container.expose | default(omit) }}"
        secrets: "{{ app_grafana__container.secrets | default(omit) }}"
        volume: "{{ app_grafana__container.volumes | default(omit) }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always

          [Unit]
          {% if app_grafana__container.requires is defined %}
          Requires={{ app_grafana__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_grafana__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'app_grafana__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ app_grafana__container.name }}"
        container_image: "{{ app_grafana__container.image }}"
