---

- name: 'Deploy Grafana container'
  tags: [ 'app_grafana' ]
  block:

    - name: 'Create Grafana directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
        owner: "{{ app_grafana__uid }}"
        mode: '750'
      with_items:
        - "{{ app_grafana__etc_dir }}"
        - "{{ app_grafana__data_dir }}"

    - name: 'Generate Grafana configuration'
      ansible.builtin.template:
        src: 'grafana.ini.j2'
        dest: "{{ app_grafana__etc_dir }}/grafana.ini"
        owner: "{{ app_grafana__uid }}"
        mode: '640'

    - name: 'Create podman containers'
      containers.podman.podman_container:
        name: "{{ app_grafana__container.name }}"
        hostname: "{{ app_grafana__container.hostname }}"
        image: "{{ app_grafana__container.image }}"
        ip: "{{ app_grafana__container.ip }}"
        network: "{{ app_grafana__container.network }}"
        etc_hosts: "{{ app_grafana__container.hosts }}"
        restart_policy: "{{ app_grafana__container.restart_policy }}"
        timezone: "{{ app_grafana__container.timezone }}"
        volume: "{{ app_grafana__container.volumes }}"
        pull: 'always'
      when: app_grafana__ipv6 | length == 0
