---

#
# Substitutes - do not change
#

app_joplin_server__hostname: "{{ joplin_hostname | default('joplin.' + dns_hostname) }}"
app_joplin_server__ip: "{{ joplin_ip | mandatory }}"
app_joplin_server__ipv6: "{{ joplin_ipv6 | default('') }}"
app_joplin_server__network: "{{ joplin_network | mandatory }}"
app_joplin_server__hosts: "{{ joplin_hosts | default({}) }}"
app_joplin_server__timezone: "{{ joplin_timezone | default(bootstrap_timezone__timezone) }}"

app_joplin_server__base_url: "{{ joplin_base_url | mandatory }}"
app_joplin_server__port: "{{ joplin_port | default(22300) }}"
app_joplin_server__db_name: "{{ joplin_db_name | default('joplin') }}"
app_joplin_server__db_user: "{{ joplin_db_user | default('joplin') }}"
app_joplin_server__db_pass: "{{ joplin_db_pass | mandatory }}"
app_joplin_server__db_host: "{{ joplin_db_host | mandatory }}"
app_joplin_server__db_port: "{{ joplin_db_port | default(5432) }}"

app_joplin_server__mailer_enabled: "{{ joplin_mailer_enabled | default(false) }}"
app_joplin_server__mailer_host: "{{ joplin_mailer_host | default('localhost') }}"
app_joplin_server__mailer_port: "{{ joplin_mailer_port | default(25) }}"
app_joplin_server__mailer_security: "{{ joplin_mailer_security | default('starttls') }}"
app_joplin_server__mailer_auth_user: "{{ joplin_mailer_auth_user | default('') }}"
app_joplin_server__mailer_auth_password: "{{ joplin_mailer_auth_password | default('') }}"
app_joplin_server__mailer_noreply_name: "{{ joplin_mailer_noreply_name | default('Joplin Server')}}"
app_joplin_server__mailer_noreply_mail: "{{ joplin_mailer_noreply_mail | default('no-reply') }}"

app_joplin_server__version: "{{ joplin_version | default('latest') }}"
app_joplin_server__container: "{{ app_joplin_server__podman_container_default }}"

#
# Defaults - do not change
#

app_joplin_server__podman_image: 'docker.io/joplin/server'

app_joplin_server__podman_container_default:
  name: 'joplin'
  hostname: "{{ app_joplin_server__hostname }}"
  image: "{{ app_joplin_server__podman_image }}:{{ app_joplin_server__version }}"
  ip: "{{ app_joplin_server__ip }}"
  ipv6: "{{ app_joplin_server__ipv6 }}"
  network: "{{ app_joplin_server__network }}"
  restart_policy: 'always'
  hosts: "{{ app_joplin_server__hosts }}"
  environment:
    APP_BASE_URL: "{{ app_joplin_server__base_url }}"
    APP_PORT: "{{ app_joplin_server__port }}"
    DB_CLIENT: 'pg'
    POSTGRES_PASSWORD: "{{ app_joplin_server__db_pass }}"
    POSTGRES_DATABASE: "{{ app_joplin_server__db_name }}"
    POSTGRES_USER: "{{ app_joplin_server__db_user }}"
    POSTGRES_PORT: "{{ app_joplin_server__db_port }}"
    POSTGRES_HOST: "{{ app_joplin_server__db_host }}"
    MAILER_ENABLED: "{{ app_joplin_server__mailer_enabled | ternary(1,0) }}"
    MAILER_HOST: "{{ app_joplin_server__mailer_host }}"
    MAILER_PORT: "{{ app_joplin_server__mailer_port }}"
    MAILER_SECURITY: "{{ app_joplin_server__mailer_security }}"
    MAILER_AUTH_USER: "{{ app_joplin_server__mailer_auth_user }}"
    MAILER_AUTH_PASSWORD: "{{ app_joplin_server__mailer_auth_password }}"
    MAILER_NOREPLY_NAME: "{{ app_joplin_server__mailer_noreply_name }}"
    MAILER_NOREPLY_EMAIL: "{{ app_joplin_server__mailer_noreply_mail }}"
  timezone: "{{ app_joplin_server__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
