---
# tasks file for roles/mount

- name: Mounting...
  tags: [ 'mount' ]
  when: mount__enable
  block:

  - name: Add storage
    tags: [ 'storage' ]
    ansible.posix.mount:
      src: "{{ item.disk }}"
      path: "{{ item.path }}"
      opts: "{{ item.options }}"
      state: mounted
      fstype: "{{ item.fs }}"
    with_items: "{{ mount__storage }}"

  - name: Bind mounts
    tags: [ 'bind' ]
    block:

    - name: Create nullfs source directories
      ansible.builtin.file:
        path: "{{ item.src }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0755') }}"
        state: directory
      with_items: "{{ mount__bind }}"
    
    - name: Create nullfs mountpoints
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0755') }}"
        state: directory
      with_items: "{{ mount__bind }}"
    
    - name: Mount nullfs locations
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.path }}"
        opts: "{{ item.options }}"
        state: mounted
        fstype: none
      with_items: "{{ mount__bind }}"
