---

#
# Substitutes - do not change
#

matrix_bridge_signal__hostname: "{{ matrix_bridge_signal_hostname | default('mautrix-signal.' + dns_hostname) }}"
matrix_bridge_signal__ip: "{{ matrix_bridge_signal_ip | mandatory }}"
matrix_bridge_signal__ipv6: "{{ matrix_bridge_signal_ipv6 | default('') }}"
matrix_bridge_signal__network: "{{ matrix_bridge_signal_network | mandatory }}"
matrix_bridge_signal__hosts: "{{ matrix_bridge_signal_hosts | default({}) }}"
matrix_bridge_signal__timezone: "{{ matrix_bridge_signal_timezone | default(bootstrap_timezone__timezone) }}"
matrix_bridge_signal__home: "{{ matrix_bridge_signal_home | mandatory }}"

matrix_bridge_signal__dns_servers: "{{ matrix_bridge_signal_dns_servers | default([]) }}"

matrix_bridge_signal__setup: "{{ matrix_bridge_signal_setup | default(true) }}"

matrix_bridge_signal__version: "{{ matrix_bridge_signal_version | default('latest') }}"
matrix_bridge_signal__container: "{{ matrix_bridge_signal__podman_container_default }}"

#
# Defaults - do not change
#

matrix_bridge_signal__uid: 1337
matrix_bridge_signal__gid: 1337

matrix_bridge_signal__podman_image: 'dock.mau.dev/mautrix/signal'

matrix_bridge_signal__podman_container_default:
  name: 'mautrix-signal'
  hostname: "{{ matrix_bridge_signal__hostname }}"
  image: "{{ matrix_bridge_signal__podman_image }}:{{ matrix_bridge_signal__version }}"
  ip: "{{ matrix_bridge_signal__ip }}"
  ipv6: "{{ matrix_bridge_signal__ipv6 }}"
  network: "{{ matrix_bridge_signal__network }}"
  restart_policy: 'always'
  hosts: "{{ matrix_bridge_signal__hosts }}"
  dns_servers: "{{ matrix_bridge_signal__dns_servers }}"
  environment:
    TZ: "{{ matrix_bridge_signal__timezone }}"
  timezone: "{{ matrix_bridge_signal__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - "{{ matrix_bridge_signal__home }}:/data"
