---

- name: Install and configure Net-SNMP
  tags: [ 'monitoring_snmp' ]
  block:

    - name: Install Net-SNMP packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ monitoring_snmp__packages }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - src: snmp.conf.j2
          dest: "{{ monitoring_snmp__etc_dir }}/snmp.conf"
        - src: snmpd.conf.j2
          dest: "{{ monitoring_snmp__etc_dir }}/snmpd.conf"
      notify:
        - Restart Net-SNMPd
