---

- name: 'Configure PostgreSQL backup'
  tags: [ 'backup_postgresql'  ]
  block:

    - name: 'Copy PostgreSQL backup scripts to host'
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup__lib_dir }}/{{ item }}"
        mode: '755'
      with_items: "{{ backup_postgresql__files }}"

    - name: 'Generate PostgreSQL backup configuration file'
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ backup__etc_dir }}/{{ item }}"
        owner: 'root'
        group: 'root'
        mode: '640'
      with_items:
        - 'postgresql'

    - name: 'Create PostgreSQL backup directory'
      ansible.builtin.file:
        mode: '750'
        owner: 'root'
        group: 'root'
        path: "{{ backup_postgresql__backup_dir }}"
        state: 'directory'
      when: 'not backup_postgresql__use_podman'
