---

- name: 'Deploy odoo container'
  tags: [ 'app_odoo' ]
  block:

    - name: 'Create odoo directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
        owner: "{{ app_odoo__uid }}"
      with_items:
        - "{{ app_odoo__config_dir }}"
        - "{{ app_odoo__data_dir }}"

    - name: 'Generate odoo configuration'
      ansible.builtin.template:
        src: 'odoo.conf.j2'
        dest: "{{ app_odoo__config_dir }}/odoo.conf"
        owner: "{{ app_odoo__uid }}"
        mode: '640'

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ app_odoo__container.name }}"
        hostname: "{{ app_odoo__container.hostname }}"
        image: "{{ app_odoo__container.image }}"
        ip: "{{ app_odoo__container.ip }}"
        network: "{{ app_odoo__container.network }}"
        restart_policy: "{{ app_odoo__container.restart_policy }}"
        etc_hosts: "{{ app_odoo__container.hosts }}"
        env: "{{ app_odoo__container.environment }}"
        timezone: "{{ app_odoo__container.timezone }}"
        volume: "{{ app_odoo__container.volumes }}"
        command: "{{ app_odoo__container.command }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: app_odoo__ipv6 | length == 0
