#!/bin/bash
source /etc/default/vnstat

for interface in $INTERFACES; do
for output in $OUTPUTS; do
  vnstati -${output} -i ${interface} -o ${WWWDIR}/${interface}_${output}.png
done
done

site="<html>
<head>
<meta http-equiv='refresh' content='30;'>
</head>
<body>
<h1>$INDEX_HEADLINE</h1>
<table>"

for output in $OUTPUTS; do
site="$site
<tr>"
for interface in $INTERFACES; do
site="$site
<td><img src='${interface}_${output}.png' /></td>"
done
site="$site
</tr>"
done

site="$site
</table>
</body>
</html>"

echo $site > $INDEX_FILE
