---

#
# Substitutes - do not change
#

app_diagrams__hostname: "{{ diagrams_hostname | default('diagrams.localhost') }}"
app_diagrams__ip: "{{ diagrams_ip | mandatory }}"
app_diagrams__network: "{{ diagrams_network | mandatory }}"
app_diagrams__hosts: "{{ diagrams_hosts | default({}) }}"

app_diagrams__base_url: "{{ diagrams_base_url | mandatory }}"

app_diagrams__container: "{{ app_diagrams__container_default | combine(diagrams_container | default({})) }}"

#
# Defaults - do not change
#

# disable letsencrypt as default, use a proxy instead
app_diagrams__acme_enabled: false

app_diagrams__container_default:
  name: diagrams
  hostname: "{{ app_diagrams__hostname }}"
  image: 'docker.io/jgraph/drawio:latest'
  ip: "{{ app_diagrams__ip }}"
  network: "{{ app_diagrams__network }}"
  environment:
    - DRAWIO_BASE_URL: "{{ app_diagrams__base_url }}"
    - LETS_ENCRYPT_ENABLED: "{{ app_diagrams__acme_enabled }}"
  restart_policy: always
  hosts: "{{ app_diagrams__hosts }}"
  skip_ca: true

#   DRAWIO_CSP_HEADER
#   DRAWIO_SELF_CONTAINED
#   DRAWIO_SERVER_URL
# X DRAWIO_BASE_URL
#   DRAWIO_VIEWER_URL
#   DRAWIO_LIGHTBOX_URL
#   DRAWIO_CONFIG
#   DRAWIO_GOOGLE_CLIENT_ID
#   DRAWIO_GOOGLE_APP_ID
#   DRAWIO_GOOGLE_CLIENT_ID
#   DRAWIO_GOOGLE_CLIENT_SECRET
#   DRAWIO_GOOGLE_VIEWER_CLIENT_ID
#   DRAWIO_GOOGLE_VIEWER_APP_ID
#   DRAWIO_GOOGLE_VIEWER_CLIENT_ID
#   DRAWIO_GOOGLE_VIEWER_CLIENT_SECRET
#   DRAWIO_MSGRAPH_CLIENT_ID
#   DRAWIO_MSGRAPH_CLIENT_SECRET
#   DRAWIO_MSGRAPH_TENANT_ID
#   DRAWIO_GITLAB_ID
#   DRAWIO_GITLAB_URL
#   DRAWIO_GITLAB_ID
#   DRAWIO_GITLAB_SECRET
#   DRAWIO_CLOUD_CONVERT_APIKEY
