---

- name: 'Deploy Synapse container'
  tags: [ 'matrix_synapse' ]
  block:

    - name: 'Create Synapse directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ matrix_synapse__uid }}"
        group: "{{ matrix_synapse__gid }}"
        mode: "{{ item.mode | default('0750') }}"
        state: 'directory'
      with_items:
        - dest: "{{ matrix_synapse__podman_data_dir }}"

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: "{{ item.name }}"
        data: "{{ item.data }}"
      with_items:
        - name: 'matrix_synapse_postgres_password'
          data: "{{ matrix_synapse__db_pass }}"
      when: 'item.data | length > 0'

    - name: "Has configuration been generate?"
      ansible.builtin.stat:
        path: "{{ matrix_synapse__podman_data_dir }}/homeserver.yaml"
      register: 'matrix_synapse_configuration_stat_result'

    - name: 'Generate synapse configuration'
      when: 'not matrix_synapse_configuration_stat_result.stat.exists and not podman___update_mode | bool'
      block:
        - name: 'Create synapse configuration file'
          containers.podman.podman_container:
            name: "{{ matrix_synapse__container.name }}-generate"
            hostname: "{{ matrix_synapse__container.hostname }}"
            image: "{{ matrix_synapse__container.image }}"
            ip: "{{ matrix_synapse__container.ip }}"
            network: "{{ matrix_synapse__container.network }}"
            env: "{{ matrix_synapse__container.environment }}"
            timezone: "{{ matrix_synapse__container.timezone }}"
            volume: "{{ matrix_synapse__container.volumes }}"
            command: 'generate'
            rm: true
          when: 'matrix_synapse__ipv6 | length == 0'

        - name: 'Create synapse configuration file'
          containers.podman.podman_container:
            name: "{{ matrix_synapse__container.name }}-generate"
            hostname: "{{ matrix_synapse__container.hostname }}"
            image: "{{ matrix_synapse__container.image }}"
            ip: "{{ matrix_synapse__container.ip }}"
            ip6: "{{ matrix_synapse__container.ipv6 }}"
            network: "{{ matrix_synapse__container.network }}"
            env: "{{ matrix_synapse__container.environment }}"
            timezone: "{{ matrix_synapse__container.timezone }}"
            volume: "{{ matrix_synapse__container.volumes }}"
            command: 'generate'
            rm: true
          when: 'matrix_synapse__ipv6 | length > 0'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ matrix_synapse__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[matrix_synapse__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ matrix_synapse__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ matrix_synapse__container.name }}"
        hostname: "{{ matrix_synapse__container.hostname }}"
        image: "{{ matrix_synapse__container.image }}"
        ip: "{{ matrix_synapse__container.ip }}"
        network: "{{ matrix_synapse__container.network }}"
        timezone: "{{ matrix_synapse__container.timezone }}"
        dns_servers: "{{ matrix_synapse__container.dns_servers }}"
        env: "{{ matrix_synapse__container.environment }}"
        label: "{{ matrix_synapse__container.labels }}"
        secrets: "{{ matrix_synapse__container.secrets }}"
        volume: "{{ matrix_synapse__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if matrix_synapse__container.requires is defined %}
          Requires={{ matrix_synapse__container.requires | join(' ') }}
          {% endif %}
          {% if matrix_synapse__container.wants is defined %}
          Wants={{ matrix_synapse__container.wants | join(' ') }}
          {% endif %}
          {% if matrix_synapse__container.after is defined %}
          After={{ matrix_synapse__container.after | join(' ') }}
          {% endif %}
          {% if matrix_synapse__container.part_of is defined %}
          PartOf={{ matrix_synapse__container.part_of | join(' ') }}
          {% endif %}
          {% if matrix_synapse__container.binds_to is defined %}
          BindsTo={{ matrix_synapse__container.binds_to | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: |
        matrix_synapse__ipv6 | length == 0
        and matrix_synapse_configuration_stat_result.stat.exists
        and not matrix_synapse__setup

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ matrix_synapse__container.name }}"
        hostname: "{{ matrix_synapse__container.hostname }}"
        image: "{{ matrix_synapse__container.image }}"
        ip: "{{ matrix_synapse__container.ip }}"
        ip6: "{{ matrix_synapse__container.ipv6 }}"
        network: "{{ matrix_synapse__container.network }}"
        timezone: "{{ matrix_synapse__container.timezone }}"
        dns_servers: "{{ matrix_synapse__container.dns_servers }}"
        env: "{{ matrix_synapse__container.environment }}"
        label: "{{ matrix_synapse__container.labels }}"
        secrets: "{{ matrix_synapse__container.secrets }}"
        volume: "{{ matrix_synapse__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if matrix_synapse__container.requires is defined %}
          Requires={{ matrix_synapse__container.requires | join(' ') }}
          {% endif %}
          {% if matrix_synapse__container.wants is defined %}
          Wants={{ matrix_synapse__container.wants | join(' ') }}
          {% endif %}
          {% if matrix_synapse__container.after is defined %}
          After={{ matrix_synapse__container.after | join(' ') }}
          {% endif %}
          {% if matrix_synapse__container.part_of is defined %}
          PartOf={{ matrix_synapse__container.part_of | join(' ') }}
          {% endif %}
          {% if matrix_synapse__container.binds_to is defined %}
          BindsTo={{ matrix_synapse__container.binds_to | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: |
        matrix_synapse__ipv6 | length > 0
        and matrix_synapse_configuration_stat_result.stat.exists
        and not matrix_synapse__setup

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ matrix_synapse__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: |
        not ansible_check_mode
        and matrix_synapse_configuration_stat_result.stat.exists
        and not matrix_synapse__setup

    - name: 'Enable autoupdate on container'
      when: 'matrix_synapse__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ matrix_synapse__container.name }}"
        container_image: "{{ matrix_synapse__container.image }}"
