---

- name: Deploy Easy-RSA certificate for realm
  when: realm.easyrsa | default(false)
  block:

    - name: Create realm structure directories
      ansible.builtin.file:
        path: "{{ pki_easyrsa_deploy__realms_dir }}/{{ realm.name }}/{{ item.name }}"
        state: directory
        owner: "{{ realm.owner | default(item.owner) }}"
        group: "{{ realm.group | default(item.group) }}"
        mode: "{{ item.mode }}"
        recurse: yes
      with_items: "{{ pki_easyrsa_deploy__realm_structure }}"

    - name: "Copy private key for {{ realm.name }}"
      ansible.builtin.copy:
        src: "{{ pki_easyrsa_deploy__pki_dir }}/private/{{ realm.name }}.key"
        dest: "{{ pki_easyrsa_deploy__realms_dir }}/{{ realm.name }}/private/{{ realm.name }}.key"
        owner: "{{ realm.owner | default(pki_easyrsa_deploy__private_owner) }}"
        group: "{{ realm.group | default(pki_easyrsa_deploy__private_group) }}"
        mode: "{{ pki_easyrsa_deploy__private_file_mode }}"
      when: not ansible_check_mode

    - name: "Copy certificate for {{ realm.name }}"
      ansible.builtin.copy:
        src: "{{ pki_easyrsa_deploy__pki_dir }}/issued/{{ realm.name }}.crt"
        dest: "{{ pki_easyrsa_deploy__realms_dir }}/{{ realm.name }}/public/{{ realm.name }}.crt"
        owner: "{{ realm.owner | default(pki_easyrsa_deploy__public_owner) }}"
        group: "{{ realm.group | default(pki_easyrsa_deploy__public_group) }}"
        mode: "{{ pki_easyrsa_deploy__public_file_mode }}"
      register: cert_state
      when: not ansible_check_mode

    - name: "Copy CA certificate for {{ realm.name }}"
      ansible.builtin.copy:
        src: "{{ pki_easyrsa_deploy__pki_dir }}/ca.crt"
        dest: "{{ pki_easyrsa_deploy__realms_dir }}/{{ realm.name }}/public/ca.crt"
        owner: "{{ realm.owner | default(pki_easyrsa_deploy__public_owner) }}"
        group: "{{ realm.group | default(pki_easyrsa_deploy__public_group) }}"
        mode: "{{ pki_easyrsa_deploy__public_file_mode }}"
      when: not ansible_check_mode

    - name: "Create fullchain for {{ realm.name }}"
      ansible.builtin.shell: "cat {{ pki_easyrsa_deploy__realms_dir }}/{{ realm.name }}/public/{{ realm.name }}.crt {{ pki_easyrsa_deploy__realms_dir }}/{{ realm.name }}/public/ca.crt > {{ pki_easyrsa_deploy__realms_dir }}/{{ realm.name }}/public/{{ realm.name }}.fullchain.crt"
      when: cert_state.changed

    - name: "Set CA certificate file mode for {{ realm.name }}"
      ansible.builtin.file:
        path: "{{ pki_easyrsa_deploy__realms_dir }}/{{ realm.name }}/public/{{ realm.name }}.fullchain.crt"
        owner: "{{ realm.owner | default(pki_easyrsa_deploy__public_owner) }}"
        group: "{{ realm.group | default(pki_easyrsa_deploy__public_group) }}"
        mode: "{{ pki_easyrsa_deploy__public_file_mode }}"
      when: not ansible_check_mode
