---

- name: Setup network configuration
  tags: [ 'net_interfaces' ]
  block:

    - name: Generate interfaces configuration
      ansible.builtin.template:
        src: interfaces.j2
        dest: "{{ net_interfaces__interfaces_file }}"
        owner: root
        group: root
        mode: 0644

    - name: Generate additional interfaces configuration
      ansible.builtin.template:
        src: interface.j2
        dest: "{{ net_interfaces__interfaces_dir }}/{{ item['priority'] }}-{{ item['name'] | default(item['interface']) }}"
        owner: root
        group: root
        mode: 0644
      with_items: "{{ net_interfaces__interfaces }}"

    - name: Bring additional interfaces up
      ansible.builtin.shell: "ifup '{{ item.interface }}'"
      with_items: "{{ net_interfaces__interfaces }}"
      when: not ansible_check_mode
