---

- name: 'Install Poweradmin'
  tags: [ 'dns_poweradmin' ]
  block:

    - name: 'Create Poweradmin directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        state: 'directory'
      with_items:
        - dest: "{{ dns_poweradmin__podman_home }}"
        - dest: "{{ dns_poweradmin__podman_db_dir }}"
          owner: '82'
          group: '82'

    - name: 'Generate Poweradmin configuration'
      ansible.builtin.template:
        src: 'settings.php.j2'
        dest: "{{ dns_poweradmin__podman_config_file }}"
      when: 'not podman___update_mode | bool'
      notify: 'Restart Poweradmin container'

    - name: 'Create Poweradmin container'
      containers.podman.podman_container:
        name: "{{ dns_poweradmin__container.name }}"
        hostname: "{{ dns_poweradmin__container.hostname }}"
        image: "{{ dns_poweradmin__container.image }}"
        ip: "{{ dns_poweradmin__container.ip }}"
        network: "{{ dns_poweradmin__container.network }}"
        timezone: "{{ dns_poweradmin__container.timezone }}"
        env: "{{ dns_poweradmin__container.environment }}"
        label: "{{ dns_poweradmin__container.labels }}"
        volume: "{{ dns_poweradmin__container.volumes }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if dns_poweradmin__container.requires is defined %}
          Requires={{ dns_poweradmin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'dns_poweradmin__ipv6 | length == 0'

    - name: 'Create Poweradmin container'
      containers.podman.podman_container:
        name: "{{ dns_poweradmin__container.name }}"
        hostname: "{{ dns_poweradmin__container.hostname }}"
        image: "{{ dns_poweradmin__container.image }}"
        ip: "{{ dns_poweradmin__container.ip }}"
        ip6: "{{ dns_poweradmin__container.ipv6 }}"
        network: "{{ dns_poweradmin__container.network }}"
        timezone: "{{ dns_poweradmin__container.timezone }}"
        env: "{{ dns_poweradmin__container.environment }}"
        label: "{{ dns_poweradmin__container.labels }}"
        volume: "{{ dns_poweradmin__container.volumes }}"
        quadlet_options: |
          
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if dns_poweradmin__container.requires is defined %}
          Requires={{ dns_poweradmin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'dns_poweradmin__ipv6 | length > 0'

    - name: 'Started and enable container'
      ansible.builtin.systemd:
        name: "{{ dns_poweradmin__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
