---

- name: 'Install Poweradmin'
  tags: [ 'dns_poweradmin' ]
  block:

    - name: 'Create Poweradmin directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        state: 'directory'
      with_items:
        - dest: "{{ dns_poweradmin__podman_home }}"
        - dest: "{{ dns_poweradmin__podman_db_dir }}"
          owner: '82'
          group: '82'

    - name: 'Generate Poweradmin configuration'
      ansible.builtin.template:
        src: 'settings.php.j2'
        dest: "{{ dns_poweradmin__podman_config_file }}"
      when: 'not podman___update_mode | bool'
      notify: 'Restart Poweradmin container'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ dns_poweradmin__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[dns_poweradmin__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ dns_poweradmin__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Create Poweradmin container'
      containers.podman.podman_container:
        name: "{{ dns_poweradmin__container.name }}"
        hostname: "{{ dns_poweradmin__container.hostname }}"
        image: "{{ dns_poweradmin__container.image }}"
        ip: "{{ dns_poweradmin__container.ip }}"
        ip6: "{{ dns_poweradmin__container.ipv6 | default(omit) }}"
        network: "{{ dns_poweradmin__container.network }}"
        timezone: "{{ dns_poweradmin__container.timezone }}"
        env: "{{ dns_poweradmin__container.environment | default(omit) }}"
        label: "{{ dns_poweradmin__container.labels | default(omit) }}"
        volume: "{{ dns_poweradmin__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always

          [Unit]
          {% if dns_poweradmin__container.requires is defined %}
          Requires={{ dns_poweradmin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Started and enable container'
      ansible.builtin.systemd:
        name: "{{ dns_poweradmin__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'dns_poweradmin__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ dns_poweradmin__container.name }}"
        container_image: "{{ dns_poweradmin__container.image }}"
