---

- name: 'Install Poweradmin'
  tags: [ 'dns_poweradmin' ]
  block:

    - name: 'Create Poweradmin directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        state: 'directory'
      with_items:
        - dest: "{{ dns_poweradmin__podman_data_dir }}"
        - dest: "{{ dns_poweradmin__podman_db_dir }}"
          owner: '82'
          group: '82'

    - name: 'Generate Poweradmin configuration'
      ansible.builtin.template:
        src: 'settings.php.j2'
        dest: "{{ dns_poweradmin__podman_config_file }}"
      when: 'not podman___update_mode'
      notify: 'Restart Poweradmin container'

    - name: 'Create Poweradmin container'
      containers.podman.podman_container:
        name: "{{ dns_poweradmin__container.name }}"
        hostname: "{{ dns_poweradmin__container.hostname }}"
        image: "{{ dns_poweradmin__container.image }}"
        ip: "{{ dns_poweradmin__container.ip }}"
        network: "{{ dns_poweradmin__container.network }}"
        restart_policy: "{{ dns_poweradmin__container.restart_policy }}"
        timezone: "{{ dns_poweradmin__container.timezone }}"
        env: "{{ dns_poweradmin__container.environment }}"
        label: "{{ dns_poweradmin__container.labels }}"
        volume: "{{ dns_poweradmin__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'dns_poweradmin__ipv6 | length == 0'

    - name: 'Create Poweradmin container'
      containers.podman.podman_container:
        name: "{{ dns_poweradmin__container.name }}"
        hostname: "{{ dns_poweradmin__container.hostname }}"
        image: "{{ dns_poweradmin__container.image }}"
        ip: "{{ dns_poweradmin__container.ip }}"
        ip6: "{{ dns_poweradmin__container.ipv6 }}"
        network: "{{ dns_poweradmin__container.network }}"
        restart_policy: "{{ dns_poweradmin__container.restart_policy }}"
        timezone: "{{ dns_poweradmin__container.timezone }}"
        env: "{{ dns_poweradmin__container.environment }}"
        label: "{{ dns_poweradmin__container.labels }}"
        volume: "{{ dns_poweradmin__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'dns_poweradmin__ipv6 | length > 0'

    - name: 'Generate systemd unit file'
      containers.podman.podman_generate_systemd:
        name: "{{ dns_poweradmin__container.name }}"
        restart_policy: "{{ dns_poweradmin__container.restart_policy }}"
        force: true
        requires: "{{ dns_poweradmin__container.requires | default([]) }}"
        dest: '/etc/systemd/system'

    - name: 'Started and enable container on systemd'
      ansible.builtin.systemd:
        name: "container-{{ dns_poweradmin__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
