---

#
# Substitutes - do not change
#

matrix_admin__hostname: "{{ matrix_admin_hostname | default('synapse-admin.' + dns_hostname) }}"
matrix_admin__ip: "{{ matrix_admin_ip | mandatory }}"
matrix_admin__ipv6: "{{ matrix_admin_ipv6 | default('') }}"
matrix_admin__network: "{{ matrix_admin_network | mandatory }}"
matrix_admin__hosts: "{{ matrix_admin_hosts | default({}) }}"
matrix_admin__timezone: "{{ matrix_admin_timezone | default(bootstrap_timezone__timezone) }}"

matrix_admin__base_path: "{{ matrix_admin_base_path | default('/synapse-admin') }}"

matrix_admin__version: "{{ matrix_admin_version | default('latest') }}"
matrix_admin__container: "{{ matrix_admin__podman_container_default }}"

#
# Defaults - do not change
#

matrix_admin__port: 80

matrix_admin__podman_image: 'docker.io/awesometechnologies/synapse-admin'

matrix_admin__podman_container_default:
  name: 'synapse-admin'
  hostname: "{{ matrix_admin__hostname }}"
  image: "{{ matrix_admin__podman_image }}:{{ matrix_admin__version }}"
  ip: "{{ matrix_admin__ip }}"
  ipv6: "{{ matrix_admin__ipv6 }}"
  network: "{{ matrix_admin__network }}"
  restart_policy: 'always'
  hosts: "{{ matrix_admin__hosts }}"
  environment:
    TZ: "{{ matrix_admin__timezone }}"
  timezone: "{{ matrix_admin__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
