---

#
# Substitutes - do not change
#

app_gitlab_ce__hostname: "{{ gitlab_hostname | default('gitlab-ce.localhost') }}"
app_gitlab_ce__ip: "{{ gitlab_ip | mandatory }}"
app_gitlab_ce__ipv6: "{{ gitlab_ipv6 | default('') }}"
app_gitlab_ce__network: "{{ gitlab_network | mandatory }}"
app_gitlab_ce__home: "{{ gitlab_home | mandatory }}"
app_gitlab_ce__version: "{{ gitlab_version | default('latest') }}"

app_gitlab_ce__hosts: "{{ gitlab_hosts | default({}) }}"
app_gitlab_ce__environment: "{{ gitlab_environment | default({}) }}"
app_gitlab_ce__publish: "{{ gitlab_publish | default([]) }}"

app_gitlab_ce__container: "{{ app_gitlab_ce__container_default | combine(gitlab_container | default({})) }}"

app_gitlab_ce__external_url: "{{ gitlab_external_url | default('') }}"
app_gitlab_ce__ssh_host: "{{ gitlab_ssh_host | default('') }}"
app_gitlab_ce__time_zone: "{{ gitlab_timezone | default('') }}"

app_gitlab_ce__smtp_enable: "{{ gitlab_smtp_enable | default(false) }}"
app_gitlab_ce__smtp_address: "{{ gitlab_smtp_address | default('') }}"
app_gitlab_ce__smtp_port: "{{ gitlab_smtp_port | default(465) }}"
app_gitlab_ce__smtp_domain: "{{ gitlab_smtp_domain | default('') }}"
app_gitlab_ce__smtp_starttls: "{{ gitlab_smtp_starttls | default(true) }}"
app_gitlab_ce__smtp_tls: "{{ gitlab_smtp_tls | default(false) }}"
app_gitlab_ce__smtp_pool: "{{ gitlab_smtp_pool | default(false) }}"

app_gitlab_ce__email_enable: "{{ gitlab_email_enable | default(true) }}"
app_gitlab_ce__email_from: "{{ gitlab_email_from | default('') }}"
app_gitlab_ce__email_display_name: "{{ gitlab_email_display_name | default('') }}"
app_gitlab_ce__email_reply_to: "{{ gitlab_email_reply_to | default('') }}"

app_gitlab_ce__monitoring_whitelist: "{{ gitlab_monitoring_whitelist | default(app_gitlab_ce__monitoring_whitelist_default) }}"

app_gitlab_ce__ldap_enable: "{{ gitlab_ldap_enable | default(false) }}"
app_gitlab_ce__ldap_label: "{{ gitlab_ldap_label | default('LDAP') }}"
app_gitlab_ce__ldap_host: "{{ gitlab_ldap_host | default('') }}"
app_gitlab_ce__ldap_port: "{{ gitlab_ldap_port | default(389) }}"
app_gitlab_ce__ldap_uid: "{{ gitlab_ldap_uid | default('sAMAccountName') }}"
app_gitlab_ce__ldap_attributes: "{{ gitlab_ldap_attributes | default({}) }}"
app_gitlab_ce__ldap_encryption: "{{ gitlab_ldap_encryption | default('plain') }}"
app_gitlab_ce__ldap_active_directory: "{{ gitlab_ldap_active_directory | default(true) }}"
app_gitlab_ce__ldap_allow_username_or_email_login: "{{ gitlab_ldap_allow_username_or_email_login | default(false) }}"
app_gitlab_ce__ldap_lowercase_usernames: "{{ gitlab_ldap_lowercase_usernames | default(false) }}"
app_gitlab_ce__ldap_block_auto_created_users: "{{ gitlab_ldap_block_auto_created_users | default(false) }}"
app_gitlab_ce__ldap_base: "{{ gitlab_ldap_base | default('') }}"
app_gitlab_ce__ldap_user_filter: "{{ gitlab_ldap_user_filter | default('') }}"

app_gitlab_ce__registry_external_url: "{{ gitlab_registry_external_url | default('') }}"
app_gitlab_ce__registry_enable: "{{ gitlab_registry_enable | default(false) }}"
app_gitlab_ce__registry_host: "{{ gitlab_registry_host | default('registry.gitlab.example.com') }}"
app_gitlab_ce__registry_port: "{{ gitlab_registry_port | default(5005) }}"
app_gitlab_ce__registry_path: "{{ gitlab_registry_path | default('/var/opt/gitlab/gitlab-rails/shared/registry') }}"
app_gitlab_ce__registry_ssl_realm: "{{ gitlab_registry_ssl_realm | default(app_gitlab_ce__registry_host) }}"


#
# Defaults - do not change
#

app_gitlab_ce__data_dir: "{{ app_gitlab_ce__home }}/data"
app_gitlab_ce__logs_dir: "{{ app_gitlab_ce__home }}/logs"
app_gitlab_ce__config_dir: "{{ app_gitlab_ce__home }}/config"
app_gitlab_ce__ssl_dir: "{{ app_gitlab_ce__config_dir }}/ssl"
app_gitlab_ce__trusted_certs_dir: "{{ app_gitlab_ce__config_dir }}/trusted-certs"

app_gitlab_ce__monitoring_whitelist_default:
  - '127.0.0.0/8'
  - '::1/128'

app_gitlab_ce__container_default:
  name: gitlab-ce
  hostname: "{{ app_gitlab_ce__hostname }}"
  image: "docker.io/gitlab/gitlab-ce:{{ app_gitlab_ce__version }}"
  ip: "{{ app_gitlab_ce__ip }}"
  ipv6: "{{ app_gitlab_ce__ipv6 }}"
  network: "{{ app_gitlab_ce__network }}"
  restart_policy: always
  hosts: "{{ app_gitlab_ce__hosts }}"
  shm_size: 256m
  environment: "{{ app_gitlab_ce__environment }}"
  expose:
    - 80
    - 443
  publish: "{{ app_gitlab_ce__publish }}"
