---

- name: 'Deploy Forgejo runner container'
  tags: [ 'app_forgejo_runner' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ app_forgejo_runner__uid }}"
        group: "{{ app_forgejo_runner__gid }}"
        mode: "{{ item.mode | default('0750') }}"
        state: 'directory'
      with_items:
        - dest: "{{ app_forgejo_runner__home }}"
        - dest: "{{ app_forgejo_runner__home }}/.cache"
          mode: 'ug=rwx,g+s'

    - name: 'Create Forgejo runner registration file'
      ansible.builtin.file:
        mode: 'ug=rw,g+s'
        path: "{{ app_forgejo_runner__home }}/.runner"
        state: 'touch'
        owner: "{{ app_forgejo_runner__uid }}"
        group: "{{ app_forgejo_runner__gid }}"
      when: 'not podman___update_mode | bool'

    - name: 'Create Forgejo runner environment file'
      ansible.builtin.template:
        mode: '440'
        dest: "{{ app_forgejo_runner__home }}/.env"
        src: 'env.j2'
        owner: "{{ app_forgejo_runner__uid }}"
        group: "{{ app_forgejo_runner__gid }}"
      when: 'not podman___update_mode | bool'

    - name: 'Create Forgejo runner configuration file'
      ansible.builtin.template:
        mode: '440'
        dest: "{{ app_forgejo_runner__home }}/config.yml"
        src: 'config.yml.j2'
        owner: "{{ app_forgejo_runner__uid }}"
        group: "{{ app_forgejo_runner__gid }}"
      when: 'not podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_forgejo_runner__container.name }}"
        hostname: "{{ app_forgejo_runner__container.hostname }}"
        image: "{{ app_forgejo_runner__container.image }}"
        ip: "{{ app_forgejo_runner__container.ip }}"
        network: "{{ app_forgejo_runner__container.network }}"
        timezone: "{{ app_forgejo_runner__container.timezone }}"
        env: "{{ app_forgejo_runner__container.environment }}"
        volume: "{{ app_forgejo_runner__container.volumes | default([]) }}"
        user: "{{ app_forgejo_runner__container.user }}"
        command: "{{ app_forgejo_runner__container.command | mandatory }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_forgejo_runner__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_forgejo_runner__container.name }}"
        hostname: "{{ app_forgejo_runner__container.hostname }}"
        image: "{{ app_forgejo_runner__container.image }}"
        ip: "{{ app_forgejo_runner__container.ip }}"
        ip6: "{{ app_forgejo_runner__container.ipv6 }}"
        network: "{{ app_forgejo_runner__container.network }}"
        timezone: "{{ app_forgejo_runner__container.timezone }}"
        env: "{{ app_forgejo_runner__container.environment }}"
        volume: "{{ app_forgejo_runner__container.volumes | default([]) }}"
        user: "{{ app_forgejo_runner__container.user }}"
        command: "{{ app_forgejo_runner__container.command | mandatory }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_forgejo_runner__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_forgejo_runner__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
