---

- name: 'Configure backup'
  tags: [ 'backup'  ]
  block:

    - name: 'Create backup configuration directory'
      ansible.builtin.file:
        mode: '755'
        owner: 'root'
        group: 'root'
        path: "{{ backup__etc_dir }}"
        state: 'directory'

    - name: 'Create backup script directory'
      ansible.builtin.file:
        mode: '755'
        owner: 'root'
        group: 'root'
        path: "{{ backup__lib_dir }}"
        state: 'directory'

    - name: 'Copy backup scripts to host'
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup__lib_dir }}/{{ item }}"
        mode: '755'
      with_items: "{{ backup__files }}"

    - name: 'Create symlink to main script'
      ansible.builtin.file:
        src: "{{ backup__lib_dir }}/900.backup"
        dest: '/etc/cron.daily/backup'
        state: 'link'
      when: 'not ansible_check_mode'

    - name: 'Generate backup configuration file'
      ansible.builtin.template:
        src: 'backup.j2'
        dest: "{{ backup__etc_dir }}/backup"
        owner: 'root'
        group: 'root'
        mode: '640'

    - name: 'Generate log rotation configuration file'
      ansible.builtin.import_role:
        name: 'bootstrap_logrotate'
      vars:
        logrotate_files: "{{ backup__logrotate_files }}"

    - name: 'Create SSH keys'
      ansible.builtin.import_role:
        name: 'backup_ssh'
      when: 'backup_ssh__enable'

    - name: 'Add borg backup scripts'
      ansible.builtin.import_role:
        name: 'backup_borg'
      when: 'backup_borg__enable'

    - name: 'Add restic backup scripts'
      ansible.builtin.import_role:
        name: 'backup_restic'
      when: 'backup_restic__enable'

    - name: 'Add MySQL/MariaDB backup scripts'
      ansible.builtin.import_role:
        name: 'backup_mysql'
      when: 'backup_mysql__enable'

    - name: 'Add PostgreSQL backup scripts'
      ansible.builtin.import_role:
        name: 'backup_postgresql'
      when: 'backup_postgresql__enable'

    - name: 'Add OpenLDAP backup scripts'
      ansible.builtin.import_role:
        name: 'backup_openldap'
      when: 'backup_openldap__enable'

    - name: 'Add GitLab backup scripts'
      ansible.builtin.import_role:
        name: 'backup_gitlab'
      when: 'backup_gitlab__enable'

    - name: 'Add InfluxDB backup scripts'
      ansible.builtin.import_role:
        name: 'backup_influxdb'
      when: 'backup_influxdb__enable'

    - name: 'Add InfluxDB Core backup scripts'
      ansible.builtin.import_role:
        name: 'backup_influxdb_core'
      when: 'backup_influxdb_core__enable'

    - name: 'Add MongoDB backup scripts'
      ansible.builtin.import_role:
        name: 'backup_mongodb'
      when: 'backup_mongodb__enable'

    - name: 'Add FoundryVTT backup scripts'
      ansible.builtin.import_role:
        name: 'backup_foundryvtt'
      when: 'backup_foundryvtt__enable'
