---
# tasks file for roles/backup

- include_tasks: nfs.yml
  when: backup__nfs_client_enable

- include_tasks: ssh.yml
  when: backup__ssh_client_enable

- include_tasks: mysql.yml
  when: backup__mysql_enable

- include_tasks: borg.yml
  when: backup__borg_enable

- name: Copy backup scripts
  ansible.builtin.copy:
    src: "usr/local/lib/backup/{{ item }}"
    dest: "/usr/local/lib/backup/{{ item }}"
    mode: 0755
  with_items: "{{ backup__scripts }}"

- name: Create symlink to main script
  ansible.builtin.file:
    src: /usr/local/lib/backup/900.backup
    dest: /etc/cron.daily/backup
    state: link
  when: not ansible_check_mode

- name: Generate configuration file
  ansible.builtin.template:
    src: etc/default/backup.j2
    dest: /etc/default/backup
    mode: 0640
  vars:
    enable: "{{ backup__enable }}"
    logfile: "{{ backup__logfile }}"
    error_logfile: "{{ backup__error_logfile }}"
    borg_enable: "{{ backup__borg_enable }}"
    borg_backup_dir: "{{ backup__borg_backup_dir }}"
    borg_cache_dir: "{{ backup__borg_cache_dir }}"
    borg_rsh: "{{ backup__borg_rsh }}"
    borg_options: "{{ backup__borg_options }}"
    borg_include: "{{ backup__borg_include }}"
    borg_exclude: "{{ backup__borg_exclude }}"
    mysql_enable: "{{ backup__mysql_enable }}"
    mysql_compress: "{{ backup__mysql_compress }}"
    mysql_replication: "{{ backup__mysql_replication }}"
    mysql_backup_dir: "{{ backup__mysql_backup_dir }}"
    mysql_host: "{{ backup__mysql_host }}"
    mysql_user: "{{ backup__mysql_user }}"
    mysql_password: "{{ backup__mysql_password }}"
    mysql_ignore_databases: "{{ backup__mysql_ignore_databases }}"
    mysql_keep_days: "{{ backup__mysql_keep_days }}"
