---

- name: Configure backup
  tags: [ 'backup'  ]
  block:

    - name: Copy backup scripts to host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup_common__lib_dir }}/{{ item }}"
        mode: '755'
      with_items: "{{ backup__files }}"

    - name: Create symlink to main script
      ansible.builtin.file:
        src: "{{ backup_common__lib_dir }}/900.backup"
        dest: /etc/cron.daily/backup
        state: link

    - name: Generate backup configuration file
      ansible.builtin.template:
        src: backup.j2
        dest: "{{ backup_common__etc_dir }}/backup"
        owner: root
        group: root
        mode: '640'

    - name: Add borg backup scripts
      ansible.builtin.import_role:
        name: backup_borg
      when: backup_borg__enable

    - name: Add MySQL/MariaDB backup scripts
      ansible.builtin.import_role:
        name: backup_mysql
      when: backup_mysql__enable

    - name: Add OpenLDAP backup scripts
      ansible.builtin.import_role:
        name: backup_openldap
      when: backup_openldap__enable
