---
# tasks file for roles/backup

- name: Install packages for NFS client
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ backup__nfs_client_packages }}"

- name: Mount backup NFS volume
  ansible.posix.mount:
    src: "{{ backup__nfs_client_src }}"
    path: "{{ backup__target_directory }}"
    opts: rw,sync,hard,intr
    state: mounted
    fstype: nfs
  when: backup__nfs_client_src | length > 0
