---

- name: 'Install Diun for podman monitoring'
  tags: [ 'monitoring', 'monitoring_diun' ]
  block:

    - name: 'Install Diun using native binaries'
      ansible.builtin.include_tasks:
        file: 'local.yml'
      when: not monitoring_diun__use_podman

    - name: 'Install Diun using podman'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: monitoring_diun__use_podman
