---

- name: 'Install Diun podman container'
  block:

    - name: 'Create Diun user directories'
      ansible.builtin.file:
        mode: '750'
        path: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ monitoring_diun__etc_dir }}"
        - "{{ monitoring_diun__lib_dir }}"

    - name: 'Generate configuration files'
      ansible.builtin.template:
        src: 'diun.yml.j2'
        dest: "{{ monitoring_diun__etc_dir }}/diun.yml"
        mode: '640'

    - name: 'Install Diun container'
      ansible.builtin.debug:
        msg: "{{ monitoring_diun__podman_container }}"
      when: ansible_check_mode

    - name: 'Install Diun container'
      containers.podman.podman_container:
        name: "{{ monitoring_diun__podman_container.name }}"
        hostname: "{{ monitoring_diun__podman_container.hostname }}"
        image: "{{ monitoring_diun__podman_container.image }}"
        ip: "{{ monitoring_diun__podman_container.ip }}"
        network: "{{ monitoring_diun__podman_container.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ monitoring_diun__podman_container.restart_policy }}"
        timezone: "{{ monitoring_diun__podman_container.timezone | default(bootstrap_timezone__timezone) }}"
        volume: "{{ monitoring_diun__podman_container.volumes }}"
        pull: 'always'
      when: not ansible_check_mode
