---
# tasks file for roles/ssmtp

- name: Install and configure ssmtp
  tags: [ 'ssmtp' ]
  when: ssmtp__enable
  block:

  - name: Install ssmtp packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ ssmtp__packages_combined }}"

  - name: Generate configuration file
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/ssmtp/ssmtp.conf.j2
      dest: /etc/ssmtp/ssmtp.conf
      owner: root
      group: root
      mode: 0444

  - name: Ensure ansible directory exists
    ansible.builtin.file:
      path: /etc/ansible
      state: directory
      owner: root
      group: root
      mode: 0750

  - name: Set ssmtp as role for sendmail
    tags: [ 'configuration' ]
    ansible.builtin.copy:
      dest: /etc/ansible/sendmail
      content: ssmtp
      owner: root
      group: root
      mode: 0644
