---

- name: 'Restart unbound'
  ansible.builtin.service:
    name: 'unbound'
    state: 'restarted'
  when: not ansible_check_mode and not dns_unbound__use_podman

- name: 'Restart unbound container'
  ansible.builtin.shell: 'podman restart unbound'
  when: not ansible_check_mode and dns_unbound__use_podman
