---

- name: Install and configure calibre
  tags: [ 'calibre' ]
  when: calibre__enable
  block:

  - name: Install calibre packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ calibre__packages }}"

  - name: Create Calibre log directory
    tags: [ 'configuration' ]
    ansible.builtin.file:
      dest: "{{ calibre__log_dir }}"
      state: directory
      owner: "{{ calibre__user }}"
      group: "{{ calibre__group }}"
      mode: 0750
