---

- name: Install nginx
  tags: [ 'webserver_nginx'  ]
  block:

    - name: Install nginx using package management
      ansible.builtin.include_tasks:
        file: apt.yml
      when: not webserver_nginx__use_podman

    - name: Install nginx using podman
      ansible.builtin.include_tasks:
        file: podman.yml
      when: webserver_nginx__use_podman
