---

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: not ansible_check_mode and not webserver_nginx__use_podman

- name: Restart nginx container
  containers.podman.podman_container:
    name: nginx
    state: started
    force_restart: true
  when: not ansible_check_mode and webserver_nginx__use_podman
