---

- name: Install PowerDNS Recursor
  tags: [ 'dns_powerdns_recursor' ]
  block:

    - name: Install PowerDNS Recursor packages
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ dns_powerdns_recursor__packages }}"

    - name: Generate PowerDNS Recursor configuration
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: 'recursor.lua.j2'
          dest: "{{ dns_powerdns_recursor__etc }}/recursor.lua"
        - src: 'recursor.conf.j2'
          dest: "{{ dns_powerdns_recursor__etc }}/recursor.conf"
      notify: Restart PowerDNS Recursor
