---

- name: Install and configure OpenDMARC
  tags: [ 'mail_opendmarc' ]
  block:

    - name: Install OpenDMARC
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ mail_opendmarc__packages }}"

    - name: Create OpenDMARC directories
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        state: directory
        owner: "{{ mail_opendmarc__user }}"
        group: "{{ mail_opendmarc__group }}"
        mode: '750'
      with_items:
        - dest: "{{ mail_opendmarc__etc_dir }}"
        - dest: "{{ mail_opendmarc__lib_dir }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '644'
      with_items:
        - src: opendmarc.j2
          dest: /etc/default/opendmarc
        - src: opendmarc.conf.j2
          dest: /etc/opendmarc.conf
      notify:
        - Restart OpenDMARC
