---

- name: Install and configure PostSRSd
  tags: [ 'mail_postsrsd' ]
  block:

    - name: Install PostSRSd
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ mail_postsrsd__packages }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: postsrsd.j2
        dest: /etc/default/postsrsd
        owner: root
        group: root
        mode: '644'
      notify:
        - Restart PostSRSd

    - name: Generate secret file
      ansible.builtin.copy:
        dest: /etc/postsrsd.secret
        content: "{{ mail_postsrsd__secret }}"
        owner: root
        group: root
        mode: '600'
      notify:
        - Restart PostSRSd
