---

- name: 'Initialize PKI common structure'
  tags: [ 'pki_common'  ]
  run_once: yes
  block:

    - name: 'Include OS-specific variables (native)'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"

    - name: 'Install PKI packages'
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ pki_common__packages }}"

    - name: 'Copy CA certificates'
      ansible.builtin.copy:
        src: "{{ pki_common__secrets_dir }}/ca-certificates/{{ item }}"
        dest: "/usr/local/share/ca-certificates/{{ item }}"
      with_items: "{{ pki_common__ca_certificates }}"
      register: 'ca_cert_state'

    - name: 'Recreate ca-certificates'
      ansible.builtin.shell: "/usr/sbin/update-ca-certificates"
      when: 'ca_cert_state.changed'
