---

- name: Install mosquitto
  block:

    - name: Install mosquitto packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ mosquitto_server__packages }}"
