---

- name: 'Install mosquitto'
  tags: [ 'mosquitto_server' ]
  block:

    - name: 'Deploy mosquitto container'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: 'mosquitto_server__use_podman'

    - name: 'Install mosquitto package'
      ansible.builtin.include_tasks:
        file: 'apt.yml'
      when: 'not mosquitto_server__use_podman'
