---

- name: Install mosquitto
  tags: [ 'mosquitto_server' ]
  block:

    - name: Install mosquitto using package management
      ansible.builtin.include_tasks:
        file: apt.yml
      when: not mosquitto_server__use_podman

    - name: Install mosquitto using podman
      ansible.builtin.include_tasks:
        file: podman.yml
      when: mosquitto_server__use_podman
