---

- name: 'Create directories'
  ansible.builtin.file:
    mode: '755'
    path: "{{ item }}"
    owner: "{{ mosquitto_server__uid }}"
    group: "{{ mosquitto_server__gid }}"
    state: 'directory'
  with_items:
    - "{{ mosquitto_server__podman_config_dir }}"
    - "{{ mosquitto_server__podman_data_dir }}"
    - "{{ mosquitto_server__podman_log_dir }}"

- name: 'Generate mosquitto configuration'
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ mosquitto_server__uid }}"
    group: "{{ mosquitto_server__gid }}"
    mode: "{{ item.mode | default('640') }}"
  with_items:
    - src: 'mosquitto.conf.j2'
      dest: "{{ mosquitto_server__podman_config_dir }}/mosquitto.conf"
    - src: 'aclfile.j2'
      dest: "{{ mosquitto_server__podman_config_dir }}/aclfile"
    - src: 'pwfile.j2'
      dest: "{{ mosquitto_server__podman_config_dir }}/pwfile"
      mode: '600'
  notify:
    - 'Restart mosquitto container'
  when: 'not podman___update_mode'

- name: 'Gathering facts about services...'
  ansible.builtin.service_facts:

- name: 'Stop container when it is running'
  ansible.builtin.systemd:
    name: "{{ mosquitto_server__container.name }}.service"
    state: 'stopped'
  when: 'ansible_facts.services[mosquitto_server__container.name + ".service"] is defined and podman___update_mode | bool'

- name: 'Pull image'
  containers.podman.podman_image:
    name: "{{ mosquitto_server__container.image }}"
    force: true
  when: 'podman___update_mode | bool'

- name: 'Install container'
  containers.podman.podman_container:
    name: "{{ mosquitto_server__container.name }}"
    hostname: "{{ mosquitto_server__container.hostname }}"
    image: "{{ mosquitto_server__container.image }}"
    ip: "{{ mosquitto_server__container.ip }}"
    ip6: "{{ mosquitto_server__container.ipv6 | default(omit) }}"
    network: "{{ mosquitto_server__container.network }}"
    timezone: "{{ mosquitto_server__container.timezone }}"
    env: "{{ mosquitto_server__container.environment | default(omit) }}"
    etc_hosts: "{{ mosquitto_server__container.etc_hosts | default(omit) }}"
    expose: "{{ mosquitto_server__container.expose | default(omit) }}"
    label: "{{ mosquitto_server__container.labels | default(omit) }}"
    publish: "{{ mosquitto_server__container.publish | default(omit) }}"
    secrets: "{{ mosquitto_server__container.secrets | default(omit) }}"
    volume: "{{ mosquitto_server__container.volumes | default(omit) }}"
    quadlet_options: |
      [Install]
      WantedBy=default.target

      [Service]
      {% if mosquitto_server__container.exec_start_pre is defined %}
      {% for command in mosquitto_server__container.exec_start_pre %}
      ExecStartPre={{ command }}
      {% endfor %}
      {% endif %}
      RestartSec=5
      Restart=always
    restart_policy: 'no'
    state: 'quadlet'
    recreate: "{{ podman___update_mode | bool }}"

- name: 'Start and enable container'
  ansible.builtin.systemd:
    name: "{{ mosquitto_server__container.name }}"
    daemon_reload: true
    state: 'started'
    enabled: true
  when: 'not ansible_check_mode'

- name: 'Encrypt passwords'
  ansible.builtin.shell: "podman exec -it {{ mosquitto_server__container.name }} mosquitto_passwd -U '/mosquitto/config/pwfile' || true"
  notify:
    - 'Restart mosquitto container'
  when: 'not podman___update_mode'
