---

- name: Install and configure Samba
  tags: [ 'samba' ]
  when: samba__server_enable
  block:

  - name: Install Samba server packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ samba__server_packages }}"

  - name: Install Samba winbind packages
    tags: [ 'packages' ]
    when: samba__winbind_enable
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ samba__winbind_packages }}"

  - name: Install smbldap packages
    tags: [ 'packages' ]
    when: samba__smbldap_enable
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ samba__smbldap_packages }}"

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: etc/samba/smb.conf.j2
      dest: /etc/samba/smb.conf
    notify:
    - Restart Samba server
    - Restart winbind

  - name: Enable Samba services
    tags: [ 'configuration', 'service' ]
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
    - smbd
    - nmbd

  - name: Enable Samba services
    tags: [ 'configuration', 'service' ]
    when: samba__winbind_enable
    ansible.builtin.service:
      name: winbind
      state: started
      enabled: yes
