---

- name: 'Configure borg backup'
  tags: [ 'backup_borg' ]
  block:

    - name: 'Include OS-specific variables'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"

    - name: 'Install borg backup packages'
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ backup_borg__packages }}"

    - name: 'Copy borg backup scripts to host'
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup__lib_dir }}/{{ item }}"
        mode: '755'
      with_items:
        - '950.backup.borgbackup'

    - name: 'Generate borg backup configuration file'
      ansible.builtin.template:
        src: 'borg.j2'
        dest: "{{ backup__etc_dir }}/borg"
        owner: 'root'
        group: 'root'
        mode: '640'

    - name: 'Write borg password file'
      no_log: true
      ansible.builtin.copy:
        dest: "{{ backup__etc_dir }}/borg_passphrase"
        owner: 'root'
        group: 'root'
        mode: '400'
        content: |
          {{ backup_borg__passphrase }}
