---

- name: Configure borg backup
  tags: [ 'backup_borg'  ]
  block:

    - name: Install borg backup packages
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ backup_borg__packages }}"

    - name: Copy borg backup scripts to host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup_common__lib_dir }}/{{ item }}"
        mode: '755'
      with_items: "{{ backup_borg__files }}"

    - name: Generate borg backup configuration file
      ansible.builtin.template:
        src: 'borg.j2'
        dest: "{{ backup_common__etc_dir }}/borg"
        owner: 'root'
        group: 'root'
        mode: '640'
