---

- name: 'Deploy Redis Insight container'
  tags: [ 'app_redisinsight' ]
  block:

    - name: 'Create Redis Insight directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
        owner: "{{ app_redisinsight__uid }}"
        group: "{{ app_redisinsight__gid }}"
      with_items:
        - "{{ app_redisinsight__data_dir }}"

    - name: 'Create podman containers'
      containers.podman.podman_container:
        name: "{{ app_redisinsight__podman_container.name }}"
        hostname: "{{ app_redisinsight__podman_container.hostname }}"
        image: "{{ app_redisinsight__podman_container.image }}"
        ip: "{{ app_redisinsight__podman_container.ip }}"
        network: "{{ app_redisinsight__podman_container.network }}"
        restart_policy: "{{ app_redisinsight__podman_container.restart_policy }}"
        env: "{{ app_redisinsight__podman_container.environment }}"
        etc_hosts: "{{ app_redisinsight__podman_container.hosts }}"
        timezone: "{{ app_redisinsight__podman_container.timezone }}"
        volume: "{{ app_redisinsight__podman_container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: app_redisinsight__ipv6 | length == 0
