---

#
# Substitutes - do not change
#

app_rocketchat__url: "{{ rocketchat_url | default('http://localhost:3000') }}"
app_rocketchat__hostname: "{{ rocketchat_hostname | default('rocketchat.localhost') }}"
app_rocketchat__ip: "{{ rocketchat_ip | mandatory }}"
app_rocketchat__ipv6: "{{ rocketchat_ipv6 | default('') }}"
app_rocketchat__network: "{{ rocketchat_network | mandatory }}"
app_rocketchat__version: "{{ rocketchat_version | default('latest') }}"
app_rocketchat__timezone: "{{ rocketchat_timezone | default(bootstrap_timezone__timezone) }}"

app_rocketchat__hosts: "{{ rocketchat_hosts | default({}) }}"

app_rocketchat__mongodb_host: "{{ rocketchat_mongodb_host | mandatory }}"
app_rocketchat__mongodb_database: "{{ rocketchat_mongodb_database | default('rocketchat') }}"
app_rocketchat__mongodb_oplog_database: "{{ rocketchat_mongodb_oplog | default('local') }}"
app_rocketchat__mongodb_username: "{{ rocketchat_mongodb_username | default('') }}"
app_rocketchat__mongodb_password: "{{ rocketchat_mongodb_password | default('') }}"
app_rocketchat__mongodb_auth_source: "{{ rocketchat_mongodb_auth_source | default('admin') }}"

#
# Defaults - do not change
#

app_rocketchat__mongodb_auth: "{{ app_rocketchat__mongodb_username if app_rocketchat__mongodb_username | length > 0 }}{{ ':' + app_rocketchat__mongodb_password if app_rocketchat__mongodb_password | length > 0 }}"
app_rocketchat__mongodb_options: "{{ 'authSource=' + app_rocketchat__mongodb_auth_source if app_rocketchat__mongodb_auth | length > 0 }}"
app_rocketchat__mongodb_oplog_options: "{{ rocketchat_mongodb_oplog_options | default(app_rocketchat__mongodb_options) }}"
app_rocketchat__mongodb_url: "mongodb://{{ app_rocketchat__mongodb_auth + '@' if app_rocketchat__mongodb_auth | length > 0 }}{{ app_rocketchat__mongodb_host }}/{{ app_rocketchat__mongodb_database }}{{ '?' + app_rocketchat__mongodb_options if app_rocketchat__mongodb_options | length > 0}}"
app_rocketchat__mongodb_oplog_url: "mongodb://{{ app_rocketchat__mongodb_auth + '@' if app_rocketchat__mongodb_auth | length > 0 }}{{ app_rocketchat__mongodb_host }}/{{ app_rocketchat__mongodb_oplog_database }}{{ '?' + app_rocketchat__mongodb_oplog_options if app_rocketchat__mongodb_oplog_options | length > 0}}"

app_rocketchat__container: "{{ app_rocketchat__container_default | combine(rocketchat_container | default({})) }}"

app_rocketchat__container_default:
  name: rocketchat
  hostname: "{{ app_rocketchat__hostname }}"
  image: "docker.io/rocketchat/rocket.chat:{{ app_rocketchat__version }}"
  ip: "{{ app_rocketchat__ip }}"
  ipv6: "{{ app_rocketchat__ipv6 }}"
  network: "{{ app_rocketchat__network }}"
  restart_policy: always
  environment:
    TZ: "{{ app_rocketchat__timezone }}"
    ROOT_URL: "{{ app_rocketchat__url }}"
    MONGO_URL: "{{ app_rocketchat__mongodb_url }}"
    MONGO_OPLOG_URL: "{{ app_rocketchat__mongodb_oplog_url }}"
  hosts: "{{ app_rocketchat__hosts }}"
  volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  shm_size: 256m
