---
# tasks file for roles/postgresql

- name: Install and configure PostgreSQL client
  tags: [ 'postgresql' ]
  when: postgresql__client_enable
  block:

  - name: Install PostgreSQL client packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ postgresql__client_packages_combined }}"

- name: Install and configure PostgreSQL server
  tags: [ 'postgresql' ]
  when: postgresql__server_enable
  block:
  
  - name: Install PostgreSQL server packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ postgresql__server_packages_combined }}"
    register: postgresql_server_packages_installation_result

