---

- name: 'Deploy OpenSSH container'
  tags: [ 'security_openssh' ]
  block:

    - name: 'Create OpenSSH directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
        owner: "{{ security_openssh__uid }}"
        group: "{{ security_openssh__uid }}"
        mode: '700'
      with_items:
        - "{{ security_openssh__data_dir }}"

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ security_openssh__podman_container.name }}"
        hostname: "{{ security_openssh__podman_container.hostname }}"
        image: "{{ security_openssh__podman_container.image }}"
        ip: "{{ security_openssh__podman_container.ip }}"
        network: "{{ security_openssh__podman_container.network }}"
        restart_policy: "{{ security_openssh__podman_container.restart_policy }}"
        etc_hosts: "{{ security_openssh__podman_container.hosts }}"
        publish: "{{ security_openssh__podman_container.publish }}"
        env: "{{ security_openssh__podman_container.environment }}"
        timezone: "{{ security_openssh__podman_container.timezone }}"
        volume: "{{ security_openssh__podman_container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: security_openssh__ipv6 | length == 0
