---

#
# Substitutes - do not change
#

database_postgresql__accounts: "{{ postgresql_accounts | default([]) }}"
database_postgresql__databases: "{{ postgresql_databases | default([]) }}"
database_postgresql__privileges: "{{ postgresql_privileges | default([]) }}"
database_postgresql__passwords: "{{ postgresql_passwords | mandatory }}"
database_postgresql__password: "{{ postgresql_password | mandatory }}"

database_postgresql__use_podman: "{{ postgresql_use_podman | default(true) }}"

database_postgresql__hostname: "{{ postgresql_hostname | default('postgresql.' + dns_hostname) }}"
database_postgresql__ip: "{{ postgresql_ip | mandatory }}"
database_postgresql__ipv6: "{{ postgresql_ipv6 | default('') }}"
database_postgresql__network: "{{ postgresql_network | mandatory }}"
database_postgresql__hosts: "{{ postgresql_hosts | default({}) }}"
database_postgresql__time_zone: "{{ postgresql_timezone | default(bootstrap_timezone__timezone) }}"
database_postgresql__home: "{{ postgresql_home | mandatory }}"

database_postgresql__port: "{{ postgresql_port | default(5432) }}"

database_postgresql__version: "{{ postgresql_version | default('alpine') }}"
database_postgresql__container: "{{ database_postgresql__podman_container_default | combine(postgresql_container | default({})) }}"

#
# Defaults - do not change
#

database_postgresql__data_dir: "{{ database_postgresql__home + '/data' if database_postgresql__use_podman else '/var/lib/postgresql' }}"

database_postgresql__podman_name: 'postgresql'
database_postgresql__podman_image: 'docker.io/library/postgres'

database_postgresql__podman_container_default:
  name: 'postgresql'
  hostname: "{{ database_postgresql__hostname }}"
  image: "{{ database_postgresql__podman_image }}:{{ database_postgresql__version }}"
  ip: "{{ database_postgresql__ip }}"
  ipv6: "{{ database_postgresql__ipv6 }}"
  network: "{{ database_postgresql__network }}"
  restart_policy: 'always'
  hosts: "{{ database_postgresql__hosts }}"
  environment:
    POSTGRES_PASSWORD: "{{ database_postgresql__password }}"
  timezone: "{{ database_postgresql__time_zone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - "{{ database_postgresql__data_dir }}:/var/lib/postgresql/data"

database_postgresql__packages: "{{
  database_postgresql__packages_podman_default[bootstrap_ansible__distribution] | default([]) if database_postgresql__use_podman
  else database_postgresql__packages_default[bootstrap_ansible__distribution] | default([])
}}"

database_postgresql__packages_podman_default:
  Debian:
    - 'libpq5'
    - 'python3-psycopg2'

database_postgresql__packages_default:
  Debian:
    - 'libpq5'
    - 'python3-psycopg2'
