---

#
# Substitutes - do not change
#

database_redis__use_podman: "{{ redis_use_podman | default(true) }}"

database_redis__hostname: "{{ redis_hostname | default('redis.' + dns_hostname) }}"
database_redis__ip: "{{ redis_ip | mandatory }}"
database_redis__ipv6: "{{ redis_ipv6 | default('') }}"
database_redis__network: "{{ redis_network | mandatory }}"
database_redis__version: "{{ redis_version | default('latest') }}"

database_redis__hosts: "{{ redis_hosts | default({}) }}"
database_redis__environment: "{{ redis_environment | default({}) }}"
database_redis__publish: "{{ redis_publish | default([]) }}"
database_redis__timezone: "{{ redis_timezone | default(bootstrap_timezone__timezone) }}"

database_redis__home: "{{ redis_home | mandatory }}"

database_redis__container: "{{ database_redis__container_default | combine(redis_container | default({})) }}"

database_redis__bind: "{{ redis_bind | default(database_redis__ip if database_redis__use_podman else '127.0.0.1 -::1') }}"

#
# Defaults - do not change
#

database_redis__container_default:
  name: 'redis'
  hostname: "{{ database_redis__hostname }}"
  image: "docker.io/redis:{{ database_redis__version }}"
  ip: "{{ database_redis__ip }}"
  ipv6: "{{ database_redis__ipv6 }}"
  network: "{{ database_redis__network }}"
  restart_policy: 'always'
  hosts: "{{ database_redis__hosts }}"
  environment: "{{ database_redis__environment }}"
  timezone: "{{ database_redis__timezone }}"
  volumes:
    - "{{ database_redis__home }}/data:/data"
    - "{{ database_redis__home }}/redis.conf:/usr/local/etc/redis/redis.conf"

database_redis__packages: "{{ database_redis__packages_default[bootstrap_ansible__distribution] | default([]) }}"

database_redis__packages_default:
  Debian:
    - redis-tools
    - redis-server
