---

- name: 'Loop over Foundry VTT instances'
  tags: [ 'app_foundryvtt' ]
  include_role:
    name: 'app_foundryvtt'
  loop: "{{ foundryvtt_instances }}"
  loop_control:
    loop_var: 'foundryvtt'
  vars:
    foundryvtt_name: "{{ foundryvtt.name }}"
    foundryvtt_home: "{{ foundryvtt.home }}"
    foundryvtt_hostname: "{{ foundryvtt.hostname }}"
    foundryvtt_ip: "{{ foundryvtt.ip }}"
    foundryvtt_ipv6: "{{ foundryvtt.ipv6 | default(app_foundryvtt__ipv6_default) }}"
    foundryvtt_environment: "{{ foundryvtt.environment | default(omit) }}"
    foundryvtt_labels: "{{ foundryvtt.labels }}"
    foundryvtt_version: "{{ foundryvtt.version }}"
