---

- name: 'Deploy Foundry VTT containers'
  tags: [ 'app_foundryvtt' ]
  block:

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ item.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[item.name + ".service"] is defined'
      with_items: "{{ app_foundryvtt__containers }}"

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ item.image | default(app_foundryvtt__container_default.image) }}"
        force: true
      when: 'podman___update_mode | bool'
      with_items: "{{ app_foundryvtt__containers }}"

    - name: 'Create containers'
      containers.podman.podman_container:
        name: "{{ item.name | mandatory }}"
        hostname: "{{ item.hostname | mandatory }}"
        image: "{{ item.image | default(app_foundryvtt__container_default.image) }}"
        ip: "{{ item.ip | mandatory }}"
        network: "{{ item.network | default(app_foundryvtt__container_default.network) }}"
        timezone: "{{ item.timezone | default(app_foundryvtt__container_default.timezone) }}"
        env: "{{ item.environment | default(app_foundryvtt__container_default.environment) }}"
        label: "{{ item.labels }}"
        volume: "{{ item.volumes | default([]) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'item.ipv6 | default("") | length == 0'
      with_items: "{{ app_foundryvtt__containers }}"

    - name: 'Create containers'
      containers.podman.podman_container:
        name: "{{ item.name | mandatory }}"
        hostname: "{{ item.hostname | mandatory }}"
        image: "{{ item.image | default(app_foundryvtt__container_default.image) }}"
        ip: "{{ item.ip | mandatory }}"
        ip6: "{{ item.ipv6 | mandatory }}"
        network: "{{ item.network | default(app_foundryvtt__container_default.network) }}"
        timezone: "{{ item.timezone | default(app_foundryvtt__container_default.timezone) }}"
        env: "{{ item.environment | default(app_foundryvtt__container_default.environment) }}"
        label: "{{ item.labels }}"
        volume: "{{ item.volumes | default([]) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'item.ipv6 | default("") | length > 0'
      with_items: "{{ app_foundryvtt__containers }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ item.name | mandatory }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      with_items: "{{ app_foundryvtt__containers }}"
      when: 'not ansible_check_mode'
