---

- name: 'Deploy Foundry VTT containers'
  tags: [ 'app_foundryvtt' ]
  block:

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_foundryvtt__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_foundryvtt__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_foundryvtt__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Create containers'
      containers.podman.podman_container:
        name: "{{ app_foundryvtt__container.name }}"
        hostname: "{{ app_foundryvtt__container.hostname }}"
        image: "{{ app_foundryvtt__container.image }}"
        ip: "{{ app_foundryvtt__container.ip }}"
        ip6: "{{ app_foundryvtt__container.ipv6 | default(omit) }}"
        network: "{{ app_foundryvtt__container.network }}"
        timezone: "{{ app_foundryvtt__container.timezone }}"
        env: "{{ app_foundryvtt__container.environment | default(omit) }}"
        etc_hosts: "{{ app_foundryvtt__container.etc_hosts | default(omit) }}"
        expose: "{{ app_foundryvtt__container.expose | default(omit) }}"
        label: "{{ app_foundryvtt__container.labels | default(omit) }}"
        publish: "{{ app_foundryvtt__container.publish | default(omit) }}"
        secrets: "{{ app_foundryvtt__container.secrets | default(omit) }}"
        volume: "{{ app_foundryvtt__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_foundryvtt__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode is defined and podman___update_mode else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'app_foundryvtt__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ app_foundryvtt__container.name }}"
        container_image: "{{ app_foundryvtt__container.image }}"
        container_schedule: "{{ foundryvtt_autoupdate_schedule | default('0 0 * * *') }}"
