---

- name: Deploy Keycloak container
  tags: [ 'app_foundryvtt' ]
  block:

# See: https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html
    - name: Create podman containers
      containers.podman.podman_container:
        name: "{{ item.name | mandatory }}"
        hostname: "{{ item.hostname | mandatory }}"
        image: "{{ item.image | default(app_foundryvtt__container_default.image) }}"
        ip: "{{ item.ip | mandatory }}"
        network: "{{ item.network | default(app_foundryvtt__container_default.network) }}"
        expose: "{{ item.expose | default(app_foundryvtt__container_default.expose | default([])) }}"
        publish: "{{ item.publish | default(app_foundryvtt__container_default.publish | default([])) }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ item.restart_policy | default(app_foundryvtt__container_default.restart_policy) }}"
        etc_hosts: "{{ item.hosts | default(app_foundryvtt__container_default.hosts) }}"
        env: "{{ item.environment | default(app_foundryvtt__container_default.environment) }}"
        timezone: "{{ item.timezone | default(app_foundryvtt__container_default.timezone) }}"
        volume: "{{ item.volumes | default(app_foundryvtt__container_default.image | default([])) }}"
      when: item.ipv6 | default('') | length == 0
      with_items: "{{ app_foundryvtt__containers }}"

# See: https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html
    - name: Create podman containers
      containers.podman.podman_container:
        name: "{{ item.name | mandatory }}"
        hostname: "{{ item.hostname | mandatory }}"
        image: "{{ item.image | default(app_foundryvtt__container_default.image) }}"
        ip: "{{ item.ip | mandatory }}"
        ipv6: "{{ item.ipv6 | mandatory }}"
        network: "{{ item.network | default(app_foundryvtt__container_default.network) }}"
        expose: "{{ item.expose | default(app_foundryvtt__container_default.expose | default([])) }}"
        publish: "{{ item.publish | default(app_foundryvtt__container_default.publish | default([])) }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ item.restart_policy | default(app_foundryvtt__container_default.restart_policy) }}"
        etc_hosts: "{{ item.hosts | default(app_foundryvtt__container_default.hosts) }}"
        env: "{{ item.environment | default(app_foundryvtt__container_default.environment) }}"
        timezone: "{{ item.timezone | default(app_foundryvtt__container_default.timezone) }}"
        volume: "{{ item.volumes | default(app_foundryvtt__container_default.image | default([])) }}"
      when: item.ipv6 | default('') | length > 0
      with_items: "{{ app_foundryvtt__containers }}"
