---

- name: 'Deploy Forgejo container'
  tags: [ 'app_forgejo' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ app_forgejo__uid }}"
        group: "{{ app_forgejo__gid }}"
        mode: "{{ item.mode | default('0700') }}"
        state: 'directory'
      with_items:
        - dest: "{{ app_forgejo__podman_home }}"

    - name: 'Create secrets'
      containers.podman.podman_secret:
        state: 'present'
        name: 'forgejo_database_passwd'
        data: "{{ app_forgejo__db_pass }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_forgejo__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_forgejo__container.name + ".service"] is defined'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_forgejo__podman_image }}"
        tag: "{{ app_forgejo__podman_tag }}"
      when: 'podman___update_mode | default(false)'

    - name:  'Install container'
      containers.podman.podman_container:
        name: "{{ app_forgejo__container.name }}"
        hostname: "{{ app_forgejo__container.hostname }}"
        image: "{{ app_forgejo__container.image }}"
        ip: "{{ app_forgejo__container.ip }}"
        network: "{{ app_forgejo__container.network }}"
        timezone: "{{ app_forgejo__container.timezone }}"
        env: "{{ app_forgejo__container.environment }}"
        label: "{{ app_forgejo__container.labels }}"
        publish: "{{ app_forgejo__container.publish }}"
        secrets: "{{ app_forgejo__container.secrets }}"
        volume: "{{ app_forgejo__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_forgejo__container.requires is defined %}
          Requires={{ app_forgejo__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'app_forgejo__ipv6 | length == 0'

    - name:  'Install container'
      containers.podman.podman_container:
        name: "{{ app_forgejo__container.name }}"
        hostname: "{{ app_forgejo__container.hostname }}"
        image: "{{ app_forgejo__container.image }}"
        ip: "{{ app_forgejo__container.ip }}"
        ip6: "{{ app_forgejo__container.ipv6 }}"
        network: "{{ app_forgejo__container.network }}"
        timezone: "{{ app_forgejo__container.timezone }}"
        env: "{{ app_forgejo__container.environment }}"
        label: "{{ app_forgejo__container.labels }}"
        publish: "{{ app_forgejo__container.publish }}"
        secrets: "{{ app_forgejo__container.secrets }}"
        volume: "{{ app_forgejo__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_forgejo__container.requires is defined %}
          Requires={{ app_forgejo__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'app_forgejo__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_forgejo__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'
