---

- name: 'Deploy Joplin server container'
  tags: [ 'app_joplin' ]
  block:

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ app_joplin_server__container.name }}"
        hostname: "{{ app_joplin_server__container.hostname }}"
        image: "{{ app_joplin_server__container.image }}"
        ip: "{{ app_joplin_server__container.ip }}"
        network: "{{ app_joplin_server__container.network }}"
        restart_policy: "{{ app_joplin_server__container.restart_policy }}"
        etc_hosts: "{{ app_joplin_server__container.hosts }}"
        env: "{{ app_joplin_server__container.environment }}"
        timezone: "{{ app_joplin_server__container.timezone }}"
        volume: "{{ app_joplin_server__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: app_joplin_server__ipv6 | length == 0
