---

- name: 'Deploy Joplin server container'
  tags: [ 'app_joplin' ]
  block:

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: "{{ item.name }}"
        data: "{{ item.data }}"
      with_items:
        - name: 'joplin_database_password'
          data: "{{ app_joplin__db_pass }}"
        - name: 'joplin_smtp_password'
          data: "{{ app_joplin__mailer_auth_password }}"
      when: 'item.data | length > 0'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_joplin__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_joplin__container.name + ".service"] is defined'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_joplin__podman_image }}"
        tag: "{{ app_joplin__podman_tag }}"
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_joplin__container.name }}"
        hostname: "{{ app_joplin__container.hostname }}"
        image: "{{ app_joplin__container.image }}"
        ip: "{{ app_joplin__container.ip }}"
        network: "{{ app_joplin__container.network }}"
        timezone: "{{ app_joplin__container.timezone }}"
        env: "{{ app_joplin__container.environment }}"
        label: "{{ app_joplin__container.labels }}"
        secrets: "{{ app_joplin__container.secrets }}"
        volume: "{{ app_joplin__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_joplin__container.requires is defined %}
          Requires={{ app_joplin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'app_joplin__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_joplin__container.name }}"
        hostname: "{{ app_joplin__container.hostname }}"
        image: "{{ app_joplin__container.image }}"
        ip: "{{ app_joplin__container.ip }}"
        ip6: "{{ app_joplin__container.ipv6 }}"
        network: "{{ app_joplin__container.network }}"
        timezone: "{{ app_joplin__container.timezone }}"
        env: "{{ app_joplin__container.environment }}"
        label: "{{ app_joplin__container.labels }}"
        secrets: "{{ app_joplin__container.secrets }}"
        volume: "{{ app_joplin__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_joplin__container.requires is defined %}
          Requires={{ app_joplin__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'app_joplin__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_joplin__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'
