---

- name: 'Deploy n8n container'
  tags: [ 'app_n8n' ]
  block:

    - name: 'Create n8n directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
        owner: "{{ app_n8n__uid }}"
      with_items:
        - "{{ app_n8n__data_dir }}"

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ app_n8n__container.name }}"
        hostname: "{{ app_n8n__container.hostname }}"
        image: "{{ app_n8n__container.image }}"
        ip: "{{ app_n8n__container.ip }}"
        network: "{{ app_n8n__container.network }}"
        restart_policy: "{{ app_n8n__container.restart_policy }}"
        etc_hosts: "{{ app_n8n__container.hosts }}"
        env: "{{ app_n8n__container.environment }}"
        timezone: "{{ app_n8n__container.timezone }}"
        volume: "{{ app_n8n__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: app_n8n__ipv6 | length == 0
