---

- name: 'Deploy n8n container'
  tags: [ 'app_n8n' ]
  block:

    - name: 'Create n8n directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
        owner: "{{ app_n8n__uid }}"
      with_items:
        - "{{ app_n8n__data_dir }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_n8n__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_n8n__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull n8n image'
      containers.podman.podman_image:
        name: "{{ app_n8n__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ app_n8n__container.name }}"
        hostname: "{{ app_n8n__container.hostname }}"
        image: "{{ app_n8n__container.image }}"
        ip: "{{ app_n8n__container.ip }}"
        ip6: "{{ app_n8n__container.ipv6 | default(omit) }}"
        network: "{{ app_n8n__container.network }}"
        env: "{{ app_n8n__container.environment | default(omit) }}"
        timezone: "{{ app_n8n__container.timezone }}"
        volume: "{{ app_n8n__container.volumes | default(omit) }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_n8n__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
