---
# tasks file for roles/mysql

- name: Install MySQL packages
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ mysql__packages_combined }}"
  tags:
  - mysql
  - packages

- name: Set password for root
  ansible.builtin.command: "mysql -e 'SET PASSWORD = PASSWORD(\"{{ mysql__password.root }}\"); FLUSH PRIVILEGES;'"
  when: mysql__password.root is defined
  tags:
  - mysql
  - bootstrap

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mysql__password.root }}"
    name: ''
    host_all: yes
    state: absent
  tags:
  - mysql
  - configuration

- name: Create databases
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ mysql__password.root }}"
    name: "{{ mysql__databases }}"
    state: present
  tags:
  - mysql
  - configuration

- name: Create database users with privileges
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mysql__password.root }}"
    name: "{{ item.name }}"
    password: "{{  mysql__password[item.name] }}"
    priv: "{{ item.privileges }}"
    state: present
  with_items: "{{ mysql__accounts }}"
  tags:
  - mysql
  - configuration
