---

- name: 'Install InfluxDB'
  tags: [ 'database_influxdb'  ]
  block:

    - name: 'Create InfluxDB directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ database_influxdb__etc_dir }}"
        - "{{ database_influxdb__data_dir }}"
        - "{{ database_influxdb__backup_dir }}"

    - name: 'Install InfluxDB container'
      containers.podman.podman_container:
        name: "{{ database_influxdb__container.name }}"
        hostname: "{{ database_influxdb__container.hostname }}"
        image: "{{ database_influxdb__container.image }}"
        ip: "{{ database_influxdb__container.ip }}"
        network: "{{ database_influxdb__container.network }}"
        etc_hosts: "{{ database_influxdb__container.hosts }}"
        expose: "{{ database_influxdb__container.expose }}"
        publish: "{{ database_influxdb__container.publish }}"
        env: "{{ database_influxdb__init_environment_default }}"
        timezone: "{{ database_influxdb__container.timezone }}"
        volume: "{{ database_influxdb__container.volumes }}"
        pull: 'always'
      when: database_influxdb__ipv6 | length == 0

