---

- name: 'Install InfluxDB'
  tags: [ 'database_influxdb'  ]
  block:

    - name: 'Include OS-specific variables (podman)'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        files:
          - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-podman.yml"
          - "{{ ansible_distribution }}-podman.yml"
        skip: true
      when: 'database_influxdb__use_podman'

    - name: 'Include InfluxDB version dependent configuration'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "podman-{{ database_influxdb__version }}.yml"
      when: 'database_influxdb__use_podman'

    - name: 'Install InfluxDB'
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - "podman-{{ database_influxdb__version }}.yml"
      when: 'database_influxdb__use_podman'
