---

- name: 'Create InfluxDB directories'
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ database_influxdb__uid }}"
    group: "{{ database_influxdb__gid }}"
    mode: '0750'
    state: 'directory'
  with_items:
    - "{{ database_influxdb__etc_dir }}"
    - "{{ database_influxdb__data_dir }}"
    - "{{ database_influxdb__backup_dir }}"

- name: 'Create secrets'
  no_log: true
  containers.podman.podman_secret:
    state: 'present'
    name: "{{ item.name }}"
    data: "{{ item.data }}"
  with_items:
    - name: 'influxdb_password'
      data: "{{ database_influxdb__password }}"
    - name: 'influxdb_admin_token'
      data: "{{ database_influxdb__admin_token }}"

- name: 'Init InfluxDB container'
  containers.podman.podman_container:
    name: "{{ database_influxdb__container.name }}"
    hostname: "{{ database_influxdb__container.hostname }}"
    image: "{{ database_influxdb__container.image }}"
    ip: "{{ database_influxdb__container.ip }}"
    network: "{{ database_influxdb__container.network }}"
    expose: "{{ database_influxdb__container.expose }}"
    publish: "{{ database_influxdb__container.publish }}"
    restart_policy: "{{ database_influxdb__container.restart_policy }}"
    timezone: "{{ database_influxdb__container.timezone }}"
    env: "{{ database_influxdb__init_environment_default }}"
    secrets: "{{ database_influxdb__secrets }}"
    volume: "{{ database_influxdb__container.volumes }}"
    pull: 'always'
    recreate: "{{ podman___update_mode | default(false) }}"
  when: 'database_influxdb__ipv6 | length == 0'

- name: 'Init InfluxDB container'
  containers.podman.podman_container:
    name: "{{ database_influxdb__container.name }}"
    hostname: "{{ database_influxdb__container.hostname }}"
    image: "{{ database_influxdb__container.image }}"
    ip: "{{ database_influxdb__container.ip }}"
    network: "{{ database_influxdb__container.network }}"
    expose: "{{ database_influxdb__container.expose }}"
    publish: "{{ database_influxdb__container.publish }}"
    restart_policy: "{{ database_influxdb__container.restart_policy }}"
    timezone: "{{ database_influxdb__container.timezone }}"
    env: "{{ database_influxdb__init_environment_default }}"
    secrets: "{{ database_influxdb__secrets }}"
    volume: "{{ database_influxdb__container.volumes }}"
    pull: 'always'
    recreate: "{{ podman___update_mode | default(false) }}"
  when: 'database_influxdb__ipv6 | length > 0'

- name: 'Wait for InfluxDB port to be opened'
  ansible.builtin.wait_for:
    host: "{{ database_influxdb__container.ip }}"
    port: "{{ database_influxdb__port }}"
