---
# tasks file for roles/powerdns

- name: Install powerdns recursor packages
  tags: [ 'packages' ]
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ powerdns__recursor_packages_combined }}"

- name: Generate configuration 
  tags: [ 'configuration' ]
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - src: etc/powerdns/recursor.conf.j2
    dest: "{{ powerdns__config_config_dir }}/recursor.conf"
  - src: "etc/powerdns/recursor.lua.j2"
    dest: "{{ powerdns__config_config_dir }}/recursor.lua"
  - src: "etc/powerdns/hosts.j2"
    dest: "{{ powerdns__config_etc_hosts_file }}"
  notify:
  - Restart pdns-recursor
