---
# tasks file for roles/powerdns

- name: Install powerdns server packages
  tags: [ 'packages' ]
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ powerdns__server_packages_combined }}"

- name: Generate configuration 
  tags: [ 'configuration' ]
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - src: etc/powerdns/pdns.conf.j2
    dest: /etc/powerdns/pdns.conf
  - src: "etc/powerdns/pdns.d/backend.conf.j2"
    dest: "/etc/powerdns/pdns.d/{{ powerdns__server_backend }}.conf"
  notify:
  - Restart pdns
