---
# tasks file for roles/nfs

- name: Install and configure NFS server
  tags: [ 'nfs' ]
  when: nfs__server_enable
  block:

  - name: Install NFS server packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ nfs__server_packages_combined }}"

- name: Install and configure NFS client
  tags: [ 'nfs' ]
  when: nfs__client_enable
  block:

  - name: Install NFS client packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ nfs__client_packages_combined }}"

  - name: Mount NFS volume
    when: nfs__client_volumes | length > 0
    tags: [ 'configuration', 'mount' ]
    ansible.posix.mount:
      src: "{{ item.src }}"
      path: "{{ item.path }}"
      opts: "{{ item.options }}"
      state: mounted
      fstype: nfs
    with_items: "{{ nfs__client_volumes }}"
