---

#
# Substitutes - do not change
#

dns_pihole__hostname: "{{ pihole_hostname | default('pihole.' + dns_hostname) }}"
dns_pihole__ip: "{{ pihole_ip | mandatory }}"
dns_pihole__ipv6: "{{ pihole_ipv6 | default('') }}"
dns_pihole__network: "{{ pihole_network | mandatory }}"
dns_pihole__hosts: "{{ pihole_hosts | default({}) }}"
dns_pihole__timezone: "{{ pihole_timezone | default(bootstrap_timezone__timezone) }}"

dns_pihole__dns_port: "{{ pihole_dns_port | default(53) }}"
dns_pihole__http_port: "{{ pihole_http_port | default(80) }}"
dns_pihole__https_port: "{{ pihole_https_port | default(443) }}"

dns_pihole__publish_http: "{{ pihole_publish_http | default(false) }}"
dns_pihole__publish_https: "{{ pihole_publish_https | default(false) }}"

dns_pihole__version: "{{ pihole_version | default('latest') }}"
dns_pihole__container: "{{ dns_pihole__podman_container_default }}"

dns_pihole__home: "{{ pihole_home | mandatory }}"
dns_pihole__password: "{{ pihole_password | mandatory }}"

#
# Defaults - do not change
#

dns_pihole__podman_image: 'docker.io/pihole/pihole'
dns_pihole__etc_dir: "{{ dns_pihole__home }}/pihole"
dns_pihole__dnsmasq_dir: "{{ dns_pihole__home }}/dnsmasq"

dns_pihole__ports: "{{ [
    dns_pihole__dns_port + ':53/udp',
    dns_pihole__dns_port + ':53/tcp'
  ] + dns_pihole__port_http + dns_pihole__port_https   
}}"

dns_pihole__port_http: "{{ [ dns_pihole__http_port + ':80/tcp' ] if dns_pihole__publish_http else [] }}"
dns_pihole__port_https: "{{ [ dns_pihole__https_port + ':443/tcp' ] if dns_pihole__publish_https else [] }}"

dns_pihole__podman_container_default:
  name: 'pihole'
  hostname: "{{ dns_pihole__hostname }}"
  image: "{{ dns_pihole__podman_image }}:{{ dns_pihole__version }}"
  ip: "{{ dns_pihole__ip }}"
  ipv6: "{{ dns_pihole__ipv6 }}"
  network: "{{ dns_pihole__network }}"
  restart_policy: 'always'
  hosts: "{{ dns_pihole__hosts }}"
  environment:
    FTLCONF_webserver_api_password: "{{ dns_pihole__password }}"
    FTLCONF_dns_listeningMode: 'all'
    TZ: "{{ dns_pihole__timezone }}"
  publish: "{{ dns_pihole__ports }}"
  timezone: "{{ dns_pihole__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - "{{ dns_pihole__etc_dir }}:/etc/pihole"
    - "{{ dns_pihole__dnsmasq_dir }}:/etc/dnsmasq.d"
