#!/bin/sh

#
# Check Raspberry Pi CPU temperature
# (C) 2019 Gerrit Beine <mail@gerritbeine.com>
#

WARN=50
CRIT=60

UTILS="/usr/lib/nagios/plugins/utils.sh"

if [ -f ${UTILS} ]; then
	. ${UTILS}
else
	echo "Monitoring utils not found"
	exit 3
fi

VCGENCMD="/usr/bin/vcgencmd"

if [ ! -f ${VCGENCMD} ]; then
	echo "Raspberry Pi utils not found"
	exit 3
fi

if [ -n "$1" ]; then
	WARN=$1
	if [ -n "$2" ]; then
		CRIT=$2
	else
		CRIT=$(($1+10))
	fi
fi

TEMPERATURE=`vcgencmd measure_temp`

TEMPERATURE=${TEMPERATURE#*=}
TEMP=${TEMPERATURE%.*}

if [ ${TEMP} -lt ${WARN} ]; then
	STATE=$STATE_OK
	MESSAGE="OK; ${TEMPERATURE}"
elif [ ${TEMP} -lt ${CRIT} ]; then
	STATE=$STATE_WARNING
	MESSAGE="WARNING; ${TEMPERATURE}"
else
	STATE=$STATE_CRITICAL
	MESSAGE="CRITICAL; ${TEMPERATURE}"
fi

echo ${MESSAGE}

exit ${STATE}

