#!/bin/bash

#
# (c) 2020-2022,  Gerrit Beine, mail@gerritbeine.com
#

OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

function usage()
{
        echo "Usage: ./check_reboot"
}

function get_uptime()
{
	if [ -x $UPTIME ]; then
		MESSAGE=`$UPTIME -p`
	fi
}

function get_reboot()
{
	if [ -f $REBOOT_FILE ]; then
		REBOOT_MESSAGE=`cat $REBOOT_FILE`
		REBOOT_REQUIRED=true
	fi
}

function check_reboot()
{
	if [ $REBOOT_REQUIRED ]; then
		echo "CRITICAL: $REBOOT_MESSAGE $MESSAGE"
		exit $CRITICAL
	else
		echo "OK: $MESSAGE"
		exit $OK
	fi
}

# -- Main -- #

UPTIME=/usr/bin/uptime
REBOOT_FILE=/var/run/reboot-required

get_uptime
get_reboot
check_reboot
