---

- name: Create realm configuration
  tags: [ 'app_keycloak_config' ]
  block:

# See: https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_realm_module.html
    - name: Create or update Keycloak realm
      tags: [ 'app_keycloak_config' ]
      community.general.keycloak_realm:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ app_keycloak__auth_url }}"
        auth_realm: "{{ app_keycloak__auth_realm }}"
        auth_username: "{{ app_keycloak__auth_username }}"
        auth_password: "{{ app_keycloak__auth_password }}"
        id: "{{ realm.id }}"
        realm: "{{ realm.realm }}"
        display_name: "{{ realm.display_name | default(app_keycloak__realm_default.display_name) }}"
        login_with_email_allowed: "{{ realm.login_with_email | default(app_keycloak__realm_default.login_with_email) }}"
        enabled: "{{ realm.enabled | default(true) }}"
        state: 'present'

# See: https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_authentication_required_actions_module.html
    - name: Create or update Keycloak required actions
      tags: [ 'app_keycloak_config' ]
      community.general.keycloak_authentication_required_actions:
        auth_keycloak_url: "{{ app_keycloak__auth_url }}"
        auth_realm: "{{ app_keycloak__auth_realm }}"
        auth_username: "{{ app_keycloak__auth_username }}"
        auth_password: "{{ app_keycloak__auth_password }}"
        realm: "{{ realm.realm }}"
        required_actions: "{{ realm.required_actions }}"
        state: 'present'

# See: https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_user_federation_module.html
    - name: Create or update Keycloak user federation
      tags: [ 'app_keycloak_config' ]
      community.general.keycloak_user_federation:
        auth_keycloak_url: "{{ app_keycloak__auth_url }}"
        auth_realm: "{{ app_keycloak__auth_realm }}"
        auth_username: "{{ app_keycloak__auth_username }}"
        auth_password: "{{ app_keycloak__auth_password }}"
        realm: "{{ realm.realm }}"
        id: "{{ item.federation_id }}"
        name: "{{ item.federation_name }}"
        provider_id: "{{ item.provider_id | default(app_keycloak__user_federation_provider_id_default) }}"
        config: "{{ item.config }}"
        mappers: "{{ item.mappers }}"
      with_items: "{{ realm.user_federation }}"

# See: https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_client_module.html
    - name: Create or update Keycloak client
      tags: [ 'app_keycloak_config' ]
      community.general.keycloak_client:
        auth_keycloak_url: "{{ app_keycloak__auth_url }}"
        auth_realm: "{{ app_keycloak__auth_realm }}"
        auth_username: "{{ app_keycloak__auth_username }}"
        auth_password: "{{ app_keycloak__auth_password }}"
        realm: "{{ realm.realm }}"
        client_id: "{{ item.client_id }}"
        name: "{{ item.name | default(app_keycloak__client_default.name) }}"
        protocol: "{{ item.protocol | default(app_keycloak__client_default.protocol) }}"
        description: "{{ item.description | default(app_keycloak__client_default.description) }}"
        redirect_uris: "{{ item.redirect_uris }}"
        root_url: "{{ item.root_url | default(app_keycloak__client_default.root_url) }}"
        web_origins: "{{ item.web_origins }}"
      with_items: "{{ realm.clients }}"
