---

- name: Create realm user federations
  tags: [ 'app_keycloak_config' ]
  block:

# See: https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_user_federation_module.html
    - name: Create or update Keycloak user federation
      tags: [ 'app_keycloak_config' ]
      community.general.keycloak_user_federation:
        auth_keycloak_url: "{{ app_keycloak__auth_url }}"
        auth_realm: "{{ app_keycloak__auth_realm }}"
        auth_username: "{{ app_keycloak__auth_username }}"
        auth_password: "{{ app_keycloak__auth_password }}"
        realm: "{{ item.realm }}"
        id: "{{ item.federation_id }}"
        name: "{{ item.federation_name | default(app_keycloak__user_federation_default.federation_name) }}"
        provider_id: "{{ item.provider_type | default(app_keycloak__user_federation_default.provider_type) }}"
        config:
          authType: "{{ item.auth_type | default(app_keycloak__user_federation_default.auth_type) }}"
          connectionUrl: "{{ item.url | mandatory }}"
          editMode: "{{ item.edit_mode | default(app_keycloak__user_federation_default.edit_mode) }}"
          rdnLDAPAttribute: "{{ item.uid_attribute | default(app_keycloak__user_federation_default.uid_attribute) }}"
          searchScope: "{{ item.scope | default(app_keycloak__user_federation_default.scope) }}"
          trustEmail: "{{ item.trust_email | default(app_keycloak__user_federation_default.trust_email) }}"
          usernameLDAPAttribute: "{{ item.uid_attribute | default(app_keycloak__user_federation_default.uid_attribute) }}"
          userObjectClasses: "{{ item.object_classes | default(app_keycloak__user_federation_default.object_classes) }}"
          usersDn: "{{ item.user_base | default(app_keycloak__user_federation_default.user_base) }}"
          uuidLDAPAttribute: "{{ item.uuid_attribute | default(app_keycloak__user_federation_default.uuid_attribute) }}"
          vendor: "{{ item.vendor | default(app_keycloak__user_federation_default.vendor) }}"
        mappers: "{{ item.mappers }}"
      with_items: "{{ realm.user_federation }}"
