---

- name: 'Restart docspell container'
  ansible.builtin.service:
    name: "{{ item }}"
    state: 'restarted'
  loop:
    - "{{ app_docspell__rest_container.name }}"
    - "{{ app_docspell__joex_container.name }}"
  when: 'not ansible_check_mode'
