---
# tasks file for roles/avahi

- name: Install and configure avahi
  tags: [ 'avahi' ]
  when: avahi__enable
  block:

  - name: Install avahi
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ avahi__packages_combined }}"

  - name: Generate avahi-daemon.conf
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/avahi/avahi-daemon.conf.j2
      dest: /etc/avahi/avahi-daemon.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - Restart avahi

  - name: Generate services
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/avahi/services/avahi.service.j2
      dest: "/etc/avahi/services/{{ item.key }}.service"
      owner: root
      group: root
      mode: 0644
    vars:
      service_group: "{{ item.value }}"
    with_dict: "{{ avahi__services_combined }}"
    notify:
    - Restart avahi
