---

- name: 'Deploy OAuth2 Proxy container'
  tags: [ 'security_oauth2_proxy' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ security_oauth2_proxy__podman_home }}"

    - name: 'Generate simple configuration'
      ansible.builtin.template:
        src: 'oauth2-proxy.cfg.j2'
        dest: "{{ security_oauth2_proxy__podman_config_file }}"
      when: 'not podman___update_mode | bool'
      notify: 'Restart oauth2-proxy container'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ security_oauth2_proxy__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[security_oauth2_proxy__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ security_oauth2_proxy__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ security_oauth2_proxy__container.name }}"
        hostname: "{{ security_oauth2_proxy__container.hostname }}"
        image: "{{ security_oauth2_proxy__container.image }}"
        ip: "{{ security_oauth2_proxy__container.ip }}"
        network: "{{ security_oauth2_proxy__container.network }}"
        timezone: "{{ security_oauth2_proxy__container.timezone }}"
        command: "{{ security_oauth2_proxy__container.command }}"
        label: "{{ security_oauth2_proxy__container.labels }}"
        volume: "{{ security_oauth2_proxy__container.volumes }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'security_oauth2_proxy__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ security_oauth2_proxy__container.name }}"
        hostname: "{{ security_oauth2_proxy__container.hostname }}"
        image: "{{ security_oauth2_proxy__container.image }}"
        ip: "{{ security_oauth2_proxy__container.ip }}"
        ip6: "{{ security_oauth2_proxy__container.ipv6 }}"
        network: "{{ security_oauth2_proxy__container.network }}"
        timezone: "{{ security_oauth2_proxy__container.timezone }}"
        command: "{{ security_oauth2_proxy__container.command }}"
        label: "{{ security_oauth2_proxy__container.labels }}"
        volume: "{{ security_oauth2_proxy__container.volumes }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'security_oauth2_proxy__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ security_oauth2_proxy__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'
