---

#
# Substitutes - do not change
#

app_phpmyadmin__hostname: "{{ phpmyadmin_hostname | default('phpmyadmin.localhost') }}"
app_phpmyadmin__ip: "{{ phpmyadmin_ip | mandatory }}"
app_phpmyadmin__network: "{{ phpmyadmin_network | mandatory }}"

app_phpmyadmin__db_user: "{{ phpmyadmin_db_user | default('phpmyadmin') }}"
app_phpmyadmin__db_pass: "{{ phpmyadmin_db_pass | mandatory }}"
app_phpmyadmin__db_host: "{{ phpmyadmin_db_host | mandatory }}"
app_phpmyadmin__db_port: "{{ phpmyadmin_db_port | default(3306) }}"
app_phpmyadmin__base_url: "{{ phpmyadmin_base_url | mandatory }}"

app_phpmyadmin__hosts: "{{ phpmyadmin_hosts | default({}) }}"

app_phpmyadmin__container: "{{ app_phpmyadmin__container_default | combine(phpmyadmin_container | default({})) }}"

#
# Defaults - do not change
#

app_phpmyadmin__config_dir: "{{ app_phpmyadmin__home }}/www"

app_phpmyadmin__account_default:
  user: "{{ app_phpmyadmin__user }}"
  uid: "{{ app_phpmyadmin__uid }}"
  gid: "{{ app_phpmyadmin__gid }}"
  home: "{{ app_phpmyadmin__home }}"

app_phpmyadmin__container_default:
  name: phpmyadmin
  hostname: "{{ app_phpmyadmin__hostname }}"
  image: 'docker.io/phpmyadmin/phpmyadmin:latest'
  ip: "{{ app_phpmyadmin__ip }}"
  network: "{{ app_phpmyadmin__network }}"
  restart_policy: always
  environment:
    - PMA_HOST: "{{ app_phpmyadmin__db_host }}"
    - PMA_ABSOLUTE_URI: "{{ app_phpmyadmin__base_url }}"
  hosts: "{{ app_phpmyadmin__hosts }}"
