---

#
# Substitutes - do not change
#

app_phpmyadmin__hostname: "{{ phpmyadmin_hostname | default('phpmyadmin.' + dns_hostname) }}"
app_phpmyadmin__ip: "{{ phpmyadmin_ip | mandatory }}"
app_phpmyadmin__ipv6: "{{ phpmyadmin_ipv6 | mandatory }}"
app_phpmyadmin__network: "{{ phpmyadmin_network | mandatory }}"

app_phpmyadmin__db: "{{ phpmyadmin_db | default('phpmyadmin') }}"
app_phpmyadmin__db_user: "{{ phpmyadmin_db_user | default('phpmyadmin') }}"
app_phpmyadmin__db_pass: "{{ phpmyadmin_db_pass | mandatory }}"
app_phpmyadmin__db_host: "{{ phpmyadmin_db_host | mandatory }}"
app_phpmyadmin__db_port: "{{ phpmyadmin_db_port | default(3306) }}"
app_phpmyadmin__base_url: "{{ phpmyadmin_base_url | mandatory }}"

app_phpmyadmin__hosts: "{{ phpmyadmin_hosts | default({}) }}"
app_phpmyadmin__timezone: "{{ phpmyadmin_timezone | default(bootstrap_timezone__timezone) }}"

#
# Defaults - do not change
#

app_phpmyadmin__config_dir: "{{ app_phpmyadmin__home }}/www"

app_phpmyadmin__account_default:
  user: "{{ app_phpmyadmin__user }}"
  uid: "{{ app_phpmyadmin__uid }}"
  gid: "{{ app_phpmyadmin__gid }}"
  home: "{{ app_phpmyadmin__home }}"

app_phpmyadmin__podman_container: "{{ app_phpmyadmin__container_default }}"

app_phpmyadmin__container_default:
  name: phpmyadmin
  hostname: "{{ app_phpmyadmin__hostname }}"
  image: 'docker.io/phpmyadmin/phpmyadmin:latest'
  ip: "{{ app_phpmyadmin__ip }}"
  network: "{{ app_phpmyadmin__network }}"
  restart_policy: always
  environment:
    PMA_PMADB: "{{ app_phpmyadmin__db }}"
    PMA_CONTROLUSER: "{{ app_phpmyadmin__db_user }}"
    PMA_CONTROLPASS: "{{ app_phpmyadmin__db_pass }}"
    PMA_HOST: "{{ app_phpmyadmin__db_host }}"
    PMA_ABSOLUTE_URI: "{{ app_phpmyadmin__base_url }}"
  hosts: "{{ app_phpmyadmin__hosts }}"
  timezone: "{{ app_phpmyadmin__timezone }}"
