---

- name: 'Install and configure Icinga 2 master'
  tags: [ 'monitoring_icinga_master' ]
  block:

    - name: 'Install Icinga 2 master using podman'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: 'monitoring_icinga_master__use_podman'
