---

- name: Install and congfigure PHP
  tags: [ 'webserver_php' ]
  block:

    - name: Install PHP packages
      ansible.builtin.apt:
        pkg: "{{ webserver_php__packages }}"
        install_recommends: no
        state: present

    - name: Install PHP modules
      ansible.builtin.apt:
        pkg: "{{ webserver_php__modules }}"
        install_recommends: no
        state: present

    - name: Enable service
      ansible.builtin.service:
        name: "php{{ webserver_php__version }}-fpm"
        state: started
        enabled: yes
      when: not ansible_check_mode

    - name: Update configuration for php-cli
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('644') }}"
      with_items:
        - src: cli.ini.j2
          dest: "{{ webserver_php__cli_etc_dir }}/php.ini"

    - name: Update configuration for php-fpm
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('644') }}"
      with_items:
        - src: fpm.ini.j2
          dest: "{{ webserver_php__fpm_etc_dir }}/php.ini"
        - src: php-fpm.conf.j2
          dest: "{{ webserver_php__fpm_etc_dir }}/php-fpm.conf"
      notify:
        - Restart php-fpm