---

- name: Install and configure nextcloud
  tags: [ 'nextcloud' ]
  when: nextcloud__enable
  block:

  - name: Create nextcloud config directory
    tags: [ 'configuration' ]
    ansible.builtin.file:
      dest: "{{ nextcloud__etc_path }}"
      state: directory
      owner: "{{ nginx__user }}"
      group: "{{ nginx__group }}"
      mode: "{{ nginx__site_mode }}"

  - name: Create nextcloud data directory
    tags: [ 'configuration' ]
    ansible.builtin.file:
      dest: "{{ nextcloud__data_path }}"
      state: directory
      owner: "{{ nginx__user }}"
      group: "{{ nginx__group }}"
      mode: "{{ nginx__site_mode }}"

  - name: Generate configuration files
    tags: [ 'configuration' ]
    when: nextcloud__nginx_enable
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner | default('root') }}"
      group: "{{ item.group | default('root') }}"
      mode: "{{ item.mode | default('0644') }}"
      backup: "{{ item.backup | default(false) }}"
    with_items:
    - src: etc/nginx/snippets/nextcloud.conf.j2
      dest: "{{ nginx__snippets_path }}/nextcloud.conf"
    - src: etc/systemd/system/nextcloud-cron.service.j2
      dest: /etc/systemd/system/nextcloud-cron.service
    - src: etc/systemd/system/nextcloud-cron.timer.j2
      dest: /etc/systemd/system/nextcloud-cron.timer
    - src: etc/systemd/system/nextcloud-cleanup.service.j2
      dest: /etc/systemd/system/nextcloud-cleanup.service
    - src: etc/systemd/system/nextcloud-cleanup.timer.j2
      dest: /etc/systemd/system/nextcloud-cleanup.timer
    - src: etc/logrotate.d/nextcloud.j2
      dest: /etc/logrotate.d/nextcloud
    - src: etc/nextcloud/config.php.j2
      dest: "{{ nextcloud__etc_path }}/config.php"
      owner: "{{ nginx__user }}"
      group: "{{ nginx__group }}"
      mode: '0640'
      backup: true

- name: Enable nextcloud cron timer
  tags: [ 'configuration', 'service' ]
  when: not ansible_check_mode
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    daemon_reload: yes
    enabled: yes
  with_items:
  - nextcloud-cron.timer
  - nextcloud-cleanup.timer
