---

- name: Configure systemd timers
  tags: [ 'systemd_timers' ]
  block:

    - name: Create timer directorie
      ansible.builtin.file:
        mode: '755'
        path: "{{ systemd_timers__timer_dir }}"
        state: directory

    - name: Generate timer files
      ansible.builtin.template:
        src: timer.j2
        dest: "{{ systemd_timers__timer_dir }}/{{ item.name }}.timer"
        owner: root
        group: root
        mode: '644'
      with_items: "{{ systemd_timers__timers }}"
      notify:
        - Reload systemd

    - name: Force systemd reload
      meta: flush_handlers
      when: not ansible_check_mode

    - name: Enable timers
      ansible.builtin.systemd:
        name: "{{ item.name }}.timer"
        enabled: "{{ item.enabled | ternary('yes', 'no') }}"
      with_items: "{{ systemd_timers__timers | selectattr('enabled', 'defined') | list }}"
      when: not ansible_check_mode
