---
# tasks file for roles/php

- name: Install and congfigure PHP
  tags: [ 'php' ]
  when: php__enable
  block:

  - name: Install PHP packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ php__packages_combined }}"

  - name: Enable service
    tags: [ 'configuration', 'service' ]
    when: php__flavor == 'fpm'
    ansible.builtin.service:
      name: "php{{ php__version }}-fpm"
      state: started
      enabled: yes
