---
# tasks file for roles/php

- name: Install PHP packages
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ php__packages_combined }}"
  tags:
  - php
  - packages
