---
# tasks file for roles/php

- name: Install and congfigure PHP
  tags: [ 'php' ]
  block:

  - name: Install PHP packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ php__packages_combined }}"
