---
# tasks file for roles/php

- name: Install and congfigure PHP
  tags: [ 'php' ]
  when: php__enable
  block:

  - name: Install PHP packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ php__packages_combined }}"

  - name: Generate configuration for PHP-FPM
    tags: [ 'configuration', 'php' ]
    when: php__flavor == 'fpm'
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: php.ini.j2
      dest: "{{ php__etc_dir }}/{{ php__version }}/fpm/php.ini"
    - src: php-fpm.conf.j2
      dest: "{{ php__etc_dir }}/{{ php__version }}/fpm/php-fpm.conf"
    notify:
    - Restart PHP-FPM

  - name: Generate pool configurations for PHP-FPM
    tags: [ 'configuration', 'php' ]
    when: php__flavor == 'fpm'
    ansible.builtin.template:
      src: pool.d/pool.conf.j2
      dest: "{{ php__etc_dir }}/{{ php__version }}/fpm/pool.d/{{ item.key }}.conf"
      owner: root
      group: root
      mode: 0644
    vars:
      pool: "{{ item.key }}"
      config: "{{ item.value }}"
    with_dict: "{{ php__fpm_pools_combined }}"
    notify:
    - Restart PHP-FPM

  - name: Enable service
    tags: [ 'configuration', 'service' ]
    when: php__flavor == 'fpm' and not ansible_check_mode
    ansible.builtin.service:
      name: "php{{ php__version }}-fpm"
      state: started
      enabled: yes
