---

- name: Restart NFS server
  tags: [ 'service' ]
  when: not ansible_check_mode
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - rpcbind
  - nfs-server
  - nfs-mountd
  - nfs-idmapd
