---

- name: Deploy GitLab CE container
  tags: [ 'app_gitlab_ce' ]
  block:

    - name: Create directories for GitLab CE
      ansible.builtin.file:
        path: "{{ item }}"
        owner: root
        group: root
        state: directory
      with_items:
        - "{{ app_gitlab_ce__data_dir }}"
        - "{{ app_gitlab_ce__logs_dir }}"
        - "{{ app_gitlab_ce__config_dir }}"
        - "{{ app_gitlab_ce__config_dir }}/trusted-certs"

    - name: Create GitLab CE configuration
      ansible.builtin.template:
        src: gitlab.rb.j2
        dest: "{{ app_gitlab_ce__config_dir }}/gitlab.rb"
        owner: root
        group: root
        mode: '640'

    - name: Copy SSL CA into containers
      ansible.builtin.copy:
        src: "{{ pki_easyrsa_deploy__ca_certificates_file }}"
        dest: "{{ app_gitlab_ce__config_dir }}/trusted-certs/{{ pki_easyrsa_deploy__ca_name }}.crt"
        remote_src: yes

    - name: Deploy GitLab CE container via podman
      ansible.builtin.import_role:
        name: podman
      vars:
        pod_containers:
          - "{{ app_gitlab_ce__container }}"
