---

#
# Substitutes - do not change
#

app_pgadmin__hostname: "{{ pgadmin_hostname | default('pgadmin.' + dns_hostname) }}"
app_pgadmin__ip: "{{ pgadmin_ip | mandatory }}"
app_pgadmin__ipv6: "{{ pgadmin_ipv6 | default('') }}"
app_pgadmin__network: "{{ pgadmin_network | mandatory }}"
app_pgadmin__hosts: "{{ pgadmin_hosts | default({}) }}"
app_pgadmin__timezone: "{{ pgadmin_timezone | default(bootstrap_timezone__timezone) }}"

app_pgadmin__user: "{{ pgadmin_user | mandatory }}"
app_pgadmin__pass: "{{ pgadmin_pass | mandatory }}"

app_pgadmin__version: "{{ pgadmin_version | default('latest') }}"
app_pgadmin__container: "{{ app_pgadmin__podman_container_default }}"

#
# Defaults - do not change
#

app_pgadmin__podman_image: 'docker.io/dpage/pgadmin4'

app_pgadmin__podman_container_default:
  name: 'pgadmin'
  hostname: "{{ app_pgadmin__hostname }}"
  image: "{{ app_pgadmin__podman_image }}:{{ app_pgadmin__version }}"
  ip: "{{ app_pgadmin__ip }}"
  ipv6: "{{ app_pgadmin__ipv6 }}"
  network: "{{ app_pgadmin__network }}"
  restart_policy: 'always'
  hosts: "{{ app_pgadmin__hosts }}"
  environment:
    PGADMIN_DEFAULT_EMAIL: "{{ app_pgadmin__user }}"
    PGADMIN_DEFAULT_PASSWORD: "{{ app_pgadmin__pass }}"
  timezone: "{{ app_pgadmin__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
