---

- name: Configure MySQL/MariaDB backup
  tags: [ 'backup_mysql'  ]
  block:

    - name: Install MySQL/MariaDB packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ backup_mysql__packages }}"

    - name: Copy MySQL/MariaDB backup scripts to host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup_common__lib_dir }}/{{ item }}"
        mode: '755'
      with_items: "{{ backup_mysql__files }}"

    - name: Generate MySQL/MariaDB backup configuration file
      ansible.builtin.template:
        src: mysql.j2
        dest: "{{ backup_common__etc_dir }}/mysql"
        owner: root
        group: root
        mode: '640'

    - name: Create MySQL/MariaDB backup directory
      ansible.builtin.file:
        mode: '750'
        owner: root
        group: root
        path: "{{ backup_mysql__backup_dir }}"
        state: directory

    - name: Configure database backup user with privileges
      community.mysql.mysql_user:
        login_user: "{{ backup_mysql__login_user }}"
        login_password: "{{ backup_mysql__login_password }}"
        login_host: "{{ backup_mysql__host }}"
        name: "{{ backup_mysql__user }}"
        host: "{{ backup_mysql__user_host }}"
        password: "{{ backup_mysql__password }}"
        priv: "{{ backup_mysql__privileges }}"
        state: present
