---

- name: Restart MariaDB service
  ansible.builtin.service:
    name: 'mariadb'
    state: 'restarted'
  when: not ansible_check_mode and not database_mariadb__use_podman

- name: Restart MariaDB container
  ansible.builtin.shell: 'podman restart mariadb'
  when: not ansible_check_mode and database_mariadb__use_podman
