---

- name: 'Restart Telegraf container'
  ansible.builtin.service:
    name: "{{ monitoring_telegraf__container.name }}"
    state: 'restarted'
  when: 'not ansible_check_mode'

- name: 'Restart Telegraf service'
  ansible.builtin.service:
    name: 'telegraf'
    state: 'restarted'
  when: 'not ansible_check_mode'
