---

- name: Configure systemd services
  tags: [ 'systemd_services' ]
  block:

    - name: Generate service files
      ansible.builtin.template:
        src: service.j2
        dest: "{{ systemd_services__system_dir }}/{{ item.name }}.service"
        owner: root
        group: root
        mode: 0644
      with_items: "{{ systemd_services__services }}"
      notify:
        - Reload systemd

    - name: Force systemd reload
      meta: flush_handlers
      when: not ansible_check_mode

    - name: Enable services
      ansible.builtin.systemd:
        name: "{{ item.name }}.service"
        enabled: "{{ item.enabled | ternary('yes', 'no') }}"
      with_items: "{{ systemd_services__services | selectattr('enabled', 'defined') | list }}"
