---

#
# Substitutes - do not change
#

matrix_synapse__hostname: "{{ matrix_hostname | default('matrix.' + dns_hostname) }}"
matrix_synapse__ip: "{{ matrix_ip | mandatory }}"
matrix_synapse__ipv6: "{{ matrix_ipv6 | default('') }}"
matrix_synapse__network: "{{ matrix_network | mandatory }}"
matrix_synapse__hosts: "{{ matrix_hosts | default({}) }}"
matrix_synapse__timezone: "{{ matrix_timezone | default(bootstrap_timezone__timezone) }}"
matrix_synapse__home: "{{ matrix_home | mandatory }}"

matrix_synapse__server_name: "{{ matrix_server_name | mandatory }}"
matrix_synapse__report_stats: "{{ matrix_report_stats | default(true) }}"
matrix_synapse__http_port: "{{ matrix_http_port | default(8008) }}"
matrix_synapse__db_type: "{{ matrix_db_type | default('sqlite') }}"
matrix_synapse__db_name: "{{ matrix_db_name | default('synapse') }}"
matrix_synapse__db_user: "{{ matrix_db_user | default('synapse') }}"
matrix_synapse__db_pass: "{{ matrix_db_pass | default('') }}"
matrix_synapse__db_host: "{{ matrix_db_host | default('') }}"
matrix_synapse__db_port: "{{ matrix_db_port | default(5432) }}"
matrix_synapse__dns_servers: "{{ matrix_dns_servers | default([]) }}"

matrix_synapse__setup: "{{ matrix_setup | default(true) }}"

matrix_synapse__version: "{{ matrix_version | default('latest') }}"
matrix_synapse__container: "{{ matrix_synapse__podman_container_default }}"

#
# Defaults - do not change
#

matrix_synapse__data_dir: "{{ matrix_synapse__home }}/data"

matrix_synapse__uid: 991
matrix_synapse__gid: 991

matrix_synapse__podman_image: 'docker.io/matrixdotorg/synapse'

matrix_synapse__podman_environment: "{{ matrix_synapse__podman_database_flavor[matrix_synapse__db_type] | combine(matrix_synapse__podman_environment_default) }}"

matrix_synapse__podman_database_flavor:
  sqlite: {}
  postgresql:
    POSTGRES_HOST: "{{ matrix_synapse__db_host }}"
    POSTGRES_PORT: "{{ matrix_synapse__db_port }}"
    POSTGRES_DB: "{{ matrix_synapse__db_name }}"
    POSTGRES_USER: "{{ matrix_synapse__db_user }}"
    POSTGRES_PASSWORD: "{{ matrix_synapse__db_pass }}"

matrix_synapse__podman_environment_default:
    SYNAPSE_SERVER_NAME: "{{ matrix_synapse__server_name }}"
    SYNAPSE_REPORT_STATS:  "{{ matrix_synapse__report_stats | ternary('yes', 'no') }}"
    SYNAPSE_HTTP_PORT: "{{ matrix_synapse__http_port }}"
    UID: "{{ matrix_synapse__uid }}"
    GID: "{{ matrix_synapse__gid }}"
    TZ: "{{ matrix_synapse__timezone }}"

matrix_synapse__podman_container_default:
  name: 'matrix'
  hostname: "{{ matrix_synapse__hostname }}"
  image: "{{ matrix_synapse__podman_image }}:{{ matrix_synapse__version }}"
  ip: "{{ matrix_synapse__ip }}"
  ipv6: "{{ matrix_synapse__ipv6 }}"
  network: "{{ matrix_synapse__network }}"
  restart_policy: 'always'
  hosts: "{{ matrix_synapse__hosts }}"
  dns_servers: "{{ matrix_synapse__dns_servers }}"
  environment: "{{ matrix_synapse__podman_environment }}"
  timezone: "{{ matrix_synapse__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - "{{ matrix_synapse__data_dir }}:/data"
