---

webserver_traefik__home: "{{ traefik_home | mandatory }}"
webserver_traefik__ip: "{{ traefik_ip | mandatory }}"
webserver_traefik__ipv6: "{{ traefik_ipv6 | default('') }}"
webserver_traefik__network: "{{ traefik_network | mandatory }}"
webserver_traefik__hostname: "{{ traefik_hostname | mandatory }}"
webserver_traefik__timezone: "{{ traefik_timezone | mandatory }}"
webserver_traefik__labels: "{{ traefik_labels | default({}) }}"

webserver_traefik__config: "{{ traefik_config | default({}) }}"
webserver_traefik__dynamic: "{{ traefik_dynamic | default({}) }}"

webserver_traefik__api_dashboard: "{{ traefik_api_dashboard | default(false) }}"
webserver_traefik__api_insecure: "{{ traefik_api_insecure | default(false) }}"
webserver_traefik__api_debug: "{{ traefik_api_debug | default(false) }}"

webserver_traefik__entrypoint_web_port: "{{ traefik_entrypoint_web_port | default(80) }}"
webserver_traefik__entrypoint_websecure_port: "{{ traefik_entrypoint_websecure_port | default(443) }}"
webserver_traefik__entrypoint_web_redirect_to_https: "{{ traefik_entrypoint_web_redirect_to_https | default(true) }}"

webserver_traefik__serverstransport_insecure_skip_verify: "{{ traefik_serverstransport_insecure_skip_verify | default(false) }}"

webserver_traefik__log_level: "{{ traefik_log_level | default('WARN') }}"

webserver_traefik__providers_docker: "{{ traefik_providers_docker | default(true) }}"
webserver_traefik__docker_socket: "{{ traefik_docker_socket | default('/var/run/docker.sock') }}"

webserver_traefik__container: "{{ webserver_traefik__podman_container_default | combine(traefik_container | default({})) }}"

#
# podman defaults
#

webserver_traefik__podman_name: 'traefik'
webserver_traefik__podman_image: 'docker.io/traefik'
webserver_traefik__podman_version: 'v3'

webserver_traefik__podman_home: "{{ webserver_traefik__home }}"
webserver_traefik__podman_config_dir: "{{ webserver_traefik__podman_home }}/dynamic"
webserver_traefik__podman_config_file: "{{ webserver_traefik__podman_home }}/traefik.yml"
webserver_traefik__podman_acme_file: "{{ webserver_traefik__podman_home }}/acme.json"

webserver_traefik__podman_container_default:
  name: "{{ webserver_traefik__podman_name }}"
  hostname: "{{ webserver_traefik__hostname }}"
  image: "{{ webserver_traefik__podman_image }}:{{ webserver_traefik__podman_version }}"
  ip: "{{ webserver_traefik__ip }}"
  ipv6: "{{ webserver_traefik__ipv6 }}"
  network: "{{ webserver_traefik__network }}"
  timezone: "{{ webserver_traefik__timezone }}"
  labels: "{{ webserver_traefik__labels }}"
  publish:
    - '80:80'
    - '[::]:80:80'
    - '443:443'
    - '[::]:443:443'
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - "{{ webserver_traefik__podman_config_dir }}:/etc/traefik/dynamic:ro"
    - "{{ webserver_traefik__podman_config_file }}:/etc/traefik/traefik.yml:ro"
    - "{{ webserver_traefik__podman_acme_file }}:/etc/traefik/acme.json"
  restart_policy: 'always'
