---

#
# Substitutes - do not change
#

app_rediscommander__hostname: "{{ rediscommander_hostname | default('rediscommander.' + dns_hostname) }}"
app_rediscommander__ip: "{{ rediscommander_ip | mandatory }}"
app_rediscommander__ipv6: "{{ rediscommander_ipv6 | default('') }}"
app_rediscommander__network: "{{ rediscommander_network | mandatory }}"
app_rediscommander__version: "{{ rediscommander_version | default('latest') }}"

app_rediscommander__base_url: "{{ rediscommander_base_url | default('') }}"
app_rediscommander__redis_hosts: "{{ rediscommander_redis_hosts | mandatory }}"

app_rediscommander__hosts: "{{ rediscommander_hosts | default({}) }}"
app_rediscommander__timezone: "{{ rediscommander_timezone | default(bootstrap_timezone__timezone) }}"

#
# Defaults - do not change
#

app_rediscommander__port: 8081

app_rediscommander__podman_image: 'ghcr.io/joeferner/redis-commander'

app_rediscommander__podman_container: "{{ app_rediscommander__container_default }}"

app_rediscommander__container_default:
  name: 'rediscommander'
  hostname: "{{ app_rediscommander__hostname }}"
  image: "{{ app_rediscommander__podman_image }}:{{ app_rediscommander__version }}"
  ip: "{{ app_rediscommander__ip }}"
  network: "{{ app_rediscommander__network }}"
  restart_policy: 'always'
  hosts: "{{ app_rediscommander__hosts }}"
  environment:
    URL_PREFIX: "{{ app_rediscommander__base_url }}"
    REDIS_HOSTS: "{{ app_rediscommander__redis_hosts | join(',') }}"
    TZ: "{{ app_rediscommander__timezone }}"
  timezone: "{{ app_rediscommander__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
