---

#
# Substitutes - do not change
#

webserver_anubis__home: "{{ anubis_home | mandatory }}"
webserver_anubis__hostname: "{{ anubis_hostname | default('anubis.' + dns_hostname) }}"
webserver_anubis__ip: "{{ anubis_ip | mandatory }}"
webserver_anubis__network: "{{ anubis_network | mandatory }}"
webserver_anubis__version: "{{ anubis_version | default('latest') }}"

webserver_anubis__hosts: "{{ anubis_hosts | default({}) }}"
webserver_anubis__environment: "{{ anubis_environment | default(webserver_anubis__environment_default) }}"
webserver_anubis__publish: "{{ anubis_publish | default([]) }}"
webserver_anubis__timezone: "{{ anubis_timezone | default(bootstrap_timezone__timezone) }}"

webserver_anubis__containers: "{{ anubis_containers | default([]) }}"
webserver_anubis__container: "{{ anubis_container | default(webserver_anubis__container_default) }}"

webserver_anubis__port: "{{ anubis_port | default(8923) }}"
webserver_anubis__bind: "{{ anubis_bind | default(':' + webserver_anubis__port) }}"
webserver_anubis__bind_network: "{{ anubis_bind_network | default('tcp') }}"
webserver_anubis__cookie_domain: "{{ anubis_cookie_domain | default('') }}"
webserver_anubis__cookie_dynamic_domain: "{{ anubis_cookie_dynamic_domain | default(false) }}"
webserver_anubis__ed25519_private_key_hex: "{{ anubis_ed25519_private_key_hex | default('') }}"
webserver_anubis__ed25519_private_key_hex_file: "{{ anubis_ed25519_private_key_hex_file | default('') }}"
webserver_anubis__policy_fname: "{{ anubis_policy_fname | default('/data/cfg/botPolicies.yaml') }}"
webserver_anubis__redirect_domains: "{{ anubis_redirect_domains | default([]) }}"
webserver_anubis__serve_robots_txt: "{{ anubis_serve_robots_txt | default(false) }}"
webserver_anubis__socket_mode: "{{ anubis_socket_mode | default('0770') }}"
webserver_anubis__strip_base_prefix: "{{ anubis_strip_base_prefix | default(false) }}"
webserver_anubis__target: "{{ anubis_target | mandatory }}"
webserver_anubis__webmaster_email: "{{ anubis_webmaster_email | default('') }}"
webserver_anubis__xff_strip_private: "{{ anubis_xff_strip_private | default(true) }}"

#
# Defaults - do not change
#

webserver_anubis__name: 'anubis'
webserver_anubis__image: 'ghcr.io/techarohq/anubis'

webserver_anubis__environment_default:
  BIND: "{{ webserver_anubis__bind }}"
  BIND_NETWORK: "{{ webserver_anubis__bind_network }}"
  COOKIE_DYNAMIC_DOMAIN: "{{ webserver_anubis__cookie_dynamic_domain | ternary('true', 'false') }}"
  POLICY_FNAME: "{{ webserver_anubis__policy_fname }}"
  REDIRECT_DOMAINS: "{{ webserver_anubis__redirect_domains | join(',') }}"
  SERVE_ROBOTS_TXT: "{{ webserver_anubis__serve_robots_txt | ternary('true', 'false') }}"
  SOCKET_MODE: "{{ webserver_anubis__socket_mode }}"
  STRIP_BASE_PREFIX: "{{ webserver_anubis__strip_base_prefix | ternary('true', 'false') }}"
  TARGET: "{{ webserver_anubis__target }}"
  XFF_STRIP_PRIVATE: "{{ webserver_anubis__xff_strip_private | ternary('true', 'false') }}"

webserver_anubis__container_default:
  name: "{{ webserver_anubis__name }}"
  hostname: "{{ webserver_anubis__hostname }}"
  image: "{{ webserver_anubis__image }}:{{ webserver_anubis__version }}"
  ip: "{{ webserver_anubis__ip }}"
  network: "{{ webserver_anubis__network }}"
  restart_policy: 'unless-stopped'
  hosts: "{{ webserver_anubis__hosts }}"
  environment: "{{ webserver_anubis__environment }}"
  timezone: "{{ webserver_anubis__timezone }}"
  volumes:
    - "{{ webserver_anubis__home }}:/data/cfg:ro"
