---

#
# Substitutes - do not change
#

app_nextcloud__hostname: "{{ nextcloud_hostname | default('nextcloud.' + dns_hostname) }}"
app_nextcloud__ip: "{{ nextcloud_ip | mandatory }}"
app_nextcloud__ipv6: "{{ nextcloud_ipv6 | default('') }}"
app_nextcloud__network: "{{ nextcloud_network | mandatory }}"
app_nextcloud__version: "{{ nextcloud_version | default('latest') }}"

app_nextcloud__hosts: "{{ nextcloud_hosts | default({}) }}"
app_nextcloud__environment: "{{ nextcloud_environment | default({}) }}"
app_nextcloud__publish: "{{ nextcloud_publish | default([]) }}"
app_nextcloud__timezone: "{{ nextcloud_timezone | default(bootstrap_timezone__timezone) }}"

app_nextcloud__home: "{{ nextcloud_home | mandatory }}"

app_nextcloud__container: "{{ app_nextcloud__container_default | combine(nextcloud_container | default({})) }}"

app_nextcloud__user: "{{ nextcloud_user | default('nextcloud') }}"
app_nextcloud__group: "{{ nextcloud_group | default(app_nextcloud__user) }}"
app_nextcloud__uid: "{{ nextcloud_uid | mandatory }}"
app_nextcloud__gid: "{{ nextcloud_gid | default(app_nextcloud__uid) }}"

app_nextcloud__admin_user: "{{ nextcloud_admin_user | default('admin') }}"
app_nextcloud__admin_pass: "{{ nextcloud_admin_pass | mandatory }}"

app_nextcloud__trusted_domains: "{{ nextcloud_trusted_domains | mandatory }}"
app_nextcloud__cli_url: "{{ nextcloud_cli_url | mandatory }}"
app_nextcloud__db: "{{ nextcloud_db | default('nextcloud') }}"
app_nextcloud__db_type: "{{ nextcloud_db_type | default('mysql') }}"
app_nextcloud__db_user: "{{ nextcloud_db_user | default('nextcloud') }}"
app_nextcloud__db_pass: "{{ nextcloud_db_pass | mandatory }}"
app_nextcloud__db_host: "{{ nextcloud_db_host | mandatory }}"
app_nextcloud__db_port: "{{ nextcloud_db_port | default(3306) }}"
app_nextcloud__db_tableprefix: "{{ nextcloud_db_tableprefix | default('oc_') }}"
app_nextcloud__db_mysql_utf8mb4: "{{ nextcloud_db_mysql_utf8mb4 | default(true) }}"

app_nextcloud__mail_from_address: "{{ nextcloud_mail_from_address | default('no-reply') }}"
app_nextcloud__mail_smtpmode: "{{ nextcloud_mail_smtpmode | default('smtp') }}"
app_nextcloud__mail_sendmailmode: "{{ nextcloud_mail_sendmailmode | default('smtp') }}"
app_nextcloud__mail_domain: "{{ nextcloud_mail_domain | mandatory }}"
app_nextcloud__mail_smtphost: "{{ nextcloud_mail_smtphost | mandatory }}"
app_nextcloud__mail_smtpport: "{{ nextcloud_mail_smtpport | default(25) }}"
app_nextcloud__mail_smtpsecure: "{{ nextcloud_mail_smtpsecure | default('ssl') }}"

app_nextcloud__memcache_local: "{{ nextcloud_memcache_local | default(true) }}"
app_nextcloud__memcache_redis: "{{ nextcloud_memcache_redis | default(false) }}"
app_nextcloud__memcache_redis_host: "{{ nextcloud_memcache_redis_host | default('localhost') }}"
app_nextcloud__memcache_redis_port: "{{ nextcloud_memcache_redis_port | default(6379) }}"

app_nextcloud__default_phone_region: "{{ nextcloud_default_phone_region | default('') }}"
app_nextcloud__lost_password_link: "{{ nextcloud_lost_password_link | default('') }}"

#
# Defaults - do not change
#

app_nextcloud__config_dir: "{{ app_nextcloud__home }}/config"
app_nextcloud__data_dir: "{{ app_nextcloud__home }}/data"

app_nextcloud__container_default:
  name: 'nextcloud'
  hostname: "{{ app_nextcloud__hostname }}"
  image: "lscr.io/linuxserver/nextcloud:{{ app_nextcloud__version }}"
  ip: "{{ app_nextcloud__ip }}"
  network: "{{ app_nextcloud__network }}"
  restart_policy: 'always'
  environment:
    PUID: "{{ app_nextcloud__uid }}"
    PGID: "{{ app_nextcloud__gid }}"
    TZ: "{{ app_nextcloud__timezone }}"
  volumes:
    - "{{ app_nextcloud__home }}/config:/config"
    - "{{ app_nextcloud__home }}/data:/data"
    - '/usr/local/share/ca-certificates:/usr/local/share/ca-certificates'
  hosts: "{{ app_nextcloud__hosts }}"
  timezone: "{{ app_nextcloud__timezone }}"
