---

- name: 'Deploy Renovate container'
  tags: [ 'app_renovate' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ item.uid | default('root') }}"
        group: "{{ item.gid | default('root') }}"
        mode: "{{ item.mode | default('0700') }}"
        state: 'directory'
      with_items:
        - dest: "{{ app_renovate__podman_home }}"
        - dest: "{{ app_renovate__podman_home }}/cache"
          uid: "12021"

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: "{{ item.name }}"
        data: "{{ item.data }}"
      with_items:
        - name: 'renovate_token'
          data: "{{ app_renovate__token }}"
        - name: 'renovate_github_token'
          data: "{{ app_renovate__github_token }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_renovate__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_renovate__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_renovate__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name:  'Install container'
      containers.podman.podman_container:
        name: "{{ app_renovate__container.name }}"
        hostname: "{{ app_renovate__container.hostname }}"
        image: "{{ app_renovate__container.image }}"
        ip: "{{ app_renovate__container.ip }}"
        network: "{{ app_renovate__container.network }}"
        timezone: "{{ app_renovate__container.timezone }}"
        env: "{{ app_renovate__container.environment }}"
        secrets: "{{ app_renovate__container.secrets }}"
        volume: "{{ app_renovate__container.volumes }}"
        command: |
          /bin/sh -c 'while true; do renovate; sleep {{ app_renovate__interval }}; done'
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_renovate__ipv6 | length == 0'

    - name:  'Install container'
      containers.podman.podman_container:
        name: "{{ app_renovate__container.name }}"
        hostname: "{{ app_renovate__container.hostname }}"
        image: "{{ app_renovate__container.image }}"
        ip: "{{ app_renovate__container.ip }}"
        ip6: "{{ app_renovate__container.ipv6 }}"
        network: "{{ app_renovate__container.network }}"
        timezone: "{{ app_renovate__container.timezone }}"
        env: "{{ app_renovate__container.environment }}"
        secrets: "{{ app_renovate__container.secrets }}"
        volume: "{{ app_renovate__container.volumes }}"
        command: |
          /bin/sh -c 'while true; do renovate; sleep {{ app_renovate__interval }}; done'
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_renovate__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_renovate__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'app_renovate__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ app_renovate__container.name }}"
        container_image: "{{ app_renovate__container.image }}"
