---

- name: Deploy nextcloud container
  tags: [ 'app_nextcloud' ]
  block:

    - name: Ensure group "nextcloud" exists with correct gid
      ansible.builtin.group:
        name: "{{ app_nextcloud__group }}"
        state: 'present'
        gid: "{{ app_nextcloud__gid }}"

    - name: Ensure user "nextcloud" exists with correct uid
      ansible.builtin.user:
        name: "{{ app_nextcloud__user }}"
        state: 'present'
        uid: "{{ app_nextcloud__uid }}"
        group: "{{ app_nextcloud__group }}"

    - name: Create nextcloud directories
      ansible.builtin.file:
        mode: '750'
        path: "{{ item }}"
        owner: "{{ app_nextcloud__user }}"
        group: "{{ app_nextcloud__group }}"
        state: 'directory'
      with_items:
        - "{{ app_nextcloud__config_dir }}"
        - "{{ app_nextcloud__config_dir }}/www/nextcloud/config"
        - "{{ app_nextcloud__data_dir }}"

    - name: Create podman containers
      containers.podman.podman_container:
        name: "{{ app_nextcloud__container.name }}"
        hostname: "{{ app_nextcloud__container.hostname }}"
        image: "{{ app_nextcloud__container.image }}"
        ip: "{{ app_nextcloud__container.ip }}"
        network: "{{ app_nextcloud__container.network }}"
        restart_policy: "{{ app_nextcloud__container.restart_policy }}"
        env: "{{ app_nextcloud__container.environment }}"
        volume: "{{ app_nextcloud__container.volumes }}"
        etc_hosts: "{{ app_nextcloud__container.hosts }}"
        timezone: "{{ app_nextcloud__container.timezone }}"
      when: app_nextcloud__ipv6 | length == 0

    - name: Update CA certificates
      ansible.builtin.shell: "podman exec -it {{ app_nextcloud__container.name }} update-ca-certificates"
