---

#
# Substitutes - do not change
#

database_mariadb__accounts: "{{ mariadb_accounts | default ([]) }}"
database_mariadb__databases: "{{ mariadb_databases | default ([]) }}"
database_mariadb__password: "{{ mariadb_password_list | mandatory }}"

database_mariadb__use_podman: "{{ mariadb_use_podman | default(true) }}"

database_mariadb__hostname: "{{ mariadb_hostname | default('mariadb.localhost') }}"
database_mariadb__ip: "{{ mariadb_ip | mandatory }}"
database_mariadb__ipv6: "{{ mariadb_ipv6 | default('') }}"
database_mariadb__network: "{{ mariadb_network | mandatory }}"
database_mariadb__hosts: "{{ mariadb_hosts | default({}) }}"
database_mariadb__time_zone: "{{ mariadb_timezone | default(bootstrap_timezone__timezone) }}"
database_mariadb__uid: "{{ mariadb_uid | mandatory }}"
database_mariadb__gid: "{{ mariadb_gid | mandatory }}"
database_mariadb__home: "{{ mariadb_home | mandatory }}"
database_mariadb__root_pass: "{{ vault__mariadb_password_list[database_mariadb__hostname]['root'] }}"

database_mariadb__port: "{{ mariadb_port | default(3306) }}"
database_mariadb__socket: "{{ mariadb_socket | default( database_mariadb__run_dir + '/mysqld.sock') }}"
database_mariadb__default_character_set: "{{ mariadb_character_set | default('utf8mb4') }}"
database_mariadb__nice: "{{ mariadb_nice | default(0) }}"
database_mariadb__user: "{{ mariadb_user | default('abc' if database_mariadb__use_podman else 'mysql') }}"
database_mariadb__pid_file: "{{ mariadb_pid_file | default( database_mariadb__run_dir + '/mysqld.pid') }}"
database_mariadb__lc_messages: "{{ mariadb_lc | default('en_US') }}"
database_mariadb__skip_external_locking: "{{ mariadb_skip_external_locking | default(true) }}"
database_mariadb__bind_address: "{{ mariadb_bind_address | default(database_mariadb__ip if database_mariadb__use_podman else '127.0.0.1') }}"

database_mariadb__key_buffer_size: "{{ mariadb_key_buffer_size | default('128M') }}"
database_mariadb__max_connections: "{{ mariadb_max_connections | default(100) }}"
database_mariadb__connect_timeout: "{{ mariadb_connect_timeout | default(5) }}"
database_mariadb__wait_timeout: "{{ mariadb_wait_timeout | default(600) }}"
database_mariadb__max_allowed_packet: "{{ mariadb_max_allowed_packet | default('16M') }}"
database_mariadb__thread_cache_size: "{{ mariadb_thread_cache_size | default(128) }}"
database_mariadb__thread_stack: "{{ mariadb_thread_stack | default('192K') }}"
database_mariadb__sort_buffer_size: "{{ mariadb_sort_buffer_size | default('4M') }}"
database_mariadb__bulk_insert_buffer_size: "{{ mariadb_bulk_insert_buffer_size | default('16M') }}"
database_mariadb__tmp_table_size: "{{ mariadb_tmp_table_size | default('32M') }}"
database_mariadb__max_heap_table_size: "{{ mariadb_max_heap_table_size | default('32M') }}"
database_mariadb__performance_schema: "{{ mariadb_performance_schema | default(false) }}"
database_mariadb__character_set_server: "{{ mariadb_character_set_server | default('utf8mb4') }}"
database_mariadb__collation_server: "{{ mariadb_collation_server | default('utf8mb4_general_ci') }}"
database_mariadb__transaction_isolation: "{{ mariadb_transaction_isolation | default('READ-COMMITTED') }}"
database_mariadb__binlog_format: "{{ mariadb_binlog_format | default('MIXED') }}"

database_mariadb__myisam_recover_options: "{{ mariadb_myisam_recover_options | default('BACKUP') }}"
database_mariadb__open_files_limit: "{{ mariadb_open_files_limit | default(2000) }}"
database_mariadb__table_open_cache: "{{ mariadb_table_open_cache | default(400) }}"
database_mariadb__table_cache: "{{ mariadb_table_cache | default(64) }}"
database_mariadb__thread_concurrency: "{{ mariadb_thread_concurrency | default(10) }}"
database_mariadb__myisam_sort_buffer_size: "{{ mariadb_myisam_sort_buffer_size | default('512M') }}"
database_mariadb__concurrent_insert: "{{ mariadb_concurrent_insert | default(2) }}"
database_mariadb__read_buffer_size: "{{ mariadb_read_buffer_size | default('2M') }}"
database_mariadb__read_rnd_buffer_size: "{{ mariadb_read_rnd_buffer_size | default('1M') }}"

database_mariadb__query_cache_limit: "{{ mariadb_query_cache_limit | default('128K') }}"
database_mariadb__query_cache_size: "{{ mariadb_query_cache_size | default('64M') }}"
database_mariadb__query_cache_type: "{{ mariadb_query_cache_type | default('DEMAND') }}"

database_mariadb__console: "{{ mariadb_console | default(true) }}"
database_mariadb__general_log: "{{ mariadb_general_log | default(false) }}"
database_mariadb__general_log_file: "{{ mariadb_general_log_file | default(database_mariadb__log_dir + '/mysql.log') }}"
database_mariadb__log_warnings: "{{ mariadb_log_warnings | default(2) }}"
database_mariadb__log_error: "{{ mariadb_log_error | default(database_mariadb__log_dir + '/mysql.log') }}"
database_mariadb__slow_query_log: "{{ mariadb_slow_query_log | default(true) }}"
database_mariadb__slow_query_log_file: "{{ mariadb_slow_query_log_file | default(database_mariadb__log_dir + '/mariadb-slow.log') }}"
database_mariadb__long_query_time: "{{ mariadb_long_query_time | default(5) }}"
database_mariadb__log_slow_rate_limit: "{{ mariadb_log_slow_rate_limit | default(1000) }}"
database_mariadb__log_queries_not_using_indexes: "{{ mariadb_log_queries_not_using_indexes | default(false) }}"
database_mariadb__log_slow_admin_statements: "{{ mariadb_log_slow_admin_statements | default(false) }}"

database_mariadb__log_bin: "{{ mariadb_log_bin | default(database_mariadb__log_dir + '/mariadb-bin') }}"
database_mariadb__log_bin_index: "{{ mariadb_log_bin_index | default(database_mariadb__log_dir + '/mariadb-bin.index') }}"
database_mariadb__expire_logs_days: "{{ mariadb_expire_logs_days | default(10) }}"
database_mariadb__max_binlog_size: "{{ mariadb_max_binlog_size | default('100M') }}"
database_mariadb__sql_mode: "{{ mariadb_sql_mode | default(['STRICT_TRANS_TABLES', 'ERROR_FOR_DIVISION_BY_ZERO', 'NO_AUTO_CREATE_USER', 'NO_ENGINE_SUBSTITUTION']) }}"

database_mariadb__default_storage_engine: "{{ mariadb_default_storage_engine | default('InnoDB') }}"
database_mariadb__innodb_log_file_size: "{{ mariadb_innodb_log_file_size | default('100M') }}"
database_mariadb__innodb_buffer_pool_size: "{{ mariadb_innodb_buffer_pool_size | default('256M') }}"
database_mariadb__innodb_log_buffer_size: "{{ mariadb_innodb_log_buffer_size | default('8M') }}"
database_mariadb__innodb_file_per_table: "{{ mariadb_innodb_file_per_table | default(1) }}"
database_mariadb__innodb_open_files: "{{ mariadb_innodb_open_files | default(400) }}"
database_mariadb__innodb_io_capacity: "{{ mariadb_innodb_io_capacity | default(400) }}"
database_mariadb__innodb_flush_method: "{{ mariadb_innodb_flush_method | default('O_DIRECT') }}"

database_mariadb__container: "{{ database_mariadb__podman_container_default | combine(mariadb_container | default({})) }}"

#
# Defaults - do not change
#

database_mariadb__server_password_reset: "mysql -e 'SET PASSWORD = PASSWORD(\"{{ database_mariadb__root_pass }}\"); FLUSH PRIVILEGES;' || mysql --password={{ database_mariadb__root_pass }} -e 'SET PASSWORD = PASSWORD(\"{{ database_mariadb__password.root }}\"); FLUSH PRIVILEGES;'"

database_mariadb__etc_dir: /etc/mysql
database_mariadb__run_dir: /var/run/mysqld
database_mariadb__base_dir: /usr
database_mariadb__data_dir: /var/lib/mysql
database_mariadb__tmp_dir: /tmp
database_mariadb__lc_messages_dir: /usr/share/mariadb
database_mariadb__log_dir: "{{ '/config/log/mysql' if database_mariadb__use_podman else '/var/log/mysql' }}"

# this configuration is used when MySQL/MariaDB is installed as a podman container
database_mariadb__podman_container_default:
  name: 'mariadb'
  hostname: "{{ database_mariadb__hostname }}"
  image: 'lscr.io/linuxserver/mariadb:latest'
  ip: "{{ database_mariadb__ip }}"
  ipv6: "{{ database_mariadb__ipv6 }}"
  network: "{{ database_mariadb__network }}"
  restart_policy: 'always'
  hosts: "{{ database_mariadb__hosts }}"
  environment:
    PUID: "{{ database_mariadb__uid }}"
    PGID: "{{ database_mariadb__gid }}"
    MYSQL_ROOT_PASSWORD: "{{ database_mariadb__root_pass }}"
  timezone: "{{ database_mariadb__time_zone }}"
  volumes:
    - "{{ database_mariadb__home }}:/config"

database_mariadb__packages: "{{
  database_mariadb__packages_podman_default[bootstrap_ansible__distribution] | default([]) if database_mariadb__use_podman
  else database_mariadb__packages_default[bootstrap_ansible__distribution] | default([])
}}"

database_mariadb__packages_podman_default:
  Debian:
    - libmariadb3
    - python3-pymysql

database_mariadb__packages_default:
  Debian:
    - dbconfig-common
    - dbconfig-mysql
    - default-mysql-client
    - default-mysql-server
    - mariadb-client
    - mariadb-server
    - mariadb-common
    - libdbd-mariadb-perl
    - python3-pymysql
    - python3-cryptography
