---

- name: Install and configure Postfix
  tags: [ 'mail_postfix' ]
  block:

    - name: Install Postfix packages
      block:
        - name: Install Postfix core packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_postfix__packages }}"
        - name: Install Postfix cdb packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_postfix__cdb_packages }}"
          when: mail_postfix__cdb_enable
        - name: Install Postfix ldap packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_postfix__ldap_packages }}"
          when: mail_postfix__ldap_enable
        - name: Install Postfix lmdb packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_postfix__lmdb_packages }}"
          when: mail_postfix__lmdb_enable
        - name: Install Postfix mysql packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_postfix__mysql_packages }}"
          when: mail_postfix__mysql_enable
        - name: Install Postfix pgsql packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_postfix__pgsql_packages }}"
          when: mail_postfix__pgsql_enable
        - name: Install Postfix sqlite packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ mail_postfix__sqlite_packages }}"
          when: mail_postfix__sqlite_enable

    - name: Generate configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: main.cf.j2
          dest: "{{ mail_postfix__etc_dir }}/main.cf"
        - src: master.cf.j2
          dest: "{{ mail_postfix__etc_dir }}/master.cf"
      notify:
        - Restart postfix

    - name: Create virtual tables directory
      ansible.builtin.file:
        path: "{{ mail_postfix__virtual_dir }}"
        state: directory
      when: mail_postfix__virtual_tables | length > 0

    - name: Generate virtual tables for lookups
      ansible.builtin.template:
        src: virtual_table.j2
        dest: "{{ mail_postfix__virtual_dir }}/{{ item.key }}"
        owner: root
        group: root
        mode: 0644
      vars:
        virtual_table: "{{ item.value }}"
      loop: "{{ mail_postfix__virtual_tables | dict2items }}"
      when: mail_postfix__virtual_tables | length > 0
      notify:
        - Restart postfix
