---

- name: Configure MongoDB backup
  tags: [ 'backup_mongodb'  ]
  block:

    - name: Install MongoDB packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ backup_mongodb__packages }}"

    - name: Copy MongoDB backup scripts to host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup_common__lib_dir }}/{{ item }}"
        mode: '755'
      with_items: "{{ backup_mongodb__files }}"

    - name: Generate MongoDB backup configuration file
      ansible.builtin.template:
        src: mongodb.j2
        dest: "{{ backup_common__etc_dir }}/mongodb"
        owner: root
        group: root
        mode: '640'

    - name: Create MongoDB backup directory
      ansible.builtin.file:
        mode: '750'
        owner: root
        group: root
        path: "{{ backup_mongodb__backup_dir }}"
        state: directory
