---

- name: Install and configure msmtp
  tags: [ 'mail_msmtp' ]
  block:

    - name: Install msmtp packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ mail_msmtp__packages }}"

    - name: Generate configuration file
      ansible.builtin.template:
        src: msmtprc.j2
        dest: /etc/msmtprc
        owner: root
        group: root
        mode: '444'

    - name: Set msmtp as role for sendmail
      ansible.builtin.copy:
        dest: /etc/ansible/sendmail
        content: msmtp
        owner: root
        group: root
        mode: '644'

    - name: Enable msmtpd service
      ansible.builtin.service:
        name: msmtpd
        state: started
        enabled: yes
      when: not ansible_check_mode
