---

- name: 'Install step-ca'
  tags: [ 'pki_stepca' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        owner: "{{ pki_stepca__uid }}"
        group: "{{ pki_stepca__gid }}"
        mode: '0750'
        state: 'directory'
      with_items:
        - "{{ pki_stepca__podman_home }}"

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        skip_existing: true
        name: 'stepca_init_password'
        data: "{{ pki_stepca__init_password }}"

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ pki_stepca__container.image }}"
        force: true
      when: 'podman___update_mode'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ pki_stepca__container.name }}"
        hostname: "{{ pki_stepca__container.hostname }}"
        image: "{{ pki_stepca__container.image }}"
        ip: "{{ pki_stepca__container.ip }}"
        ip6: "{{ pki_stepca__container.ipv6 | default(omit) }}"
        network: "{{ pki_stepca__container.network }}"
        timezone: "{{ pki_stepca__container.timezone }}"
        env: "{{ pki_stepca__container.environment | default(omit) }}"
        label: "{{ pki_stepca__container.labels | default(omit) }}"
        publish: "{{ pki_stepca__container.publish | default(omit) }}"
        secrets: "{{ pki_stepca__container.secrets | default(omit) }}"
        volume: "{{ pki_stepca__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ pki_stepca__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'
