---

- name: 'Install step-ca'
  tags: [ 'pki_stepca' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        owner: "{{ pki_stepca__uid }}"
        group: "{{ pki_stepca__gid }}"
        mode: '0750'
        state: 'directory'
      with_items:
        - "{{ pki_stepca__podman_home }}"

    - name: 'Create secrets'
      containers.podman.podman_secret:
        state: 'present'
        skip_existing: true
        name: 'stepca_init_password'
        data: "{{ pki_stepca__init_password }}"

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ pki_stepca__container.name }}"
        hostname: "{{ pki_stepca__container.hostname }}"
        image: "{{ pki_stepca__container.image }}"
        ip: "{{ pki_stepca__container.ip }}"
        network: "{{ pki_stepca__container.network }}"
        restart_policy: "{{ pki_stepca__container.restart_policy }}"
        timezone: "{{ pki_stepca__container.timezone }}"
        env: "{{ pki_stepca__container.environment }}"
        label: "{{ pki_stepca__container.labels }}"
        secrets: "{{ pki_stepca__container.secrets }}"
        volume: "{{ pki_stepca__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'pki_stepca__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ pki_stepca__container.name }}"
        hostname: "{{ pki_stepca__container.hostname }}"
        image: "{{ pki_stepca__container.image }}"
        ip: "{{ pki_stepca__container.ip }}"
        ipv6: "{{ pki_stepca__container.ipv6 }}"
        network: "{{ pki_stepca__container.network }}"
        restart_policy: "{{ pki_stepca__container.restart_policy }}"
        timezone: "{{ pki_stepca__container.timezone }}"
        env: "{{ pki_stepca__container.environment }}"
        label: "{{ pki_stepca__container.labels }}"
        secrets: "{{ pki_stepca__container.secrets }}"
        volume: "{{ pki_stepca__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'pki_stepca__ipv6 | length > 0'
