---

- name: Install and configure DHCPv4
  tags: [ 'dhcp' ]
  when: dhcp__client_v4_enable or dhcp__server_v4_enable 
  block:

  - name: Install DHCPv4 client packages
    tags: [ 'packages' ]
    when: dhcp__client_v4_enable
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ dhcp__client_v4_packages }}"

  - name: Install DHCPv4 server packages
    tags: [ 'packages' ]
    when: dhcp__server_v4_enable
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ dhcp__server_v4_packages }}"

  - name: Generate configuration files
    tags: [ 'configuration' ]
    when: dhcp__server_v4_enable
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: etc/default/isc-dhcp-server.j2
      dest: /etc/default/isc-dhcp-server
    - src: etc/dhcp/dhcpd.conf.j2
      dest: "{{ dhcp__etc_path }}/dhcpd.conf"
    notify:
    - Restart DHCPv4
