---

#
# Substitutes - do not change
#

app_gitlab_runner__hostname: "{{ gitlab_runner_hostname | default('gitlab-runner.localhost') }}"
app_gitlab_runner__ip: "{{ gitlab_runner_ip | mandatory }}"
app_gitlab_runner__network: "{{ gitlab_runner_network | mandatory }}"
app_gitlab_runner__docker_sock: "{{ gitlab_runner_docker_sock | default('/var/run/docker.sock') }}"
app_gitlab_runner__home: "{{ gitlab_runner_home | mandatory }}"

app_gitlab_runner__hosts: "{{ gitlab_runner_hosts | default({}) }}"

app_gitlab_runner__container: "{{ app_gitlab_runner__container_default | combine(gitlab_runner_container | default({})) }}"

#
# Defaults - do not change
#

app_gitlab_runner__container_default:
  name: gitlab-runner
  hostname: "{{ app_gitlab_runner__hostname }}"
  image: 'docker.io/gitlab/gitlab-runner:latest'
  ip: "{{ app_gitlab_runner__ip }}"
  network: "{{ app_gitlab_runner__network }}"
  restart_policy: always
  volumes:
    - "{{ app_gitlab_runner__home }}:/etc/gitlab-runner"
    - "{{ app_gitlab_runner__docker_sock }}:/var/run/docker.sock"
  hosts: "{{ app_gitlab_runner__hosts }}"
