---

- name: Restart WireGuard
  ansible.builtin.service:
    name: "wg-quick@{{ item.item.interface }}"
    state: restarted
  with_items: "{{ vpn_wireguard__create_config_result.results }}"
  when: not ansible_check_mode and item.changed
