---

- name: 'Install unbound DNS resolver'
  tags: [ 'dns_unbound' ]
  block:

    - name: 'Install unbound DNS resolver packages'
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ dns_unbound__packages }}"

    - name: 'Generate unbound DNS configuration'
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: 'remote-control.conf.j2'
          dest: "{{ dns_unbound__etc }}/remote-control.conf"
        - src: 'server.conf.j2'
          dest: "{{ dns_unbound__etc }}/server.conf"
      notify: 'Restart unbound'

    - name: 'Disable unbound resolvconf'
      when: dns_unbound__disable_resolvconf and not ansible_check_mode
      block:

        - ansible.builtin.service:
            name: 'unbound-resolvconf'
            state: 'stopped'
            enabled: false

        - ansible.builtin.shell: "test -f /etc/resolvconf.conf && sed -Ei 's/^unbound_conf=/#unbound_conf=/' /etc/resolvconf.conf"
          ignore_errors: true

        - ansible.builtin.file:
            path: "{{ dns_unbound__etc }}/resolvconf_resolvers.conf"
            state: 'absent'

      notify: 'Restart unbound'
