---

- name: 'Install unbound'
  tags: [ 'dns_unbound'  ]
  block:

    - name: 'Install unbound using podman'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: 'dns_unbound__use_podman'
