---

- name: 'Install container'
  containers.podman.podman_container:
    name: "{{ dns_unbound__container.name }}"
    hostname: "{{ dns_unbound__container.hostname }}"
    image: "{{ dns_unbound__container.image }}"
    ip: "{{ dns_unbound__container.ip }}"
    network: "{{ dns_unbound__container.network }}"
    timezone: "{{ dns_unbound__container.timezone }}"
    publish: "{{ dns_unbound__container.publish }}"
    volume: "{{ dns_unbound__container.volumes }}"
    quadlet_options: |
      [Install]
      WantedBy=default.target

      [Service]
      RestartSec=5
      Restart=always
      
      [Unit]
      {% if dns_unbound__container.requires is defined %}
      Requires={{ dns_unbound__container.requires | join(' ') }}
      {% endif %}
    restart_policy: 'no'
    state: 'quadlet'
    recreate: "{{ podman___update_mode | bool }}"
  when: 'dns_unbound__ipv6 | length == 0'

- name: 'Install container'
  containers.podman.podman_container:
    name: "{{ dns_unbound__container.name }}"
    hostname: "{{ dns_unbound__container.hostname }}"
    image: "{{ dns_unbound__container.image }}"
    ip: "{{ dns_unbound__container.ip }}"
    ip6: "{{ dns_unbound__container.ipv6 }}"
    network: "{{ dns_unbound__container.network }}"
    timezone: "{{ dns_unbound__container.timezone }}"
    publish: "{{ dns_unbound__container.publish }}"
    volume: "{{ dns_unbound__container.volumes }}"
    quadlet_options: |
      [Install]
      WantedBy=default.target

      [Service]
      RestartSec=5
      Restart=always
      
      [Unit]
      {% if dns_unbound__container.requires is defined %}
      Requires={{ dns_unbound__container.requires | join(' ') }}
      {% endif %}
    restart_policy: 'no'
    state: 'quadlet'
    recreate: "{{ podman___update_mode | bool }}"
  when: 'dns_unbound__ipv6 | length > 0'

- name: 'Start and enable container'
  ansible.builtin.systemd_service:
    name: "{{ dns_unbound__container.name }}"
    daemon_reload: true
    state: "{{ 'restarted' if podman___update_mode is defined and podman___update_mode else 'started' }}"
    enabled: true
  when: 'not ansible_check_mode'

- name: 'Enable autoupdate on container'
  when: 'dns_unbound__autoupdate_enabled'
  include_role:
    name: 'container_update'
  vars:
    container_name: "{{ dns_unbound__container.name }}"
    container_image: "{{ dns_unbound__container.image }}"
    container_schedule: "{{ dns_unbound__autoupdate_schedule }}"
