---

- name: Install unbound using podman
  block:

    - name: Create unbound directory
      ansible.builtin.file:
        mode: '750'
        path: "{{ dns_unbound__home }}"
        state: 'directory'
        owner: "{{ dns_unbound__uid }}"
        group: "{{ dns_unbound__uid }}"
      when: not ansible_check_mode

    - name: Generate unbound configuration
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '640'
        owner: "{{ dns_unbound__uid }}"
        group: "{{ dns_unbound__uid }}"
      with_items:
        - src: 'unbound.conf.j2'
          dest: "{{ dns_unbound__home }}/unbound.conf"
        - src: 'forward-records.conf.j2'
          dest: "{{ dns_unbound__home }}/forward-records.conf"
        - src: 'a-records.conf.j2'
          dest: "{{ dns_unbound__home }}/a-records.conf"
        - src: 'srv-records.conf.j2'
          dest: "{{ dns_unbound__home }}/srv-records.conf"
      notify: Restart unbound container
      when: not podman___update_mode

    - name: Install unbound container
      containers.podman.podman_container:
        name: "{{ dns_unbound__container.name }}"
        hostname: "{{ dns_unbound__container.hostname }}"
        image: "{{ dns_unbound__container.image }}"
        ip: "{{ dns_unbound__container.ip }}"
        network: "{{ dns_unbound__container.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ dns_unbound__container.restart_policy }}"
        etc_hosts: "{{ dns_unbound__container.hosts }}"
        timezone: "{{ dns_unbound__container.timezone }}"
        volume: "{{ dns_unbound__container.volumes }}"
        publish: "{{ dns_unbound__container.publish }}"
        pull: 'always'
      notify: Restart unbound container
      when: dns_unbound__ipv6 | length == 0
