---

- name: 'Install Traefik'
  tags: [ 'webserver_traefik' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ webserver_traefik__podman_home }}"
        - "{{ webserver_traefik__podman_config_dir }}"

    - name: 'Generate configuration'
      ansible.builtin.copy:
        content: "{{ webserver_traefik__config | to_nice_yaml(indent=2) }}"
        dest: "{{ webserver_traefik__podman_config_file }}"
      when: 'not podman___update_mode | bool and webserver_traefik__config | length > 0'
      notify: 'Restart traefik container'

    - name: 'Ensure acme.json exists'
      ansible.builtin.file:
        dest: "{{ webserver_traefik__podman_acme_file }}"
        mode: '0600'
        state: 'touch'

    - name: 'Generate dynamic configuration'
      ansible.builtin.copy:
        content: "{{ item.value | to_nice_yaml(indent=2) }}"
        dest: "{{ webserver_traefik__podman_config_dir }}/{{ item.key }}.yml"
      when: 'not podman___update_mode | bool and webserver_traefik__dynamic | length > 0'
      with_dict: "{{ webserver_traefik__dynamic }}"

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: "{{ item.name }}"
        data: "{{ item.data }}"
      with_items: "{{ webserver_traefik__secrets }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ webserver_traefik__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[webserver_traefik__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ webserver_traefik__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ webserver_traefik__container.name }}"
        hostname: "{{ webserver_traefik__container.hostname }}"
        image: "{{ webserver_traefik__container.image }}"
        ip: "{{ webserver_traefik__container.ip }}"
        ip6: "{{ webserver_traefik__container.ipv6 | default(omit) }}"
        network: "{{ webserver_traefik__container.network }}"
        timezone: "{{ webserver_traefik__container.timezone }}"
        etc_hosts: "{{ webserver_traefik__container.etc_hosts | default(omit) }}"
        env: "{{ webserver_traefik__container.environment | default(omit) }}"
        expose: "{{ webserver_traefik__container.expose | default(omit) }}"
        label: "{{ webserver_traefik__container.labels | default(omit) }}"
        publish: "{{ webserver_traefik__container.publish | default(omit) }}"
        secrets: "{{ webserver_traefik__container.secrets | default(omit) }}"
        volume: "{{ webserver_traefik__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ webserver_traefik__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'webserver_traefik__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ webserver_traefik__container.name }}"
        container_image: "{{ webserver_traefik__container.image }}"
        container_schedule: "{{ webserver_traefik__autoupdate_schedule }}"
