---

- name: 'Install traefik'
  tags: [ 'webserver_traefik' ]
  block:

    - name: 'Create traefik directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ webserver_traefik__podman_data_dir }}"

    - name: 'Generate traefik configuration'
      ansible.builtin.template:
        src: 'traefik.yml.j2'
        dest: "{{ webserver_traefik__podman_config_file }}"
      when: 'not podman___update_mode'
      notify: 'Restart traefik container'

    - name: 'Ensure acme.json exists'
      ansible.builtin.file:
        dest: "{{ webserver_traefik__podman_acme_file }}"
        mode: '0600'
        state: 'touch'

    - name: 'Install traefik container'
      containers.podman.podman_container:
        name: "{{ webserver_traefik__container.name }}"
        hostname: "{{ webserver_traefik__container.hostname }}"
        image: "{{ webserver_traefik__container.image }}"
        ip: "{{ webserver_traefik__container.ip }}"
        network: "{{ webserver_traefik__container.network }}"
        restart_policy: "{{ webserver_traefik__container.restart_policy }}"
        timezone: "{{ webserver_traefik__container.timezone }}"
        publish: "{{ webserver_traefik__container.publish }}"
        volume: "{{ webserver_traefik__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'webserver_traefik__ipv6 | length == 0'

    - name: 'Install traefik container'
      containers.podman.podman_container:
        name: "{{ webserver_traefik__container.name }}"
        hostname: "{{ webserver_traefik__container.hostname }}"
        image: "{{ webserver_traefik__container.image }}"
        ip: "{{ webserver_traefik__container.ip }}"
        ipv6: "{{ webserver_traefik__container.ipv6 }}"
        network: "{{ webserver_traefik__container.network }}"
        restart_policy: "{{ webserver_traefik__container.restart_policy }}"
        timezone: "{{ webserver_traefik__container.timezone }}"
        publish: "{{ webserver_traefik__container.publish }}"
        volume: "{{ webserver_traefik__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'webserver_traefik__ipv6 | length > 0'
