---

- name: 'Install Traefik'
  tags: [ 'webserver_traefik' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ webserver_traefik__podman_home }}"
        - "{{ webserver_traefik__podman_config_dir }}"

    - name: 'Generate simple configuration'
      ansible.builtin.template:
        src: 'traefik.yml.j2'
        dest: "{{ webserver_traefik__podman_config_file }}"
      when: 'not podman___update_mode and webserver_traefik__config | length == 0'
      notify: 'Restart traefik container'

    - name: 'Generate configuration'
      ansible.builtin.copy:
        content: "{{ webserver_traefik__config | to_nice_yaml(indent=2) }}"
        dest: "{{ webserver_traefik__podman_config_file }}"
      when: 'not podman___update_mode and webserver_traefik__config | length > 0'
      notify: 'Restart traefik container'

    - name: 'Ensure acme.json exists'
      ansible.builtin.file:
        dest: "{{ webserver_traefik__podman_acme_file }}"
        mode: '0600'
        state: 'touch'

    - name: 'Generate dynamic configuration'
      ansible.builtin.copy:
        content: "{{ item.value | to_nice_yaml(indent=2) }}"
        dest: "{{ webserver_traefik__podman_config_dir }}/{{ item.key }}.yml"
      when: 'not podman___update_mode and webserver_traefik__dynamic | length > 0'
      with_dict: "{{ webserver_traefik__dynamic }}"

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ webserver_traefik__container.image }}"
        force: true
      when: 'podman___update_mode'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ webserver_traefik__container.name }}"
        hostname: "{{ webserver_traefik__container.hostname }}"
        image: "{{ webserver_traefik__container.image }}"
        ip: "{{ webserver_traefik__container.ip }}"
        network: "{{ webserver_traefik__container.network }}"
        timezone: "{{ webserver_traefik__container.timezone }}"
        label: "{{ webserver_traefik__container.labels }}"
        publish: "{{ webserver_traefik__container.publish }}"
        volume: "{{ webserver_traefik__container.volumes }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'webserver_traefik__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ webserver_traefik__container.name }}"
        hostname: "{{ webserver_traefik__container.hostname }}"
        image: "{{ webserver_traefik__container.image }}"
        ip: "{{ webserver_traefik__container.ip }}"
        ip6: "{{ webserver_traefik__container.ipv6 }}"
        network: "{{ webserver_traefik__container.network }}"
        timezone: "{{ webserver_traefik__container.timezone }}"
        label: "{{ webserver_traefik__container.labels }}"
        publish: "{{ webserver_traefik__container.publish }}"
        volume: "{{ webserver_traefik__container.volumes }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: 'webserver_traefik__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ webserver_traefik__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'
