---

#
# Substitutes - do not change
#

app_redisinsight__hostname: "{{ redisinsight_hostname | default('redisinsight.' + dns_hostname) }}"
app_redisinsight__ip: "{{ redisinsight_ip | mandatory }}"
app_redisinsight__ipv6: "{{ redisinsight_ipv6 | default('') }}"
app_redisinsight__network: "{{ redisinsight_network | mandatory }}"
app_redisinsight__version: "{{ redisinsight_version | default('latest') }}"
app_redisinsight__home: "{{ redisinsight_home | mandatory }}"

app_redisinsight__hosts: "{{ redisinsight_hosts | default({}) }}"
app_redisinsight__timezone: "{{ redisinsight_timezone | default(bootstrap_timezone__timezone) }}"

#
# Defaults - do not change
#

app_redisinsight__data_dir: "{{ app_redisinsight__home }}/data"

app_redisinsight__port: 5540
app_redisinsight__uid: 1000
app_redisinsight__gid: 1000

app_redisinsight__podman_image: 'docker.io/redis/redisinsight'

app_redisinsight__podman_container: "{{ app_redisinsight__container_default }}"

app_redisinsight__container_default:
  name: 'redisinsight'
  hostname: "{{ app_redisinsight__hostname }}"
  image: "{{ app_redisinsight__podman_image }}:{{ app_redisinsight__version }}"
  ip: "{{ app_redisinsight__ip }}"
  network: "{{ app_redisinsight__network }}"
  restart_policy: 'always'
  hosts: "{{ app_redisinsight__hosts }}"
  environment:
    TZ: "{{ app_redisinsight__timezone }}"
  timezone: "{{ app_redisinsight__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - "{{ app_redisinsight__data_dir }}:/data"
