---

- name: Install schema to OpenLDAP server
  block:

    - name: "Is schema {{ schema }} available on host?"
      ansible.builtin.stat:
        path: "{{ openldap_server__schema_dir }}/{{ schema }}.schema"
      register: schema_stat_result

    - name: "Copy schema {{ schema }} file"
      ansible.builtin.copy:
        src: "{{ schema }}.schema"
        dest: "{{ openldap_server__schema_dir }}/{{ schema }}.schema"
        owner: root
        group: root
        mode: '644'
      register: schema_copy_result
      when: not schema_stat_result.stat.exists and not ansible_check_mode

    - name: "Is LDIF for schema {{ schema }} available on host?"
      ansible.builtin.stat:
        path: "{{ openldap_server__schema_dir }}/{{ schema }}.ldif"
      register: schema_ldif_stat_result

    - name: "Create schema {{ schema }} LDIF file"
      ansible.builtin.shell: "schema2ldif {{ openldap_server__schema_dir }}/{{ schema }}.schema | sed -e '/^#/d' > {{ openldap_server__schema_dir }}/{{ schema }}.ldif"
      when: not schema_ldif_stat_result.stat.exists or schema_copy_result.changed
