---

#
# Substitutes - do not change
#

security_openssh__podman_home: "{{ openssh_home | mandatory }}"

security_openssh__hostname: "{{ openssh_hostname | default('ssh.' + dns_hostname) }}"
security_openssh__ip: "{{ openssh_ip | mandatory }}"
security_openssh__ipv6: "{{ openssh_ipv6 | default('') }}"
security_openssh__network: "{{ openssh_network | mandatory }}"
security_openssh__hosts: "{{ openssh_hosts | default({}) }}"
security_openssh__version: "{{ openssh_version | default('latest') }}"
security_openssh__timezone: "{{ openssh_timezone | default(bootstrap_timezone__timezone) }}"
security_openssh__uid: "{{ openssh_uid | default(security_openssh__uid_default) }}"
security_openssh__gid: "{{ openssh_gid | default(security_openssh__gid_default) }}"

security_openssh__port: "{{ openssh_port | default(2222) }}"
security_openssh__public_port: "{{ openssh_public_port | default(security_openssh__port) }}"

security_openssh__public_key: "{{ openssh_public_key | mandatory }}"
security_openssh__user_name: "{{ openssh_user_name | default('linuxserver.io') }}"

security_openssh__environment: "{{ security_openssh__environment_default  | combine(openssh_environment | default({})) }}"
security_openssh__volumes: "{{ security_openssh__volumes_default + openssh_volumes | default([]) }}"

#
# Defaults - do not change
#

security_openssh__podman_container: "{{ security_openssh__podman_container_default }}"

security_openssh__data_dir: "{{ security_openssh__podman_home }}/config"

security_openssh__uid_default: 1000
security_openssh__gid_default: 1000

security_openssh__environment_default:
  PUID: "{{ security_openssh__uid }}"
  PGID: "{{ security_openssh__gid }}"
  TZ: "{{ security_openssh__timezone }}"
  PUBLIC_KEY: "{{ security_openssh__public_key }}"
  USER_NAME: "{{ security_openssh__user_name }}"

security_openssh__volumes_default:
  - '/etc/localtime:/etc/localtime:ro'
  - '/etc/timezone:/etc/timezone:ro'
  - "{{ security_openssh__data_dir }}:/config"

security_openssh__podman_name: 'ssh'
security_openssh__podman_image: 'lscr.io/linuxserver/openssh-server'

security_openssh__podman_container_default:
  name: "{{ security_openssh__podman_name }}"
  hostname: "{{ security_openssh__hostname }}"
  image: "{{ security_openssh__podman_image }}:{{ security_openssh__version }}"
  ip: "{{ security_openssh__ip }}"
  ipv6: "{{ security_openssh__ipv6 }}"
  network: "{{ security_openssh__network }}"
  restart_policy: 'always'
  hosts: "{{ security_openssh__hosts }}"
  publish:
   - "{{ security_openssh__public_port }}:{{ security_openssh__port }}"
  environment: "{{ security_openssh__environment }}"
  timezone: "{{ security_openssh__timezone }}"
  volumes: "{{ security_openssh__volumes }}"
