---

- name: Install and configure smartmontools
  tags: [ 'smartmon' ]
  when: smartmon__enable
  block:

  - name: Install smartmon packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ smartmon__packages }}"

  - name: Enable service
    tags: [ 'configuration', 'service' ]
    when: smartmon__smartd_enable
    ansible.builtin.service:
      name: smartd
      state: started
      enabled: yes

  - name: Disable service
    tags: [ 'configuration', 'service' ]
    when: not smartmon__smartd_enable
    ansible.builtin.service:
      name: smartd
      state: stopped
      enabled: no
