---

- name: Configure OpenLDAP backup
  tags: [ 'backup_openldap'  ]
  block:

    - name: Install OpenLDAP packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ backup_openldap__packages }}"

    - name: Copy OpenLDAP backup scripts to host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ backup_common__lib_dir }}/{{ item }}"
        mode: '755'
      with_items: "{{ backup_openldap__files }}"

    - name: Generate OpenLDAP backup configuration file
      ansible.builtin.template:
        src: openldap.j2
        dest: "{{ backup_common__etc_dir }}/openldap"
        owner: root
        group: root
        mode: '640'

    - name: Create OpenLDAP backup directory
      ansible.builtin.file:
        mode: '750'
        owner: root
        group: root
        path: "{{ backup_openldap__backup_dir }}"
        state: directory
