---

- name: 'Install vzlogger'
  tags: [ 'smarthome_vzlogger' ]
  block:

    - name: 'Create vzlogger directories'
      ansible.builtin.file:
        path: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ smarthome_vzlogger__podman_home }}"

    - name: 'Generate configuration'
      ansible.builtin.copy:
        content: "{{ smarthome_vzlogger__config | to_nice_json(indent=4) }}"
        dest: "{{ smarthome_vzlogger__podman_home }}/vzlogger.conf"
        mode: '400'
      notify:
        - 'Restart vzlogger container'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ smarthome_vzlogger__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[smarthome_vzlogger__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ smarthome_vzlogger__container.image }}"
        force: true
      when: 'podman___update_mode'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ smarthome_vzlogger__container.name }}"
        hostname: "{{ smarthome_vzlogger__container.hostname }}"
        image: "{{ smarthome_vzlogger__container.image }}"
        ip: "{{ smarthome_vzlogger__container.ip }}"
        network: "{{ smarthome_vzlogger__container.network }}"
        timezone: "{{ smarthome_vzlogger__container.timezone | mandatory }}"
        device: "{{ smarthome_vzlogger__container.devices }}"
        label: "{{ smarthome_vzlogger__container.labels }}"
        publish: "{{ smarthome_vzlogger__container.publish }}"
        volume: "{{ smarthome_vzlogger__container.volumes }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'smarthome_vzlogger__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ smarthome_vzlogger__container.name }}"
        hostname: "{{ smarthome_vzlogger__container.hostname }}"
        image: "{{ smarthome_vzlogger__container.image }}"
        ip: "{{ smarthome_vzlogger__container.ip }}"
        ip6: "{{ smarthome_vzlogger__container.ipv6 }}"
        network: "{{ smarthome_vzlogger__container.network }}"
        timezone: "{{ smarthome_vzlogger__container.timezone | mandatory }}"
        device: "{{ smarthome_vzlogger__container.devices }}"
        label: "{{ smarthome_vzlogger__container.labels }}"
        publish: "{{ smarthome_vzlogger__container.publish }}"
        volume: "{{ smarthome_vzlogger__container.volumes }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'smarthome_vzlogger__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ smarthome_vzlogger__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode is defined and podman___update_mode else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
