---

- name: 'Install and configure Icinga 2 web'
  tags: [ 'monitoring_icinga_web' ]
  block:

    - name: 'Install Icinga 2 web using podman'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: 'monitoring_icinga_web__use_podman'
