---

- name: 'Install and configure Icinga 2 web'
  block:

    - name: 'Create directories for Icinga 2 web'
      ansible.builtin.file:
        path: "{{ item }}"
        owner: "{{ monitoring_icinga_web__user }}"
        group: "{{ monitoring_icinga_web__group }}"
        state: 'directory'
      with_items:
        - "{{ monitoring_icinga_web__dir }}"
        - "{{ monitoring_icinga_web__var_dir }}"
        - "{{ monitoring_icinga_web__modules_enabled_dir }}"
        - "{{ monitoring_icinga_web__modules_etc_dir }}/monitoring"

    - name: 'Generate configuration files'
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ monitoring_icinga_web__user }}"
        group: "{{ monitoring_icinga_web__group }}"
        mode: '660'
      with_items:
        - src: 'authentication.ini.j2'
          dest: "{{ monitoring_icinga_web__dir }}/authentication.ini"
        - src: 'config.ini.j2'
          dest: "{{ monitoring_icinga_web__dir }}/config.ini"
        - src: 'groups.ini.j2'
          dest: "{{ monitoring_icinga_web__dir }}/groups.ini"
        - src: 'resources.ini.j2'
          dest: "{{ monitoring_icinga_web__dir }}/resources.ini"
        - src: 'roles.ini.j2'
          dest: "{{ monitoring_icinga_web__dir }}/roles.ini"

    - name: 'Generate configuration files for monitoring'
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ monitoring_icinga_web__user }}"
        group: "{{ monitoring_icinga_web__group }}"
        mode: '660'
      with_items:
        - src: 'monitoring_backends.ini.j2'
          dest: "{{ monitoring_icinga_web__modules_etc_dir }}/monitoring/backends.ini"

    - name: 'Enable modules for Icinga Web 2'
      ansible.builtin.file:
        src: "{{ monitoring_icinga_web__modules_dir }}/{{ item }}"
        dest: "{{ monitoring_icinga_web__modules_enabled_dir }}/{{ item }}"
        state: 'link'
        force: 'yes'
      with_items: "{{ monitoring_icinga_web__modules_enabled }}"

    - name: 'Create podman containers'
      containers.podman.podman_container:
        name: "{{ monitoring_icinga_web__container.name }}"
        hostname: "{{ monitoring_icinga_web__container.hostname }}"
        image: "{{ monitoring_icinga_web__container.image }}"
        ip: "{{ monitoring_icinga_web__container.ip }}"
        network: "{{ monitoring_icinga_web__container.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ monitoring_icinga_web__container.restart_policy }}"
        etc_hosts: "{{ monitoring_icinga_web__container.hosts }}"
        env: "{{ monitoring_icinga_web__container.environment }}"
        timezone: "{{ monitoring_icinga_web__container.timezone }}"
        volume: "{{ [
          monitoring_icinga_web__data_dir + ':/data',
        ] }}"
      when: 'monitoring_icinga_web__ipv6 | length == 0'

    - name: 'Create podman containers'
      containers.podman.podman_container:
        name: "{{ monitoring_icinga_web__container.name }}"
        hostname: "{{ monitoring_icinga_web__container.hostname }}"
        image: "{{ monitoring_icinga_web__container.image }}"
        ip: "{{ monitoring_icinga_web__container.ip }}"
        ip6: "{{ monitoring_icinga_web__container.ipv6 }}"
        network: "{{ monitoring_icinga_web__container.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ monitoring_icinga_web__container.restart_policy }}"
        etc_hosts: "{{ monitoring_icinga_web__container.hosts }}"
        env: "{{ monitoring_icinga_web__container.environment }}"
        timezone: "{{ monitoring_icinga_web__container.timezone }}"
        volume: "{{ [
          monitoring_icinga_web__data_dir + ':/data',
        ] }}"
      when: 'monitoring_icinga_web__ipv6 | length > 0'
