---

dovecot__logging_log_path: "{{ dovecot_logging_log_path | default('') }}"
dovecot__logging_info_log_path: "{{ dovecot_logging_info_log_path | default('') }}"
dovecot__logging_debug_log_path: "{{ dovecot_logging_debug_log_path | default('') }}"
dovecot__logging_syslog_facility: "{{ dovecot_logging_syslog_facility | default('mail') }}"

dovecot__logging_log_debug: "{{ dovecot_logging_log_debug | default('') }}"
dovecot__logging_log_core_filter: "{{ dovecot_logging_log_core_filter | default('') }}"
dovecot__logging_auth_verbose: "{{ dovecot_logging_auth_verbose | default(false) }}"
dovecot__logging_auth_verbose_passwords: "{{ dovecot_logging_auth_verbose_passwords | default(false) }}"
dovecot__logging_auth_debug: "{{ dovecot_logging_auth_debug | default(false) }}"
dovecot__logging_auth_debug_passwords: "{{ dovecot_logging_auth_debug_passwords | default(false) }}"
dovecot__logging_mail_debug: "{{ dovecot_logging_mail_debug | default(false) }}"
dovecot__logging_verbose_ssl: "{{ dovecot_logging_verbose_ssl | default(false) }}"

dovecot__logging_log_timestamp: "{{ dovecot_logging_log_timestamp | default('\"%b %d %H:%M:%S \"') }}"
dovecot__logging_login_log_format_elements: "{{ dovecot_logging_login_log_format_elements | default('user=<%u> method=%m rip=%r lip=%l mpid=%e %c session=<%{session}>') }}"
dovecot__logging_login_log_format: "{{ dovecot_logging_login_log_format | default('%$: %s') }}"
dovecot__logging_mail_log_prefix: "{{ dovecot_logging_mail_log_prefix | default('\"%s(%u)<%{pid}><%{session}>: \"') }}"
dovecot__logging_deliver_log_format: "{{ dovecot_logging_deliver_log_format | default('msgid=%m: %$') }}"

dovecot__plugin_mail_log: "{{ dovecot_plugin_mail_log | default(false) }}"
dovecot__plugin_mail_log_events: "{{ dovecot_plugin_mail_log_events | default(['delete', 'undelete', 'expunge', 'copy', 'mailbox_delete', 'mailbox_rename']) }}"
dovecot__plugin_mail_log_fields: "{{ dovecot_plugin_mail_log_fields | default(['uid', 'box', 'msgid', 'size']) }}"
