---

- name: Install ACME pki support (certbot)
  tags: [ 'pki', 'pki_acme'  ]
  block:

    - name: Install certbot using package management
      ansible.builtin.include_tasks:
        file: apt.yml
      when: not pki_acme__use_podman

    - name: Install certbot using podman
      ansible.builtin.include_tasks:
        file: podman.yml
      when: pki_acme__use_podman
