---

- name: Install ACME pki support
  tags: [ 'pki_acme'  ]
  block:

    - name: Install pki packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ pki_acme__packages }}"

    - name: Register or update ACME account
      when: pki_acme__email | length > 0
      ansible.builtin.shell: |
        certbot update_account {{ pki_acme__register_options }} || certbot register {{ pki_acme__register_options }}
      environment: "{{ pki_acme__environment }}"
