---

- name: Install and configure postgrey
  tags: [ 'mail_postgrey' ]
  block:

    - name: Install postgrey
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ mail_postgrey__packages }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: postgrey.j2
        dest: /etc/default/postgrey
        owner: root
        group: root
        mode: '644'
      notify:
        - Restart postgrey
