---

- name: Deploy diagrams.net container
  tags: [ 'app_diagrams' ]
  block:

    - name: Create podman containers
      containers.podman.podman_container:
        name: "{{ app_diagrams__container.name }}"
        hostname: "{{ app_diagrams__container.hostname }}"
        image: "{{ app_diagrams__container.image }}"
        ip: "{{ app_diagrams__container.ip }}"
        network: "{{ app_diagrams__container.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ app_diagrams__container.restart_policy }}"
        etc_hosts: "{{ app_diagrams__container.hosts }}"
        env: "{{ app_diagrams__container.environment }}"
        timezone: "{{ app_diagrams__container.timezone }}"
      when: app_diagrams__ipv6 | length == 0
