---

- name: Initialize Easy-RSA CA
  tags: [ 'pki_easyrsa_ca'  ]
  run_once: yes
  become: no
  block:

    - name: Create secrets directory
      local_action:
        module: ansible.builtin.file
        path: "{{ pki_easyrsa_ca__pki_dir }}"
        state: directory
        mode: '750'

    - name: Is Easy-RSA PKI initialized?
      local_action:
        module: ansible.builtin.stat
        path: "{{ pki_easyrsa_ca__pki_dir }}/safessl-easyrsa.cnf"
      register: easyrsa_pki_stat_result

    - name: Is Easy-RSA CA initialized?
      local_action:
        module: ansible.builtin.stat
        path: "{{ pki_easyrsa_ca__pki_dir }}/ca.crt"
      register: easyrsa_ca_stat_result

    - name: Init Easy-RSA PKI
      local_action:
        module: ansible.builtin.command
        chdir: "{{ pki_easyrsa_ca__pki_dir }}"
        cmd: "{{ pki_easyrsa_ca__path }} init-pki"
      environment: "{{ pki_easyrsa_ca__environment }}"
      when: not easyrsa_pki_stat_result.stat.exists

    - name: Remove vars file after initialization
      local_action:
        module: ansible.builtin.file
        path: "{{ pki_easyrsa_ca__pki_dir }}/vars"
        state: absent

    - name: Create Easy-RSA CA
      local_action:
        module: ansible.builtin.command
        chdir: "{{ pki_easyrsa_ca__pki_dir }}"
        cmd: "{{ pki_easyrsa_ca__path }} build-ca"
      environment: "{{ pki_easyrsa_ca__environment }}"
      when: not easyrsa_ca_stat_result.stat.exists

    - name: Ensure Eays-RSA directories exist
      local_action:
        module: ansible.builtin.file
        dest: "{{ pki_easyrsa_ca__pki_dir }}/{{ item }}"
        state: directory
        recurse: yes
      with_items: "{{ pki_easyrsa_ca__directories_gitkeep }}"
      when: not easyrsa_pki_stat_result.stat.exists

    - name: Keep Eays-RSA directories in git
      local_action:
        module: ansible.builtin.file
        dest: "{{ pki_easyrsa_ca__pki_dir }}/{{ item }}/.gitkeep"
        state: touch
      with_items: "{{ pki_easyrsa_ca__directories_gitkeep }}"
      when: not easyrsa_pki_stat_result.stat.exists
