---

#
# Substitutes - do not change
#

matrix_bridge_discord__hostname: "{{ matrix_bridge_discord_hostname | default('mautrix-discord.' + dns_hostname) }}"
matrix_bridge_discord__ip: "{{ matrix_bridge_discord_ip | mandatory }}"
matrix_bridge_discord__ipv6: "{{ matrix_bridge_discord_ipv6 | default('') }}"
matrix_bridge_discord__network: "{{ matrix_bridge_discord_network | mandatory }}"
matrix_bridge_discord__hosts: "{{ matrix_bridge_discord_hosts | default({}) }}"
matrix_bridge_discord__timezone: "{{ matrix_bridge_discord_timezone | default(bootstrap_timezone__timezone) }}"
matrix_bridge_discord__home: "{{ matrix_bridge_discord_home | mandatory }}"

matrix_bridge_discord__dns_servers: "{{ matrix_bridge_discord_dns_servers | default([]) }}"

matrix_bridge_discord__setup: "{{ matrix_bridge_discord_setup | default(true) }}"

matrix_bridge_discord__version: "{{ matrix_bridge_discord_version | default('latest') }}"
matrix_bridge_discord__container: "{{ matrix_bridge_discord__podman_container_default }}"

#
# Defaults - do not change
#

matrix_bridge_discord__uid: 1337
matrix_bridge_discord__gid: 1337

matrix_bridge_discord__podman_image: 'dock.mau.dev/mautrix/discord'

matrix_bridge_discord__podman_container_default:
  name: 'mautrix-discord'
  hostname: "{{ matrix_bridge_discord__hostname }}"
  image: "{{ matrix_bridge_discord__podman_image }}:{{ matrix_bridge_discord__version }}"
  ip: "{{ matrix_bridge_discord__ip }}"
  ipv6: "{{ matrix_bridge_discord__ipv6 }}"
  network: "{{ matrix_bridge_discord__network }}"
  restart_policy: 'always'
  hosts: "{{ matrix_bridge_discord__hosts }}"
  dns_servers: "{{ matrix_bridge_discord__dns_servers }}"
  environment:
    TZ: "{{ matrix_bridge_discord__timezone }}"
  timezone: "{{ matrix_bridge_discord__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - "{{ matrix_bridge_discord__home }}:/data"
