---

- name: 'Deploy pgAdmin container'
  tags: [ 'app_pgadmin' ]
  block:

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ app_pgadmin__container.name }}"
        hostname: "{{ app_pgadmin__container.hostname }}"
        image: "{{ app_pgadmin__container.image }}"
        ip: "{{ app_pgadmin__container.ip }}"
        network: "{{ app_pgadmin__container.network }}"
        restart_policy: "{{ app_pgadmin__container.restart_policy }}"
        etc_hosts: "{{ app_pgadmin__container.hosts }}"
        env: "{{ app_pgadmin__container.environment }}"
        timezone: "{{ app_pgadmin__container.timezone }}"
        volume: "{{ app_pgadmin__container.volumes }}"
        pull: 'always'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: app_pgadmin__ipv6 | length == 0
