---

- name: Install fail2ban
  tags: [ 'security_fail2ban' ]
  block:

    - name: Install fail2ban packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ security_fail2ban__packages }}"

    - name: Configure fail2ban
      ansible.builtin.template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: 0644
      notify:
      - Restart fail2ban

    - name: Configure fail2ban filters
      ansible.builtin.template:
        src: filter.conf.j2
        dest: "/etc/fail2ban/filter.d/{{ item.name }}.conf"
        owner: root
        group: root
        mode: 0644
      with_items: "{{ security_fail2ban__filter }}"
      notify:
      - Restart fail2ban

    - name: Configure fail2ban jails
      ansible.builtin.template:
        src: jail.conf.j2
        dest: "/etc/fail2ban/jail.d/{{ item.name }}.conf"
        owner: root
        group: root
        mode: 0644
      with_items: "{{ security_fail2ban__jails }}"
      notify:
      - Restart fail2ban
