---

- name: 'Restart Icinga'
  ansible.builtin.systemd_service:
    daemon_reload: "{{ monitoring_icinga_agent__cert_source_dir | length > 0 }}"
    name: 'icinga2'
    state: 'restarted'
  when: 'not ansible_check_mode'
