---

- name: Configure systemd
  tags: [ 'systemd' ]
  when: systemd__enable
  block:

  - name: Generate service files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/systemd/system/service.j2
      dest: "/etc/systemd/system/{{ item.name }}.service"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd__services }}"
    notify:
    - Reload systemd

  - name: Generate timer files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/systemd/system/timer.j2
      dest: "/etc/systemd/system/{{ item.name }}.timer"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd__timers }}"
    notify:
    - Reload systemd

  - name: Force systemd reload
    when: not ansible_check_mode
    meta: flush_handlers

  - name: Enable services
    tags: [ 'configuration' ]
    ansible.builtin.systemd:
      name: "{{ item.name }}.service"
      enabled: "{{ item.enabled | ternary('yes', 'no') }}"
    with_items: "{{ systemd__services | selectattr('item.enabled', 'defined') }}"

  - name: Enable timers
    tags: [ 'configuration' ]
    ansible.builtin.systemd:
      name: "{{ item.name }}.service"
      enabled: "{{ item.enabled | ternary('yes', 'no') }}"
    with_items: "{{ systemd__timers | selectattr('item.enabled', 'defined')  }}"
