---

- name: 'Install logfiles monitoring plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__check_logfiles_packages }}"

- name: 'Enable check_logfiles plugin'
  ansible.builtin.file:
    state: 'link'
    src: "{{ monitoring_plugins__plugin_dir }}/check_logfiles"
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_logfiles"
