---

- name: 'Install nginx monitoring plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__check_nginx_packages }}"

- name: 'Copy nginx monitoring plugin to host'
  ansible.builtin.copy:
    src: 'check_nginx_status.pl'
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_nginx_status.pl"
    mode: '755'

- name: 'Generate nginx monitoring plugin configuration file'
  ansible.builtin.template:
    src: 'check_nginx_status.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_nginx_status.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'
