---

- name: 'Install check_running_kernel plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__check_running_kernel_packages }}"

- name: 'Enable check_running_kernel plugin'
  ansible.builtin.file:
    state: 'link'
    src: "{{ monitoring_plugins__plugin_dir }}/check_running_kernel"
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_running_kernel"
