---

- name: 'Install S.M.A.R.T. monitoring plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__check_smart_packages }}"

- name: 'Generate S.M.A.R.T. monitoring plugin configuration file'
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'
  with_items:
    - src: 'check_ide_smart.conf.j2'
      dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_ide_smart.conf"
    - src: 'check_smartpl.conf.j2'
      dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_smartpl.conf"

- name: 'Add sudoers entry for podman monitoring plugin'
  community.general.sudoers:
    name: 'icinga-run-ide-smart'
    state: 'present'
    user: 'nagios'
    commands:
      - '/usr/lib/nagios/plugins/check_ide_smart'
      - '/usr/lib/nagios/plugins/check_smart.pl'
      - '/usr/sbin/smartctl'
