---

- name: 'Install RAID plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__check_raid_packages }}"

- name: 'Generate RAID plugin configuration file'
  ansible.builtin.template:
    src: 'check_raid.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_raid.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'

- name: 'Enable RAID plugin'
  ansible.builtin.file:
    state: 'link'
    src: "{{ monitoring_plugins__plugin_dir }}/check_raid"
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_raid"

- name: 'Add sudoers entry for RAID monitoring plugin'
  community.general.sudoers:
    name: 'icinga-run-raid'
    state: 'present'
    user: 'nagios'
    commands:
      - '/sbin/dmsetup'
