---

- name: 'Generate reboot monitoring plugin configuration file'
  ansible.builtin.template:
    src: 'check_running_kernel.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_running_kernel.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'
