---

- name: 'Install pgactivity monitoring plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__check_pgactivity_packages }}"

- name: 'Copy pgactivity monitoring plugin to host'
  ansible.builtin.copy:
    src: 'check_pgactivity.pl'
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_pgactivity.pl"
    mode: '755'

- name: 'Generate pgactivity monitoring plugin configuration file'
  ansible.builtin.template:
    src: 'check_pgactivity.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_pgactivity.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'

- name: 'Create PostgreSQL service file'
  no_log: true
  ansible.builtin.copy:
    dest: "{{ monitoring_plugins__home_dir }}/.pg_service.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '400'
    content: |
      [nagios]
      host={{ monitoring_plugins__credentials_postgresql_host }}
      port={{ monitoring_plugins__credentials_postgresql_port }}
      user={{ monitoring_plugins__credentials_postgresql_user }}

- name: 'Create PostgreSQL password file'
  no_log: true
  ansible.builtin.copy:
    dest: "{{ monitoring_plugins__home_dir }}/.pgpass"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '400'
    content: |
      {{ monitoring_plugins__credentials_postgresql_host }}:{{ monitoring_plugins__credentials_postgresql_port }}:postgres:{{ monitoring_plugins__credentials_postgresql_user }}:{{ monitoring_plugins__credentials_postgresql_password }}
