---

- name: 'Copy pass alive monitoring plugin to host'
  ansible.builtin.copy:
    src: 'check_pass_alive'
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_pass_alive"
    mode: '755'

- name: 'Generate reboot monitoring plugin configuration file'
  ansible.builtin.template:
    src: 'check_pass_alive.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_pass_alive.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'

- name: 'Add sudoers entry for pass alive monitoring plugin'
  community.general.sudoers:
    name: 'icinga-run-pass-alive'
    state: 'present'
    user: 'nagios'
    commands:
      - "{{ monitoring_plugins__plugin_local_dir }}/check_pass_alive"
