---

- name: 'Install TLS certificate monitoring plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__check_tls_cert_packages }}"

- name: 'Copy TLS certificate monitoring plugin to host'
  ansible.builtin.copy:
    src: 'check_tls_cert.py'
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_tls_cert"
    mode: '755'

- name: 'Generate TLS certificate monitoring plugin configuration file'
  ansible.builtin.template:
    src: 'check_tls_cert.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_tls_cert.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'
