---

- name: 'Copy container stats monitoring plugin to host'
  ansible.builtin.copy:
    src: 'check_container_stats_docker.py'
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_container_stats_docker.py"
    mode: '755'

- name: 'Generate container stats monitoring plugin configuration file'
  ansible.builtin.template:
    src: 'check_container_stats_docker.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_container_stats_docker.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'
