---

- name: 'Install systemd monitoring plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__check_systemd_packages }}"

- name: 'Copy systemd monitoring plugin to host'
  ansible.builtin.copy:
    src: 'check_systemd.py'
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_systemd.py"
    mode: '755'

- name: 'Generate systemd monitoring plugin configuration file'
  ansible.builtin.template:
    src: 'check_systemd.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_systemd.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'
