---

- name: 'Generate RAID plugin configuration file'
  ansible.builtin.template:
    src: 'check_raid.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_raid.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'

- name: 'Add sudoers entry for RAID monitoring plugin'
  community.general.sudoers:
    name: 'icinga-run-raid'
    state: 'present'
    user: 'nagios'
    commands:
      - '/sbin/dmsetup'
