---

- name: 'Install systemd monitoring plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__check_systemd_packages }}"

- name: 'Enable check_systemd plugin'
  ansible.builtin.file:
    state: 'link'
    src: "{{ monitoring_plugins__plugin_dir }}/check_systemd"
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_systemd"
