---

- name: 'Copy container stats monitoring plugin to host'
  ansible.builtin.copy:
    src: 'check_container_stats_podman.py'
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_container_stats_podman.py"
    mode: '755'

- name: 'Generate container stats monitoring plugin configuration file'
  ansible.builtin.template:
    src: 'check_container_stats_podman.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_container_stats_podman.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'

- name: 'Add sudoers entry for podman monitoring plugin'
  community.general.sudoers:
    name: 'icinga-run-podman'
    state: 'present'
    user: 'nagios'
    commands:
      - '/usr/local/lib/nagios/plugins/check_container_stats_podman.py'
