---

- name: 'Install certexp monitoring plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__check_certexp_packages }}"

- name: 'Copy certexp monitoring plugin to host'
  ansible.builtin.copy:
    src: 'check_certexp.pl'
    dest: "{{ monitoring_plugins__plugin_local_dir }}/check_certexp.pl"
    mode: '755'

- name: 'Generate certexp monitoring plugin configuration file'
  ansible.builtin.template:
    src: 'check_certexp.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_certexp.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'
