---

- name: 'Store MariaDB credentials in file'
  no_log: true
  ansible.builtin.copy:
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/credentials_mariadb"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '440'
    content: |
      [client]
      user={{ monitoring_plugins__credentials_mariadb_user }}
      password={{ monitoring_plugins__credentials_mariadb_password }}
