---

- name: 'Store MySQL credentials in file'
  no_log: true
  ansible.builtin.copy:
    dest: "{{ monitoring_plugins__home_dir }}/.my.cnf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '400'
    content: |
      [client]
      user={{ monitoring_plugins__credentials_mysql_user }}
      password={{ monitoring_plugins__credentials_mysql_password }}
    
