---

- name: Install and configure monitoring plugins
  tags: [ 'monitoring_plugins' ]
  block:

    - name: Create local monitoring plugins directory
      ansible.builtin.file:
        dest: "{{ monitoring_plugins__plugin_local_dir }}"
        owner: root
        group: root
        mode: '755'
        state: directory

    - name: Create Icinga monitoring plugins directory
      ansible.builtin.file:
        dest: "{{ monitoring_plugins__plugin_etc_dir }}"
        owner: "{{ monitoring_icinga_common__user }}"
        group: "{{ monitoring_icinga_common__group }}"
        mode: '755'
        state: directory

    - name: Install certexp monitoring plugin
      when: monitoring_plugins__check_certexp
      block:

        - name: Install certexp monitoring plugin packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ monitoring_plugins__check_certexp_packages }}"

        - name: Copy certexp monitoring plugin to host
          ansible.builtin.copy:
            src: check_certexp.pl
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_certexp.pl"
            mode: '755'

        - name: Generate certexp monitoring plugin configuration file
          ansible.builtin.template:
            src: check_certexp.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_certexp.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install container stats (Docker) monitoring plugin
      when: monitoring_plugins__check_container_docker
      block:

        - name: Copy container stats monitoring plugin to host
          ansible.builtin.copy:
            src: check_container_stats_docker.py
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_container_stats_docker.py"
            mode: '755'

        - name: Generate container stats monitoring plugin configuration file
          ansible.builtin.template:
            src: check_container_stats_docker.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_container_stats_docker.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install container stats (podman) monitoring plugin
      when: monitoring_plugins__check_container_podman
      block:

        - name: Copy container stats monitoring plugin to host
          ansible.builtin.copy:
            src: check_container_stats_podman.py
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_container_stats_podman.py"
            mode: '755'

        - name: Generate container stats monitoring plugin configuration file
          ansible.builtin.template:
            src: check_container_stats_podman.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_container_stats_podman.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install nginx monitoring plugin
      when: monitoring_plugins__check_nginx
      block:

        - name: Install nginx monitoring plugin packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ monitoring_plugins__check_nginx_packages }}"

        - name: Copy nginx monitoring plugin to host
          ansible.builtin.copy:
            src: check_nginx_status.pl
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_nginx_status.pl"
            mode: '755'

        - name: Generate nginx monitoring plugin configuration file
          ansible.builtin.template:
            src: check_nginx_status.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_nginx_status.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install mem monitoring plugin
      when: monitoring_plugins__check_mem
      block:

        - name: Copy mem monitoring plugin to host
          ansible.builtin.copy:
            src: check_mem.pl
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_mem.pl"
            mode: '755'

        - name: Generate mem monitoring plugin configuration file
          ansible.builtin.template:
            src: check_mem.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_mem.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install phpfpm monitoring plugin
      when: monitoring_plugins__check_phpfpm
      block:

        - name: Install phpfpm monitoring plugin packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ monitoring_plugins__check_phpfpm_packages }}"

        - name: Copy phpfpm monitoring plugin to host
          ansible.builtin.copy:
            src: check_phpfpm_status.pl
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_phpfpm_status.pl"
            mode: '755'

        - name: Generate phpfpm monitoring plugin configuration file
          ansible.builtin.template:
            src: check_phpfpm_status.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_phpfpm_status.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install pushover notification plugin
      when: monitoring_plugins__pushover
      block:

        - name: Install pushover notification plugin packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ monitoring_plugins__pushover_packages }}"

        - name: Copy pushover notification plugin to host
          ansible.builtin.copy:
            src: pushover.pl
            dest: "{{ monitoring_plugins__plugin_local_dir }}/pushover.pl"
            mode: '755'

        - name: Generate pushover notification plugin configuration file
          ansible.builtin.template:
            src: pushover.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/pushover.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install reboot monitoring plugin
      when: monitoring_plugins__check_reboot
      block:

        - name: Install reboot monitoring plugin packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ monitoring_plugins__check_reboot_packages }}"

        - name: Copy reboot monitoring plugin to host
          ansible.builtin.copy:
            src: check_reboot
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_reboot"
            mode: '755'

        - name: Generate reboot monitoring plugin configuration file
          ansible.builtin.template:
            src: check_reboot.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_reboot.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'


    - name: Install Rocket.Chat notification plugin
      when: monitoring_plugins__rocketchat
      block:

        - name: Copy Rocket.Chat notification plugin to host
          ansible.builtin.copy:
            src: "{{ monitoring_plugins__rocketchat_plugin }}"
            dest: "{{ monitoring_plugins__plugin_local_dir }}/notify_rocketchat"
            mode: '755'

        - name: Generate Rocket.Chat notification plugin configuration file
          ansible.builtin.template:
            src: rocketchat.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/notifiy_rocketchat.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install systemd monitoring plugin
      when: monitoring_plugins__check_systemd
      block:

        - name: Install systemd monitoring plugin packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ monitoring_plugins__check_systemd_packages }}"

        - name: Copy systemd monitoring plugin to host
          ansible.builtin.copy:
            src: check_systemd.py
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_systemd.py"
            mode: '755'

        - name: Generate systemd monitoring plugin configuration file
          ansible.builtin.template:
            src: check_systemd.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_systemd.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'
