---

- name: Install and configure monitoring plugins
  tags: [ 'monitoring_plugins' ]
  block:

    - name: Create local monitoring plugins directory
      ansible.builtin.file:
        dest: "{{ monitoring_plugins__plugin_local_dir }}"
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Create Icinga monitoring plugins directory
      ansible.builtin.file:
        dest: "{{ monitoring_plugins__plugin_etc_dir }}"
        owner: "{{ monitoring_icinga_common__user }}"
        group: "{{ monitoring_icinga_common__group }}"
        mode: 0755
        state: directory

    - name: Install certexp monitoring plugin
      when: monitoring_plugins__check_certexp
      block:

        - name: Install certexp monitoring plugin packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ monitoring_plugins__check_certexp_packages }}"

        - name: Copy certexp monitoring plugin to host
          ansible.builtin.copy:
            src: check_certexp.pl
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_certexp.pl"
            mode: '755'

        - name: Generate certexp monitoring plugin configuration file
          ansible.builtin.template:
            src: check_certexp.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_certexp.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install mem monitoring plugin
      when: monitoring_plugins__check_mem
      block:

        - name: Copy mem monitoring plugin to host
          ansible.builtin.copy:
            src: check_mem.pl
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_mem.pl"
            mode: '755'

        - name: Generate mem monitoring plugin configuration file
          ansible.builtin.template:
            src: check_mem.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_mem.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install reboot monitoring plugin
      when: monitoring_plugins__check_reboot
      block:

        - name: Install reboot monitoring plugin packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ monitoring_plugins__check_reboot_packages }}"

        - name: Copy reboot monitoring plugin to host
          ansible.builtin.copy:
            src: check_reboot
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_reboot"
            mode: '755'

        - name: Generate reboot monitoring plugin configuration file
          ansible.builtin.template:
            src: check_reboot.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_reboot.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'

    - name: Install systemd monitoring plugin
      when: monitoring_plugins__check_systemd
      block:

        - name: Install systemd monitoring plugin packages
          ansible.builtin.apt:
            update_cache: yes
            install_recommends: no
            pkg: "{{ monitoring_plugins__check_systemd_packages }}"

        - name: Copy systemd monitoring plugin to host
          ansible.builtin.copy:
            src: check_systemd.py
            dest: "{{ monitoring_plugins__plugin_local_dir }}/check_systemd.py"
            mode: '755'

        - name: Generate systemd monitoring plugin configuration file
          ansible.builtin.template:
            src: check_systemd.conf.j2
            dest: "{{ monitoring_plugins__plugin_etc_dir }}/check_systemd.conf"
            owner: "{{ monitoring_icinga_common__user }}"
            group: "{{ monitoring_icinga_common__group }}"
            mode: '644'
