---

- name: 'Install and configure monitoring plugins'
  tags: [ 'monitoring_plugins' ]
  block:

    - name: 'Include OS-specific variables'
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"

    - name: 'Create local monitoring plugins directory'
      ansible.builtin.file:
        dest: "{{ monitoring_plugins__plugin_local_dir }}"
        owner: 'root'
        group: 'root'
        mode: '755'
        state: 'directory'

    - name: 'Create Icinga monitoring plugins directory'
      ansible.builtin.file:
        dest: "{{ monitoring_plugins__plugin_etc_dir }}"
        owner: "{{ monitoring_plugins__user }}"
        group: "{{ monitoring_plugins__group }}"
        mode: '755'
        state: 'directory'

    - name: 'Install certexp monitoring plugin'
      when: 'monitoring_plugins__check_certexp | bool'
      ansible.builtin.include_tasks:
        file: 'check_certexp.yml'

    - name: 'Install container stats (Docker) monitoring plugin'
      when: 'monitoring_plugins__check_docker | bool'
      ansible.builtin.include_tasks:
        file: 'check_docker.yml'

    - name: 'Install mem monitoring plugin'
      when: 'monitoring_plugins__check_mem | bool'
      ansible.builtin.include_tasks:
        file: 'check_mem.yml'

    - name: 'Install nginx monitoring plugin'
      when: 'monitoring_plugins__check_nginx | bool'
      ansible.builtin.include_tasks:
        file: 'check_nginx.yml'

    - name: 'Install phpfpm monitoring plugin'
      when: 'monitoring_plugins__check_phpfpm | bool'
      ansible.builtin.include_tasks:
        file: 'check_phpfpm.yml'

    - name: 'Install container stats (podman) monitoring plugin'
      when: 'monitoring_plugins__check_podman | bool'
      ansible.builtin.include_tasks:
        file: 'check_podman.yml'

    - name: 'Install reboot monitoring plugin'
      when: 'monitoring_plugins__check_reboot | bool'
      ansible.builtin.include_tasks:
        file: 'check_reboot.yml'

    - name: 'Install systemd monitoring plugin'
      when: 'monitoring_plugins__check_systemd | bool'
      ansible.builtin.include_tasks:
        file: 'check_systemd.yml'

    - name: 'Install pgactivity monitoring plugin'
      when: 'monitoring_plugins__check_pgactivity | bool'
      ansible.builtin.include_tasks:
        file: 'check_pgactivity.yml'

    - name: 'Install pushover notification plugin'
      when: 'monitoring_plugins__notification_pushover | bool'
      ansible.builtin.include_tasks:
        file: 'notification_pushover.yml'

    - name: 'Install Rocket.Chat notification plugin'
      when: 'monitoring_plugins__notification_rocketchat | bool'
      ansible.builtin.include_tasks:
        file: 'notification_rocketchat.yml'

    - name: 'Store MariaDB credentials'
      when: 'monitoring_plugins__credentials_mariadb | bool'
      ansible.builtin.include_tasks:
        file: 'credentials_mariadb.yml'

    - name: 'Store MySQL credentials'
      when: 'monitoring_plugins__credentials_mysql | bool'
      ansible.builtin.include_tasks:
        file: 'credentials_mysql.yml'
