---

- name: 'Copy Rocket.Chat notification plugin to host'
  ansible.builtin.copy:
    src: "{{ monitoring_plugins__rocketchat_plugin }}"
    dest: "{{ monitoring_plugins__plugin_local_dir }}/notify_rocketchat"
    mode: '755'

- name: 'Generate Rocket.Chat notification plugin configuration file'
  ansible.builtin.template:
    src: 'rocketchat.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/notifiy_rocketchat.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'
