---

- name: 'Install pushover notification plugin packages'
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ monitoring_plugins__pushover_packages }}"

- name: 'Copy pushover notification plugin to host'
  ansible.builtin.copy:
    src: 'pushover.pl'
    dest: "{{ monitoring_plugins__plugin_local_dir }}/pushover.pl"
    mode: '755'

- name: 'Generate pushover notification plugin configuration file'
  ansible.builtin.template:
    src: 'pushover.conf.j2'
    dest: "{{ monitoring_plugins__plugin_etc_dir }}/pushover.conf"
    owner: "{{ monitoring_plugins__user }}"
    group: "{{ monitoring_plugins__group }}"
    mode: '644'
