---

- name: Install and configure Icinga 2 PKI
  tags: [ 'monitoring_icinga_pki' ]
  block:

    - name: Create directory for SSL certificates
      ansible.builtin.file:
        dest: "{{ monitoring_icinga_pki__crt_dir }}"
        owner: "{{ monitoring_icinga_pki__user }}"
        group: "{{ monitoring_icinga_pki__group }}"
        mode: '700'
        state: directory

    - name: Copy SSL certificates to Icinga certificate directory
      when: not ansible_check_mode
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ monitoring_icinga_pki__crt_dir }}"
        owner: "{{ monitoring_icinga_pki__user }}"
        group: "{{ monitoring_icinga_pki__group }}"
        remote_src: yes
      with_items: "{{ monitoring_icinga_pki__certificate_files }}"
      notify:
        - Restart Icinga
