---

- name: 'Deploy Wallabag container'
  tags: [ 'app_wallabag' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: 'nobody'
        group: 'nogroup'
        mode: "{{ item.mode | default('0755') }}"
        state: 'directory'
      with_items:
        - dest: "{{ app_wallabag__podman_data_dir }}"
        - dest: "{{ app_wallabag__podman_images_dir }}"
        - dest: "{{ app_wallabag__podman_var_dir }}"

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: "{{ item.name }}"
        data: "{{ item.data }}"
      with_items:
        - name: 'wallabag_mysql_root_password'
          data: "{{ app_wallabag__mysql_root_password }}"
        - name: 'wallabag_postgres_password'
          data: "{{ app_wallabag__postgres_password }}"
        - name: 'wallabag_symfony_env_database_password'
          data: "{{ app_wallabag__db_pass }}"
        - name: 'wallabag_symfony_env_mailer_dsn'
          data: "{{ app_wallabag__mailer_dsn }}"
        - name: 'wallabag_symfony_env_secret'
          data: "{{ app_wallabag__secret }}"
      when: 'item.data | length > 0'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_wallabag__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_wallabag__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_wallabag__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_wallabag__container.name }}"
        hostname: "{{ app_wallabag__container.hostname }}"
        image: "{{ app_wallabag__container.image }}"
        ip: "{{ app_wallabag__container.ip }}"
        network: "{{ app_wallabag__container.network }}"
        timezone: "{{ app_wallabag__container.timezone }}"
        env: "{{ app_wallabag__container.environment }}"
        label: "{{ app_wallabag__container.labels }}"
        secrets: "{{ app_wallabag__container.secrets }}"
        volume: "{{ app_wallabag__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_wallabag__container.requires is defined %}
          Requires={{ app_wallabag__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_wallabag__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_wallabag__container.name }}"
        hostname: "{{ app_wallabag__container.hostname }}"
        image: "{{ app_wallabag__container.image }}"
        ip: "{{ app_wallabag__container.ip }}"
        ip6: "{{ app_wallabag__container.ipv6 }}"
        network: "{{ app_wallabag__container.network }}"
        timezone: "{{ app_wallabag__container.timezone }}"
        env: "{{ app_wallabag__container.environment }}"
        label: "{{ app_wallabag__container.labels }}"
        secrets: "{{ app_wallabag__container.secrets }}"
        volume: "{{ app_wallabag__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if app_wallabag__container.requires is defined %}
          Requires={{ app_wallabag__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'app_wallabag__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_wallabag__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'app_wallabag__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ app_wallabag__container.name }}"
        container_image: "{{ app_wallabag__container.image }}"
