---

- name: Deploy Wallabag container
  tags: [ 'app_wallabag' ]
  block:

    - name: Create Wallabag directories
      ansible.builtin.file:
        mode: '750'
        path: "{{ item }}"
        owner: 'nobody'
        group: 'nogroup'
        state: 'directory'
      with_items:
        - "{{ app_wallabag__data_dir }}"
        - "{{ app_wallabag__images_dir }}"
        - "{{ app_wallabag__var_dir }}"

# See: https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html
    - name: Create podman containers
      containers.podman.podman_container:
        name: "{{ app_wallabag__container.name }}"
        hostname: "{{ app_wallabag__container.hostname }}"
        image: "{{ app_wallabag__container.image }}"
        ip: "{{ app_wallabag__container.ip }}"
        network: "{{ app_wallabag__container.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ app_wallabag__container.restart_policy }}"
        etc_hosts: "{{ app_wallabag__container.hosts }}"
        env: "{{ app_wallabag__container.environment }}"
        timezone: "{{ app_wallabag__container.timezone }}"
        volume: "{{ app_wallabag__container.volumes | default([]) }}"
      when: app_wallabag__ipv6 | length == 0
