---

- name: Initial configuration
  tags: [ 'configuration' ]
  block:

  - name: Generate configuration files
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: etc/ldap/ldap.conf.j2
      dest: /etc/ldap/ldap.conf
    - src: etc/nslcd.conf.j2
      dest: /etc/nslcd.conf
    notify:
    - Restart nslcd
    - Restart nscd
    - Restart systemd-logind
