---

- name: Database initializiation
  tags: [ 'configuration', 'init' ]
  block:

  - name: Database already initialized?
    ansible.builtin.shell: "slapcat | wc -l"
    register: database_initialized_stat

  - name: Create database root entry
    when: database_initialized_stat.stdout | int == 0
    ansible.builtin.shell: |
      systemctl stop slapd
      echo "dn: ${LDAP__BASEDN}
      objectClass: top
      objectClass: dcObject
      objectClass: organization
      o: ${LDAP__ORGANIZATION}
      
      dn: ${LDAP_ROOTDN}
      objectclass: organizationalRole
      " | slapadd
      systemctl start slapd
    environment:
      LDAP__ROOTDN: "{{ ldap__server_root_dn }}"
      LDAP__BASEDN: "{{ ldap__server_base_dn }}"
      LDAP__ORGANIZATION: "{{ ldap__server_organization }}"

