---

- name: Install and configure ldap server
  tags: [ 'ldap' ]
  when: ldap__server_enable
  block:

  - name: Create directory for LDAP schema files
    ansible.builtin.file:
      dest: "{{ ldap__schema_dir }}"
      owner: openldap
      group: openldap
      mode: 0755
      state: directory

  - name: Maintain schema files
    tags: [ 'configuration', 'schema' ]
    include_tasks: schema.yml
    loop_control:
      loop_var: schema
    with_items: "{{ ldap__server_schema_combined }}"

  - name: Install ldap server packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ ldap__server_packages_combined }}"

  - name: Maintain configuration
    tags: [ 'configuration' ]
    include_tasks: config.yml

  - name: Maintain database
    tags: [ 'database' ]
    include_tasks: database.yml

  - name: Generate configuration file for shelldap
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "root/shelldap.rc.j2"
      dest: "/root/.shelldap.rc"
      owner: root
      group: root
      mode: 0640

- name: Install and configure ldap client
  tags: [ 'ldap' ]
  when: ldap__client_enable
  block:

  - name: Install ldap client packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ ldap__client_packages_combined }}"

  - name: Maintain configuration
    tags: [ 'configuration' ]
    include_tasks: client.yml
