---

- name: Install schema to LDAP server
  tags: [ 'schema' ]
  block:

  - name: "Is schema {{ schema }}  available on host?"
    ansible.builtin.stat:
      path: "{{ ldap__schema_dir }}/{{ schema }}.schema"
    register: schema_stat_result

  - name: "Copy schema {{ schema }} file"
    when: not schema_stat_result.stat.exists
    ansible.builtin.copy:
      src: "{{ ldap__schema_dir | regex_replace('^/', '') }}/{{ schema }}.schema"
      dest: "{{ ldap__schema_dir }}/{{ schema }}.schema"
      owner: root
      group: root
      mode: 0644
    register: schema_copy_result

  - name: "Is LDIF for schema {{ schema }}  available on host?"
    ansible.builtin.stat:
      path: "{{ ldap__schema_dir }}/{{ schema }}.ldif"
    register: schema_ldif_stat_result

  - name: "Create schema {{ schema }} LDIF file"
    when: not schema_ldif_stat_result.stat.exists or schema_copy_result.changed
    ansible.builtin.shell: "schema2ldif {{ ldap__schema_dir }}/{{ schema }}.schema | sed -e '/^#/d' > {{ ldap__schema_dir }}/{{ schema }}.ldif"
