---

- name: Install podman
  tags: [ 'podman' ]
  block:

    - name: Install podman packages
      ansible.builtin.apt:
        update_cache: 'yes'
        install_recommends: 'no'
        pkg: "{{ podman__packages }}"

    - name: Create podman networks
      containers.podman.podman_network:
        name: "{{ item.name }}"
        disable_dns: "{{ item.disable_dns | default(false) }}"
        driver: "{{ item.driver | default('bridge') }}"
        internal: "{{ item.internal | default(false) }}"
        net_config: "{{ [
          { 'gateway': item.gateway, 'subnet': item.address + '/' + item.netmask },
          { 'gateway': item.ipv6_gateway, 'subnet': item.ipv6_gateway + '/' + item.ipv6_prefixlength }
        ] if item.ipv6 | default(false) else [
          { 'gateway': item.gateway, 'subnet': item.address + '/' + item.netmask }
        ] }}"
        ipv6: "{{ item.ipv6 | default(false) }}"
      with_items: "{{ podman__networks }}"

