---

- name: 'Install Anubis'
  tags: [ 'webserver_anubis' ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ webserver_anubis__podman_home }}"

    - name: 'Generate simple configuration'
      ansible.builtin.copy:
        src: 'botPolicies.yaml'
        dest: "{{ webserver_anubis__podman_home }}"
      when: 'not podman___update_mode | bool and webserver_anubis__config | length == 0'
      notify: 'Restart Anubis container'

    - name: 'Generate configuration'
      ansible.builtin.copy:
        content: "{{ webserver_anubis__config | to_nice_yaml(indent=2) }}"
        dest: "{{ webserver_anubis__podman_home }}/botPolicies.yaml"
      when: 'not podman___update_mode | bool and webserver_anubis__config | length > 0'
      notify: 'Restart Anubis container'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ webserver_anubis__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[webserver_anubis__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ webserver_anubis__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ webserver_anubis__container.name }}"
        hostname: "{{ webserver_anubis__container.hostname }}"
        image: "{{ webserver_anubis__container.image }}"
        ip: "{{ webserver_anubis__container.ip }}"
        ip6: "{{ webserver_anubis__container.ipv6 | default(omit) }}"
        network: "{{ webserver_anubis__container.network }}"
        timezone: "{{ webserver_anubis__container.timezone }}"
        env: "{{ webserver_anubis__container.environment | default(omit) }}"
        etc_hosts: "{{ webserver_anubis__container.etc_hosts | default(omit) }}"
        expose: "{{ webserver_anubis__container.expose | default(omit) }}"
        label: "{{ webserver_anubis__container.labels | default(omit) }}"
        publish: "{{ webserver_anubis__container.publish | default(omit) }}"
        secrets: "{{ webserver_anubis__container.secrets | default(omit) }}"
        volume: "{{ webserver_anubis__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ webserver_anubis__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'webserver_anubis__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ webserver_anubis__container.name }}"
        container_image: "{{ webserver_anubis__container.image }}"
