---

- name: Install and configure chrony
  tags: [ 'chrony' ]
  when: chrony__enable
  block:

  - name: Install chrony packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ chrony__packages }}"

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode | default('644') }}"
    with_items:
    - src: etc/chrony/chrony.conf.j2
      dest: /etc/chrony/chrony.conf
    - src: etc/chrony/chrony.keys.j2
      dest: /etc/chrony/chrony.keys
      mode: 640
    - src: etc/default/chrony.j2
      dest: /etc/default/chrony
    notify:
    - Restart chrony

  - name: Enable service
    tags: [ 'configuration', 'service' ]
    ansible.builtin.service:
      name: chrony
      state: started
      enabled: yes
