---

- name: Restart pdns
  tags: [ 'service' ]
  when: powerdns__server_enable
  ansible.builtin.service:
    name: pdns
    state: restarted

- name: Restart pdns-recursor
  tags: [ 'service' ]
  when: powerdns__recursor_enable
  ansible.builtin.service:
    name: pdns-recursor
    state: restarted
