---

#
# Substitutes - do not change
#

matrix_bridge_whatsapp__hostname: "{{ matrix_bridge_whatsapp_hostname | default('mautrix-whatsapp.' + dns_hostname) }}"
matrix_bridge_whatsapp__ip: "{{ matrix_bridge_whatsapp_ip | mandatory }}"
matrix_bridge_whatsapp__ipv6: "{{ matrix_bridge_whatsapp_ipv6 | default('') }}"
matrix_bridge_whatsapp__network: "{{ matrix_bridge_whatsapp_network | mandatory }}"
matrix_bridge_whatsapp__hosts: "{{ matrix_bridge_whatsapp_hosts | default({}) }}"
matrix_bridge_whatsapp__timezone: "{{ matrix_bridge_whatsapp_timezone | default(bootstrap_timezone__timezone) }}"
matrix_bridge_whatsapp__home: "{{ matrix_bridge_whatsapp_home | mandatory }}"

matrix_bridge_whatsapp__dns_servers: "{{ matrix_bridge_whatsapp_dns_servers | default([]) }}"

matrix_bridge_whatsapp__setup: "{{ matrix_bridge_whatsapp_setup | default(true) }}"

matrix_bridge_whatsapp__version: "{{ matrix_bridge_whatsapp_version | default('latest') }}"
matrix_bridge_whatsapp__container: "{{ matrix_bridge_whatsapp__podman_container_default }}"

#
# Defaults - do not change
#

matrix_bridge_whatsapp__uid: 1337
matrix_bridge_whatsapp__gid: 1337

matrix_bridge_whatsapp__podman_image: 'dock.mau.dev/mautrix/whatsapp'

matrix_bridge_whatsapp__podman_container_default:
  name: 'mautrix-whatsapp'
  hostname: "{{ matrix_bridge_whatsapp__hostname }}"
  image: "{{ matrix_bridge_whatsapp__podman_image }}:{{ matrix_bridge_whatsapp__version }}"
  ip: "{{ matrix_bridge_whatsapp__ip }}"
  ipv6: "{{ matrix_bridge_whatsapp__ipv6 }}"
  network: "{{ matrix_bridge_whatsapp__network }}"
  restart_policy: 'always'
  hosts: "{{ matrix_bridge_whatsapp__hosts }}"
  dns_servers: "{{ matrix_bridge_whatsapp__dns_servers }}"
  environment:
    TZ: "{{ matrix_bridge_whatsapp__timezone }}"
  timezone: "{{ matrix_bridge_whatsapp__timezone }}"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - "{{ matrix_bridge_whatsapp__home }}:/data"
