---

- name: Install and configure jellyfin
  tags: [ 'jellyfin' ]
  when: jellyfin__enable
  block:

  - name: Install jellyfin packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ jellyfin__packages }}"

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: jellyfin
      group: jellyfin
      mode: 0644
    with_items:
    - src: etc/jellyfin/encoding.xml.j2
      dest: /etc/jellyfin/encoding.xml
    - src: etc/jellyfin/migrations.xml.j2
      dest: /etc/jellyfin/migrations.xml
    - src: etc/jellyfin/network.xml.j2
      dest: /etc/jellyfin/network.xml
    - src: etc/jellyfin/system.xml.j2
      dest: /etc/jellyfin/system.xml
