---

- name: Install and configure clamsmtpd
  tags: [ 'mail_clamsmtpd' ]
  block:

    - name: Install clamsmtpd
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ mail_clamsmtpd__packages }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: clamsmtpd.conf.j2
        dest: /etc/clamsmtpd.conf
        owner: root
        group: root
        mode: '644'
      notify:
        - Restart clamsmtpd
