---

- name: 'Deploy IcingaDB container'
  tags: [ 'monitoring_icinga_icingadb'  ]
  block:

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'icingadb_database_password'
        data: "{{ monitoring_icinga_icingadb__db_pass }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ monitoring_icinga_icingadb__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[monitoring_icinga_icingadb__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ monitoring_icinga_icingadb__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ monitoring_icinga_icingadb__container.name }}"
        hostname: "{{ monitoring_icinga_icingadb__container.hostname }}"
        image: "{{ monitoring_icinga_icingadb__container.image }}"
        ip: "{{ monitoring_icinga_icingadb__container.ip }}"
        network: "{{ monitoring_icinga_icingadb__container.network }}"
        timezone: "{{ monitoring_icinga_icingadb__container.timezone }}"
        env: "{{ monitoring_icinga_icingadb__container.environment }}"
        secrets: "{{ monitoring_icinga_icingadb__container.secrets }}"
        volume: "{{ monitoring_icinga_icingadb__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if monitoring_icinga_icingadb__container.requires is defined %}
          Requires={{ monitoring_icinga_icingadb__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'monitoring_icinga_icingadb__ipv6 | length == 0'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ monitoring_icinga_icingadb__container.name }}"
        hostname: "{{ monitoring_icinga_icingadb__container.hostname }}"
        image: "{{ monitoring_icinga_icingadb__container.image }}"
        ip: "{{ monitoring_icinga_icingadb__container.ip }}"
        ip6: "{{ monitoring_icinga_icingadb__container.ipv6 }}"
        network: "{{ monitoring_icinga_icingadb__container.network }}"
        timezone: "{{ monitoring_icinga_icingadb__container.timezone }}"
        env: "{{ monitoring_icinga_icingadb__container.environment }}"
        secrets: "{{ monitoring_icinga_icingadb__container.secrets }}"
        volume: "{{ monitoring_icinga_icingadb__container.volumes }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target
          
          [Service]
          RestartSec=5
          Restart=always
          
          [Unit]
          {% if monitoring_icinga_icingadb__container.requires is defined %}
          Requires={{ monitoring_icinga_icingadb__container.requires | join(' ') }}
          {% endif %}
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"
      when: 'monitoring_icinga_icingadb__ipv6 | length > 0'

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ monitoring_icinga_icingadb__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'
