---

- name: Create Icinga 2 configuration
  tags: [ 'monitoring_icinga_config' ]
  block:

    - name: Create directories for Icinga 2 configuration
      ansible.builtin.file:
        path: "{{ item }}"
        owner: "{{ monitoring_icinga_config__user }}"
        group: "{{ monitoring_icinga_config__group }}"
        state: 'directory'
      with_items:
        - "{{ monitoring_icinga_config__conf_dir }}"
        - "{{ monitoring_icinga_config__features_available_dir }}"
        - "{{ monitoring_icinga_config__features_enabled_dir }}"
        - "{{ monitoring_icinga_config__zones_dir }}"

    - name: Generate configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default(monitoring_icinga_config__user) }}"
        group: "{{ item.group | default(monitoring_icinga_config__group) }}"
        mode: "{{ item.mode | default('644') }}"
      with_items: "{{ monitoring_icinga_config__configuration_files }}"
      notify:
        - Restart Icinga

    - name: Create directories for zones
      ansible.builtin.file:
        dest: "{{ monitoring_icinga_config__zones_dir }}/{{ item.key }}"
        owner: "{{ monitoring_icinga_config__user }}"
        group: "{{ monitoring_icinga_config__group }}"
        mode: '755'
        state: 'directory'
      with_dict: "{{ monitoring_icinga_config__zone_hosts }}"

    - name: Generate host configuration files for zones
      ansible.builtin.template:
        src: 'hosts.conf.j2'
        dest: "{{ monitoring_icinga_config__zones_dir }}/{{ item.key }}/hosts.conf"
        owner: "{{ monitoring_icinga_config__user }}"
        group: "{{ monitoring_icinga_config__group }}"
        mode: '644'
      with_dict: "{{ monitoring_icinga_config__zone_hosts }}"
      vars:
        monitoring_icinga_config__hosts: "{{ item.value }}"
      notify:
        - Restart Icinga

    - name: Generate service configuration files for zones
      ansible.builtin.template:
        src: 'services.conf.j2'
        dest: "{{ monitoring_icinga_config__zones_dir }}/{{ item.key }}/services.conf"
        owner: "{{ monitoring_icinga_config__user }}"
        group: "{{ monitoring_icinga_config__group }}"
        mode: '644'
      with_dict: "{{ monitoring_icinga_config__zone_services }}"
      vars:
        monitoring_icinga_config__services: "{{ item.value }}"
      notify:
        - Restart Icinga

    - name: Remove obsolete configuration files
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'absent'
      with_items: "{{ monitoring_icinga_config__configuration_files_absent }}"
      notify:
        - Restart Icinga

    - name: Enable features
      ansible.builtin.file:
        src: "../features-available/{{ item }}.conf"
        dest: "{{ monitoring_icinga_config__features_enabled_dir }}/{{ item }}.conf"
        state: 'link'
      with_items: "{{ monitoring_icinga_config__features_enabled }}"
      notify:
        - Restart Icinga
