---

- name: 'Deploy Pi-hole container'
  tags: [ 'dns_pihole' ]
  block:

    - name: 'Create Pi-hole directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        state: 'directory'
        mode: '750'
      with_items:
        - "{{ dns_pihole__etc_dir }}"
        - "{{ dns_pihole__dnsmasq_dir }}"

    - name: 'Create podman container'
      containers.podman.podman_container:
        name: "{{ dns_pihole__container.name }}"
        hostname: "{{ dns_pihole__container.hostname }}"
        image: "{{ dns_pihole__container.image }}"
        ip: "{{ dns_pihole__container.ip }}"
        network: "{{ dns_pihole__container.network }}"
        restart_policy: "{{ dns_pihole__container.restart_policy }}"
        etc_hosts: "{{ dns_pihole__container.hosts }}"
        env: "{{ dns_pihole__container.environment }}"
        timezone: "{{ dns_pihole__container.timezone }}"
        publish: "{{ dns_pihole__container.publish }}"
        volume: "{{ dns_pihole__container.volumes }}"
        pull: 'always'
        cap_add:
          - 'cap_chown'
          - 'cap_net_bind_service'
          - 'cap_sys_nice'
        recreate: "{{ podman___update_mode | default(false) }}"
      when: dns_pihole__ipv6 | length == 0
