---

- name: 'Install Pi-hole'
  tags: [ 'dns_pihole' ]
  block:

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: 'webserver_api_password'
        data: "{{ dns_pihole__password }}"

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item }}"
        mode: '750'
        state: 'directory'
      with_items:
        - "{{ dns_pihole__podman_etc_dir }}"
        - "{{ dns_pihole__podman_dnsmasq_dir }}"
        - "{{ dns_pihole__podman_log_dir }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ dns_pihole__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[dns_pihole__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ dns_pihole__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ dns_pihole__container.name }}"
        hostname: "{{ dns_pihole__container.hostname }}"
        image: "{{ dns_pihole__container.image }}"
        ip: "{{ dns_pihole__container.ip }}"
        ip6: "{{ dns_pihole__container.ipv6 | default(omit) }}"
        network: "{{ dns_pihole__container.network }}"
        timezone: "{{ dns_pihole__container.timezone }}"
        env: "{{ dns_pihole__container.environment | default(omit) }}"
        etc_hosts: "{{ dns_pihole__container.etc_hosts | default(omit) }}"
        expose: "{{ dns_pihole__container.expose | default(omit) }}"
        label: "{{ dns_pihole__container.labels | default(omit) }}"
        publish: "{{ dns_pihole__container.publish | default(omit) }}"
        secrets: "{{ dns_pihole__container.secrets | default(omit) }}"
        volume: "{{ dns_pihole__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ dns_pihole__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode is defined and podman___update_mode else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'dns_pihole__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ dns_pihole__container.name }}"
        container_image: "{{ dns_pihole__container.image }}"
        container_schedule: "{{ dns_pihole__autoupdate_schedule }}"
