---
# tasks file for roles/cups

- name: Install and configure cups
  when: cups__enable
  block:

  - name: Install cups
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ cups__packages_combined }}"

  - name: Publish PPD files
    tags: [ 'configuration' ]
    ansible.builtin.copy:
      dest: "{{ cups__etc_dir }}/ppd/{{ item.ppd }}"
      src: "etc/cups/ppd/{{ item.ppd }}"
      owner: root
      group: lp
      mode: 0640
    with_items: "{{ cups__printers }}"

  - name: Generate cupsd.conf
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/cups/cupsd.conf.j2
      dest: "{{ cups__etc_dir }}/cupsd.conf"
      owner: root
      group: root
      mode: 0644
    vars:
      cups__locations: "{{ cups__locations_combined }}"
    notify:
    - Restart cups

  - name: Generate printers.conf
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/cups/printers.conf.j2
      dest: "{{ cups__etc_dir }}/printers.conf"
      owner: root
      group: lp
      mode: 0600
    notify:
    - Restart cups

  - name: Copy SSL certificates for realm
    tags: [ 'configuration' ]
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: true
      owner: root
      group: lp
      mode: 0600
    with_items:
    - src: "{{ pki__realms_dir }}/{{ cups__ssl_certificate }}/private/{{ cups__ssl_certificate }}.key"
      dest: "{{ cups__etc_dir }}/ssl/{{ cups__ssl_certificate }}.key"
    - src: "{{ pki__realms_dir }}/{{ cups__ssl_certificate }}/public/{{ cups__ssl_certificate }}.crt"
      dest: "{{ cups__etc_dir }}/ssl/{{ cups__ssl_certificate }}.crt"
    notify:
    - Restart cups
