---
# tasks file for roles/cups

- name: Install cups
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ cups__packages_combined }}"

- name: Publish PPD files
  ansible.builtin.copy:
    dest: "/etc/cups/ppd/{{ item.ppd }}"
    src: "etc/cups/ppd/{{ item.ppd }}"
    owner: root
    group: lp
    mode: 0640
  with_items: "{{ cups__printers }}"

- name: Generate cupsd.conf
  ansible.builtin.template:
    src: etc/cups/cupsd.conf.j2
    dest: /etc/cups/cupsd.conf
    owner: root
    group: root
    mode: 0644
  vars:
    browsing: "{{ cups__browsing }}"
    web_interface: "{{ cups__web_interface }}"
    listen: "{{ cups__listen }}"
    locations: "{{ cups__locations }}"
  notify:
  - Restart cups

- name: Generate printers.conf
  ansible.builtin.template:
    src: etc/cups/printers.conf.j2
    dest: /etc/cups/printers.conf
    owner: root
    group: lp
    mode: 0600
  vars:
    printers: "{{ cups__printers }}"
  notify:
  - Restart cups
