---
# tasks file for roles/cups

- name: Install and configure cups
  when: cups__enable
  block:

  - name: Install cups
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ cups__packages_combined }}"

  - name: Publish PPD files
    tags: [ 'configuration' ]
    ansible.builtin.copy:
      dest: "/etc/cups/ppd/{{ item.ppd }}"
      src: "etc/cups/ppd/{{ item.ppd }}"
      owner: root
      group: lp
      mode: 0640
    with_items: "{{ cups__printers }}"

  - name: Generate cupsd.conf
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/cups/cupsd.conf.j2
      dest: /etc/cups/cupsd.conf
      owner: root
      group: root
      mode: 0644
    vars:
      cups__locations: "{{ cups__locations_combined }}"
    notify:
    - Restart cups

  - name: Generate printers.conf
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/cups/printers.conf.j2
      dest: /etc/cups/printers.conf
      owner: root
      group: lp
      mode: 0600
    notify:
    - Restart cups
