---

- name: Configure unattended upgrades
  tags: [ 'apt_unattended_upgrades'  ]
  block:

    - name: Install unattended upgrades packages
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg: "{{ apt_unattended_upgrades__packages }}"

    - name: Generate unattended upgrades configuration file
      ansible.builtin.template:
        src: 50unattended-upgrades.j2
        dest: "{{ apt_unattended_upgrades__conf_dir }}/50unattended-upgrades"
        owner: root
        group: root
        mode: '644'
