---

- name: 'Install InfluxDB'
  tags: [ 'database_influxdb_core'  ]
  block:

    - name: 'Create directories'
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        owner: "{{ database_influxdb_core__uid }}"
        group: "{{ database_influxdb_core__gid }}"
        mode: "{{ item.mode | default('0700') }}"
        state: 'directory'
      with_items:
        - dest: "{{ database_influxdb_core__podman_data_dir }}"
        - dest: "{{ database_influxdb_core__podman_plugins_dir }}"
        - dest: "{{ database_influxdb_core__podman_backup_dir }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ database_influxdb_core__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[database_influxdb_core__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ database_influxdb_core__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ database_influxdb_core__container.name }}"
        hostname: "{{ database_influxdb_core__container.hostname }}"
        image: "{{ database_influxdb_core__container.image }}"
        ip: "{{ database_influxdb_core__container.ip }}"
        ip6: "{{ database_influxdb_core__container.ipv6 | default(omit) }}"
        network: "{{ database_influxdb_core__container.network }}"
        timezone: "{{ database_influxdb_core__container.timezone }}"
        env: "{{ database_influxdb_core__container.environment | default(omit) }}"
        etc_hosts: "{{ database_influxdb_core__container.etc_hosts | default(omit) }}"
        label: "{{ database_influxdb_core__container.labels | default(omit) }}"
        publish: "{{ database_influxdb_core__container.publish | default(omit) }}"
        expose: "{{ database_influxdb_core__container.expose | default(omit) }}"
        secrets: "{{ database_influxdb_core__container.secrets | default(omit) }}"
        volume: "{{ database_influxdb_core__container.volumes | default(omit) }}"
        command: "{{ database_influxdb_core__container.command | default(omit) }}"
        quadlet_options: |
          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ database_influxdb_core__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode | bool else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Wait for InfluxDB port to be opened'
      ansible.builtin.wait_for:
        host: "{{ database_influxdb_core__container.ip }}"
        port: "{{ database_influxdb_core__port }}"

    - name: 'Enable autoupdate on container'
      when: 'database_influxdb_core__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ database_influxdb_core__container.name }}"
        container_image: "{{ database_influxdb_core__container.image }}"
