---

- name: 'Deploy Collabora container'
  tags: [ 'app_collabora' ]
  block:

    - name: 'Create secrets'
      no_log: true
      containers.podman.podman_secret:
        state: 'present'
        name: "{{ item.name }}"
        data: "{{ item.data }}"
      with_items:
        - name: 'collabora_password'
          data: "{{ app_collabora__password }}"

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ app_collabora__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[app_collabora__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ app_collabora__container.image }}"
        force: true
      when: 'podman___update_mode | bool'

    - name: 'Install container'
      containers.podman.podman_container:
        name: "{{ app_collabora__container.name }}"
        hostname: "{{ app_collabora__container.hostname }}"
        image: "{{ app_collabora__container.image }}"
        ip: "{{ app_collabora__container.ip }}"
        ip6: "{{ app_collabora__container.ipv6 | default(omit) }}"
        network: "{{ app_collabora__container.network }}"
        timezone: "{{ app_collabora__container.timezone }}"
        env: "{{ app_collabora__container.environment | default(omit) }}"
        label: "{{ app_collabora__container.labels | default(omit) }}"
        secrets: "{{ app_collabora__container.secrets | default(omit) }}"
        volume: "{{ app_collabora__container.volumes | default(omit) }}"
        cap_add:
          - 'SYS_CHROOT'
          - 'SYS_ADMIN'
          - 'FOWNER'
          - 'CHOWN'
          - 'MKNOD'
        quadlet_options: |
          PodmanArgs=--no-healthcheck

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ app_collabora__container.name }}"
        daemon_reload: true
        state: 'started'
        enabled: true
      when: 'not ansible_check_mode'

    - name: 'Enable autoupdate on container'
      when: 'app_collabora__autoupdate_enabled'
      include_role:
        name: 'container_update'
      vars:
        container_name: "{{ app_collabora__container.name }}"
        container_image: "{{ app_collabora__container.image }}"
