---
# tasks file for roles/pki

- name: Install pki ACME packages
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ pki__acme_packages_combined }}"
  when: pki__acme_enable
  tags:
  - pki
  - acme
  - packages

- name: Register or update ACME account
  ansible.builtin.shell: |
    certbot update_account {{ pki__acme_register_options }} || certbot register {{ pki__acme_register_options }}
  environment: "{{ pki__acme_environment }}"
  when: pki__acme_email | length > 0
  tags:
  - pki
  - acme
