---

- name: Install pki ACME packages
  tags: [ 'packages' ]
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ pki__acme_packages_combined }}"

- name: Register or update ACME account
  tags: [ 'configuration' ]
  when: pki__acme_email | length > 0
  ansible.builtin.shell: |
    certbot update_account {{ pki__acme_register_options }} || certbot register {{ pki__acme_register_options }}
  environment: "{{ pki__acme_environment }}"
