---
# tasks file for roles/pki

- name: Create secrets directory
  tags: [ 'local' ]
  become: false
  local_action:
    module: ansible.builtin.file
    path: "{{ pki__secrets_dir }}"
    state: directory
    mode: 0750

- name: Is Easy-RSA PKI initialized?
  tags: [ 'local' ]
  become: false
  local_action:
    module: ansible.builtin.stat
    path: "{{ pki__secrets_dir }}/safessl-easyrsa.cnf"
  register: easyrsa_pki_stat_result

- name: Is Easy-RSA CA initialized?
  tags: [ 'local' ]
  become: false
  local_action:
    module: ansible.builtin.stat
    path: "{{ pki__secrets_dir }}/ca.crt"
  register: easyrsa_ca_stat_result

- name: Init Easy-RSA PKI
  tags: [ 'local' ]
  when: not easyrsa_pki_stat_result.stat.exists
  become: false
  local_action:
    module: ansible.builtin.command
    chdir: "{{ pki__secrets_dir }}"
    cmd: "{{ pki__easyrsa_path }} init-pki"
  environment: "{{ pki__easyrsa_environment }}"

- name: Create Easy-RSA CA
  tags: [ 'local' ]
  when: not easyrsa_ca_stat_result.stat.exists
  become: false
  local_action:
    module: ansible.builtin.command
    chdir: "{{ pki__secrets_dir }}"
    cmd: "{{ pki__easyrsa_path }} build-ca"
  environment: "{{ pki__easyrsa_environment }}"

- name: Keep Eays-RSA directories in git
  tags: [ 'local' ]
  when: not easyrsa_pki_stat_result.stat.exists
  become: false
  local_action:
    module: ansible.builtin.file
    dest: "{{ pki__secrets_dir }}/{{ item }}/.gitkeep"
    state: touch
  environment: "{{ pki__easyrsa_environment }}"
  with_items: "{{ pki__easyrsa_directories_gitkeep }}"
