---
# tasks file for roles/pki

- name: Create secrets directory
  local_action:
    module: ansible.builtin.file
    path: "{{ pki__secrets_dir }}"
    state: directory
    mode: 0750
  become: false
  tags:
  - local
  - easyrsa

- name: Is Easy-RSA PKI initialized?
  local_action:
    module: ansible.builtin.stat
    path: "{{ pki__secrets_dir }}/safessl-easyrsa.cnf"
  register: easyrsa_pki_stat_result
  become: false
  tags:
  - local
  - easyrsa

- name: Is Easy-RSA CA initialized?
  local_action:
    module: ansible.builtin.stat
    path: "{{ pki__secrets_dir }}/ca.crt"
  register: easyrsa_ca_stat_result
  become: false
  tags:
  - local
  - easyrsa

- name: Init Easy-RSA PKI
  local_action:
    module: ansible.builtin.command
    chdir: "{{ pki__secrets_dir }}"
    cmd: "{{ pki__easyrsa_path }} init-pki"
  become: false
  environment: "{{ pki__easyrsa_environment }}"
  when: not easyrsa_pki_stat_result.stat.exists
  tags:
  - local
  - easyrsa

- name: Create Easy-RSA CA
  local_action:
    module: ansible.builtin.command
    chdir: "{{ pki__secrets_dir }}"
    cmd: "{{ pki__easyrsa_path }} build-ca"
  become: false
  environment: "{{ pki__easyrsa_environment }}"
  when: not easyrsa_ca_stat_result.stat.exists
  tags:
  - local
  - easyrsa
