---
# tasks file for roles/pki

- name: Install pki packages
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items: "{{ pki__packages_combined }}"
  tags:
  - pki
  - packages

- name: Create pki directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
  - "{{ pki__root_dir }}"
  - "{{ pki__realms_dir }}"
  tags:
  - pki
  - bootstrap

- name: Prepare for ACME
  include: acme.yml
  when: pki__acme_enable
  tags:
  - pki
  - acme
  - bootstrap

- name: Prepare for Easy-RSA
  include: easyrsa.yml
  when: pki__easyrsa_enable
  tags:
  - pki
  - easyrsa
  - bootstrap

- name: Create realms
  include: realm.yml
  with_items: "{{ pki__realms }}"
  loop_control:
    loop_var: realm
