---
# tasks file for roles/pki

- name: Install and configure PKI
  tags: [ 'pki' ]
  when: pki__enable
  block:

  - name: Install pki packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ pki__packages_combined }}"

  - name: Create pki directories
    tags: [ 'bootstrap' ]
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
    - "{{ pki__root_dir }}"
    - "{{ pki__realms_dir }}"

- name: Install and configure ACME
  tags: [ 'pki', 'acme', 'init' ]
  when: pki__enable and pki__acme_enable
  include: acme_init.yml

- name: Install and configure Easy-RSA
  tags: [ 'pki', 'easyrsa', 'init' ]
  when: pki__enable and pki__easyrsa_enable
  run_once: yes
  include: easyrsa_init.yml

- name: Create realms
  tags: [ 'pki' ]
  when: pki__enable
  include: realm.yml
  loop_control:
    loop_var: realm
  with_items: "{{ pki__realms }}"
