---
# tasks file for roles/pki

- name: "Has certificate for {{ realm.name }} been generated?"
  local_action:
    module: ansible.builtin.stat
    path: "{{ pki__secrets_dir }}/issued/{{ realm.name }}.crt"
  register: easyrsa_realm_stat_result
  become: false
  tags:
  - local
  - easyrsa

- name: "Create server certificate for {{ realm.name }}"
  local_action:
    module: ansible.builtin.command
    chdir: "{{ pki__secrets_dir }}"
    cmd: "{{ pki__easyrsa_path }} build-server-full {{ realm.name }}"
  become: false
  environment: "{{ pki__easyrsa_environment | combine(realm.easyrsa_environment) }}"
  when: not easyrsa_realm_stat_result.stat.exists and realm.easyrsa_type == 'server'
  tags:
  - local
  - easyrsa

- name: "Create client certificate for {{ realm.name }}"
  local_action:
    module: ansible.builtin.command
    chdir: "{{ pki__secrets_dir }}"
    cmd: "{{ pki__easyrsa_path }} build-server-full {{ realm.name }}"
  become: false
  environment: "{{ pki__easyrsa_environment | combine(realm.easyrsa_environment) }}"
  when: not easyrsa_realm_stat_result.stat.exists and realm.easyrsa_type == 'client'
  tags:
  - local
  - easyrsa

- name: "Copy private key for {{ realm.name }}"
  ansible.builtin.copy:
    src: "{{ pki__secrets_dir }}/private/{{ realm.name }}.key"
    dest: "{{ pki__realms_dir }}/{{ realm.name }}/private/{{ realm.name }}.key"
    owner: root
    group: "{{ pki__private_group }}"
    mode: "{{ pki__private_file_mode }}"
  tags:
  - pki
  - certificate
  - easyrsa

- name: "Copy certificate for {{ realm.name }}"
  ansible.builtin.copy:
    src: "{{ pki__secrets_dir }}/issued/{{ realm.name }}.crt"
    dest: "{{ pki__realms_dir }}/{{ realm.name }}/public/{{ realm.name }}.crt"
    owner: root
    group: "{{ pki__public_group }}"
    mode: "{{ pki__public_file_mode }}"
  tags:
  - pki
  - certificate
  - easyrsa

- name: "Copy CA certificate for {{ realm.name }}"
  ansible.builtin.copy:
    src: "{{ pki__secrets_dir }}/ca.crt"
    dest: "{{ pki__realms_dir }}/{{ realm.name }}/public/ca.crt"
    owner: root
    group: "{{ pki__public_group }}"
    mode: "{{ pki__public_file_mode }}"
  tags:
  - pki
  - certificate
  - easyrsa
