---
# tasks file for roles/pki

- name: Create realm directory
  ansible.builtin.file:
    path: "{{ pki__realms_dir }}/{{ realm.name }}"
    state: directory
    owner: root
    group: "{{ pki__public_group }}"
    mode: "{{ pki__public_dir_mode }}"

- name: Create realm structure directories
  ansible.builtin.file:
    path: "{{ pki__realms_dir }}/{{ realm.name }}/{{ item.name }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ pki__realm_structure }}"

- name: Create Easy-RSA certificate for realm
  include: realm-easyrsa.yml
  when: pki__easyrsa_enable and realm.easyrsa | default(false)

- name: Create ACME certificate for realm
  include: realm-acme.yml
  when: pki__acme_enable and realm.acme | default(false)
