---
# tasks file for roles/pki

- name: "Has certificate for realm {{ realm.name }} been aquired?"
  ansible.builtin.stat:
    path: "{{ pki__acme_renewal_dir }}/{{ realm.name }}.conf"
  register: acme_realm_stat_result
  tags:
  - pki
  - acme

- name: "Aquire ACME certificate for realm {{ realm.name }}"
  ansible.builtin.command:
    cmd: "certbot run {{ pki__acme_global_options }} --cert-name {{ realm.name }} -d {{ realm.domains | join(' -d ') }} --rsa-key-size {{ realm.key_size | default(2048) }}"
  environment: "{{ pki__acme_environment }}"
  when: not acme_realm_stat_result.stat.exists
  tags:
  - pki
  - acme
