---

- name: Install and configure awstats
  tags: [ 'statistics', 'awstats' ]
  when: statistics__awstats_enable
  block:
  - name: Install awstats packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ statistics__awstats_packages }}"

  - name: Generate configuration for awstats
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: etc/awstats/awstats.conf.local.j2
      dest: "{{ statistics__awstats_etc_dir }}/awstats.conf.local"

  - name: Generate configuration for sites
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: etc/awstats/awstats.conf.template.j2
      dest: "{{ statistics__awstats_etc_dir }}/awstats.{{ item.key }}.conf"
      owner: root
      group: root
      mode: 0644
    vars:
      log: "{{ item.value }}"
    loop: "{{ statistics__awstats_conf | dict2items }}"

  - name: Remove obsolete configuration files
    tags: [ 'bootstrap', 'configuration' ]
    ansible.builtin.file:
      dest: "{{ item }}"
      state: absent
    with_items: "{{ statistics__awstats_files_absent }}"
