---

- name: Install and configure awstats
  tags: [ 'statistics', 'awstats' ]
  when: statistics__awstats_enable
  block:
  - name: Install awstats packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ statistics__awstats_packages }}"
