---

- name: Install and configure vnstat
  tags: [ 'statistics', 'vnstat' ]
  when: statistics__vnstat_enable
  block:
  - name: Install vnstat packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ statistics__vnstat_packages }}"
  
- name: Generate configuration files
  tags: [ 'configuration' ]
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - src: etc/vnstat.conf.j2
    dest: /etc/vnstat.conf
  - src: etc/default/vnstat.j2
    dest: /etc/default/vnstat
  - src: etc/systemd/system/server-statistics.service.j2
    dest: /etc/systemd/system/server-statistics.service
  - src: etc/systemd/system/server-statistics.timer.j2
    dest: /etc/systemd/system/server-statistics.timer
  notify:
  - Restart vnstat

- name: Install server statistics generation
  copy:
    src: vnstatgen
    dest: /usr/local/bin/vnstatgen
    owner: root
    group: root
    mode: 0755

- name: Enable vnstat service
  tags: [ 'configuration', 'service' ]
  ansible.builtin.service:
    name: vnstat
    state: started
    enabled: yes

- name: Enable vnstatgen server-statistics
  tags: [ 'configuration', 'service' ]
  when: not ansible_check_mode
  ansible.builtin.systemd:
    name: server-statistics.timer
    state: started
    daemon_reload: yes
    enabled: yes
