---

- name: Install and configure vnstat
  tags: [ 'statistics', 'vnstat' ]
  when: statistics__vnstat_enable
  block:
  - name: Install vnstat packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ statistics__vnstat_packages }}"
