---

- name: Install and configure DMARC
  tags: [ 'postfix', 'dkim' ]
  when: postfix__dmarc_enable
  block:

  - name: Install DMARC packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ postfix__dmarc_packages }}"

  - name: Create DMARC directory
    ansible.builtin.file:
      dest: "{{ postfix__dmarc_opendmarc_etc_path }}"
      state: directory
      owner: opendmarc
      group: opendmarc
      mode: 0755

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: etc/default/opendmarc.j2
      dest: /etc/default/opendmarc
    - src: etc/opendmarc.conf.j2
      dest: /etc/opendmarc.conf
    notify:
    - Restart opendmarc
