---

- name: Install and configure postgrey
  tags: [ 'postfix', 'postgrey' ]
  when: postfix__postgrey_enable
  block:

  - name: Install postgrey packages
    tags: [ 'packages' ]
    ansible.builtin.apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items: "{{ postfix__postgrey_packages }}"

  - name: Generate configuration files
    tags: [ 'configuration' ]
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
    - src: etc/default/postgrey.j2
      dest: /etc/default/postgrey
    notify:
    - Restart postgrey
