---

- name: Install mqttbroker
  tags: [ 'smarthome_mqttbroker' ]
  block:

    - name: Create mqttbroker directories
      ansible.builtin.file:
        mode: '755'
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ smarthome_mqttbroker__home }}"

    - name: Generate mqttbroker configuration files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('644') }}"
      with_items:
        - src: mqttbroker.conf.j2
          dest: "{{ smarthome_mqttbroker__config_file }}"
      notify:
        - Restart mqttbroker container

    - name: Install mqttbroker container
      containers.podman.podman_container:
        name: "{{ smarthome_mqttbroker__container.name }}"
        hostname: "{{ smarthome_mqttbroker__container.hostname }}"
        image: "{{ smarthome_mqttbroker__container.image }}"
        ip: "{{ smarthome_mqttbroker__container.ip }}"
        network: "{{ smarthome_mqttbroker__container.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ smarthome_mqttbroker__container.restart_policy }}"
        etc_hosts: "{{ smarthome_mqttbroker__container.hosts }}"
        timezone: "{{ smarthome_mqttbroker__container.timezone }}"
        volume: "{{ smarthome_mqttbroker__container.volumes }}"
      when: smarthome_mqttbroker__ipv6 | length == 0
