---

- name: 'Install coe2mqtt'
  tags: [ 'smarthome_coe2mqtt' ]
  block:

    - name: 'Create coe2mqtt directories'
      ansible.builtin.file:
        mode: '755'
        path: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ smarthome_coe2mqtt__home }}"

    - name: 'Generate coe2mqtt configuration files'
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('644') }}"
      with_items:
        - src: 'coe2mqtt.conf.j2'
          dest: "{{ smarthome_coe2mqtt__config_file }}"
      notify:
        - 'Restart coe2mqtt container'

    - name: 'Install coe2mqtt container'
      containers.podman.podman_container:
        name: "{{ smarthome_coe2mqtt__container.name }}"
        hostname: "{{ smarthome_coe2mqtt__container.hostname }}"
        image: "{{ smarthome_coe2mqtt__container.image }}"
        ip: "{{ smarthome_coe2mqtt__container.ip }}"
        network: "{{ smarthome_coe2mqtt__container.network }}"
        recreate: "{{ podman___update_mode | default(false) }}"
        restart_policy: "{{ smarthome_coe2mqtt__container.restart_policy }}"
        etc_hosts: "{{ smarthome_coe2mqtt__container.hosts }}"
        timezone: "{{ smarthome_coe2mqtt__container.timezone }}"
        volume: "{{ smarthome_coe2mqtt__container.volumes }}"
        pull: 'always'
      when: 'smarthome_coe2mqtt__ipv6 | length == 0'
