---

- name: 'Install coe2mqtt'
  tags: [ 'smarthome_coe2mqtt' ]
  block:

    - name: 'Create coe2mqtt directories'
      ansible.builtin.file:
        mode: '755'
        path: "{{ item }}"
        state: 'directory'
      with_items:
        - "{{ smarthome_coe2mqtt__podman_home }}"

    - name: 'Generate configuration'
      ansible.builtin.copy:
        content: "{{ smarthome_coe2mqtt__config | to_nice_json(indent=4) }}"
        dest: "{{ smarthome_coe2mqtt__podman_home }}/coe2mqtt.conf"
        mode: '400'
      notify:
        - 'Restart coe2mqtt container'

    - name: 'Gathering facts about services...'
      ansible.builtin.service_facts:

    - name: 'Stop container when it is running'
      ansible.builtin.systemd:
        name: "{{ smarthome_coe2mqtt__container.name }}.service"
        state: 'stopped'
      when: 'ansible_facts.services[smarthome_coe2mqtt__container.name + ".service"] is defined and podman___update_mode | bool'

    - name: 'Pull image'
      containers.podman.podman_image:
        name: "{{ smarthome_coe2mqtt__container.image }}"
        force: true
      when: 'podman___update_mode'

    - name: 'Install coe2mqtt container'
      containers.podman.podman_container:
        name: "{{ smarthome_coe2mqtt__container.name }}"
        hostname: "{{ smarthome_coe2mqtt__container.hostname }}"
        image: "{{ smarthome_coe2mqtt__container.image }}"
        ip: "{{ smarthome_coe2mqtt__container.ip }}"
        ip6: "{{ smarthome_coe2mqtt__container.ipv6 | default(omit) }}"
        network: "{{ smarthome_coe2mqtt__container.network }}"
        timezone: "{{ smarthome_coe2mqtt__container.timezone }}"
        env: "{{ smarthome_coe2mqtt__container.environment | default(omit) }}"
        etc_hosts: "{{ smarthome_coe2mqtt__container.etc_hosts | default(omit) }}"
        expose: "{{ smarthome_coe2mqtt__container.expose | default(omit) }}"
        label: "{{ smarthome_coe2mqtt__container.labels | default(omit) }}"
        publish: "{{ smarthome_coe2mqtt__container.publish | default(omit) }}"
        secrets: "{{ smarthome_coe2mqtt__container.secrets | default(omit) }}"
        volume: "{{ smarthome_coe2mqtt__container.volumes | default(omit) }}"
        quadlet_options: |

          [Install]
          WantedBy=default.target

          [Service]
          RestartSec=5
          Restart=always
        restart_policy: 'no'
        state: 'quadlet'
        recreate: "{{ podman___update_mode | bool }}"

    - name: 'Start and enable container'
      ansible.builtin.systemd:
        name: "{{ smarthome_coe2mqtt__container.name }}"
        daemon_reload: true
        state: "{{ 'restarted' if podman___update_mode is defined and podman___update_mode else 'started' }}"
        enabled: true
      when: 'not ansible_check_mode'
