---

- name: 'Register or update ACME account'
  ansible.builtin.shell: |
    {{ pki_certbot__command}} show_account \
      --server {{ item.value }} \ 
    || \
    {{ pki_certbot__command}} register \
      --server {{ item.value }} {{ pki_certbot__command_register_options }}
  with_dict: "{{ pki_certbot__provider_server }}"
  when: 'pki_certbot__email | length > 0'
