---

- name: Currently not supported
  ansible.builtin.fail:
    msg: Currently not supported

- name: Install pki packages
  ansible.builtin.apt:
    update_cache: yes
    install_recommends: no
    pkg: "{{ pki_certbot__packages }}"
