---

- name: 'Install Certbot'
  tags: [ 'pki_certbot' ]
  block:

    - name: 'Install Certbot using package management'
      ansible.builtin.include_tasks:
        file: 'apt.yml'
      when: 'not pki_certbot__use_podman and not pki_certbot___certificates_only'

    - name: 'Install Certbot using podman'
      ansible.builtin.include_tasks:
        file: 'podman.yml'
      when: 'pki_certbot__use_podman and not pki_certbot___certificates_only'

    - name: 'Register or update ACME accounts'
      ansible.builtin.include_tasks:
        file: 'accounts.yml'
      when: 'not pki_certbot___certificates_only and not podman___update_mode'

    - name: 'Create certificates'
      ansible.builtin.include_tasks:
        file: 'realms.yml'
      when: 'not podman___update_mode'
