---

- name: 'Create directories'
  ansible.builtin.file:
    mode: '755'
    path: "{{ item }}"
    state: 'directory'
  with_items:
    - "{{ pki_certbot__podman_etc_dir }}"
    - "{{ pki_certbot__podman_lib_dir }}"
    - "{{ pki_certbot__podman_log_dir }}"

- name: 'Copy CA certificates bundle'
  ansible.builtin.copy:
    src: '/etc/ssl/certs/ca-certificates.crt'
    dest: "{{ pki_certbot__podman_etc_dir }}/ca-bundle.pem"
    remote_src: true

- name: 'Create configuration files for plugins'
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ pki_certbot__podman_etc_dir }}/{{ item }}"
    mode: '400'
  with_items: "{{ pki_certbot__plugins }}"

- name: 'Gathering facts about services...'
  ansible.builtin.service_facts:

- name: 'Stop container when it is running'
  ansible.builtin.systemd:
    name: "{{ pki_certbot__container.name }}.service"
    state: 'stopped'
  when: 'ansible_facts.services[pki_certbot__container.name + ".service"] is defined'

- name: 'Pull image'
  containers.podman.podman_image:
    name: "{{ pki_certbot__podman_image }}"
    tag: "{{ pki_certbot__podman_tag }}"
    force: true
  when: 'podman___update_mode | bool'

- name: 'Install container'
  containers.podman.podman_container:
    name: "{{ pki_certbot__container.name }}"
    hostname: "{{ pki_certbot__container.hostname }}"
    image: "{{ pki_certbot__container.image }}"
    ip: "{{ pki_certbot__container.ip }}"
    network: "{{ pki_certbot__container.network }}"
    timezone: "{{ pki_certbot__container.timezone }}"
    volume: "{{ pki_certbot__container.volumes }}"
    quadlet_options: |

      [Install]
      WantedBy=default.target

      [Service]
      RestartSec=5
      Restart=on-failure
    entrypoint: "{{ pki_certbot__podman_command }}"
    restart_policy: 'no'
    state: 'quadlet'
    recreate: "{{ podman___update_mode | default(false) }}"
  when: 'pki_certbot__ipv6 | length == 0'

- name: 'Install container'
  containers.podman.podman_container:
    name: "{{ pki_certbot__container.name }}"
    hostname: "{{ pki_certbot__container.hostname }}"
    image: "{{ pki_certbot__container.image }}"
    ip: "{{ pki_certbot__container.ip }}"
    ip6: "{{ pki_certbot__container.ipv6 }}"
    network: "{{ pki_certbot__container.network }}"
    timezone: "{{ pki_certbot__container.timezone }}"
    volume: "{{ pki_certbot__container.volumes }}"
    quadlet_options: |

      [Install]
      WantedBy=default.target

      [Service]
      RestartSec=5
      Restart=on-failure
    entrypoint: "{{ pki_certbot__podman_command }}"
    restart_policy: 'no'
    state: 'quadlet'
    recreate: "{{ podman___update_mode | default(false) }}"
  when: 'pki_certbot__ipv6 | length > 0'

- name: 'Start and enable container'
  ansible.builtin.systemd:
    name: "{{ pki_certbot__container.name }}"
    daemon_reload: true
    state: 'started'
    enabled: true
  when: 'not ansible_check_mode'

- name: 'Create systemd renew service'
  ansible.builtin.import_role:
    name: 'systemd_services'
  vars:
    systemd_services:
      - name: 'certbot-podman-renew'
        description: 'podman container: Certbot renew'
        wants:
          - 'certbot-podman-renew.timer'
        type: 'simple'
        user: 'root'
        exec_start: "{{ pki_certbot__command }} renew"
        environment:
          PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

- name: 'Create systemd renew timer'
  ansible.builtin.import_role:
    name: 'systemd_timers'
  vars:
    systemd_timers:
      - name: 'certbot-podman-renew'
        description: 'podman container: Certbot renew timer'
        on_calendar: 'daily'
        persistent: 'true'
        wanted_by:
          - 'timers.target'
        enabled: true
