---

- name: "Create certificates"
  ansible.builtin.shell: |
    [ -f '{{ pki_certbot__podman_etc_dir }}/renewal/{{ item.realm }}.conf' ] || \
    {{ pki_certbot__command}} certonly \
      --server {{ item.server | default(pki_certbot__provider_server[pki_certbot__provider]) }} \
      --authenticator {{ item.authenticator | default('standalone') }} {{ item.authenticator_options | default('') }} \
      --key-type {{ item.key_type | default('ecdsa') }} \
      {{ '--elliptic-curve ' + item.elliptic_curve if item.elliptic_curve is defined and ( item.key_type is not defined or item.key_type == 'ecdsa') }} \
      {{ '--rsa-key-size ' + item.key_size | default('2048') if item.key_type is defined and item.key_type == 'rsa' }} \
      --cert-name {{ item.realm }} \
      --domain {{ item.realm }} \
      {{ '--domains ' + item.domains | join (',') if item.domains is defined }}
  with_items: "{{ pki_certbot__realms }}"
