---

#
# Substitutes - do not change
#

app_forgejo_runner__user: "{{ forgejo_runner_user | default('forgejo-runner') }}"
app_forgejo_runner__uid: "{{ forgejo_runner_uid | mandatory }}"
app_forgejo_runner__gid: "{{ forgejo_runner_gid | default(app_forgejo_runner__uid) }}"
app_forgejo_runner__home: "{{ forgejo_runner_home | mandatory }}"

app_forgejo_runner__hostname: "{{ forgejo_runner_hostname | default('forgejo-runner.' + dns_hostname) }}"
app_forgejo_runner__ip: "{{ forgejo_runner_ip | mandatory }}"
app_forgejo_runner__ipv6: "{{ forgejo_runner_ipv6 | default('') }}"
app_forgejo_runner__version: "{{ forgejo_runner_version | default('9') }}"

app_forgejo_runner__network: "{{ forgejo_runner_network | mandatory }}"
app_forgejo_runner__hosts: "{{ forgejo_runner_hosts | default({}) }}"
app_forgejo_runner__timezone: "{{ forgejo_runner_timezone | default(bootstrap_timezone__timezone) }}"

app_forgejo_runner__container: "{{ app_forgejo_runner__container_default | combine(forgejo_runner_container | default({})) }}"
app_forgejo_runner__volumes: "{{ forgejo_runner_volumes | default(app_forgejo_runner__volumes_default) }}"

app_forgejo_runner__setup: "{{ forgejo_runner_setup | default(true) }}"
app_forgejo_runner__docker_host: "{{ forgejo_runner_docker_host | mandatory }}"

app_forgejo_runner__dind: "{{ forgejo_runner_dind | default(true) }}"
app_forgejo_runner__dind_hostname: "{{ forgejo_runner_dind_hostname | default('forgejo-dind.' + dns_hostname) }}"
app_forgejo_runner__dind_ip: "{{ forgejo_runner_dind_ip | mandatory }}"
app_forgejo_runner__dind_container: "{{ app_forgejo_runner__dind_container_default }}"

app_forgejo_runner__log_level: "{{ forgejo_runner_log_level | default('info') }}"
app_forgejo_runner__log_job_level: "{{ forgejo_runner_log_job_level | default('info') }}"

app_forgejo_runner__container_enable_ipv6: "{{ forgejo_runner_container_enable_ipv6 | default(app_forgejo_runner__ipv6 | length > 0) }}"
app_forgejo_runner__container_privileged: "{{ forgejo_runner_container_privileged | default(false) }}"
app_forgejo_runner__container_valid_volumes: "{{ forgejo_runner_container_valid_volumes | default([]) }}"
app_forgejo_runner__container_force_pull: "{{ forgejo_runner_container_force_pull | default(false) }}"

#
# Defaults - do not change
#

app_forgejo_runner__command: "{{
  ['/bin/sh', '-c', 'while true ; do sleep 1 ; done ;'] if app_forgejo_runner__setup
  else ['/bin/sh', '-c', 'sleep 5; forgejo-runner daemon --config /data/config.yml']
}}"

app_forgejo_runner__volumes_default:
  - "{{ app_forgejo_runner__home }}:/data"
  - '/etc/timezone:/etc/timezone:ro'
  - '/etc/localtime:/etc/localtime:ro'

# See: https://forgejo.org/docs/latest/admin/installation-docker/
app_forgejo_runner__container_default:
  name: 'forgejo-runner'
  hostname: "{{ app_forgejo_runner__hostname }}"
  image: "data.forgejo.org/forgejo/runner:{{ app_forgejo_runner__version }}"
  ip: "{{ app_forgejo_runner__ip }}"
  network: "{{ app_forgejo_runner__network }}"
  restart_policy: 'always'
  environment:
    USER_UID: "{{ app_forgejo_runner__uid }}"
    USER_GID: "{{ app_forgejo_runner__gid }}"
    DOCKER_HOST: "{{ app_forgejo_runner__docker_host }}"
  volumes: "{{ app_forgejo_runner__volumes }}"
  hosts: "{{ app_forgejo_runner__hosts }}"
  user: "{{ app_forgejo_runner__uid }}:{{ app_forgejo_runner__gid }}"
  timezone: "{{ app_forgejo_runner__timezone }}"
  command: "{{ app_forgejo_runner__command }}"

app_forgejo_runner__dind_container_default:
  name: 'forgejo-dind'
  hostname: "{{ app_forgejo_runner__dind_hostname }}"
  image: 'docker:dind'
  ip: "{{ app_forgejo_runner__dind_ip }}"
  network: "{{ app_forgejo_runner__network }}"
  restart_policy: 'always'
  volumes:
    - '/etc/timezone:/etc/timezone:ro'
    - '/etc/localtime:/etc/localtime:ro'
  timezone: "{{ app_forgejo_runner__timezone }}"
  privileged: true
  command: ['dockerd', '-H', 'tcp://0.0.0.0:2375', '--tls=false']
