---

- name: Restart Redis service
  ansible.builtin.service:
    name: 'redis'
    state: 'restarted'
  when: not ansible_check_mode and not database_redis__use_podman

- name: Restart Redis container
  ansible.builtin.shell: 'podman restart redis'
  when: not ansible_check_mode and database_redis__use_podman
