---

- name: 'Deploy Keycloak container'
  tags: [ 'security_keycloak' ]
  block:

    - name: 'Deploy Keycloak container'
      tags: [ 'security_keycloak_container' ]
      ansible.builtin.include_tasks:
        file: 'podman.yml'

    - name: 'Create or update Keycloak realms'
      tags: [ 'security_keycloak_config' ]
      ansible.builtin.include_tasks:
        file: 'realm.yml'
      loop_control:
        loop_var: 'realm'
      with_items: "{{ security_keycloak__realms }}"
      when: 'not podman___update_mode'
