---

- name: 'Create secrets'
  no_log: true
  containers.podman.podman_secret:
    state: 'present'
    name: "{{ item.name }}"
    data: "{{ item.data }}"
  with_items:
    - name: 'keycloak_database_passwd'
      data: "{{ security_keycloak__db_pass }}"
    - name: 'keycloak_admin_passwd'
      data: "{{ security_keycloak__password }}"
  when: 'item.data | length > 0'

- name: 'Gathering facts about services...'
  ansible.builtin.service_facts:

- name: 'Stop container when it is running'
  ansible.builtin.systemd:
    name: "{{ security_keycloak__container.name }}.service"
    state: 'stopped'
  when: 'ansible_facts.services[security_keycloak__container.name + ".service"] is defined'

- name: 'Pull image'
  containers.podman.podman_image:
    name: "{{ security_keycloak__container.image }}"
    force: true
  when: 'podman___update_mode | bool'

- name: 'Install container'
  containers.podman.podman_container:
    name: "{{ security_keycloak__container.name }}"
    hostname: "{{ security_keycloak__container.hostname }}"
    image: "{{ security_keycloak__container.image }}"
    ip: "{{ security_keycloak__container.ip }}"
    ip6: "{{ security_keycloak__container.ipv6 | default(omit) }}"
    network: "{{ security_keycloak__container.network }}"
    timezone: "{{ security_keycloak__container.timezone }}"
    env: "{{ security_keycloak__container.environment | default(omit) }}"
    etc_hosts: "{{ security_keycloak__container.etc_hosts | default(omit) }}"
    expose: "{{ security_keycloak__container.expose | default(omit) }}"
    label: "{{ security_keycloak__container.labels | default(omit) }}"
    publish: "{{ security_keycloak__container.publish | default(omit) }}"
    secrets: "{{ security_keycloak__container.secrets | default(omit) }}"
    volume: "{{ security_keycloak__container.volumes | default(omit) }}"
    shm_size: "{{ security_keycloak__container.shm_size | default(omit) }}"
    command: "{{ security_keycloak__container.command | default(omit) }}"
    quadlet_options: |
      [Install]
      WantedBy=default.target

      [Service]
      {% if security_keycloak__container.exec_start_pre is defined %}
      {% for command in security_keycloak__container.exec_start_pre %}
      ExecStartPre={{ command }}
      {% endfor %}
      {% endif %}
      RestartSec=5
      Restart=always

      [Unit]
      {% if security_keycloak__container.requires is defined %}
      Requires={{ security_keycloak__container.requires | join(' ') }}
      {% endif %}
    restart_policy: 'no'
    state: 'quadlet'
    recreate: "{{ podman___update_mode | bool }}"

- name: 'Start and enable container'
  ansible.builtin.systemd:
    name: "{{ security_keycloak__container.name }}"
    daemon_reload: true
    state: 'started'
    enabled: true
  when: 'not ansible_check_mode'

- name: 'Wait starting up keycloak containers'
  ansible.builtin.wait_for:
    host: "{{ security_keycloak__container.ip }}"
    port: "{{ security_keycloak__http_port if security_keycloak__http_enabled else security_keycloak__https_port }}"

- name: 'Enable autoupdate on container'
  when: 'security_keycloak__autoupdate_enabled'
  include_role:
    name: 'container_update'
  vars:
    container_name: "{{ security_keycloak__container.name }}"
    container_image: "{{ security_keycloak__container.image }}"
