---

#
# Substitutes - do not change
#

app_keycloak__hostname: "{{ keycloak_hostname | default('keycloak.localhost') }}"
app_keycloak__ip: "{{ keycloak_ip | mandatory }}"
app_keycloak__ipv6: "{{ keycloak_ipv6 | default('') }}"
app_keycloak__network: "{{ keycloak_network | mandatory }}"
app_keycloak__version: "{{ keycloak_version | default('latest') }}"

app_keycloak__hosts: "{{ keycloak_hosts | default({}) }}"
app_keycloak__environment: "{{ keycloak_environment | default({}) }}"
app_keycloak__publish: "{{ keycloak_publish | default([]) }}"
app_keycloak__time_zone: "{{ keycloak_timezone | default(bootstrap_timezone__timezone) }}"

app_keycloak__container: "{{ app_keycloak__container_default | combine(keycloak_container | default({})) }}"
app_keycloak__container_bootstrap_timeout: "{{ keycloak_wait_for_container | default(60) }}"

app_keycloak__realms: "{{ keycloak_realms | default([]) }}"

app_keycloak__url: "{{ keycloak_url | mandatory }}"
app_keycloak__admin: "{{ keycloak_admin | mandatory }}"
app_keycloak__password: "{{ keycloak_password | mandatory }}"

#
# Defaults - do not change
#

app_keycloak__container_default:
  name: 'keycloak'
  hostname: "{{ app_keycloak__hostname }}"
  image: "quay.io/keycloak/keycloak:{{ app_keycloak__version }}"
  ip: "{{ app_keycloak__ip }}"
  ipv6: "{{ app_keycloak__ipv6 }}"
  network: "{{ app_keycloak__network }}"
  restart_policy: 'always'
  hosts: "{{ app_keycloak__hosts }}"
  shm_size: '256m'
  environment: "{{ app_keycloak__environment }}"
  publish: "{{ app_keycloak__publish }}"
  timezone: "{{ app_keycloak__time_zone }}"
  command: 'start-dev'

app_keycloak__auth_url: "{{ app_keycloak__url }}"
app_keycloak__auth_username: "{{ app_keycloak__admin }}"
app_keycloak__auth_password: "{{ app_keycloak__password }}"
app_keycloak__auth_realm: 'master'
app_keycloak__auth_client_id: 'admin-cli'

app_keycloak__realm_default:
  display_name: ''
  login_with_email: true
  smtp_server: ''

app_keycloak__user_federation_default:
  federation_name: 'User Federation'
  provider_type: 'ldap'
  auth_type: 'none'
  edit_mode: 'READ_ONLY'
  uid_attribute: 'cn'
  scope: 1
  trust_email: false
  object_classes: 'inetOrgPerson, organizationalPerson'
  user_base: 'ou=Users'
  uuid_attribute: 'entryUUID'
  vendor: 'other'

app_keycloak__client_default:
  name: ''
  protocol: 'openid-connect'
  description: ''
  root_url: ''
