---

#
# Substitutes - do not change
#

app_keycloak__hostname: "{{ keycloak_hostname | default('keycloak.localhost') }}"
app_keycloak__ip: "{{ keycloak_ip | mandatory }}"
app_keycloak__ipv6: "{{ keycloak_ipv6 | default('') }}"
app_keycloak__network: "{{ keycloak_network | mandatory }}"
app_keycloak__version: "{{ keycloak_version | default('latest') }}"

app_keycloak__hosts: "{{ keycloak_hosts | default({}) }}"
app_keycloak__environment: "{{ keycloak_environment | default({}) }}"
app_keycloak__publish: "{{ keycloak_publish | default([]) }}"
app_keycloak__time_zone: "{{ keycloak_timezone | default(bootstrap_timezone__timezone) }}"

app_keycloak__container: "{{ app_keycloak__container_default | combine(keycloak_container | default({})) }}"
app_keycloak__container_bootstrap_timeout: "{{ keycloak_wait_for_container | default(60) }}"

app_keycloak__realms: "{{ keycloak_realms | default([]) }}"

app_keycloak__url: "{{ keycloak_url | mandatory }}"
app_keycloak__admin: "{{ keycloak_admin | mandatory }}"
app_keycloak__password: "{{ keycloak_password | mandatory }}"

#
# Defaults - do not change
#

app_keycloak__container_default:
  name: 'keycloak'
  hostname: "{{ app_keycloak__hostname }}"
  image: "quay.io/keycloak/keycloak:{{ app_keycloak__version }}"
  ip: "{{ app_keycloak__ip }}"
  ipv6: "{{ app_keycloak__ipv6 }}"
  network: "{{ app_keycloak__network }}"
  restart_policy: 'always'
  hosts: "{{ app_keycloak__hosts }}"
  shm_size: '256m'
  environment: "{{ app_keycloak__environment }}"
  publish: "{{ app_keycloak__publish }}"
  timezone: "{{ app_keycloak__time_zone }}"
  command: 'start-dev'

app_keycloak__auth_url: "{{ app_keycloak__url }}"
app_keycloak__auth_username: "{{ app_keycloak__admin }}"
app_keycloak__auth_password: "{{ app_keycloak__password }}"
app_keycloak__auth_realm: 'master'
app_keycloak__auth_client_id: 'admin-cli'

app_keycloak__realm_default:
  display_name: ''
  login_with_email: true
  smtp_server: ''

app_keycloak__user_federation_provider_id_default: 'ldap'
app_keycloak__user_federation_auth_type_default: 'none'
app_keycloak__user_federation_edit_mode_default: 'READ_ONLY'
app_keycloak__user_federation_rdn_ldap_attribute_default: 'cn'
app_keycloak__user_federation_search_scope_default: 1
app_keycloak__user_federation_trust_email_default: false
app_keycloak__user_federation_username_ldap_attribute_default: "{{ app_keycloak__user_federation_rdn_ldap_attribute_default }}"
app_keycloak__user_federation_user_object_classes_default: 'inetOrgPerson, organizationalPerson'
app_keycloak__user_federation_uuid_ldap_attribute_default: 'objectGUID'

app_keycloak__client_default:
  name: ''
  protocol: 'openid-connect'
  description: ''
  root_url: ''
